import type { LevelSpec } from "./types.js";

/**
 * A1 — Beginner. 8 ünite, 46 ders.
 *
 * Sıralama CEFR kriteryel dizilimini izler: 'be' → kişi/aidiyet → nesne ve yer →
 * present simple → yetenek/hoşlanma → betimleme → günlük işlemler → geçmiş.
 *
 * RİTİM KURALI: her ünite bir `practice` dersiyle kapanır ve hiçbir yerde 4'ten
 * fazla gramer dersi arka arkaya gelmez. Konuşma uygulamasında uzun gramer
 * serisi öğrenciyi konuşturmadan yoruyor; `scripts/lint-curriculum.ts` bunu
 * denetliyor. Saf kelime dersi YOKTUR — kelime işlevin içine gömülüdür.
 */
export const A1: LevelSpec = {
  level: "A1",
  label: "Beginner",
  units: [
    {
      index: 1,
      title: "Hello and Introductions",
      goal: "Introduce yourself, say where you are from, and ask someone the same",
    },
    {
      index: 2,
      title: "People Around Me",
      goal: "Talk about your family, your job and the people close to you",
    },
    {
      index: 3,
      title: "Things and Places",
      goal: "Name everyday objects and say what there is around you",
    },
    {
      index: 4,
      title: "Everyday Life",
      goal: "Describe your daily routine and say when you do things",
    },
    {
      index: 5,
      title: "Likes and Free Time",
      goal: "Say what you like doing, what you can do, and ask for help",
    },
    {
      index: 6,
      title: "Describing",
      goal: "Describe people, places and the weather in simple sentences",
    },
    {
      index: 7,
      title: "Out and About",
      goal: "Order food, buy things, ask for directions and travel around a city",
    },
    {
      index: 8,
      title: "Talking About the Past",
      goal: "Talk about what you did and tell a short story about a past day",
    },
  ],
  lessons: [
    // --- Ünite 1 · Hello and Introductions -------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "phrases",
      title: "Hello, I'm…",
      focus: "greeting someone and introducing yourself",
      themeHint: "meeting a new classmate on the first day of a course",
      targetPhrases: ["nice to meet you", "my name is", "how are you"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "grammar",
      title: "Am, Is, Are",
      focus: "the present of 'be': affirmative sentences and contractions",
      themeHint: "introducing the people in a photo",
      targetPhrases: ["I am", "he is", "they are"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "Are You a Student?",
      focus: "'be': yes/no questions and short answers",
      themeHint: "two people getting to know each other at a bus stop",
      targetPhrases: ["are you", "yes I am", "no I'm not"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "grammar",
      title: "I'm Not from Here",
      focus: "'be': negative sentences",
      themeHint: "correcting a wrong guess about someone",
      targetPhrases: ["I'm not", "it isn't", "we aren't"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "phrases",
      title: "Where Are You From?",
      focus: "countries and nationalities with 'be from'",
      themeHint: "small talk between travellers waiting at an airport",
      targetPhrases: ["I'm from", "where are you from", "I live in"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "Meeting Someone New",
      focus: "introducing yourself and asking someone else the same questions",
      themeHint: "the first few minutes of a conversation with a stranger at an event",
      targetPhrases: ["nice to meet you", "where are you from", "what about you"],
    },

    // --- Ünite 2 · People Around Me ---------------------------------------------
    {
      position: 7,
      unitIndex: 2,
      kind: "grammar",
      title: "This Is My Sister",
      focus: "possessive adjectives: my, your, his, her, our, their",
      themeHint: "showing family photos to a friend",
      targetPhrases: ["this is my", "her name is", "our teacher"],
    },
    {
      position: 8,
      unitIndex: 2,
      kind: "grammar",
      title: "He, She, They",
      focus: "subject pronouns used with 'be' to talk about other people",
      themeHint: "describing colleagues to someone new at the office",
      targetPhrases: ["she's my friend", "he works here", "they're students"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "Have You Got a Pen?",
      focus: "'have got' for possession: affirmative, negative and questions",
      themeHint: "borrowing small things from a classmate",
      targetPhrases: ["I've got", "have you got", "she hasn't got"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "phrases",
      title: "What's Your Job?",
      focus: "talking about jobs, with a / an before professions",
      themeHint: "chatting about work at a friend's party",
      targetPhrases: ["I'm a teacher", "what do you do", "he's an engineer"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "phrases",
      title: "How Old Are You?",
      focus: "numbers up to one hundred and asking about age",
      themeHint: "filling in a simple form with a receptionist",
      targetPhrases: ["how old are you", "I'm twenty five", "she's ten"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "practice",
      title: "People in My Life",
      focus: "talking about your family, friends and the people you work with",
      themeHint: "explaining who everyone is while looking through photos",
      targetPhrases: ["this is my", "she works as", "we're good friends"],
    },

    // --- Ünite 3 · Things and Places --------------------------------------------
    {
      position: 13,
      unitIndex: 3,
      kind: "grammar",
      title: "A Cat or an Apple?",
      focus: "the indefinite articles a and an",
      themeHint: "naming things you can see in a room",
      targetPhrases: ["it's a book", "it's an apple", "I have a car"],
    },
    {
      position: 14,
      unitIndex: 3,
      kind: "grammar",
      title: "One Book, Two Books",
      focus: "regular plurals and the most common irregular ones",
      themeHint: "counting things in a shop window",
      targetPhrases: ["two books", "three children", "some people"],
    },
    {
      position: 15,
      unitIndex: 3,
      kind: "grammar",
      title: "This, That, These, Those",
      focus: "demonstratives for things near and far",
      themeHint: "choosing between items on a market stall",
      targetPhrases: ["this is", "that one", "these are mine"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "phrases",
      title: "What's in Your Bag?",
      focus: "everyday objects and asking what things are",
      themeHint: "emptying a bag at a security check",
      targetPhrases: ["what is this", "it's my phone", "I need my keys"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "grammar",
      title: "There's a Cafe Nearby",
      focus: "there is / there are: affirmative and negative",
      themeHint: "describing what is in your neighbourhood",
      targetPhrases: ["there is a", "there are two", "there isn't any"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "grammar",
      title: "Is There a Bank Here?",
      focus: "there is / there are: questions and short answers",
      themeHint: "asking a hotel receptionist what is in the area",
      targetPhrases: ["is there a", "are there any", "yes there is"],
    },
    {
      position: 19,
      unitIndex: 3,
      kind: "grammar",
      title: "On, In, Under",
      focus: "prepositions of place",
      themeHint: "helping someone find something they lost at home",
      targetPhrases: ["on the table", "in my bag", "next to the door"],
    },
    {
      position: 20,
      unitIndex: 3,
      kind: "practice",
      title: "Around My Neighbourhood",
      focus: "describing what there is near your home and where things are",
      themeHint: "telling a visitor what is worth seeing near where you live",
      targetPhrases: ["there's a", "it's near", "just around the corner"],
    },

    // --- Ünite 4 · Everyday Life ------------------------------------------------
    {
      position: 21,
      unitIndex: 4,
      kind: "grammar",
      title: "I Wake Up at Seven",
      focus: "present simple affirmative with I, you, we and they",
      themeHint: "comparing morning routines with a friend",
      targetPhrases: ["I wake up", "we start at", "they finish late"],
    },
    {
      position: 22,
      unitIndex: 4,
      kind: "grammar",
      title: "She Works at Night",
      focus: "present simple: third person -s",
      themeHint: "talking about what people in different jobs do",
      targetPhrases: ["she works", "he lives", "it starts at"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "grammar",
      title: "I Don't Drink Coffee",
      focus: "present simple: negative sentences",
      themeHint: "explaining your habits to someone offering you things",
      targetPhrases: ["I don't", "she doesn't", "we don't work"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "grammar",
      title: "Do You Live Here?",
      focus: "present simple: yes/no questions and short answers",
      themeHint: "getting to know a new neighbour",
      targetPhrases: ["do you", "does she", "yes I do"],
    },
    {
      position: 25,
      unitIndex: 4,
      kind: "phrases",
      title: "What Time Is It?",
      focus: "telling the time and using at, on and in for time",
      themeHint: "checking when a shop opens and closes",
      targetPhrases: ["what time is it", "it's half past", "at six o'clock"],
    },
    {
      position: 26,
      unitIndex: 4,
      kind: "grammar",
      title: "Always, Sometimes, Never",
      focus: "frequency words and where they go in a sentence",
      themeHint: "talking about how often you do everyday things",
      targetPhrases: ["I always", "she never", "we sometimes go"],
    },
    {
      position: 27,
      unitIndex: 4,
      kind: "practice",
      title: "My Morning",
      focus: "describing your own daily routine from start to finish",
      themeHint: "telling a new friend what a normal weekday looks like for you",
      targetPhrases: ["I usually", "after that", "before work"],
    },

    // --- Ünite 5 · Likes and Free Time ------------------------------------------
    {
      position: 28,
      unitIndex: 5,
      kind: "grammar",
      title: "I Love Cooking",
      focus: "like, love and hate followed by an -ing word",
      themeHint: "finding out what two people have in common",
      targetPhrases: ["I love", "I don't like", "she enjoys cooking"],
    },
    {
      position: 29,
      unitIndex: 5,
      kind: "grammar",
      title: "Do You Like It?",
      focus: "object pronouns: me, him, her, it, us, them",
      themeHint: "giving opinions about a gift someone received",
      targetPhrases: ["I like it", "call me", "tell them"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "grammar",
      title: "I Can Swim",
      focus: "can and can't for ability",
      themeHint: "talking about skills while joining a sports club",
      targetPhrases: ["I can", "I can't", "she can drive"],
    },
    {
      position: 31,
      unitIndex: 5,
      kind: "grammar",
      title: "Can You Help Me?",
      focus: "can for requests and permission",
      themeHint: "asking a colleague for a small favour",
      targetPhrases: ["can you help", "can I have", "of course"],
    },
    {
      position: 32,
      unitIndex: 5,
      kind: "practice",
      title: "My Weekend",
      focus: "talking about free time, hobbies and what you do at weekends",
      themeHint: "two friends catching up on a Monday morning",
      targetPhrases: ["at the weekend", "I usually", "with my friends"],
    },

    // --- Ünite 6 · Describing ---------------------------------------------------
    {
      position: 33,
      unitIndex: 6,
      kind: "grammar",
      title: "A Small Red Car",
      focus: "where descriptive words go: before a noun and after 'be'",
      themeHint: "describing items in a lost property office",
      targetPhrases: ["it's very small", "my new phone", "really nice"],
    },
    {
      position: 34,
      unitIndex: 6,
      kind: "phrases",
      title: "What Does She Look Like?",
      focus: "describing what people look like",
      themeHint: "describing someone you are waiting to meet",
      targetPhrases: ["she has long hair", "he is tall", "what does she look like"],
    },
    {
      position: 35,
      unitIndex: 6,
      kind: "phrases",
      title: "It's Cold Today",
      focus: "talking about the weather and the seasons",
      themeHint: "deciding what to wear before going out",
      targetPhrases: ["it's cold", "it's raining", "what's the weather like"],
    },
    {
      position: 36,
      unitIndex: 6,
      kind: "practice",
      title: "My Favorite Place",
      focus: "describing a room or a place you like and saying what is in it",
      themeHint: "showing someone around your favourite place",
      targetPhrases: ["there is", "on the left", "I really like"],
    },

    // --- Ünite 7 · Out and About ------------------------------------------------
    {
      position: 37,
      unitIndex: 7,
      kind: "phrases",
      title: "Two Coffees, Please",
      focus: "ordering food and drink with 'I'd like' and 'Can I have'",
      themeHint: "a small coffee shop at lunchtime",
      targetPhrases: ["I'd like", "can I have", "anything else"],
    },
    {
      position: 38,
      unitIndex: 7,
      kind: "phrases",
      title: "How Much Is It?",
      focus: "asking about prices and quantities when shopping",
      themeHint: "buying something small in a busy shop",
      targetPhrases: ["how much is it", "that's too expensive", "I'll take it"],
    },
    {
      position: 39,
      unitIndex: 7,
      kind: "grammar",
      title: "Some Bread, Any Milk",
      focus: "countable and uncountable words with some and any",
      themeHint: "checking what is missing before going to the supermarket",
      targetPhrases: ["some bread", "any milk", "we need some"],
    },
    {
      position: 40,
      unitIndex: 7,
      kind: "phrases",
      title: "Turn Left at the Corner",
      focus: "giving and following directions with command words",
      themeHint: "a tourist asking how to reach the station",
      targetPhrases: ["turn left", "go straight on", "it's on your right"],
    },
    {
      position: 41,
      unitIndex: 7,
      kind: "phrases",
      title: "Getting There",
      focus: "transport words and saying how you travel with 'by'",
      themeHint: "comparing how two people get to work",
      targetPhrases: ["by bus", "I walk to work", "it takes ten minutes"],
    },

    // --- Ünite 8 · Talking About the Past ---------------------------------------
    {
      position: 42,
      unitIndex: 8,
      kind: "grammar",
      title: "I Was There",
      focus: "the past of 'be': was and were",
      themeHint: "explaining where you were yesterday",
      targetPhrases: ["I was", "we were", "it wasn't"],
    },
    {
      position: 43,
      unitIndex: 8,
      kind: "grammar",
      title: "We Watched a Film",
      focus: "past simple with regular endings, affirmative sentences",
      themeHint: "telling someone what you did last night",
      targetPhrases: ["I watched", "we visited", "she worked late"],
    },
    {
      position: 44,
      unitIndex: 8,
      kind: "grammar",
      title: "I Went, I Saw",
      focus: "past simple with the most common irregular words",
      themeHint: "talking about a day trip you took",
      targetPhrases: ["I went", "I saw", "we had dinner"],
    },
    {
      position: 45,
      unitIndex: 8,
      kind: "grammar",
      title: "Did You Like It?",
      focus: "past simple: questions and negative sentences",
      themeHint: "asking a friend about an event you missed",
      targetPhrases: ["did you", "I didn't", "did she go"],
    },
    {
      position: 46,
      unitIndex: 8,
      kind: "practice",
      title: "Last Weekend",
      focus: "telling a short story about something you did recently",
      themeHint: "sharing weekend news with a colleague",
      targetPhrases: ["last weekend", "and then", "it was great"],
    },
  ],
};
