import type { LevelSpec } from "./types.js";

/**
 * A2 — Pre-Intermediate. 9 ünite, 57 ders.
 *
 * A1 şimdiki zaman ve tek cümlelik geçmiş üzerine kuruluydu; A2 bunları ANLATIYA
 * ve PLANA bağlar: hikâye anlatma (past continuous), gelecek (going to / will),
 * karşılaştırma, zorunluluk-tavsiye, deneyim (present perfect), miktar, koşul,
 * ve gerçek işlemler (rezervasyon, şikâyet, telefon).
 *
 * A1'deki ritim kuralı burada da geçerli: her ünite `practice` ile kapanır ve
 * 4'ten fazla gramer dersi arka arkaya gelmez (bkz. scripts/lint-curriculum.ts).
 * Ünite 8 kasten tamamen `phrases`: bu seviyede öğrenciyi kilitleyen şey gramer
 * değil, işlem yapamamak.
 */
export const A2: LevelSpec = {
  level: "A2",
  label: "Pre-Intermediate",
  units: [
    {
      index: 1,
      title: "Telling Stories",
      goal: "Tell a story about the past and say what was happening when something else happened",
    },
    {
      index: 2,
      title: "Plans and Predictions",
      goal: "Talk about your plans, make predictions and arrange to meet someone",
    },
    {
      index: 3,
      title: "Comparing",
      goal: "Compare people, places and things, and explain which one you prefer",
    },
    {
      index: 4,
      title: "Rules and Advice",
      goal: "Talk about what you must and must not do, and give advice to someone",
    },
    {
      index: 5,
      title: "Experiences",
      goal: "Talk about things you have and have not done in your life",
    },
    {
      index: 6,
      title: "Quantity and Detail",
      goal: "Say how much of something there is and describe things more precisely",
    },
    {
      index: 7,
      title: "Reasons and Conditions",
      goal: "Explain why you do things and talk about what will happen if something else does",
    },
    {
      index: 8,
      title: "Getting Things Done",
      goal: "Book, ask, complain and sort out a problem politely in English",
    },
    {
      index: 9,
      title: "People and Things",
      goal: "Describe people and things in longer sentences and give your opinion",
    },
  ],
  lessons: [
    // --- Ünite 1 · Telling Stories ----------------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "grammar",
      title: "While I Was Waiting",
      focus: "past continuous: affirmative and negative sentences",
      themeHint: "explaining what you were doing during a power cut",
      targetPhrases: ["I was waiting", "we were talking", "it wasn't working"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "grammar",
      title: "What Were You Doing?",
      focus: "past continuous: questions",
      themeHint: "a friendly conversation about where everyone was that evening",
      targetPhrases: ["what were you doing", "were you working", "I was just"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "It Happened While…",
      focus: "past simple and past continuous together, with when and while",
      themeHint: "describing the moment something unexpected interrupted your day",
      targetPhrases: ["while I was", "when it happened", "suddenly I heard"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "phrases",
      title: "Ago, Last, Yesterday",
      focus: "expressions that say when something happened in the past",
      themeHint: "talking about when you last did various things",
      targetPhrases: ["two years ago", "last summer", "about a month ago"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "phrases",
      title: "First, Then, After That",
      focus: "putting the events of a story in order",
      themeHint: "retelling how a small everyday disaster unfolded",
      targetPhrases: ["first of all", "after that", "in the end"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "My Best Holiday",
      focus: "telling the full story of a past trip",
      themeHint: "two colleagues sharing holiday stories after the summer",
      targetPhrases: ["we stayed in", "it was amazing", "I'll never forget"],
    },

    // --- Ünite 2 · Plans and Predictions ----------------------------------------
    {
      position: 7,
      unitIndex: 2,
      kind: "grammar",
      title: "I'm Going to Move",
      focus: "'be going to' for plans and intentions",
      themeHint: "telling a friend about a big decision you have made",
      targetPhrases: ["I'm going to", "we're going to", "she's going to"],
    },
    {
      position: 8,
      unitIndex: 2,
      kind: "grammar",
      title: "Are You Going to Come?",
      focus: "'be going to': questions and negatives",
      themeHint: "finding out who is joining an upcoming event",
      targetPhrases: ["are you going to", "I'm not going to", "what are you going to"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "I Think It Will Rain",
      focus: "will for predictions about the future",
      themeHint: "guessing how tomorrow and next year will turn out",
      targetPhrases: ["I think it will", "it will probably", "it won't"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "phrases",
      title: "Tomorrow, Next Week",
      focus: "expressions that say when something will happen",
      themeHint: "agreeing on when the things on a list will get done",
      targetPhrases: ["next week", "in two weeks", "later this year"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "grammar",
      title: "I'll Get It!",
      focus: "will for offers and decisions made at the moment of speaking",
      themeHint: "helping out when something suddenly needs doing",
      targetPhrases: ["I'll do it", "shall I help", "don't worry"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "grammar",
      title: "I'm Meeting Sam at Six",
      focus: "present continuous for fixed future arrangements",
      themeHint: "comparing diaries for the coming week",
      targetPhrases: ["I'm meeting", "we're leaving at", "what are you doing"],
    },
    {
      position: 13,
      unitIndex: 2,
      kind: "practice",
      title: "Let's Make a Plan",
      focus: "arranging to meet someone and agreeing on the details",
      themeHint: "two busy people trying to find a free evening",
      targetPhrases: ["how about", "does that work", "see you then"],
    },

    // --- Ünite 3 · Comparing ----------------------------------------------------
    {
      position: 14,
      unitIndex: 3,
      kind: "grammar",
      title: "Bigger and Better",
      focus: "comparing two things with short words plus -er and than",
      themeHint: "comparing two flats you are thinking about renting",
      targetPhrases: ["bigger than", "cheaper than", "much better"],
    },
    {
      position: 15,
      unitIndex: 3,
      kind: "grammar",
      title: "More Interesting Than",
      focus: "comparing with 'more' and the common irregular comparisons",
      themeHint: "discussing two cities you have both visited",
      targetPhrases: ["more expensive than", "less crowded", "worse than"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "grammar",
      title: "The Best One",
      focus: "superlatives for the top or bottom of a group",
      themeHint: "picking favourites from a list of places or things",
      targetPhrases: ["it's the best", "that's the cheapest", "my favourite one"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "phrases",
      title: "I Prefer This One",
      focus: "saying which of two things you prefer and why",
      themeHint: "choosing between two products in a shop",
      targetPhrases: ["I prefer", "I like this one", "I'd rather have"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "grammar",
      title: "As Cheap As",
      focus: "'as … as' and 'not as … as' for saying things are equal or not",
      themeHint: "arguing that two options are closer than they look",
      targetPhrases: ["as good as", "not as expensive", "just as nice"],
    },
    {
      position: 19,
      unitIndex: 3,
      kind: "grammar",
      title: "He Drives Carefully",
      focus: "describing how someone does something",
      themeHint: "describing people's habits at work or on the road",
      targetPhrases: ["very carefully", "he speaks slowly", "quite well"],
    },
    {
      position: 20,
      unitIndex: 3,
      kind: "practice",
      title: "Which One Would You Pick?",
      focus: "comparing two real options and explaining your choice",
      themeHint: "helping a friend choose between two offers",
      targetPhrases: ["I'd rather", "it depends on", "in my opinion"],
    },

    // --- Ünite 4 · Rules and Advice ---------------------------------------------
    {
      position: 21,
      unitIndex: 4,
      kind: "grammar",
      title: "I Have to Work",
      focus: "'have to' and 'has to' for things that are necessary",
      themeHint: "explaining the rules of your job or your home",
      targetPhrases: ["I have to", "she has to", "do you have to"],
    },
    {
      position: 22,
      unitIndex: 4,
      kind: "grammar",
      title: "You Don't Have to Come",
      focus: "the difference between 'don't have to' and 'mustn't'",
      themeHint: "explaining which rules are strict and which are optional",
      targetPhrases: ["you don't have to", "you mustn't", "we have to"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "grammar",
      title: "You Should Rest",
      focus: "should and shouldn't for advice",
      themeHint: "a friend who is working too much and sleeping too little",
      targetPhrases: ["you should", "you shouldn't", "maybe you should"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "grammar",
      title: "Can I Ask Something?",
      focus: "could and may for polite requests and permission",
      themeHint: "asking for something in a formal situation",
      targetPhrases: ["could you", "may I", "would it be okay"],
    },
    {
      position: 25,
      unitIndex: 4,
      kind: "phrases",
      title: "What's the Matter?",
      focus: "describing health problems and talking to a doctor",
      themeHint: "a short appointment at a walk-in clinic",
      targetPhrases: ["I don't feel well", "my head hurts", "you should see"],
    },
    {
      position: 26,
      unitIndex: 4,
      kind: "practice",
      title: "A Friend Needs Help",
      focus: "listening to someone's problem and giving advice",
      themeHint: "a friend unsure whether to change jobs",
      targetPhrases: ["if I were you", "have you tried", "that sounds hard"],
    },

    // --- Ünite 5 · Experiences --------------------------------------------------
    {
      position: 27,
      unitIndex: 5,
      kind: "grammar",
      title: "Have You Ever Been?",
      focus: "present perfect with 'ever' to ask about life experience",
      themeHint: "finding out what unusual things someone has done",
      targetPhrases: ["have you ever", "yes I have", "I have been to"],
    },
    {
      position: 28,
      unitIndex: 5,
      kind: "grammar",
      title: "I've Never Tried That",
      focus: "present perfect with 'never'",
      themeHint: "admitting the ordinary things you have somehow never done",
      targetPhrases: ["I've never", "she's never", "never in my life"],
    },
    {
      position: 29,
      unitIndex: 5,
      kind: "grammar",
      title: "Been or Gone?",
      focus: "the difference between 'has been' and 'has gone'",
      themeHint: "explaining where colleagues are and where they have travelled",
      targetPhrases: ["he's gone to", "I've been to", "she's been there"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "phrases",
      title: "Tell Me More",
      focus: "asking follow-up questions about someone's experience",
      themeHint: "keeping a conversation going when someone shares news",
      targetPhrases: ["what was it like", "how long", "tell me more"],
    },
    {
      position: 31,
      unitIndex: 5,
      kind: "grammar",
      title: "I've Already Finished",
      focus: "present perfect with already and just",
      themeHint: "reporting progress on a shared task",
      targetPhrases: ["I've already", "I've just", "she's just left"],
    },
    {
      position: 32,
      unitIndex: 5,
      kind: "grammar",
      title: "Have You Done It Yet?",
      focus: "present perfect questions and negatives with yet",
      themeHint: "chasing up things that were supposed to be done",
      targetPhrases: ["have you finished", "not yet", "I haven't yet"],
    },
    {
      position: 33,
      unitIndex: 5,
      kind: "practice",
      title: "Two Truths and a Lie",
      focus: "sharing unusual experiences and asking about someone else's",
      themeHint: "a getting-to-know-you game between new colleagues",
      targetPhrases: ["I've never", "have you ever", "that can't be true"],
    },

    // --- Ünite 6 · Quantity and Detail ------------------------------------------
    {
      position: 34,
      unitIndex: 6,
      kind: "grammar",
      title: "How Much Sugar?",
      focus: "much, many and 'a lot of' with things you can and cannot count",
      themeHint: "working out what is left in the kitchen",
      targetPhrases: ["how much", "how many", "not much"],
    },
    {
      position: 35,
      unitIndex: 6,
      kind: "grammar",
      title: "A Few or a Little?",
      focus: "'a few' and 'a little' for small amounts",
      themeHint: "describing how much time and money something needs",
      targetPhrases: ["just a few", "only a little", "quite a lot"],
    },
    {
      position: 36,
      unitIndex: 6,
      kind: "grammar",
      title: "Too Small, Not Big Enough",
      focus: "'too' before and 'enough' after a describing word",
      themeHint: "explaining why something does not fit or does not work",
      targetPhrases: ["it's too small", "not big enough", "too expensive"],
    },
    {
      position: 37,
      unitIndex: 6,
      kind: "phrases",
      title: "How Long, How Far",
      focus: "asking about time, distance and size",
      themeHint: "planning a journey and checking the practical details",
      targetPhrases: ["how long does it", "how far is", "about ten kilometres"],
    },
    {
      position: 38,
      unitIndex: 6,
      kind: "grammar",
      title: "Something, Anything, Nothing",
      focus: "words built with some-, any- and no-",
      themeHint: "looking for something in an empty fridge",
      targetPhrases: ["something to eat", "anything else", "nothing special"],
    },
    {
      position: 39,
      unitIndex: 6,
      kind: "grammar",
      title: "Mine, Yours, Theirs",
      focus: "possessive pronouns and asking with 'whose'",
      themeHint: "sorting out whose things are whose after a shared trip",
      targetPhrases: ["it's mine", "that's yours", "whose is this"],
    },
    {
      position: 40,
      unitIndex: 6,
      kind: "practice",
      title: "Packing for a Trip",
      focus: "deciding what to take and how much of it you need",
      themeHint: "two people packing one suitcase together",
      targetPhrases: ["I don't need", "we should take", "that's enough"],
    },

    // --- Ünite 7 · Reasons and Conditions ---------------------------------------
    {
      position: 41,
      unitIndex: 7,
      kind: "grammar",
      title: "Because and So",
      focus: "joining two ideas with because and so",
      themeHint: "explaining a decision you had to make quickly",
      targetPhrases: ["because I was", "so I decided", "that's why"],
    },
    {
      position: 42,
      unitIndex: 7,
      kind: "grammar",
      title: "If It Rains, We'll Stay",
      focus: "talking about a likely future situation and its result with if",
      themeHint: "planning an outdoor event around bad weather",
      targetPhrases: ["if it rains", "I'll call you", "if you want"],
    },
    {
      position: 43,
      unitIndex: 7,
      kind: "grammar",
      title: "When Water Boils",
      focus: "using if and when for things that are always true",
      themeHint: "explaining how a simple machine or routine works",
      targetPhrases: ["if you heat", "when it gets", "it always happens"],
    },
    {
      position: 44,
      unitIndex: 7,
      kind: "phrases",
      title: "Maybe, Probably, Definitely",
      focus: "saying how sure or unsure you are about something",
      themeHint: "answering questions when you cannot commit to an answer",
      targetPhrases: ["I'm not sure", "probably not", "almost certainly"],
    },
    {
      position: 45,
      unitIndex: 7,
      kind: "grammar",
      title: "I Came Here to Learn",
      focus: "using 'to' plus an action word to explain why you do something",
      themeHint: "explaining your reasons for a big change",
      targetPhrases: ["to learn English", "to get better", "I came here to"],
    },
    {
      position: 46,
      unitIndex: 7,
      kind: "grammar",
      title: "I Want to Go, I Enjoy Going",
      focus: "which common words are followed by 'to' and which by -ing",
      themeHint: "talking about what you want and what you enjoy",
      targetPhrases: ["I want to", "I enjoy", "I'd like to"],
    },
    {
      position: 47,
      unitIndex: 7,
      kind: "practice",
      title: "Making a Decision",
      focus: "talking through a choice and what would follow from it",
      themeHint: "weighing up whether to move to another city",
      targetPhrases: ["on the other hand", "if I do that", "I've decided to"],
    },

    // --- Ünite 8 · Getting Things Done ------------------------------------------
    {
      position: 48,
      unitIndex: 8,
      kind: "phrases",
      title: "Would You Mind?",
      focus: "making polite requests and answering them",
      themeHint: "asking a stranger for a small favour",
      targetPhrases: ["would you mind", "not at all", "of course not"],
    },
    {
      position: 49,
      unitIndex: 8,
      kind: "phrases",
      title: "I'm Sorry, I Can't",
      focus: "saying no politely and apologising",
      themeHint: "turning down an invitation you would like to accept",
      targetPhrases: ["I'm afraid I can't", "sorry about that", "maybe next time"],
    },
    {
      position: 50,
      unitIndex: 8,
      kind: "phrases",
      title: "Booking a Room",
      focus: "booking travel and a place to stay",
      themeHint: "a phone call to a small hotel",
      targetPhrases: ["I'd like to book", "for two nights", "is breakfast included"],
    },
    {
      position: 51,
      unitIndex: 8,
      kind: "phrases",
      title: "Something Went Wrong",
      focus: "complaining politely and returning something",
      themeHint: "taking a faulty item back to a shop",
      targetPhrases: ["there's a problem", "it doesn't work", "could I get a refund"],
    },
    {
      position: 52,
      unitIndex: 8,
      kind: "phrases",
      title: "Can You Say That Again?",
      focus: "asking someone to repeat, slow down or explain",
      themeHint: "a fast speaker on a bad phone line",
      targetPhrases: ["could you repeat that", "what does that mean", "sorry I didn't catch"],
    },
    {
      position: 53,
      unitIndex: 8,
      kind: "practice",
      title: "Sorting Out a Problem",
      focus: "solving a real problem on the phone from start to finish",
      themeHint: "calling about an order that never arrived",
      targetPhrases: ["I'm calling about", "let me check", "thanks for your help"],
    },

    // --- Ünite 9 · People and Things --------------------------------------------
    {
      position: 54,
      unitIndex: 9,
      kind: "grammar",
      title: "The Man Who Helped Me",
      focus: "joining sentences with who, which and that",
      themeHint: "describing a person or a thing you cannot name exactly",
      targetPhrases: ["someone who", "something that", "people who live"],
    },
    {
      position: 55,
      unitIndex: 9,
      kind: "grammar",
      title: "I Used to Play Football",
      focus: "'used to' for past habits that have stopped",
      themeHint: "talking about how your life was different years ago",
      targetPhrases: ["I used to", "we used to", "didn't use to"],
    },
    {
      position: 56,
      unitIndex: 9,
      kind: "phrases",
      title: "What Do You Think?",
      focus: "giving an opinion, agreeing and disagreeing politely",
      themeHint: "a light disagreement about something everyday",
      targetPhrases: ["I think so", "I don't agree", "you're right"],
    },
    {
      position: 57,
      unitIndex: 9,
      kind: "practice",
      title: "A Film Worth Watching",
      focus: "recommending a film or a book and saying why",
      themeHint: "convincing a friend to watch or read something",
      targetPhrases: ["you should watch", "it's about", "I'd recommend it"],
    },
  ],
};
