import type { LevelSpec } from "./types.js";

/**
 * B1 — Intermediate. 11 ünite, 68 ders.
 *
 * A2 tek olayları anlatabiliyordu; B1 bunları BİRBİRİNE BAĞLAR: olaylar arası sıra
 * (past perfect), süregelen deneyim (present perfect continuous), başkasının sözünü
 * aktarma, edilgen, ilgi cümlecikleri, çıkarım. Seviyenin ağırlık merkezi burası —
 * gramer oranı en yüksek seviye B1'dir ve bu kasıtlıdır.
 *
 * Ritim kuralı: her ünite `practice` ile kapanır, 4'ten fazla gramer dersi arka
 * arkaya gelmez (bkz. scripts/lint-curriculum.ts).
 */
export const B1: LevelSpec = {
  level: "B1",
  label: "Intermediate",
  units: [
    {
      index: 1,
      title: "Telling Your Story",
      goal: "Tell a longer story and make clear which event happened before which",
    },
    {
      index: 2,
      title: "Life So Far",
      goal: "Talk about your experience and how long you have been doing things",
    },
    {
      index: 3,
      title: "Plans and Predictions",
      goal: "Talk about the future in detail and say how likely something is",
    },
    {
      index: 4,
      title: "If and When",
      goal: "Talk about imaginary situations, conditions and things you would change",
    },
    {
      index: 5,
      title: "What People Say",
      goal: "Report what other people said, asked and told you to do",
    },
    {
      index: 6,
      title: "Things Get Done",
      goal: "Describe what happens to something without saying who does it",
    },
    {
      index: 7,
      title: "Describing People and Things",
      goal: "Add detail to a description using longer, joined-up sentences",
    },
    {
      index: 8,
      title: "Guessing and Concluding",
      goal: "Say what you think is true and how sure you are about it",
    },
    {
      index: 9,
      title: "Habits Then and Now",
      goal: "Compare how things used to be with how they are today",
    },
    {
      index: 10,
      title: "Choosing Your Words",
      goal: "Pick the right word pattern and explain yourself precisely",
    },
    {
      index: 11,
      title: "Putting It Together",
      goal: "Hold a real discussion: give your view, react, and keep it going",
    },
  ],
  lessons: [
    // --- Ünite 1 · Telling Your Story -------------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "grammar",
      title: "It Had Already Started",
      focus: "past perfect for an event that happened before another past event",
      themeHint: "arriving late and explaining what you missed",
      targetPhrases: ["it had already", "I had never", "by then we had"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "grammar",
      title: "By the Time I Got There",
      focus: "past perfect with by the time, already and just",
      themeHint: "describing a chain of events that went wrong",
      targetPhrases: ["by the time", "had just left", "we had already"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "Setting the Scene",
      focus: "past continuous and past simple working together in a story",
      themeHint: "describing where you were when you heard some news",
      targetPhrases: ["I was walking", "when I saw", "while we were"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "grammar",
      title: "What Had Happened Before",
      focus: "past perfect in questions and negatives",
      themeHint: "asking someone to fill in the missing part of a story",
      targetPhrases: ["had you ever", "I hadn't", "what had happened"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "phrases",
      title: "Suddenly, Meanwhile, Later",
      focus: "expressions that move a story from one moment to the next",
      themeHint: "retelling an eventful journey",
      targetPhrases: ["all of a sudden", "not long after", "in the meantime"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "A Story Worth Telling",
      focus: "telling a longer story about something that happened to you",
      themeHint: "two friends swapping stories over dinner",
      targetPhrases: ["you won't believe", "it turned out", "in the end"],
    },

    // --- Ünite 2 · Life So Far ---------------------------------------------------
    {
      position: 7,
      unitIndex: 2,
      kind: "grammar",
      title: "I've Lived Here for Years",
      focus: "present perfect with for and since",
      themeHint: "talking about how long you have done the things in your life",
      // "for three years" kişisel gerçek dayatıyordu — süre nötr olmalı (inceleme, Ağu 2026)
      targetPhrases: ["I've lived here", "for a long time", "since I was"],
    },
    {
      position: 8,
      unitIndex: 2,
      kind: "grammar",
      title: "Have You Finished Yet?",
      focus: "choosing between present perfect and past simple by time period",
      themeHint: "checking what is done and what is still open",
      targetPhrases: ["have you finished", "I did that", "not yet"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "I've Been Working on It",
      focus: "present perfect continuous for an activity still going on",
      themeHint: "explaining what has been keeping you busy lately",
      // "she's been away" hem kişisel gerçek hem de PPC bile değil — hedef yapıyı taşımıyordu
      targetPhrases: ["I've been working", "we've been trying", "I've been learning"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "grammar",
      title: "How Long Have You Been Doing That?",
      focus: "present perfect continuous in questions",
      themeHint: "getting to know what someone has been up to",
      // "since last year" kişisel gerçek dayatıyordu
      targetPhrases: ["how long have you", "have you been", "for a while"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "phrases",
      title: "Milestones and Firsts",
      focus: "talking about achievements and turning points in your life",
      themeHint: "comparing life stories with a new colleague",
      targetPhrases: ["I've just started", "it's been about", "for the first time"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "practice",
      title: "Where I've Got To",
      focus: "describing your progress in something you are working on",
      themeHint: "updating a friend on a long-running project",
      targetPhrases: ["so far I've", "I still haven't", "I'm getting there"],
    },

    // --- Ünite 3 · Plans and Predictions -----------------------------------------
    {
      position: 13,
      unitIndex: 3,
      kind: "grammar",
      title: "This Time Next Year",
      focus: "future continuous for something in progress at a future moment",
      themeHint: "imagining where you will be a year from now",
      targetPhrases: ["this time next year", "I'll be working", "we'll be living"],
    },
    {
      position: 14,
      unitIndex: 3,
      kind: "grammar",
      title: "I'll Have Finished by Then",
      focus: "future perfect for something completed before a future point",
      themeHint: "planning backwards from a deadline",
      // "we'll have moved" kişisel gerçek dayatıyordu
      targetPhrases: ["I'll have finished", "by next month", "by the end of"],
    },
    {
      position: 15,
      unitIndex: 3,
      kind: "phrases",
      title: "Likely, Bound To, Unlikely",
      focus: "saying how probable you think something is",
      themeHint: "predicting how a plan is going to turn out",
      targetPhrases: ["it's likely to", "bound to happen", "not very likely"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "phrases",
      title: "Making Arrangements",
      focus: "fixing plans with other people and confirming details",
      themeHint: "organising a group meet-up over messages",
      targetPhrases: ["shall we say", "does that suit you", "let's pencil it in"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "grammar",
      title: "Might, May, Could",
      focus: "talking about future possibility that is still open",
      themeHint: "discussing options none of you have decided on",
      targetPhrases: ["it might", "we could always", "there may be"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "practice",
      title: "The Year Ahead",
      focus: "talking about your plans, hopes and worries for the coming year",
      themeHint: "a New Year conversation between old friends",
      targetPhrases: ["I'm hoping to", "I'd really like", "if all goes well"],
    },

    // --- Ünite 4 · If and When ---------------------------------------------------
    {
      position: 19,
      unitIndex: 4,
      kind: "grammar",
      title: "If I Had More Time",
      focus: "second conditional for unreal or unlikely present situations",
      themeHint: "daydreaming about a completely different life",
      targetPhrases: ["if I had", "I would", "I'd probably"],
    },
    {
      position: 20,
      unitIndex: 4,
      kind: "grammar",
      title: "Unless You Ask",
      focus: "unless, as long as and provided that for stating conditions",
      themeHint: "explaining the terms of an offer",
      targetPhrases: ["unless you", "as long as", "provided that you"],
    },
    {
      position: 21,
      unitIndex: 4,
      kind: "grammar",
      title: "In Case It Rains",
      focus: "in case for precautions, and how it differs from if",
      themeHint: "packing for a trip with unpredictable weather",
      targetPhrases: ["in case it", "just in case", "take it with you"],
    },
    {
      position: 22,
      unitIndex: 4,
      kind: "grammar",
      title: "I Wish Things Were Different",
      focus: "wish and if only for regrets about the present",
      themeHint: "admitting what you would change about your situation",
      targetPhrases: ["I wish I", "if only", "I wish it were"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "phrases",
      title: "On the One Hand",
      focus: "weighing two sides of a question out loud",
      themeHint: "thinking through a difficult choice with a friend",
      targetPhrases: ["on the one hand", "then again", "all things considered"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "practice",
      title: "What Would You Do?",
      focus: "talking through imaginary situations and defending your answer",
      themeHint: "a what-would-you-do game between friends",
      targetPhrases: ["what would you do", "I'd probably", "I definitely wouldn't"],
    },

    // --- Ünite 5 · What People Say -----------------------------------------------
    {
      position: 25,
      unitIndex: 5,
      kind: "grammar",
      title: "He Said He Was Tired",
      focus: "reporting statements and shifting the words back in time",
      themeHint: "passing on what a colleague told you earlier",
      targetPhrases: ["he said he", "she told me", "they said they'd"],
    },
    {
      position: 26,
      unitIndex: 5,
      kind: "grammar",
      title: "She Asked Where I Lived",
      focus: "reporting questions and the word order they take",
      themeHint: "describing a job interview afterwards",
      targetPhrases: ["she asked me", "he wanted to know", "they asked whether"],
    },
    {
      position: 27,
      unitIndex: 5,
      kind: "grammar",
      title: "They Told Me to Wait",
      focus: "reporting requests, orders and advice",
      themeHint: "explaining the instructions you were given",
      targetPhrases: ["told me to", "asked me to", "advised me to"],
    },
    {
      position: 28,
      unitIndex: 5,
      kind: "grammar",
      title: "Admit, Deny, Suggest",
      focus: "reporting words that carry more meaning than say and tell",
      themeHint: "describing how a disagreement at work unfolded",
      targetPhrases: ["he admitted that", "she suggested", "they denied it"],
    },
    {
      position: 29,
      unitIndex: 5,
      kind: "phrases",
      title: "Passing On a Message",
      focus: "relaying what someone else said to a third person",
      themeHint: "taking a message for a colleague who is out",
      targetPhrases: ["message for you", "she said to tell", "I'll pass it on"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "practice",
      title: "What Did They Tell You?",
      focus: "retelling a whole conversation you were part of",
      themeHint: "comparing two versions of the same meeting",
      targetPhrases: ["they told me that", "apparently she", "that's not what I heard"],
    },

    // --- Ünite 6 · Things Get Done -----------------------------------------------
    {
      position: 31,
      unitIndex: 6,
      kind: "grammar",
      title: "It Was Built in 1900",
      focus: "past events described without saying who did them",
      themeHint: "showing a visitor around an old building",
      targetPhrases: ["it was built", "they were made", "was designed by"],
    },
    {
      position: 32,
      unitIndex: 6,
      kind: "grammar",
      title: "English Is Spoken Here",
      focus: "present habits and facts described without naming the doer",
      themeHint: "explaining how things work where you live",
      targetPhrases: ["is spoken", "are sold", "it's known as"],
    },
    {
      position: 33,
      unitIndex: 6,
      kind: "grammar",
      title: "It Has Been Repaired",
      focus: "recent results described without naming who produced them",
      themeHint: "reporting that a long-standing problem is sorted",
      targetPhrases: ["it has been", "they've been fixed", "has already been done"],
    },
    {
      position: 34,
      unitIndex: 6,
      kind: "grammar",
      title: "Who Was It Made By?",
      focus: "asking such questions and naming the doer when it matters",
      themeHint: "asking about where something came from",
      targetPhrases: ["who was it", "made by", "was it done by"],
    },
    {
      position: 35,
      unitIndex: 6,
      kind: "phrases",
      title: "Reporting an Incident",
      focus: "describing what happened when you cannot say who was responsible",
      themeHint: "reporting damage to a building manager",
      targetPhrases: ["something was taken", "it appears that", "no one was hurt"],
    },
    {
      position: 36,
      unitIndex: 6,
      kind: "practice",
      title: "How It's Made",
      focus: "explaining a process step by step",
      themeHint: "explaining your work to someone outside your field",
      targetPhrases: ["first it's", "then it gets", "after that it's"],
    },

    // --- Ünite 7 · Describing People and Things ----------------------------------
    {
      position: 37,
      unitIndex: 7,
      kind: "grammar",
      title: "The Woman Who Called",
      focus: "joining sentences with who, which and that to identify someone",
      themeHint: "picking out one person from a group",
      targetPhrases: ["people who", "something that", "anyone who wants"],
    },
    {
      position: 38,
      unitIndex: 7,
      kind: "grammar",
      title: "My Brother, Who Lives Abroad",
      focus: "adding extra information with commas around the added part",
      themeHint: "adding detail about people as you mention them",
      // "my brother who" non-defining hedefi virgülsüz temsil ediyordu (defining okunur) — çıkarıldı
      targetPhrases: ["which was lovely", "who happens to be"],
    },
    {
      position: 39,
      unitIndex: 7,
      kind: "grammar",
      title: "The Place Where We Met",
      focus: "using where, when and whose to join sentences",
      themeHint: "describing a place that has a story attached to it",
      targetPhrases: ["where we met", "whose name is", "when it happened"],
    },
    {
      position: 40,
      unitIndex: 7,
      kind: "grammar",
      title: "A Nice Old Wooden Table",
      focus: "the order describing words go in before a thing",
      themeHint: "describing furniture at a second-hand market",
      targetPhrases: ["nice old", "small round", "big red one"],
    },
    {
      position: 41,
      unitIndex: 7,
      kind: "phrases",
      title: "Hard to Describe",
      focus: "describing something when you do not know the exact word",
      themeHint: "explaining what you need in a hardware shop",
      targetPhrases: ["it's a kind of", "sort of like", "what do you call"],
    },
    {
      position: 42,
      unitIndex: 7,
      kind: "practice",
      title: "Someone I Admire",
      focus: "describing a person in detail and saying why they matter to you",
      themeHint: "telling someone about a person who shaped your life",
      targetPhrases: ["what I admire", "he's the kind of", "she always used to"],
    },

    // --- Ünite 8 · Guessing and Concluding ---------------------------------------
    {
      position: 43,
      unitIndex: 8,
      kind: "grammar",
      title: "She Must Be Tired",
      focus: "must, might and can't for working out what is true now",
      themeHint: "guessing what is going on with someone you know",
      targetPhrases: ["she must be", "it can't be", "he might be"],
    },
    {
      position: 44,
      unitIndex: 8,
      kind: "grammar",
      title: "It Can't Have Been Him",
      focus: "must have, might have and can't have for working out the past",
      themeHint: "arguing about what really happened last night",
      targetPhrases: ["must have been", "can't have", "might have gone"],
    },
    {
      position: 45,
      unitIndex: 8,
      kind: "phrases",
      title: "It Looks Like Rain",
      focus: "saying what something seems or appears to be",
      themeHint: "commenting on a situation you are not sure about",
      targetPhrases: ["it looks like", "seems to be", "sounds like"],
    },
    {
      position: 46,
      unitIndex: 8,
      kind: "phrases",
      title: "I'm Not Sure, But",
      focus: "softening a guess so you are not fully committed to it",
      themeHint: "offering an opinion carefully in a meeting",
      targetPhrases: ["I'm not sure but", "I could be wrong", "as far as I know"],
    },
    {
      position: 47,
      unitIndex: 8,
      kind: "phrases",
      title: "Apparently, It Turns Out",
      focus: "passing on something you heard without vouching for it",
      themeHint: "sharing news that went round the office",
      targetPhrases: ["it turns out", "apparently he", "I heard that"],
    },
    {
      position: 48,
      unitIndex: 8,
      kind: "practice",
      title: "Solving a Mystery",
      focus: "working out what happened from the clues you have",
      themeHint: "piecing together a strange event with a friend",
      targetPhrases: ["it must have", "that would explain", "I bet it was"],
    },

    // --- Ünite 9 · Habits Then and Now -------------------------------------------
    {
      position: 49,
      unitIndex: 9,
      kind: "grammar",
      title: "I Used to Smoke",
      focus: "used to for habits and states that have stopped",
      themeHint: "talking about who you were ten years ago",
      targetPhrases: ["I used to", "didn't use to", "did you use to"],
    },
    {
      position: 50,
      unitIndex: 9,
      kind: "grammar",
      title: "We Would Spend Summers There",
      focus: "would for actions repeated again and again in the past",
      themeHint: "remembering childhood routines",
      targetPhrases: ["we would always", "every summer we'd", "he would often"],
    },
    {
      position: 51,
      unitIndex: 9,
      kind: "grammar",
      title: "I'm Getting Used to It",
      focus: "be used to and get used to for what has become normal",
      themeHint: "adjusting to a big change in your life",
      targetPhrases: ["I'm used to", "getting used to", "not used to"],
    },
    {
      position: 52,
      unitIndex: 9,
      kind: "grammar",
      title: "Always Complaining",
      focus: "always with the -ing form for habits that irritate you",
      themeHint: "grumbling affectionately about someone close to you",
      targetPhrases: ["he's always", "she's forever", "they're constantly"],
    },
    {
      position: 53,
      unitIndex: 9,
      kind: "phrases",
      title: "How Things Have Changed",
      focus: "comparing how things were with how they are now",
      themeHint: "talking about how your city has changed",
      targetPhrases: ["these days", "back then", "it's not the same"],
    },
    {
      position: 54,
      unitIndex: 9,
      kind: "practice",
      title: "Then and Now",
      focus: "describing how your own life has changed over the years",
      themeHint: "catching up with someone after many years apart",
      targetPhrases: ["back in those days", "now I tend to", "so much has changed"],
    },

    // --- Ünite 10 · Choosing Your Words ------------------------------------------
    {
      position: 55,
      unitIndex: 10,
      kind: "grammar",
      title: "I Enjoy Reading, I Want to Read",
      focus: "which common words are followed by -ing and which by to",
      themeHint: "talking about what you like and what you plan to do",
      targetPhrases: ["I enjoy", "I want to", "I'd rather"],
    },
    {
      position: 56,
      unitIndex: 10,
      kind: "grammar",
      title: "I Stopped Smoking, I Stopped to Smoke",
      focus: "words whose meaning changes depending on -ing or to",
      themeHint: "clearing up a misunderstanding caused by one word",
      targetPhrases: ["I stopped doing", "I remember meeting", "I tried calling"],
    },
    {
      position: 57,
      unitIndex: 10,
      kind: "grammar",
      title: "Look Up, Look After",
      focus: "common two-word expressions and where the object goes",
      themeHint: "everyday instructions around the house",
      targetPhrases: ["look it up", "look after", "pick them up"],
    },
    {
      position: 58,
      unitIndex: 10,
      kind: "phrases",
      title: "Saying It More Precisely",
      focus: "choosing a more exact word than the first one that comes to mind",
      themeHint: "describing a problem to someone who can fix it",
      targetPhrases: ["more like", "to be precise", "what I mean is"],
    },
    {
      position: 59,
      unitIndex: 10,
      kind: "grammar",
      title: "It's Worth Trying",
      focus: "fixed expressions that take an -ing word after them",
      themeHint: "encouraging someone to give something a go",
      targetPhrases: ["it's worth", "there's no point", "I can't help"],
    },
    {
      position: 60,
      unitIndex: 10,
      kind: "grammar",
      title: "Although, However, Despite",
      focus: "showing contrast between two ideas in one stretch of speech",
      themeHint: "presenting both sides of a decision you have made",
      targetPhrases: ["although it was", "even though", "despite that"],
    },
    {
      position: 61,
      unitIndex: 10,
      kind: "practice",
      title: "Explaining Yourself Clearly",
      focus: "explaining something complicated in simple words",
      themeHint: "teaching a friend something you know well",
      targetPhrases: ["let me put it", "in other words", "does that make sense"],
    },

    // --- Ünite 11 · Putting It Together ------------------------------------------
    {
      position: 62,
      unitIndex: 11,
      kind: "grammar",
      title: "You're Coming, Aren't You?",
      focus: "short check questions added to the end of a sentence",
      themeHint: "confirming arrangements informally",
      targetPhrases: ["aren't you", "isn't it", "haven't we"],
    },
    {
      position: 63,
      unitIndex: 11,
      kind: "grammar",
      title: "So Tired, Such a Long Day",
      focus: "so and such for adding force to what you say",
      themeHint: "complaining about an exhausting day",
      targetPhrases: ["so tired", "such a long", "it was so"],
    },
    {
      position: 64,
      unitIndex: 11,
      kind: "grammar",
      title: "Enough, Too Much, Plenty",
      focus: "talking about amounts precisely",
      themeHint: "working out how much of something is needed",
      targetPhrases: ["not enough", "too much", "plenty of time"],
    },
    {
      position: 65,
      unitIndex: 11,
      kind: "phrases",
      title: "Getting Your Point Across",
      focus: "giving an opinion and agreeing or disagreeing with force",
      themeHint: "a lively discussion among friends",
      targetPhrases: ["in my view", "I couldn't agree more", "I see your point"],
    },
    {
      position: 66,
      unitIndex: 11,
      kind: "phrases",
      title: "Keeping a Conversation Going",
      focus: "follow-up questions and reactions that invite someone to say more",
      themeHint: "drawing out a new acquaintance",
      targetPhrases: ["that's interesting", "how come", "tell me more about"],
    },
    {
      position: 67,
      unitIndex: 11,
      kind: "practice",
      title: "A Real Discussion",
      focus: "discussing a topic you genuinely care about",
      themeHint: "a conversation that gets properly into a subject",
      targetPhrases: ["what strikes me is", "I've always thought", "to be honest"],
    },
    {
      position: 68,
      unitIndex: 11,
      kind: "practice",
      title: "Telling It Like It Is",
      focus: "giving your honest view even when it is uncomfortable",
      themeHint: "giving feedback to someone whose work you respect",
      targetPhrases: ["I have to say", "if I'm honest", "no offence but"],
    },
  ],
};
