import type { LevelSpec } from "./types.js";

/**
 * B2 — Upper-Intermediate. 11 ünite, 74 ders.
 *
 * B1 olayları birbirine bağlamayı öğretti; B2 öğrenciyi TUTUM sahibi yapar:
 * olmamış geçmişi tartışmak (3. koşul), sorumluluğu bulanıklaştırmak (aktarım ve
 * ettirgen), vurguyu yönetmek (yarma cümleler, devrik yapı), kesinlik derecesini
 * ayarlamak, kayıt değiştirmek (resmi/samimi).
 *
 * Gramer oranı B1'e göre düşer, `practice` payı yükselir: bu seviyede öğrenciyi
 * tıkayan şey kural bilgisi değil, uzun konuşmayı taşıyamamak.
 */
export const B2: LevelSpec = {
  level: "B2",
  label: "Upper-Intermediate",
  units: [
    {
      index: 1,
      title: "Looking Back with Regret",
      goal: "Talk about how the past could have gone differently and what you would change",
    },
    {
      index: 2,
      title: "What Might Have Been",
      goal: "Discuss alternatives to what actually happened and judge past decisions",
    },
    {
      index: 3,
      title: "Reporting and Rumour",
      goal: "Report what is claimed without taking responsibility for it",
    },
    {
      index: 4,
      title: "Getting Things Done by Others",
      goal: "Arrange for other people to do things and complain when they go wrong",
    },
    {
      index: 5,
      title: "Describing Complex Situations",
      goal: "Pack more information into fewer, longer sentences",
    },
    {
      index: 6,
      title: "Emphasis and Focus",
      goal: "Put the weight of a sentence exactly where you want it",
    },
    {
      index: 7,
      title: "Degrees of Certainty",
      goal: "Show precisely how confident you are about a claim",
    },
    {
      index: 8,
      title: "Contrast and Concession",
      goal: "Concede a point and still make your own, in one breath",
    },
    {
      index: 9,
      title: "Shades of Meaning",
      goal: "Choose between near-synonyms and say difficult things kindly",
    },
    {
      index: 10,
      title: "Formal and Informal",
      goal: "Move between formal and casual English on purpose",
    },
    {
      index: 11,
      title: "Discussing Real Issues",
      goal: "Hold your own in a real discussion and bring it to a close",
    },
  ],
  lessons: [
    // --- Ünite 1 · Looking Back with Regret --------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "grammar",
      title: "If I Had Known",
      focus: "third conditional: setting up a past situation that did not happen",
      themeHint: "explaining why you did not act at the time",
      targetPhrases: ["if I had known", "had I known", "if only I'd"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "grammar",
      title: "I Would Have Called",
      focus: "third conditional: the result half of the sentence",
      themeHint: "apologising for something you failed to do",
      targetPhrases: ["I would have", "we'd have", "it would have been"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "I Should Have Listened",
      focus: "should have and ought to have for regret and criticism",
      themeHint: "admitting you ignored good advice",
      targetPhrases: ["I should have", "you shouldn't have", "ought to have"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "grammar",
      title: "If I Had Studied, I'd Be Rich Now",
      focus: "mixed conditional: a past cause with a present result",
      themeHint: "tracing today's situation back to one old decision",
      targetPhrases: ["if I'd studied", "I'd be", "we would be now"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "phrases",
      title: "Looking Back",
      focus: "expressions for regret and hindsight",
      themeHint: "reflecting honestly on a rough period",
      targetPhrases: ["looking back", "with hindsight", "at the time I"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "The Turning Point",
      focus: "talking about a single decision that changed your direction",
      themeHint: "a long conversation about how life took its shape",
      targetPhrases: ["that's when everything", "it all changed", "if that hadn't"],
    },
    {
      position: 7,
      unitIndex: 1,
      kind: "practice",
      title: "What I'd Do Differently",
      focus: "reflecting on a mistake and what you learned from it",
      themeHint: "mentoring someone about to make the same choice",
      targetPhrases: ["what I'd change", "next time I'd", "I'd never do that"],
    },

    // --- Ünite 2 · What Might Have Been ------------------------------------------
    {
      position: 8,
      unitIndex: 2,
      kind: "grammar",
      title: "It Might Have Been Worse",
      focus: "might have and could have for possibilities in the past",
      themeHint: "putting a near miss into perspective",
      targetPhrases: ["might have been", "could have gone", "it could've"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "You Needn't Have Bothered",
      focus: "needn't have and didn't need to, and how they differ",
      themeHint: "reacting to an unnecessary favour",
      targetPhrases: ["you needn't have", "I didn't need to", "there was no need"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "grammar",
      title: "I'd Rather You Hadn't",
      focus: "would rather and would sooner pointing at the past",
      themeHint: "telling someone their help was not welcome",
      targetPhrases: ["I'd rather you", "I'd sooner", "I wish you hadn't"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "phrases",
      title: "Suppose We Had Gone",
      focus: "playing out a past that never happened",
      themeHint: "two friends replaying an old what-if",
      targetPhrases: ["suppose we had", "imagine if we'd", "what if we had"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "phrases",
      title: "It Was Meant to Be",
      focus: "expressions about luck, fate and coincidence",
      themeHint: "telling the story of an unlikely meeting",
      targetPhrases: ["meant to be", "just as well", "as luck would have"],
    },
    {
      position: 13,
      unitIndex: 2,
      kind: "practice",
      title: "Was It Worth It?",
      focus: "judging whether a past decision paid off",
      themeHint: "weighing up a costly choice years later",
      targetPhrases: ["was it worth", "on balance", "I don't regret"],
    },
    {
      position: 14,
      unitIndex: 2,
      kind: "practice",
      title: "An Alternative Life",
      focus: "imagining in detail the path you did not take",
      themeHint: "a late-night conversation about roads not taken",
      targetPhrases: ["I might have ended", "who knows where", "things would be"],
    },

    // --- Ünite 3 · Reporting and Rumour ------------------------------------------
    {
      position: 15,
      unitIndex: 3,
      kind: "grammar",
      title: "It Is Said That",
      focus: "impersonal reporting with it is said and it is believed",
      themeHint: "summarising what people generally claim",
      targetPhrases: ["it is said", "it is believed", "it's thought that"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "grammar",
      title: "He Is Thought to Be",
      focus: "the personal reporting pattern with is thought and is said",
      themeHint: "describing a public figure from second-hand accounts",
      targetPhrases: ["he is thought", "she is said", "they are believed"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "grammar",
      title: "She Denied Taking It",
      focus: "reporting words followed by an -ing word",
      themeHint: "recounting how an accusation was handled",
      targetPhrases: ["denied taking", "admitted knowing", "suggested waiting"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "grammar",
      title: "He Refused to Comment",
      focus: "reporting words followed by to and an action",
      themeHint: "describing how a request was answered",
      targetPhrases: ["refused to", "agreed to", "promised to send"],
    },
    {
      position: 19,
      unitIndex: 3,
      kind: "phrases",
      title: "Sources and Hedging",
      focus: "quoting a source without committing to it yourself",
      themeHint: "relaying information you cannot verify",
      targetPhrases: ["according to", "sources say", "it has emerged"],
    },
    {
      position: 20,
      unitIndex: 3,
      kind: "phrases",
      title: "Rumour Has It",
      focus: "passing on unverified news and flagging it as such",
      themeHint: "office gossip that may or may not be true",
      targetPhrases: ["rumour has it", "word is that", "so I'm told"],
    },
    {
      position: 21,
      unitIndex: 3,
      kind: "practice",
      title: "The Story Behind the Headline",
      focus: "discussing a news story and how far it can be trusted",
      themeHint: "two people reading the same story differently",
      targetPhrases: ["what's actually happened", "I'd take that with", "who's saying this"],
    },

    // --- Ünite 4 · Getting Things Done by Others ---------------------------------
    {
      position: 22,
      unitIndex: 4,
      kind: "grammar",
      title: "I Had My Hair Cut",
      focus: "have something done for services you arrange",
      themeHint: "describing what you paid someone else to do",
      targetPhrases: ["I had my hair", "I got it done", "have it cleaned"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "grammar",
      title: "We Got the Roof Fixed",
      focus: "get something done, and when it feels different from have",
      themeHint: "talking through work on your home",
      targetPhrases: ["we got it fixed", "getting it repaired", "had it replaced"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "grammar",
      title: "I Need This Sorted",
      focus: "need and want followed by a finished result",
      themeHint: "pressing for something to be dealt with",
      targetPhrases: ["I need this", "I want it done", "we need it fixed"],
    },
    {
      position: 25,
      unitIndex: 4,
      kind: "grammar",
      title: "Make, Let, Help",
      focus: "making someone do something and allowing them to",
      themeHint: "describing how a strict or relaxed boss operates",
      targetPhrases: ["they made me", "she let me", "he helped me"],
    },
    {
      position: 26,
      unitIndex: 4,
      kind: "phrases",
      title: "Arranging Services",
      focus: "booking work and chasing it up",
      themeHint: "calling a tradesperson about a job",
      targetPhrases: ["could you come out", "when could you", "how much would that be"],
    },
    {
      position: 27,
      unitIndex: 4,
      kind: "phrases",
      title: "When It Goes Wrong",
      focus: "complaining about work that was done badly",
      themeHint: "following up on a job that was not finished properly",
      targetPhrases: ["it still isn't", "you said you'd", "I'd like it redone"],
    },
    {
      position: 28,
      unitIndex: 4,
      kind: "practice",
      title: "Sorting Out the House",
      focus: "organising several pieces of work over the phone",
      themeHint: "coordinating a small renovation",
      targetPhrases: ["I'm calling about", "we'd like to get", "when can you start"],
    },

    // --- Ünite 5 · Describing Complex Situations ---------------------------------
    {
      position: 29,
      unitIndex: 5,
      kind: "grammar",
      title: "Having Finished, She Left",
      focus: "opening a sentence with having plus a finished action",
      themeHint: "narrating a sequence of events efficiently",
      targetPhrases: ["having finished", "having said that", "having done that"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "grammar",
      title: "Built in 1920, It Still Stands",
      focus: "opening a sentence with a done-form to add background",
      themeHint: "describing a building or an object with a history",
      targetPhrases: ["built in", "founded in", "written by hand"],
    },
    {
      position: 31,
      unitIndex: 5,
      kind: "grammar",
      title: "The Man Standing Over There",
      focus: "adding an -ing description straight after the thing described",
      themeHint: "pointing someone out in a crowd",
      targetPhrases: ["standing over there", "sitting next to", "waiting outside"],
    },
    {
      position: 32,
      unitIndex: 5,
      kind: "grammar",
      title: "Both of Which Were Late",
      focus: "quantity words inside a joined-up sentence",
      themeHint: "summarising several related problems at once",
      targetPhrases: ["both of which", "all of whom", "some of which"],
    },
    {
      position: 33,
      unitIndex: 5,
      kind: "phrases",
      title: "Painting a Picture",
      focus: "vivid description that puts the listener in the scene",
      themeHint: "describing somewhere you have just come back from",
      targetPhrases: ["picture this", "it's the kind of place", "you can almost hear"],
    },
    {
      position: 34,
      unitIndex: 5,
      kind: "practice",
      title: "A Place I Know Well",
      focus: "describing a complex place richly and at length",
      themeHint: "convincing someone to visit somewhere you love",
      targetPhrases: ["what I love about", "every time I go", "it hasn't changed"],
    },
    {
      position: 35,
      unitIndex: 5,
      kind: "practice",
      title: "Explaining a Situation",
      focus: "laying out something complicated so it can be followed",
      themeHint: "bringing a colleague up to speed on a tangled problem",
      targetPhrases: ["let me back up", "so basically", "what it comes down to"],
    },

    // --- Ünite 6 · Emphasis and Focus --------------------------------------------
    {
      position: 36,
      unitIndex: 6,
      kind: "grammar",
      title: "What I Need Is Time",
      focus: "starting with what to push the important part to the end",
      themeHint: "stating clearly what you actually want",
      targetPhrases: ["what I need is", "what happened was", "what bothers me is"],
    },
    {
      position: 37,
      unitIndex: 6,
      kind: "grammar",
      title: "It Was You Who Said It",
      focus: "starting with it was to single one element out",
      themeHint: "correcting someone's account of events",
      targetPhrases: ["it was you who", "it's this that", "it was then that"],
    },
    {
      position: 38,
      unitIndex: 6,
      kind: "grammar",
      title: "Never Have I Seen That",
      focus: "putting a negative word first and flipping the order after it",
      themeHint: "reacting strongly to something remarkable",
      targetPhrases: ["never have I", "not only did", "rarely do we"],
    },
    {
      position: 39,
      unitIndex: 6,
      kind: "phrases",
      title: "The Thing Is",
      focus: "flagging the important part of what you are about to say",
      themeHint: "getting to the heart of a disagreement",
      targetPhrases: ["thing is", "here's the thing", "my point is"],
    },
    {
      position: 40,
      unitIndex: 6,
      kind: "phrases",
      title: "Absolutely, Utterly, Completely",
      focus: "intensifying words and which ones pair with which",
      themeHint: "reacting with feeling to news",
      targetPhrases: ["absolutely right", "utterly wrong", "completely different"],
    },
    {
      position: 41,
      unitIndex: 6,
      kind: "practice",
      title: "Making a Case",
      focus: "arguing a point and making the key part land",
      themeHint: "persuading a group to back your proposal",
      targetPhrases: ["my argument is", "consider this", "that's precisely why"],
    },
    {
      position: 42,
      unitIndex: 6,
      kind: "practice",
      title: "Standing Your Ground",
      focus: "holding your position when someone pushes back",
      themeHint: "a disagreement where neither side gives up easily",
      targetPhrases: ["I still think", "I take your point but", "that doesn't change"],
    },

    // --- Ünite 7 · Degrees of Certainty ------------------------------------------
    {
      position: 43,
      unitIndex: 7,
      kind: "grammar",
      title: "It's Bound to Happen",
      focus: "expressing near-certainty about what is coming",
      themeHint: "predicting an outcome you consider inevitable",
      targetPhrases: ["bound to", "certain to", "it's only a matter"],
    },
    {
      position: 44,
      unitIndex: 7,
      kind: "grammar",
      title: "She's Unlikely to Agree",
      focus: "expressing improbability without saying no outright",
      themeHint: "managing expectations before a difficult meeting",
      targetPhrases: ["unlikely to", "I doubt", "there's little chance"],
    },
    {
      position: 45,
      unitIndex: 7,
      kind: "grammar",
      title: "It May Well Be",
      focus: "strengthening and weakening a guess with small words",
      themeHint: "commenting on an uncertain forecast",
      targetPhrases: ["may well be", "could well", "might just"],
    },
    {
      position: 46,
      unitIndex: 7,
      kind: "phrases",
      title: "Presumably, Allegedly",
      focus: "single words that signal how sure you are",
      themeHint: "discussing a story where the facts are unclear",
      targetPhrases: ["presumably he", "allegedly she", "supposedly it"],
    },
    {
      position: 47,
      unitIndex: 7,
      kind: "phrases",
      title: "Hedging Your Bets",
      focus: "committing to less than you actually believe",
      themeHint: "answering a question you cannot fully back up",
      targetPhrases: ["I'd say roughly", "more or less", "give or take"],
    },
    {
      position: 48,
      unitIndex: 7,
      kind: "practice",
      title: "Reading the Signs",
      focus: "interpreting an ambiguous situation out loud",
      themeHint: "two colleagues working out what a decision really means",
      targetPhrases: ["that suggests", "it points to", "reading between the lines"],
    },
    {
      position: 49,
      unitIndex: 7,
      kind: "practice",
      title: "How Sure Are You?",
      focus: "defending a prediction and admitting its limits",
      themeHint: "being challenged on a confident claim",
      targetPhrases: ["I'm fairly confident", "I wouldn't bet on", "I'd put money on"],
    },

    // --- Ünite 8 · Contrast and Concession ---------------------------------------
    {
      position: 50,
      unitIndex: 8,
      kind: "grammar",
      title: "Despite Being Tired",
      focus: "despite and in spite of followed by an -ing word",
      themeHint: "describing something you did against the odds",
      targetPhrases: ["despite being", "in spite of", "despite having"],
    },
    {
      position: 51,
      unitIndex: 8,
      kind: "grammar",
      title: "Whereas I Prefer Quiet",
      focus: "whereas and while for setting two things directly against each other",
      themeHint: "comparing two very different personalities",
      targetPhrases: ["whereas I", "while she", "I on the other hand"],
    },
    {
      position: 52,
      unitIndex: 8,
      kind: "grammar",
      title: "Even If It Costs More",
      focus: "even if and even though, and the difference between them",
      themeHint: "committing to a course of action regardless",
      targetPhrases: ["even if", "even though", "even so"],
    },
    {
      position: 53,
      unitIndex: 8,
      kind: "grammar",
      title: "Much As I'd Like To",
      focus: "conceding first in order to refuse politely",
      themeHint: "turning down something you genuinely wanted",
      targetPhrases: ["much as I'd like", "tempting as it is", "I'm afraid I can't"],
    },
    {
      position: 54,
      unitIndex: 8,
      kind: "phrases",
      title: "Yes, But Then Again",
      focus: "granting a point before making your own",
      themeHint: "a debate where both sides have something right",
      targetPhrases: ["fair enough but", "that said", "having said that"],
    },
    {
      position: 55,
      unitIndex: 8,
      kind: "practice",
      title: "Pros and Cons",
      focus: "arguing both sides of a real question and landing somewhere",
      themeHint: "deciding as a pair whether to take a risk",
      targetPhrases: ["on the plus side", "downside is", "weighing it up"],
    },
    {
      position: 56,
      unitIndex: 8,
      kind: "practice",
      title: "Changing Your Mind",
      focus: "being persuaded and saying so gracefully",
      themeHint: "a conversation that genuinely shifts your view",
      targetPhrases: ["you've convinced me", "I hadn't thought of", "fair point"],
    },

    // --- Ünite 9 · Shades of Meaning ---------------------------------------------
    {
      position: 57,
      unitIndex: 9,
      kind: "grammar",
      title: "Remember to Do, Remember Doing",
      focus: "words whose meaning flips between to and -ing",
      themeHint: "sorting out a confusion about who was told what",
      targetPhrases: ["remember to call", "remember calling", "I forgot to"],
    },
    {
      position: 58,
      unitIndex: 9,
      kind: "grammar",
      title: "I Regret to Tell You",
      focus: "formal announcements with regret, be pleased and be sorry",
      themeHint: "delivering an official decision",
      targetPhrases: ["I regret to", "I'm pleased to", "we're sorry to"],
    },
    {
      position: 59,
      unitIndex: 9,
      kind: "grammar",
      title: "Slightly, Fairly, Somewhat",
      focus: "softening how strong a description is",
      themeHint: "giving a measured assessment of something",
      targetPhrases: ["slightly better", "fairly good", "somewhat unusual"],
    },
    {
      position: 60,
      unitIndex: 9,
      kind: "grammar",
      title: "Nearly, Barely, Hardly",
      focus: "near-negative words and what they quietly imply",
      themeHint: "describing a close call",
      targetPhrases: ["barely enough", "hardly any", "nearly finished"],
    },
    {
      position: 61,
      unitIndex: 9,
      kind: "phrases",
      title: "Close Enough",
      focus: "approximating when you do not have exact facts",
      themeHint: "giving numbers you are not certain of",
      targetPhrases: ["roughly speaking", "somewhere around", "give or take a bit"],
    },
    {
      position: 62,
      unitIndex: 9,
      kind: "phrases",
      title: "Loaded Words",
      focus: "choosing between words that mean the same but feel different",
      themeHint: "describing the same person kindly and unkindly",
      targetPhrases: ["I'd call it", "you could say", "that's putting it mildly"],
    },
    {
      position: 63,
      unitIndex: 9,
      kind: "practice",
      title: "Saying It Kindly",
      focus: "delivering an unwelcome opinion without causing offence",
      themeHint: "telling a friend something they will not want to hear",
      targetPhrases: ["I hope you don't mind", "with respect", "can I be frank"],
    },

    // --- Ünite 10 · Formal and Informal ------------------------------------------
    {
      position: 64,
      unitIndex: 10,
      kind: "phrases",
      title: "Would You Be So Kind",
      focus: "formal requests and how far up the scale to go",
      themeHint: "asking a favour of someone senior",
      targetPhrases: ["would you be so kind", "I wonder if you could", "if it's not too much"],
    },
    {
      position: 65,
      unitIndex: 10,
      kind: "phrases",
      title: "Give Us a Hand",
      focus: "casual requests between people who know each other",
      themeHint: "asking a friend for help moving something",
      targetPhrases: ["give us a hand", "can you grab", "do us a favour"],
    },
    {
      position: 66,
      unitIndex: 10,
      kind: "phrases",
      title: "I Am Writing to Enquire",
      focus: "the language of a formal written message",
      themeHint: "contacting an organisation you have no relationship with",
      targetPhrases: ["I am writing to", "I would be grateful", "please find attached"],
    },
    {
      position: 67,
      unitIndex: 10,
      kind: "phrases",
      title: "Just a Quick One",
      focus: "the language of a casual written message",
      themeHint: "messaging a colleague you get on with",
      targetPhrases: ["quick one", "just checking", "let me know"],
    },
    {
      position: 68,
      unitIndex: 10,
      kind: "grammar",
      title: "Softening the Blow",
      focus: "distancing language that makes bad news land more gently",
      themeHint: "announcing a decision people will not like",
      targetPhrases: ["unfortunately we", "I'm afraid there's", "it seems there may be"],
    },
    {
      position: 69,
      unitIndex: 10,
      kind: "practice",
      title: "A Difficult Email",
      focus: "working out how to raise a delicate matter in writing",
      themeHint: "raising a problem with someone you must keep working with",
      targetPhrases: ["I wanted to raise", "I appreciate that", "would it be possible"],
    },
    {
      position: 70,
      unitIndex: 10,
      kind: "practice",
      title: "Same Thing, Two Ways",
      focus: "saying one message formally and then casually",
      themeHint: "the same news given to a client and to a friend",
      targetPhrases: ["formally you'd say", "but you'd tell a friend", "same thing really"],
    },

    // --- Ünite 11 · Discussing Real Issues ---------------------------------------
    {
      position: 71,
      unitIndex: 11,
      kind: "phrases",
      title: "Backing Up an Opinion",
      focus: "supporting a claim with reasons and examples",
      themeHint: "being asked to justify something you asserted",
      targetPhrases: ["for instance", "take for example", "that's borne out by"],
    },
    {
      position: 72,
      unitIndex: 11,
      kind: "practice",
      title: "Where Do You Stand?",
      focus: "taking and defending a position on a contested topic",
      themeHint: "a discussion where people genuinely disagree",
      targetPhrases: ["I come down on", "where I stand is", "I feel strongly that"],
    },
    {
      position: 73,
      unitIndex: 11,
      kind: "practice",
      title: "Finding Common Ground",
      focus: "moving a disagreement towards something both sides accept",
      themeHint: "two people trying to settle a long-running argument",
      targetPhrases: ["we both agree that", "where we differ", "can we settle on"],
    },
    {
      position: 74,
      unitIndex: 11,
      kind: "practice",
      title: "Wrapping Up a Discussion",
      focus: "summarising what was said and closing cleanly",
      themeHint: "bringing a long conversation to an end",
      targetPhrases: ["to sum up", "so where does that leave", "let's leave it there"],
    },
  ],
};
