import type { LevelSpec } from "./types.js";

/**
 * C1 — Advanced. 10 ünite, 64 ders.
 *
 * Buradan itibaren ağırlık merkezi gramerden KULLANIMA kayar. C1 öğrencisi
 * yapıları zaten biliyor; eksik olan şey vurguyu yönetmek, ima etmek, kayıt
 * değiştirmek, uzun bir konuşmayı taşımak ve tartışmada ayakta kalmak.
 *
 * Bu yüzden gramer oranı belirgin biçimde düşer, `practice` ve `phrases` payı
 * yükselir. Gramer dersleri kalan az sayıdaki ileri yapıya ayrılmıştır
 * (devrik yapı, gerçek dışı geçmiş, eksilti, adlaştırma).
 */
export const C1: LevelSpec = {
  level: "C1",
  label: "Advanced",
  units: [
    {
      index: 1,
      title: "The Art of Emphasis",
      goal: "Put the weight of what you say exactly where you intend it",
    },
    {
      index: 2,
      title: "Unreal and Hypothetical",
      goal: "Reason about situations that are not and never were the case",
    },
    {
      index: 3,
      title: "Saying Less, Meaning More",
      goal: "Leave things out on purpose and pick up what others leave out",
    },
    {
      index: 4,
      title: "Formal Register",
      goal: "Speak and write in official English without sounding stiff",
    },
    {
      index: 5,
      title: "Building an Argument",
      goal: "Construct a case, concede fairly, and answer objections",
    },
    {
      index: 6,
      title: "Narrative Craft",
      goal: "Tell a story that holds attention and lands its point",
    },
    {
      index: 7,
      title: "Precision and Nuance",
      goal: "Find the exact word and the exact degree",
    },
    {
      index: 8,
      title: "Professional Communication",
      goal: "Disagree, negotiate and deliver hard news without damage",
    },
    {
      index: 9,
      title: "Culture and Idiom",
      goal: "Handle idiom, humour and the unwritten rules of a conversation",
    },
    {
      index: 10,
      title: "Extended Discussion",
      goal: "Hold the floor at length on anything, including what you do not know",
    },
  ],
  lessons: [
    // --- Ünite 1 · The Art of Emphasis -------------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "grammar",
      title: "Not Only Did She Come",
      focus: "flipping the word order after a negative opener for emphasis",
      themeHint: "recounting something that exceeded every expectation",
      targetPhrases: ["not only did", "no sooner had", "not once did"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "grammar",
      title: "Only Then Did I Realise",
      focus: "flipping the order after only, not until and no sooner",
      themeHint: "describing a delayed realisation",
      targetPhrases: ["only then did", "only after", "not until then"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "It Is Precisely This That",
      focus: "advanced front-loading to pinpoint one element",
      themeHint: "correcting a misreading of your position",
      targetPhrases: ["it is precisely", "what matters here is", "this is exactly what"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "phrases",
      title: "What Struck Me Most",
      focus: "foregrounding your own reaction to something",
      themeHint: "reporting back on an experience that affected you",
      targetPhrases: ["what struck me", "what stood out", "what I noticed was"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "practice",
      title: "Driving a Point Home",
      focus: "arguing with deliberate emphasis so the key point cannot be missed",
      themeHint: "a discussion where you have one thing you need understood",
      targetPhrases: ["let me be clear", "make no mistake", "I cannot stress enough"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "Understated but Firm",
      focus: "making a strong point quietly rather than loudly",
      themeHint: "holding a line without raising your voice",
      targetPhrases: ["I'd simply note", "it's worth remembering", "I'll leave it there"],
    },

    // --- Ünite 2 · Unreal and Hypothetical ---------------------------------------
    {
      position: 7,
      unitIndex: 2,
      kind: "grammar",
      title: "Were I to Suggest",
      focus: "hypothetical sentences built without if",
      themeHint: "floating an idea carefully in a formal setting",
      targetPhrases: ["were I to", "were it not", "should that happen"],
    },
    {
      position: 8,
      unitIndex: 2,
      kind: "grammar",
      title: "Had It Not Been for You",
      focus: "had it not been for and but for, to credit or blame a cause",
      themeHint: "acknowledging someone who changed an outcome",
      targetPhrases: ["had it not been", "but for your", "if it weren't for"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "It's Time You Decided",
      focus: "the unreal past after it's time, would rather and suppose",
      themeHint: "pushing someone gently towards a decision",
      targetPhrases: ["it's time you", "I'd rather you", "it's about time"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "phrases",
      title: "Supposing That Were True",
      focus: "framing an extended hypothetical for discussion",
      themeHint: "exploring an idea without endorsing it",
      targetPhrases: ["supposing that were", "let's say for argument", "assuming that's so"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "phrases",
      title: "On the Assumption That",
      focus: "stating openly what your argument rests on",
      themeHint: "making your premises explicit before arguing",
      targetPhrases: ["on the assumption", "taking as given", "starting from the idea"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "practice",
      title: "A Thought Experiment",
      focus: "reasoning step by step through an impossible scenario",
      themeHint: "two people testing an idea by pushing it to extremes",
      targetPhrases: ["imagine for a moment", "suppose instead that", "where would that leave"],
    },
    {
      position: 13,
      unitIndex: 2,
      kind: "practice",
      title: "If Things Were Otherwise",
      focus: "discussing at length how a real situation could have been different",
      themeHint: "a reflective conversation about a shared history",
      targetPhrases: ["were things different", "in another world", "that would change everything"],
    },

    // --- Ünite 3 · Saying Less, Meaning More -------------------------------------
    {
      position: 14,
      unitIndex: 3,
      kind: "grammar",
      title: "I Would If I Could",
      focus: "leaving out the part the listener can already supply",
      themeHint: "answering without repeating what was just said",
      targetPhrases: ["I would if", "I'd love to but", "I wish I could"],
    },
    {
      position: 15,
      unitIndex: 3,
      kind: "grammar",
      title: "Some Do, Some Don't",
      focus: "standing in for a whole idea with so, do and one",
      themeHint: "agreeing and disagreeing economically",
      targetPhrases: ["some do", "so do I", "neither did she"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "phrases",
      title: "Not That I'd Mind",
      focus: "throwaway qualifications that adjust what you just said",
      themeHint: "softening a statement after the fact",
      targetPhrases: ["not that I'd", "if anything", "though I doubt it"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "phrases",
      title: "Reading What Isn't Said",
      focus: "naming the implication behind someone's words",
      themeHint: "unpacking a carefully worded message",
      targetPhrases: ["what he's getting at", "she's hinting that", "that implies"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "practice",
      title: "Between the Lines",
      focus: "discussing what someone really meant and how you know",
      themeHint: "two colleagues decoding an ambiguous announcement",
      targetPhrases: ["what she really meant", "reading it another way", "there's more to it"],
    },
    {
      position: 19,
      unitIndex: 3,
      kind: "practice",
      title: "Saying No Without Saying No",
      focus: "declining by implication rather than refusing outright",
      themeHint: "turning something down while keeping the door open",
      targetPhrases: ["I'll think about it", "that's one option", "let me come back"],
    },

    // --- Ünite 4 · Formal Register -----------------------------------------------
    {
      position: 20,
      unitIndex: 4,
      kind: "grammar",
      title: "The Committee Recommends",
      focus: "turning actions into things to sound official",
      themeHint: "summarising a decision in institutional language",
      targetPhrases: ["it is recommended", "our recommendation is", "consideration was given"],
    },
    {
      position: 21,
      unitIndex: 4,
      kind: "grammar",
      title: "It Was Agreed That",
      focus: "impersonal reporting that removes the actor entirely",
      themeHint: "writing up the record of a meeting",
      targetPhrases: ["it was agreed", "it was decided", "it was noted that"],
    },
    {
      position: 22,
      unitIndex: 4,
      kind: "grammar",
      title: "Should You Require Assistance",
      focus: "formal hypotheticals built without if",
      themeHint: "closing an official letter",
      targetPhrases: ["should you require", "should there be", "were you to need"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "phrases",
      title: "Institutional Language",
      focus: "the standard vocabulary of official communication",
      themeHint: "reading and answering an official notice",
      targetPhrases: ["with regard to", "in accordance with", "pursuant to"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "practice",
      title: "A Formal Complaint",
      focus: "raising a serious issue in fully formal English",
      themeHint: "escalating a problem that informal channels did not solve",
      targetPhrases: ["I wish to raise", "I would draw attention", "I trust this will"],
    },
    {
      position: 25,
      unitIndex: 4,
      kind: "practice",
      title: "Presenting to a Board",
      focus: "delivering a short, structured formal presentation",
      themeHint: "presenting a proposal to senior decision makers",
      targetPhrases: ["I'd like to begin", "turning to the second", "to conclude"],
    },

    // --- Ünite 5 · Building an Argument ------------------------------------------
    {
      position: 26,
      unitIndex: 5,
      kind: "phrases",
      title: "Given That, It Follows",
      focus: "signalling the logical steps of an argument",
      themeHint: "walking someone through your reasoning",
      targetPhrases: ["given that", "it follows that", "which means that"],
    },
    {
      position: 27,
      unitIndex: 5,
      kind: "phrases",
      title: "Granted, However",
      focus: "conceding a point in order to strengthen your own",
      themeHint: "arguing with someone whose case is partly right",
      targetPhrases: ["granted that", "I'll admit that", "that notwithstanding"],
    },
    {
      position: 28,
      unitIndex: 5,
      kind: "phrases",
      title: "Correlation and Cause",
      focus: "being careful about claiming that one thing caused another",
      themeHint: "questioning a confident claim about why something happened",
      targetPhrases: ["that doesn't prove", "it may simply reflect", "correlation isn't cause"],
    },
    {
      position: 29,
      unitIndex: 5,
      kind: "phrases",
      title: "The Counterargument",
      focus: "stating the opposing view fairly before answering it",
      themeHint: "presenting both sides before taking one",
      targetPhrases: ["one might argue", "critics would say", "against that"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "practice",
      title: "Anticipating Objections",
      focus: "arguing while pre-empting the reply you expect",
      themeHint: "making a case to an audience you know is sceptical",
      targetPhrases: ["you might object that", "some will say", "I'd answer that by"],
    },
    {
      position: 31,
      unitIndex: 5,
      kind: "practice",
      title: "A Structured Case",
      focus: "arguing a position from opening to conclusion",
      themeHint: "a formal debate on a question with two real sides",
      targetPhrases: ["my first point", "which brings me to", "for these reasons"],
    },
    {
      position: 32,
      unitIndex: 5,
      kind: "practice",
      title: "Defending Under Pressure",
      focus: "holding up when your argument is challenged hard",
      themeHint: "being cross-examined on a claim you made",
      targetPhrases: ["I stand by that", "that misses my point", "let me clarify"],
    },

    // --- Ünite 6 · Narrative Craft -----------------------------------------------
    {
      position: 33,
      unitIndex: 6,
      kind: "grammar",
      title: "Little Did They Know",
      focus: "inverted openers that hint at what is coming",
      themeHint: "telling a story where the ending recasts the beginning",
      targetPhrases: ["little did they know", "unbeknown to them", "what nobody realised"],
    },
    {
      position: 34,
      unitIndex: 6,
      kind: "phrases",
      title: "Pacing a Story",
      focus: "speeding up and slowing down a narrative for effect",
      themeHint: "stretching the tense part and skipping the dull part",
      targetPhrases: ["and then out of nowhere", "for weeks nothing", "then everything shifted"],
    },
    {
      position: 35,
      unitIndex: 6,
      kind: "phrases",
      title: "The Detail That Matters",
      focus: "choosing what to include and what to leave out",
      themeHint: "telling a long story to someone short of time",
      targetPhrases: ["what you need to know", "I'll spare you", "here's the part"],
    },
    {
      position: 36,
      unitIndex: 6,
      kind: "phrases",
      title: "Bringing People to Life",
      focus: "reporting other people's speech vividly inside a story",
      themeHint: "acting out a conversation as you retell it",
      targetPhrases: ["and he goes", "she just looked", "you could see it"],
    },
    {
      position: 37,
      unitIndex: 6,
      kind: "practice",
      title: "A Story That Lands",
      focus: "telling an anecdote that gets the reaction you want",
      themeHint: "the story you always tell at gatherings",
      targetPhrases: ["you had to be there", "I'll never forget it", "still makes me laugh"],
    },
    {
      position: 38,
      unitIndex: 6,
      kind: "practice",
      title: "Retelling for Effect",
      focus: "telling the same story two ways for two audiences",
      themeHint: "the same events told to a friend and to a manager",
      targetPhrases: ["short version is", "long story short", "to put it another way"],
    },

    // --- Ünite 7 · Precision and Nuance ------------------------------------------
    {
      position: 39,
      unitIndex: 7,
      kind: "phrases",
      title: "Imply and Infer",
      focus: "pairs of words that are commonly confused with each other",
      themeHint: "clearing up a misunderstanding about who meant what",
      targetPhrases: ["what I'm implying", "what you inferred", "there's a difference"],
    },
    {
      position: 40,
      unitIndex: 7,
      kind: "phrases",
      title: "Degrees of Approval",
      focus: "the scale from barely acceptable to genuinely excellent",
      themeHint: "reviewing something honestly without exaggerating",
      targetPhrases: ["perfectly decent", "genuinely outstanding", "not without merit"],
    },
    {
      position: 41,
      unitIndex: 7,
      kind: "grammar",
      title: "Hedged and Blunt",
      focus: "how much distance to put between yourself and a claim",
      themeHint: "the same assessment given carefully and directly",
      targetPhrases: ["it would appear", "one could argue", "quite frankly"],
    },
    {
      position: 42,
      unitIndex: 7,
      kind: "grammar",
      title: "Tends To, Has a Habit Of",
      focus: "describing tendencies with the right degree of commitment",
      themeHint: "characterising someone's behaviour fairly",
      targetPhrases: ["tends to", "has a habit of", "more often than not"],
    },
    {
      position: 43,
      unitIndex: 7,
      kind: "practice",
      title: "Almost the Right Word",
      focus: "narrowing down to the exact term you are reaching for",
      themeHint: "talking your way towards a word you cannot recall",
      targetPhrases: ["not quite that", "closer to", "what I'm reaching for"],
    },
    {
      position: 44,
      unitIndex: 7,
      kind: "practice",
      title: "Describing Something Complicated",
      focus: "giving an accurate account of something genuinely messy",
      themeHint: "explaining a situation with no simple version",
      targetPhrases: ["there are several layers", "it's tangled up with", "in short"],
    },
    {
      position: 45,
      unitIndex: 7,
      kind: "practice",
      title: "Choosing the Register",
      focus: "delivering the same content at three levels of formality",
      themeHint: "one message, three different audiences",
      targetPhrases: ["formally I'd say", "casually it's just", "somewhere in between"],
    },

    // --- Ünite 8 · Professional Communication ------------------------------------
    {
      position: 46,
      unitIndex: 8,
      kind: "phrases",
      title: "Diplomatic Disagreement",
      focus: "objecting clearly without damaging the relationship",
      themeHint: "disagreeing with someone you need on your side",
      targetPhrases: ["I see it differently", "with respect I'd argue", "I'm not entirely convinced"],
    },
    {
      position: 47,
      unitIndex: 8,
      kind: "phrases",
      title: "Chairing a Discussion",
      focus: "running a conversation with several people in it",
      themeHint: "keeping a meeting on track and on time",
      targetPhrases: ["let's hear from", "coming back to", "we're running short"],
    },
    {
      position: 48,
      unitIndex: 8,
      kind: "phrases",
      title: "Negotiating Position",
      focus: "signalling where you can move and where you cannot",
      themeHint: "the middle stage of a negotiation",
      targetPhrases: ["there's room on", "that's not something we", "what if we both"],
    },
    {
      position: 49,
      unitIndex: 8,
      kind: "phrases",
      title: "Delivering Bad News",
      focus: "announcing something unwelcome clearly and humanely",
      themeHint: "telling a team about a decision they will dislike",
      targetPhrases: ["I'm afraid we've decided", "this wasn't easy", "I want to be straight"],
    },
    {
      position: 50,
      unitIndex: 8,
      kind: "practice",
      title: "Giving Difficult Feedback",
      focus: "a candid conversation that stays constructive",
      themeHint: "telling someone their work is not good enough yet",
      targetPhrases: ["what I've observed is", "how do you see it", "I'd like us to"],
    },
    {
      position: 51,
      unitIndex: 8,
      kind: "practice",
      title: "A Negotiation",
      focus: "reaching an agreement that neither side resents",
      themeHint: "settling terms where both sides want more",
      targetPhrases: ["I could live with", "that's my limit", "do we have a deal"],
    },
    {
      position: 52,
      unitIndex: 8,
      kind: "practice",
      title: "Handling a Crisis Call",
      focus: "staying clear and calm while information is still incomplete",
      themeHint: "briefing someone urgently about a developing problem",
      targetPhrases: ["here's what we know", "what we're doing now", "I'll update you"],
    },

    // --- Ünite 9 · Culture and Idiom ---------------------------------------------
    {
      position: 53,
      unitIndex: 9,
      kind: "phrases",
      title: "Idioms Worth Knowing",
      focus: "common fixed expressions and the situations they fit",
      themeHint: "a conversation full of everyday figurative language",
      targetPhrases: ["it's a long shot", "that ship has sailed", "off the top of"],
    },
    {
      position: 54,
      unitIndex: 9,
      kind: "grammar",
      title: "Words That Go Together",
      focus: "which words habitually pair with which",
      themeHint: "polishing wording that is correct but sounds wrong",
      targetPhrases: ["heavy rain", "strong argument", "deeply grateful"],
    },
    {
      position: 55,
      unitIndex: 9,
      kind: "phrases",
      title: "Humour and Irony",
      focus: "signalling that you do not mean something literally",
      themeHint: "a light exchange where tone carries the meaning",
      targetPhrases: ["well that went well", "just what I needed", "no pressure then"],
    },
    {
      position: 56,
      unitIndex: 9,
      kind: "phrases",
      title: "What Not to Say",
      focus: "expressions that land badly and safer alternatives",
      themeHint: "coaching someone before an important conversation",
      targetPhrases: ["I'd avoid saying", "that could be taken", "safer to say"],
    },
    {
      position: 57,
      unitIndex: 9,
      kind: "practice",
      title: "Reading the Room",
      focus: "adjusting how you speak to the company you are in",
      themeHint: "the same person in two very different rooms",
      targetPhrases: ["maybe not here", "I'll keep it short", "reading the mood"],
    },
    {
      position: 58,
      unitIndex: 9,
      kind: "practice",
      title: "Talking Across Cultures",
      focus: "a conversation where the unspoken assumptions differ",
      themeHint: "two people from different working cultures collaborating",
      targetPhrases: ["where I'm from", "how does that work", "I don't want to assume"],
    },

    // --- Ünite 10 · Extended Discussion ------------------------------------------
    {
      position: 59,
      unitIndex: 10,
      kind: "phrases",
      title: "Sustaining a Long Turn",
      focus: "holding the floor coherently for more than a few sentences",
      themeHint: "answering a big question without trailing off",
      targetPhrases: ["there are three things", "before I get to", "coming back to my"],
    },
    {
      position: 60,
      unitIndex: 10,
      kind: "phrases",
      title: "Signposting Where You're Going",
      focus: "mapping a long answer so the listener can follow",
      themeHint: "laying out an answer before giving it",
      targetPhrases: ["I'll start with", "then I'll turn to", "finally I want to"],
    },
    {
      position: 61,
      unitIndex: 10,
      kind: "practice",
      title: "An Abstract Question",
      focus: "discussing a question that has no clean answer",
      themeHint: "a philosophical conversation between friends",
      targetPhrases: ["it depends what we mean", "I'd distinguish between", "there's no clean answer"],
    },
    {
      position: 62,
      unitIndex: 10,
      kind: "practice",
      title: "A Subject You Know Deeply",
      focus: "going into real depth on something you know well",
      themeHint: "explaining your field to an intelligent outsider",
      targetPhrases: ["what most people miss", "in my experience", "what's interesting is"],
    },
    {
      position: 63,
      unitIndex: 10,
      kind: "practice",
      title: "A Subject You Know Nothing About",
      focus: "coping gracefully when you are out of your depth",
      themeHint: "being asked about something outside your expertise",
      targetPhrases: ["I'm out of my depth", "correct me if", "from what little I"],
    },
    {
      position: 64,
      unitIndex: 10,
      kind: "practice",
      title: "Closing the Loop",
      focus: "summarising a long discussion fairly to both sides",
      themeHint: "ending a conversation that covered a lot of ground",
      targetPhrases: ["so where we've landed", "to bring it together", "that's where I'll stop"],
    },
  ],
};
