import type { LevelSpec } from "./types.js";

/**
 * C2 — Proficient. 9 ünite, 62 ders.
 *
 * Bu seviyede öğretilecek yeni yapı kalmadı; öğrenciyi tıkayan şey akıcılık,
 * nüans ve uzun konuşmayı taşıyabilmek. Bu yüzden dersler ağırlıklı olarak
 * `practice` — pazar lideri de bu seviyede tamamen konu-tartışma dersleri veriyor.
 *
 * Bu, `focus` alanının anlamını kaydırır: burada bir gramer yapısı değil, bir
 * İLETİŞİM BECERİSİ tarif eder ("bir görüşmede pozisyon yumuşatmak").
 * `lesson-gen` prompt'u `kind: practice` için ayrı yönerge taşıyor — anlatım
 * maddeleri kural değil, konuşma stratejisi ve hazır kalıp verir.
 */
export const C2: LevelSpec = {
  level: "C2",
  label: "Proficient",
  units: [
    {
      index: 1,
      title: "Nuance and Connotation",
      goal: "Choose between words that mean the same but land differently",
    },
    {
      index: 2,
      title: "Persuasion",
      goal: "Move someone's position without pressure or manipulation",
    },
    {
      index: 3,
      title: "Negotiation",
      goal: "Reach agreement while protecting both your interests and the relationship",
    },
    {
      index: 4,
      title: "Debate",
      goal: "Argue rigorously, concede honestly and answer what you would rather avoid",
    },
    {
      index: 5,
      title: "Humour and Irony",
      goal: "Use and read humour, including when it misfires",
    },
    {
      index: 6,
      title: "Storytelling at Length",
      goal: "Hold an audience through a long narrative that goes somewhere",
    },
    {
      index: 7,
      title: "Abstract Topics",
      goal: "Discuss questions that have no settled answer",
    },
    {
      index: 8,
      title: "Professional Register",
      goal: "Speak with authority, and for other people, under scrutiny",
    },
    {
      index: 9,
      title: "Free Discussion",
      goal: "Talk comfortably and at length with anyone about anything",
    },
  ],
  lessons: [
    // --- Ünite 1 · Nuance and Connotation ----------------------------------------
    {
      position: 1,
      unitIndex: 1,
      kind: "phrases",
      title: "The Weight of a Word",
      focus: "choosing between near-synonyms by what they suggest, not what they mean",
      themeHint: "describing the same behaviour generously and harshly",
      targetPhrases: ["I'd hesitate to call", "closer to say", "that carries a suggestion"],
    },
    {
      position: 2,
      unitIndex: 1,
      kind: "phrases",
      title: "Faint Praise",
      focus: "saying something positive that is heard as criticism",
      themeHint: "reviewing work you were not impressed by",
      targetPhrases: ["it's certainly different", "not bad for", "you've clearly worked hard"],
    },
    {
      position: 3,
      unitIndex: 1,
      kind: "grammar",
      title: "Deliberate Vagueness",
      focus: "being unspecific on purpose while still sounding responsive",
      themeHint: "answering a question you do not want to answer fully",
      targetPhrases: ["something along those lines", "one might say", "in a manner of speaking"],
    },
    {
      position: 4,
      unitIndex: 1,
      kind: "phrases",
      title: "Overstatement and Understatement",
      focus: "dialling a description up or down for effect",
      themeHint: "describing a disaster and a triumph in the same register",
      targetPhrases: ["slightly inconvenient", "somewhat of an issue", "to put it mildly"],
    },
    {
      position: 5,
      unitIndex: 1,
      kind: "practice",
      title: "Describing a Person Precisely",
      focus: "building a portrait of someone that avoids cliche",
      themeHint: "describing a complicated person to someone who has never met them",
      targetPhrases: ["what defines him is", "she comes across as", "I'd describe her as"],
    },
    {
      position: 6,
      unitIndex: 1,
      kind: "practice",
      title: "The Same Fact, Three Framings",
      focus: "reframing one event three ways without changing the facts",
      themeHint: "one piece of news told to three different people",
      targetPhrases: ["put another way", "seen differently", "or you could say"],
    },
    {
      position: 7,
      unitIndex: 1,
      kind: "practice",
      title: "Choosing Your Words Carefully",
      focus: "a conversation where the exact wording carries real consequences",
      themeHint: "a sensitive discussion where precision matters",
      targetPhrases: ["I want to be careful", "let me rephrase", "what I mean precisely"],
    },

    // --- Ünite 2 · Persuasion -----------------------------------------------------
    {
      position: 8,
      unitIndex: 2,
      kind: "phrases",
      title: "Appeals That Work",
      focus: "appealing to reason, to feeling and to your own credibility",
      themeHint: "making the same case three different ways",
      targetPhrases: ["think about what happens", "you know as well", "evidence points to"],
    },
    {
      position: 9,
      unitIndex: 2,
      kind: "grammar",
      title: "The Rhetorical Question",
      focus: "questions that make a statement rather than seek an answer",
      themeHint: "a persuasive stretch of speech built around questions",
      targetPhrases: ["who wouldn't want", "isn't that the point", "why would anyone"],
    },
    {
      position: 10,
      unitIndex: 2,
      kind: "phrases",
      title: "Repetition and Rhythm",
      focus: "patterns of repetition that make a point stick",
      themeHint: "a short speech built to be remembered",
      targetPhrases: ["again and again", "not once but twice", "over and over"],
    },
    {
      position: 11,
      unitIndex: 2,
      kind: "practice",
      title: "Pitching an Idea",
      focus: "a short persuasive pitch with a clear ask",
      themeHint: "two minutes to sell an idea to someone busy",
      targetPhrases: ["here's the opportunity", "what this gives you", "imagine if we could"],
    },
    {
      position: 12,
      unitIndex: 2,
      kind: "practice",
      title: "Winning a Sceptic",
      focus: "persuading someone who starts out against you",
      themeHint: "a conversation with someone who has already said no",
      targetPhrases: ["I know how it sounds", "hear me out", "you're right to question"],
    },
    {
      position: 13,
      unitIndex: 2,
      kind: "practice",
      title: "Persuading Without Pressure",
      focus: "influencing someone while leaving the decision genuinely theirs",
      themeHint: "advising a friend without pushing them",
      targetPhrases: ["it's entirely your call", "worth considering perhaps", "no obligation at all"],
    },
    {
      position: 14,
      unitIndex: 2,
      kind: "practice",
      title: "Changing Someone's Mind",
      focus: "a real attempt to shift a firmly held view",
      themeHint: "a long conversation about something you disagree on",
      targetPhrases: ["what would convince you", "does that shift anything", "I'm asking you to"],
    },

    // --- Ünite 3 · Negotiation ----------------------------------------------------
    {
      position: 15,
      unitIndex: 3,
      kind: "phrases",
      title: "Opening Positions",
      focus: "the language of a first offer and a first response",
      themeHint: "the opening minutes of a negotiation",
      targetPhrases: ["what we're looking for", "our starting point", "ideally we'd want"],
    },
    {
      position: 16,
      unitIndex: 3,
      kind: "phrases",
      title: "Trading and Conceding",
      focus: "giving something in order to get something",
      themeHint: "the middle of a negotiation where both sides move",
      targetPhrases: ["if you can do", "we could move on", "in exchange for"],
    },
    {
      position: 17,
      unitIndex: 3,
      kind: "phrases",
      title: "Deadlock and Deadlines",
      focus: "moving a conversation that has stopped moving",
      themeHint: "a negotiation running out of time and patience",
      targetPhrases: ["we're going round circles", "by end of week", "let's park that"],
    },
    {
      position: 18,
      unitIndex: 3,
      kind: "practice",
      title: "A Salary Conversation",
      focus: "negotiating your own terms without damaging the relationship",
      themeHint: "asking for more from someone who decides it",
      targetPhrases: ["based on what I bring", "I was hoping for", "is there flexibility"],
    },
    {
      position: 19,
      unitIndex: 3,
      kind: "practice",
      title: "A Difficult Client",
      focus: "holding your value under sustained pressure",
      themeHint: "a client pushing hard on price and scope",
      targetPhrases: ["I understand the frustration", "what I can offer", "that's simply not possible"],
    },
    {
      position: 20,
      unitIndex: 3,
      kind: "practice",
      title: "Multi-Party Negotiation",
      focus: "reaching one agreement among three competing interests",
      themeHint: "a discussion where nobody can get everything",
      targetPhrases: ["speaking for my side", "can we all accept", "that works for us"],
    },
    {
      position: 21,
      unitIndex: 3,
      kind: "practice",
      title: "Walking Away",
      focus: "ending without a deal but keeping the relationship intact",
      themeHint: "closing a negotiation that cannot be closed",
      targetPhrases: ["I don't think we", "no hard feelings", "let's stay in touch"],
    },

    // --- Ünite 4 · Debate ---------------------------------------------------------
    {
      position: 22,
      unitIndex: 4,
      kind: "phrases",
      title: "Framing the Question",
      focus: "defining the terms before the argument starts",
      themeHint: "two people who disagree about what they are disagreeing about",
      targetPhrases: ["before we start let's", "what exactly do we mean", "that's the real question"],
    },
    {
      position: 23,
      unitIndex: 4,
      kind: "phrases",
      title: "Attacking an Argument",
      focus: "going after the reasoning rather than the person",
      themeHint: "challenging a case that sounds stronger than it is",
      targetPhrases: ["that assumes", "your premise is", "that doesn't follow"],
    },
    {
      position: 24,
      unitIndex: 4,
      kind: "phrases",
      title: "Concession as Strategy",
      focus: "giving ground deliberately in order to gain it",
      themeHint: "an argument you win by agreeing first",
      targetPhrases: ["I'll grant you that", "you're right about", "even accepting that"],
    },
    {
      position: 25,
      unitIndex: 4,
      kind: "practice",
      title: "A Formal Debate",
      focus: "arguing a clear motion under debate conventions",
      themeHint: "a structured debate with sides assigned",
      targetPhrases: ["I oppose the motion", "my opponent claims", "I put it to you"],
    },
    {
      position: 26,
      unitIndex: 4,
      kind: "practice",
      title: "Devil's Advocate",
      focus: "arguing a case you personally do not believe",
      themeHint: "being asked to defend the opposite of your view",
      targetPhrases: ["for the sake of argument", "someone has to say", "let me push back"],
    },
    {
      position: 27,
      unitIndex: 4,
      kind: "practice",
      title: "The Uncomfortable Question",
      focus: "answering the question you would rather avoid",
      themeHint: "being pressed on the weakest part of your position",
      targetPhrases: ["that's a fair question", "I won't pretend", "honestly I don't know"],
    },
    {
      position: 28,
      unitIndex: 4,
      kind: "practice",
      title: "When You're Wrong",
      focus: "conceding an argument without losing standing",
      themeHint: "realising mid-discussion that the other side is right",
      targetPhrases: ["I was mistaken", "you've changed my mind", "I withdraw that"],
    },

    // --- Ünite 5 · Humour and Irony -----------------------------------------------
    {
      position: 29,
      unitIndex: 5,
      kind: "phrases",
      title: "Dry and Deadpan",
      focus: "humour delivered flat, without signalling itself",
      themeHint: "reacting to a minor disaster with total calm",
      targetPhrases: ["how thrilling", "can't wait", "delighted I'm sure"],
    },
    {
      position: 30,
      unitIndex: 5,
      kind: "phrases",
      title: "Self-Deprecation",
      focus: "making yourself the joke without seeming to fish for reassurance",
      themeHint: "admitting a weakness lightly",
      targetPhrases: ["I'm hopeless at", "typical of me", "don't ask me why"],
    },
    {
      position: 31,
      unitIndex: 5,
      kind: "phrases",
      title: "Sarcasm and Its Risks",
      focus: "when sarcasm works and when it does real damage",
      themeHint: "a remark that could be taken two ways",
      targetPhrases: ["oh brilliant", "just perfect", "that went well"],
    },
    {
      position: 32,
      unitIndex: 5,
      kind: "practice",
      title: "Banter",
      focus: "fast, friendly back-and-forth that stays warm",
      themeHint: "old friends winding each other up",
      targetPhrases: ["you would say that", "takes one to know", "very funny"],
    },
    {
      position: 33,
      unitIndex: 5,
      kind: "practice",
      title: "Reading a Joke That Fell Flat",
      focus: "recovering when humour lands badly",
      themeHint: "a light remark that clearly did not go down well",
      targetPhrases: ["too soon", "ignore me", "that came out wrong"],
    },
    {
      position: 34,
      unitIndex: 5,
      kind: "practice",
      title: "Humour in a Serious Setting",
      focus: "lightening a tense moment without undercutting it",
      themeHint: "a difficult meeting that needs air let into it",
      targetPhrases: ["on a lighter note", "if I may", "we could all use"],
    },
    {
      position: 35,
      unitIndex: 5,
      kind: "practice",
      title: "Telling a Funny Story",
      focus: "building an anecdote so the laugh arrives where you want it",
      themeHint: "the story you tell when everyone is relaxed",
      targetPhrases: ["you'll appreciate this", "it gets better", "and that's not all"],
    },

    // --- Ünite 6 · Storytelling at Length -----------------------------------------
    {
      position: 36,
      unitIndex: 6,
      kind: "phrases",
      title: "Structure of a Long Story",
      focus: "shaping a narrative that runs for many minutes",
      themeHint: "a story too long to tell without a plan",
      targetPhrases: ["it starts years before", "but first you need", "and here's where"],
    },
    {
      position: 37,
      unitIndex: 6,
      kind: "grammar",
      title: "Switching Time for Effect",
      focus: "moving between past and present inside a story to heighten it",
      themeHint: "reliving a moment as if it were happening now",
      targetPhrases: ["so I'm standing there", "and he turns round", "next thing I know"],
    },
    {
      position: 38,
      unitIndex: 6,
      kind: "phrases",
      title: "Digression and Return",
      focus: "going off on a tangent and getting back cleanly",
      themeHint: "a story that keeps needing background",
      targetPhrases: ["but I'm getting ahead", "anyway where was I", "back to the point"],
    },
    {
      position: 39,
      unitIndex: 6,
      kind: "practice",
      title: "A Life Story",
      focus: "telling your own history at length and with shape",
      themeHint: "being asked to explain how you got here",
      targetPhrases: ["I grew up", "that shaped everything", "looking at it now"],
    },
    {
      position: 40,
      unitIndex: 6,
      kind: "practice",
      title: "Someone Else's Story",
      focus: "retelling a story that is not yours without distorting it",
      themeHint: "passing on something you were told in confidence",
      targetPhrases: ["as she tells it", "apparently what happened", "I've only heard"],
    },
    {
      position: 41,
      unitIndex: 6,
      kind: "practice",
      title: "A Story With a Point",
      focus: "narrative that exists to argue something",
      themeHint: "using an anecdote to win an argument",
      targetPhrases: ["and that's exactly why", "which brings me back", "that's what I mean"],
    },
    {
      position: 42,
      unitIndex: 6,
      kind: "practice",
      title: "Holding an Audience",
      focus: "sustaining a long turn that nobody wants to interrupt",
      themeHint: "the whole table listening to one person",
      targetPhrases: ["bear with me", "this is the part", "you'll see why"],
    },

    // --- Ünite 7 · Abstract Topics ------------------------------------------------
    {
      position: 43,
      unitIndex: 7,
      kind: "phrases",
      title: "Talking About Ideas",
      focus: "the vocabulary of abstraction and generalisation",
      themeHint: "a conversation that leaves concrete examples behind",
      targetPhrases: ["in principle at least", "broadly speaking", "at a fundamental level"],
    },
    {
      position: 44,
      unitIndex: 7,
      kind: "practice",
      title: "Defining the Undefinable",
      focus: "pinning down a concept that resists a clean definition",
      themeHint: "two people trying to define something everyone uses loosely",
      targetPhrases: ["it resists definition", "closest I can get", "we'd know it when"],
    },
    {
      position: 45,
      unitIndex: 7,
      kind: "practice",
      title: "Ethics and Trade-offs",
      focus: "discussing a dilemma where every option costs something",
      themeHint: "a hard case with no clean answer",
      targetPhrases: ["there's no clean choice", "someone pays either way", "I'd weigh it as"],
    },
    {
      position: 46,
      unitIndex: 7,
      kind: "practice",
      title: "Technology and Society",
      focus: "discussing a broad contemporary question from several angles",
      themeHint: "a conversation about a change nobody fully understands yet",
      targetPhrases: ["it cuts both ways", "we're already seeing", "hard to put back"],
    },
    {
      position: 47,
      unitIndex: 7,
      kind: "practice",
      title: "Art and Taste",
      focus: "defending a judgement that cannot be proved",
      themeHint: "disagreeing about something one of you loves",
      targetPhrases: ["it does something to me", "I can't defend it", "does that matter"],
    },
    {
      position: 48,
      unitIndex: 7,
      kind: "practice",
      title: "What Makes a Good Life",
      focus: "a genuinely open discussion about what matters",
      themeHint: "a long, unhurried conversation between people who trust each other",
      targetPhrases: ["for me it comes down", "I used to think", "ask me again in"],
    },
    {
      position: 49,
      unitIndex: 7,
      kind: "practice",
      title: "Disagreeing About Values",
      focus: "a disagreement where the gap is fundamental, not factual",
      themeHint: "two people who will not convince each other, talking anyway",
      targetPhrases: ["we start from different", "I don't expect to", "we'll have to differ"],
    },

    // --- Ünite 8 · Professional Register ------------------------------------------
    {
      position: 50,
      unitIndex: 8,
      kind: "phrases",
      title: "The Language of Leadership",
      focus: "how authority speaks without sounding authoritarian",
      themeHint: "addressing a team at a difficult moment",
      targetPhrases: ["what I'm asking of", "here's where we're going", "I take responsibility"],
    },
    {
      position: 51,
      unitIndex: 8,
      kind: "grammar",
      title: "Vagueness as Strategy",
      focus: "saying very little while sounding substantive",
      themeHint: "answering before a decision has actually been made",
      targetPhrases: ["we're exploring options", "nothing has been decided", "in due course"],
    },
    {
      position: 52,
      unitIndex: 8,
      kind: "practice",
      title: "An Interview at Senior Level",
      focus: "a high-stakes professional conversation about your own record",
      themeHint: "an interview where the questions are open and hard",
      targetPhrases: ["what I'd bring is", "my track record", "where I'd start"],
    },
    {
      position: 53,
      unitIndex: 8,
      kind: "practice",
      title: "Briefing and Being Briefed",
      focus: "moving dense information in both directions efficiently",
      themeHint: "a handover with very little time",
      targetPhrases: ["three things you need", "what's the headline", "anything I've missed"],
    },
    {
      position: 54,
      unitIndex: 8,
      kind: "practice",
      title: "Public Speaking",
      focus: "delivering a short prepared address to a room",
      themeHint: "speaking at an event where you represent something",
      targetPhrases: ["thank you for having", "I want to leave you", "let me close with"],
    },
    {
      position: 55,
      unitIndex: 8,
      kind: "practice",
      title: "Questions Under Scrutiny",
      focus: "handling unscripted questions from a sceptical room",
      themeHint: "the question session after a difficult announcement",
      targetPhrases: ["good question", "I'd push back on", "let me address that"],
    },
    {
      position: 56,
      unitIndex: 8,
      kind: "practice",
      title: "Representing an Organisation",
      focus: "speaking for other people rather than for yourself",
      themeHint: "answering as the voice of an institution",
      targetPhrases: ["our position is", "I can't speak to", "what we can say"],
    },

    // --- Ünite 9 · Free Discussion ------------------------------------------------
    {
      position: 57,
      unitIndex: 9,
      kind: "practice",
      title: "Small Talk at Altitude",
      focus: "effortless conversation with someone you have just met",
      themeHint: "a chance encounter with an interesting stranger",
      targetPhrases: ["how do you know", "what brings you here", "small world"],
    },
    {
      position: 58,
      unitIndex: 9,
      kind: "practice",
      title: "A Long Conversation",
      focus: "sustaining an unhurried conversation over a long stretch",
      themeHint: "an evening that runs much later than planned",
      targetPhrases: ["that reminds me", "speaking of which", "we've been here hours"],
    },
    {
      position: 59,
      unitIndex: 9,
      kind: "practice",
      title: "Guilty Pleasures",
      focus: "confessing tastes you defend with irony and charm",
      themeHint: "admitting the tastes you pretend not to have",
      targetPhrases: ["I must confess", "my guilty pleasure", "I'm not proud of"],
    },
    {
      position: 60,
      unitIndex: 9,
      kind: "practice",
      title: "Commuting Stories",
      focus: "turning a mundane daily experience into a story worth hearing",
      themeHint: "making a daily commute sound like an adventure",
      targetPhrases: ["packed like sardines", "out of nowhere", "at the crack of dawn"],
    },
    {
      position: 61,
      unitIndex: 9,
      kind: "practice",
      title: "City vs. Small Town",
      focus: "arguing lifestyle trade-offs with texture and nuance",
      themeHint: "a friendly argument about where life is better",
      targetPhrases: ["pace of life", "on your doorstep", "sense of community"],
    },
    {
      position: 62,
      unitIndex: 9,
      kind: "practice",
      title: "Interviewing Someone",
      focus: "drawing out a person you have only just met",
      themeHint: "getting someone reserved to open up",
      targetPhrases: ["tell me about", "what made you", "how did that feel"],
    },
    {
      position: 63,
      unitIndex: 9,
      kind: "practice",
      title: "Being Interviewed",
      focus: "answering well with no preparation and no script",
      themeHint: "being asked about yourself without warning",
      targetPhrases: ["good of you to ask", "I suppose the honest", "let me think"],
    },
    {
      position: 64,
      unitIndex: 9,
      kind: "practice",
      title: "A Conversation That Matters",
      focus: "a conversation with real stakes and real feeling",
      themeHint: "saying something to someone that you have put off saying",
      targetPhrases: ["I need to say", "this is hard for me", "thank you for listening"],
    },
    {
      position: 65,
      unitIndex: 9,
      kind: "practice",
      title: "Just Talking",
      focus: "unstructured conversation with no agenda at all",
      themeHint: "two people talking for the pleasure of it",
      targetPhrases: ["no idea honestly", "isn't that funny", "anyway how are you"],
    },
  ],
};
