/** A1 · Ünite 5-8 — Likes and Free Time · Describing · Out and About · The Past (24 ders). */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A1_U5_8: Authored[] = [
  // --- Ünite 5 · Likes and Free Time -----------------------------------------
  {
    id: "a1-i-love-cooking",
    topic: "like, love and hate plus -ing",
    objectives: ["Say what I like and do not like doing.", "Find things I have in common with someone."],
    goal: "Talk about the activities you enjoy and find something in common.",
    target: "like / love / hate plus verb-ing",
    correction: "Model the phrase with the -ing form and let the learner say it again.",
    summary: "You learned to say what you like, love and hate doing, using the -ing form.",
    minutes: 6,
    points: [
      {
        form: "I love cooking",
        claims: [
          "After like, love, hate and enjoy, the next verb takes -ing.",
          "The strength goes: I hate it, I don't like it, I like it, I love it.",
        ],
        ex: ["I love cooking.", "She enjoys cooking too.", "I hate getting up early."],
      },
      {
        form: "I don't like",
        claims: [
          "For the negative, use 'don't like' or 'doesn't like' plus the -ing form.",
          "'I don't mind' means it is fine for you, not good and not bad.",
        ],
        ex: ["I don't like waiting.", "He doesn't like flying.", "I don't mind cooking."],
      },
    ],
    ex: [
      fill("I love ___ new places when I travel.", ["visiting", "seeing"]),
      mcq("Which sentence is correct?", [
        "She enjoys reading in the evening.",
        "She enjoys read in the evening.",
        "She enjoys to reading in the evening.",
      ], 0),
      say("I / not like / get up / early", [
        "I don't like getting up early.",
        "I do not like getting up early.",
      ]),
    ],
    open: {
      q: "Tell me two things you love doing and one thing you do not like doing.",
      must: ["I love", "I don't like"],
      criteria: "The answer uses like, love or hate with the -ing form.",
      example: "I love cooking and swimming, but I don't like cleaning the kitchen.",
    },
    success: "The learner says what they like and dislike doing with the -ing form at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I love travelling.",
        "I love travel.",
        "I am love travelling.",
      ], 0),
      qfill("He doesn't like ___ up early at weekends. (get)", ["getting"]),
      qmcq("Which phrase means it is fine for you?", ["I don't mind.", "I hate it.", "I never like it."], 0),
    ],
    scenes: [
      sc("Elif", "a friend planning a free day", "to find an activity you both enjoy",
        "You and a friend have a free Saturday and no plan yet.",
        "Say what you enjoy doing and find something you both like.",
        "We have the whole day. Any ideas about what we could do?", "cheerful"),
      sc("Simon", "a colleague organising a team activity", "to choose an activity the team will enjoy",
        "Your team is choosing an activity for a company day.",
        "Say what you enjoy and what you would rather not do.",
        "I'm collecting ideas for the team day. What sort of thing do you enjoy?", "friendly"),
      sc("Talia", "a traveller in the same hostel", "to find someone to explore the city with",
        "You meet a traveller who is looking for company for the day.",
        "Say what you like doing when you travel.",
        "I'm going out to explore today. What do you enjoy doing in a new city?", "relaxed"),
      sc("Mr. Bianchi", "your teacher", "to hear about students' interests",
        "The class is talking about free time.",
        "Say what you love and hate doing.",
        "Let's talk about free time. What do you love doing?", "warm"),
      sc("Ms. Halim", "the examiner", "to hear you talk about your interests",
        "The examiner asks about your free time.",
        "Talk about what you enjoy and do not enjoy doing.",
        "What do you like doing when you are not working?", "neutral"),
    ],
  },

  {
    id: "a1-do-you-like-it",
    topic: "me, him, her, it, us, them",
    objectives: ["Use object pronouns after a verb.", "Give an opinion about something without repeating the noun."],
    goal: "Give opinions about things without repeating their names.",
    target: "me / him / her / it / us / them",
    correction: "Replace the noun with the right pronoun and let the learner repeat the sentence.",
    summary: "You learned the words me, him, her, it, us and them, and where they go in a sentence.",
    minutes: 6,
    points: [
      {
        form: "me, him, her, it, us, them",
        claims: [
          "These words come after the verb: I like it, she knows him, they help us.",
          "Use 'it' for one thing and 'them' for more than one thing or person.",
          "Do not use I, he or she after a verb: say 'call me', not 'call I'.",
        ],
        ex: ["I like it a lot.", "Please call me tonight.", "Tell them about the party."],
      },
      {
        form: "I like it",
        claims: [
          "When you have already named the thing, use 'it' or 'them' instead of the name.",
          "This makes your answer sound natural instead of repeating words.",
        ],
        ex: ["Do you like the film? Yes, I like it.", "The shoes are nice. I really like them."],
      },
    ],
    ex: [
      fill("I saw the new film yesterday. I liked ___ a lot.", ["it"]),
      mcq("Which sentence is correct?", [
        "Please call me later.",
        "Please call I later.",
        "Please call my later.",
      ], 0),
      say("tell / them / about the party", ["Tell them about the party."]),
    ],
    open: {
      q: "Your friend gives you a gift. Say what you think about it, without repeating the name of the gift.",
      // Dersin hedefi NESNE ZAMİRİ; "I like it" fiili de dayatıyordu ve öğrenci
      // "I love it" dediğinde örnek cevapla kalıp uyuşmuyordu.
      must: ["it", "them"],
      criteria: "The answer uses an object pronoun instead of repeating the noun.",
      example: "Thank you so much, I love it! I will use it every day.",
    },
    success: "The learner uses object pronouns correctly instead of repeating nouns.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "She knows him very well.",
        "She knows he very well.",
        "She knows his very well.",
      ], 0),
      qfill("These are my keys. Can you give ___ to me?", ["them"]),
      qmcq("Your friend asks about a book you read. What is natural?", [
        "I really enjoyed it.",
        "I really enjoyed the book the book.",
        "I really enjoyed she.",
      ], 0),
    ],
    scenes: [
      sc("Dora", "a friend who gave you a present", "to hear what you think of the present",
        "A friend has given you a birthday present and is waiting for your reaction.",
        "Say what you think, using it and them.",
        "Go on, open it! What do you think?", "excited"),
      sc("Nils", "a colleague who made a presentation", "to get honest feedback on his slides",
        "A colleague shows you the slides he prepared.",
        "Give your opinion using pronouns.",
        "I finished the slides last night. How do they look to you?", "hopeful"),
      sc("Ceyda", "a shop assistant", "to help you decide about the items you tried",
        "You have tried on some clothes in a shop.",
        "Say what you think about them.",
        "How did you get on with those? What do you think?", "helpful"),
      sc("Mr. Payne", "your teacher", "to practise giving opinions",
        "In class you are giving opinions about photos and objects.",
        "Give opinions using it and them.",
        "Here are some pictures. What do you think of them?", "warm"),
      sc("Ms. Ortiz", "the examiner", "to check that you can give short opinions",
        "The examiner asks about things you have seen recently.",
        "Give opinions with object pronouns.",
        "Tell me about a film or a book you know. What did you think?", "neutral"),
    ],
  },

  {
    id: "a1-i-can-swim",
    topic: "can and can't for ability",
    objectives: ["Say what I can and cannot do.", "Ask about someone's abilities."],
    goal: "Talk about what you are able to do.",
    target: "I can / I can't / she can drive",
    correction: "Model can plus the plain verb and let the learner repeat the sentence.",
    summary: "You learned to say what you can and cannot do, and to ask other people.",
    minutes: 5,
    points: [
      {
        form: "I can / she can",
        claims: [
          "'Can' is the same for every person: I can, she can, they can.",
          "After 'can' the verb has no 'to' and no -s: 'she can drive', not 'she can to drives'.",
        ],
        ex: ["I can swim.", "She can drive.", "They can speak three languages."],
      },
      {
        form: "I can't",
        claims: [
          "The negative is 'cannot', and in speaking we say 'can't'.",
          "Questions put can first: 'Can you swim?' The answer is 'Yes, I can' or 'No, I can't'.",
        ],
        ex: ["I can't swim very well.", "Can you drive? No, I can't."],
      },
    ],
    ex: [
      fill("I ___ speak a little Spanish, but not much.", ["can"]),
      mcq("Which sentence is correct?", [
        "She can drive a car.",
        "She can to drive a car.",
        "She cans drive a car.",
      ], 0),
      say("I / not can / play / the guitar", [
        "I can't play the guitar.",
        "I cannot play the guitar.",
      ]),
    ],
    open: {
      q: "You are joining a sports club. Say two things you can do and one thing you cannot do yet.",
      must: ["I can", "I can't"],
      criteria: "The answer uses can and can't with the plain verb.",
      example: "I can swim and I can play tennis, but I can't ski yet.",
    },
    success: "The learner talks about abilities with can and can't at least twice.",
    quiz: [
      qmcq("Which question is correct?", ["Can you swim?", "Do you can swim?", "Are you can swim?"], 0),
      qfill("He ___ cook very well; he burns everything.", ["can't", "cannot"]),
      qmcq("Someone asks 'Can you drive?' You cannot. What do you say?", [
        "No, I can't.",
        "No, I don't can.",
        "No, I am not can.",
      ], 0),
    ],
    scenes: [
      sc("Berta", "a friend organising a trip", "to plan activities everyone can do",
        "A friend is planning a weekend trip with activities.",
        "Say what you can and cannot do.",
        "There's swimming, cycling and climbing. What works for you?", "energetic"),
      sc("Andre", "a manager checking team skills", "to find out what skills the team has",
        "Your manager is asking the team about their skills.",
        "Say what you can do and what you are still learning.",
        "I'm mapping the skills in the team. What are you good at?", "practical"),
      sc("Ingrid", "an instructor at the sports centre", "to put you in the right group",
        "You are joining a class and the instructor checks your level.",
        "Say what you can and cannot do.",
        "Before I put you in a group, what can you already do?", "friendly"),
      sc("Mr. Okafor", "your teacher", "to learn what the class can already do",
        "The class is talking about skills and abilities.",
        "Say what you can do and ask a classmate.",
        "Let's find out what this class can do. Who wants to start?", "warm"),
      sc("Ms. Grey", "the examiner", "to check that you can talk about ability",
        "The examiner asks about your skills.",
        "Say what you can and cannot do, with details.",
        "What can you do well, and what would you like to learn?", "neutral"),
    ],
  },

  {
    id: "a1-can-you-help-me",
    topic: "asking for help and permission",
    objectives: ["Ask for help politely with can.", "Ask for permission and answer."],
    goal: "Ask a colleague or a friend for a small favour.",
    target: "can you help / can I have / of course",
    correction: "Model the polite question and let the learner ask it again.",
    summary: "You learned to ask for help and permission with can, and how to answer politely.",
    minutes: 5,
    points: [
      {
        form: "Can you...?",
        claims: [
          "Use 'Can you' plus a verb to ask someone to do something for you.",
          "Adding 'please' makes the request friendlier.",
        ],
        ex: ["Can you help me, please?", "Can you open the window?"],
      },
      {
        form: "Can I...?",
        claims: [
          "Use 'Can I' to ask for permission or to ask for something you want.",
          "'Could I' is a little more polite and works in the same way.",
        ],
        ex: ["Can I have a glass of water?", "Could I use your phone?"],
      },
      {
        form: "Of course / Sorry, I can't",
        claims: [
          "Say 'Of course' or 'Sure' to agree, and 'Sorry, I can't' to say no politely.",
          "Give a short reason after saying no: it sounds kinder.",
        ],
        ex: ["Of course, here you are.", "Sorry, I can't right now. I'm in a meeting."],
      },
    ],
    ex: [
      fill("___ you help me with this box, please?", ["Can", "Could"]),
      mcq("You want a glass of water in a cafe. What do you say?", [
        "Can I have a glass of water, please?",
        "Can I to have a glass of water, please?",
        "I can have a glass of water, please?",
      ], 0),
      say("of course / here / you are", ["Of course, here you are."]),
    ],
    open: {
      q: "You need two small favours from a colleague. Ask politely and thank them.",
      must: ["can you help", "can I have"],
      criteria: "The answer asks politely with can and thanks the other person.",
      example: "Can you help me with this file, please? And can I have five minutes of your time later?",
    },
    success: "The learner asks for help or permission politely at least twice.",
    quiz: [
      qmcq("Which is a polite request?", [
        "Can you help me, please?",
        "You help me now.",
        "Help you me?",
      ], 0),
      qfill("___ I use your pen for a second?", ["Can", "Could"]),
      qmcq("Someone asks for help and you are free. What do you say?", [
        "Of course!",
        "Sorry, I can.",
        "No, of course.",
      ], 0),
    ],
    scenes: [
      sc("Maya", "a neighbour with her hands full", "to get through the door with her shopping",
        "Your neighbour is at the door with heavy bags.",
        "Offer help and ask her some questions.",
        "Oh, these bags are so heavy! Could I ask you something?", "grateful"),
      sc("Dan", "a colleague at the next desk", "to keep the office running smoothly",
        "You need a few things from a colleague during a busy morning.",
        "Ask politely for help and for things you need.",
        "Morning! You look like you need something. What is it?", "friendly"),
      sc("Priya", "a hotel receptionist", "to help a guest with requests",
        "You need several things at your hotel.",
        "Ask politely for each thing.",
        "Good evening. How can I help you?", "polite"),
      sc("Mrs. Tan", "your teacher", "to practise polite requests",
        "In class you practise asking for things politely.",
        "Ask for help and permission with can.",
        "Imagine you need something from me. What would you say?", "warm"),
      sc("Mr. Ivanov", "the examiner", "to check that you can make polite requests",
        "The examiner asks you to role play asking for help.",
        "Make two polite requests.",
        "Imagine you need my help with something. What would you ask?", "neutral"),
    ],
  },

  {
    id: "a1-my-weekend",
    topic: "talking about your weekend",
    objectives: ["Talk about what I do at weekends.", "Ask a friend about their weekend."],
    goal: "Catch up with a friend about weekends and free time.",
    target: "at the weekend / I usually / with my friends",
    correction: "Give a natural weekend phrase and let the learner use it in their answer.",
    summary: "You practised talking about weekends, hobbies and who you spend time with.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "at the weekend",
        claims: [
          "Say 'at the weekend' for weekends in general and 'this weekend' for the coming one.",
          "Add 'usually' to talk about what normally happens.",
        ],
        ex: ["At the weekend I usually sleep late.", "This weekend I'm visiting my parents."],
      },
      {
        form: "with my friends",
        claims: [
          "Use 'with' plus a person to say who you spend time with.",
          "You can add a place after it: with my friends in the park.",
        ],
        ex: ["I play football with my friends.", "I go out with my family on Sundays."],
      },
    ],
    ex: [
      fill("___ the weekend I usually see my family.", ["At"]),
      mcq("Which sentence is correct?", [
        "I go to the park with my friends.",
        "I go to the park with my friend's.",
        "I go to the park by my friends.",
      ], 0),
      say("I / usually / stay / at home / on Sundays", ["I usually stay at home on Sundays."]),
    ],
    open: {
      q: "Tell me what you usually do at the weekend and who you do it with.",
      must: ["at the weekend", "with my friends"],
      criteria: "The answer describes weekend activities and says who is involved.",
      example: "At the weekend I usually go running, and on Saturday evening I meet up with my friends.",
    },
    success: "The learner describes weekend routines and asks the other person about theirs.",
    quiz: [
      qmcq("Which phrase talks about weekends in general?", [
        "at the weekend",
        "in the weekend day",
        "on weekend time",
      ], 0),
      qfill("I play tennis ___ my brother every Saturday.", ["with"]),
      qmcq("Which sentence is correct?", [
        "I usually get up late on Sundays.",
        "I get up usually late on Sundays.",
        "Usually I am get up late on Sundays.",
      ], 0),
    ],
    scenes: [
      sc("Rosie", "a friend you meet on Monday", "to hear about your weekend",
        "It is Monday morning and you meet a friend for coffee.",
        "Talk about your weekend and ask about hers.",
        "Monday again! How was your weekend?", "cheerful"),
      sc("Tobias", "a colleague at the coffee machine", "to make friendly small talk",
        "You meet a colleague at the coffee machine on Monday.",
        "Talk about weekends and free time.",
        "Back to work! Did you do anything nice at the weekend?", "friendly"),
      sc("Ana", "a fellow guest at breakfast", "to swap ideas for the weekend in the city",
        "You are at a hostel breakfast and the weekend is coming.",
        "Talk about what you usually do and what you might do here.",
        "It's Friday tomorrow. What do you normally do at weekends?", "relaxed"),
      sc("Mr. Vidal", "your teacher", "to hear a longer answer about free time",
        "In class you are talking about weekends.",
        "Describe your usual weekend in detail.",
        "Tell us about a typical weekend for you. Where do we start?", "warm"),
      sc("Ms. Blanc", "the examiner", "to hear you speak for about a minute",
        "The examiner asks about your weekends.",
        "Describe what you usually do and with whom.",
        "Could you tell me what you usually do at the weekend?", "neutral"),
    ],
  },

  {
    id: "a1-lets-go-out",
    topic: "inviting someone out",
    objectives: ["Invite someone to do something.", "Accept or refuse an invitation politely."],
    goal: "Make plans with a friend for the evening.",
    target: "do you want to / let's go / sounds good",
    correction: "Give the natural invitation phrase and let the learner try the exchange again.",
    summary: "You learned how to invite someone out and how to say yes or no politely.",
    minutes: 5,
    points: [
      {
        form: "Do you want to...?",
        claims: [
          "'Do you want to' plus a verb is a simple, friendly way to invite someone.",
          "'Would you like to' is the same idea but a little more polite.",
        ],
        ex: ["Do you want to see a film tonight?", "Would you like to join us?"],
      },
      {
        form: "Let's go",
        claims: [
          "'Let's' plus a plain verb suggests doing something together.",
          "It already includes you, so do not add 'we': say 'Let's go', not 'Let's we go'.",
        ],
        ex: ["Let's go to that new place.", "Let's meet at seven."],
      },
      {
        form: "Sounds good / Sorry, I can't",
        claims: [
          "Say 'Sounds good' or 'I'd love to' to accept an invitation.",
          "To refuse, say 'Sorry, I can't' and give a short reason.",
        ],
        ex: ["Sounds good, see you there.", "Sorry, I can't tonight. I'm working late."],
      },
    ],
    ex: [
      fill("___ go to the cinema tonight!", ["Let's"]),
      mcq("A friend invites you and you are free and happy to go. What do you say?", [
        "Sounds good!",
        "Sorry, I can't.",
        "Never mind, thanks.",
      ], 0),
      say("do / you / want / to / have dinner", ["Do you want to have dinner?"]),
    ],
    open: {
      q: "Invite a friend to do something this evening and suggest a time.",
      must: ["do you want to", "let's go"],
      criteria: "The answer makes an invitation and suggests a plan or a time.",
      example: "Do you want to get something to eat tonight? Let's go at about eight.",
    },
    success: "The learner invites, suggests a time and responds to the other person's answer.",
    quiz: [
      qmcq("Which sentence is an invitation?", [
        "Do you want to come with us?",
        "You are coming with us now.",
        "I want you come with us.",
      ], 0),
      qfill("___ meet at the station at six.", ["Let's"]),
      qmcq("You cannot accept an invitation. What is polite?", [
        "Sorry, I can't tonight.",
        "No, I don't want.",
        "That is impossible for me, no.",
      ], 0),
    ],
    scenes: [
      sc("Jonas", "a friend who is free tonight", "to make a plan for the evening",
        "You and a friend are texting about the evening.",
        "Invite him, agree on a place and a time.",
        "I've finished work early today. Any plans for tonight?", "cheerful"),
      sc("Claire", "a colleague after work", "to organise something with the team",
        "Some colleagues are going out after work.",
        "Invite your colleague and agree on the details.",
        "A few of us might go out later. Are you interested?", "friendly"),
      sc("Miguel", "a traveller in your hostel", "to find company for the evening",
        "You want to go out and ask a traveller to come along.",
        "Invite him and make the plan.",
        "There's a street festival tonight, apparently. Are you going out?", "relaxed"),
      sc("Ms. Weiss", "your teacher", "to practise invitations",
        "In class you practise inviting and answering.",
        "Make an invitation and respond to one.",
        "Let's practise invitations. Would you like to start?", "warm"),
      sc("Mr. Frank", "the examiner", "to check that you can invite and respond",
        "The examiner asks you to role play making plans.",
        "Invite the examiner and agree on a plan.",
        "Imagine we are friends making plans. What would you suggest?", "neutral"),
    ],
  },

  // --- Ünite 6 · Describing ---------------------------------------------------
  {
    id: "a1-a-small-red-car",
    topic: "where describing words go",
    objectives: ["Put describing words before the noun.", "Use very and really to make a description stronger."],
    goal: "Describe an object clearly so someone can find it.",
    target: "it's very small / my new phone / really nice",
    correction: "Say the phrase with the words in the right order and let the learner repeat it.",
    summary: "You learned where describing words go and how to make them stronger with very and really.",
    minutes: 6,
    points: [
      {
        form: "a small red car",
        claims: [
          "Describing words come before the thing they describe: a small car, a red bag.",
          "They never change for plural: 'two small cars', not 'two smalls cars'.",
          "You can also put them after 'be': the car is small.",
        ],
        ex: ["It's a small red car.", "My new phone is black.", "The bag is very heavy."],
      },
      {
        form: "very / really",
        claims: [
          "Put 'very' or 'really' before the describing word to make it stronger.",
          "'Quite' makes it weaker: quite big means big, but not very big.",
        ],
        ex: ["It's very small.", "That's really nice.", "The room is quite big."],
      },
    ],
    ex: [
      fill("I lost a ___ black bag on the bus.", ["small", "big"]),
      mcq("Which sentence is correct?", [
        "I have two small dogs.",
        "I have two smalls dogs.",
        "I have two dogs smalls.",
      ], 0),
      say("it / be / very / small", ["It's very small.", "It is very small."]),
    ],
    open: {
      q: "You lost a bag. Describe it so someone can find it: size, colour and one more detail.",
      must: ["it's a small", "it's really"],
      criteria: "The answer describes an object with describing words in the correct position.",
      example: "It's a small black bag. It's really old and there's a red label on it.",
    },
    success: "The learner describes objects with correct word order at least twice.",
    quiz: [
      qmcq("Which is correct?", ["a big blue box", "a box big blue", "a blue big of box"], 0),
      qfill("This coffee is ___ hot. Be careful!", ["very", "really"]),
      qmcq("Which sentence is correct?", [
        "My new phone is very light.",
        "My phone new is very light.",
        "My new phone very light.",
      ], 0),
    ],
    scenes: [
      sc("Nell", "a friend helping you search", "to find the thing you lost",
        "You lost something at a friend's house and describe it on the phone.",
        "Describe the object with size, colour and details.",
        "I'll go and look now. What exactly am I looking for?", "helpful"),
      sc("Georg", "a colleague at the lost property desk", "to match your description with lost items",
        "You are describing a lost item at the office reception.",
        "Describe the object precisely.",
        "We have several items here. Can you describe yours?", "practical"),
      sc("Ivana", "an airport lost luggage officer", "to identify your suitcase",
        "Your suitcase did not arrive and you have to describe it.",
        "Describe the suitcase in detail.",
        "I need a description for the report. What does your case look like?", "polite"),
      sc("Mr. Sato", "your teacher", "to practise describing objects",
        "The teacher hides an object and you describe it.",
        "Describe objects with several describing words.",
        "I have something in my bag. Describe something you can see instead?", "warm"),
      sc("Ms. Dean", "the examiner", "to check that you can describe things",
        "The examiner shows pictures of similar objects.",
        "Describe one so the examiner knows which one you mean.",
        "There are four bags in this picture. Can you describe one of them?", "neutral"),
    ],
  },

  {
    id: "a1-what-does-she-look-like",
    topic: "describing people",
    objectives: ["Describe someone's appearance.", "Ask what someone looks like."],
    goal: "Describe a person so someone can recognise them.",
    target: "she has long hair / he is tall / what does she look like",
    correction: "Model the correct verb for the detail and let the learner say the sentence again.",
    summary: "You learned to describe what people look like and how to ask about it.",
    minutes: 6,
    points: [
      {
        form: "he is tall",
        claims: [
          "Use 'be' for height, age and general looks: he is tall, she is young.",
        ],
        ex: ["He is tall and quite thin.", "She is about thirty."],
      },
      {
        form: "she has long hair",
        claims: [
          "Use 'have' or 'has' for hair, eyes and glasses: she has long hair, he has glasses.",
          "The colour comes before the noun: dark hair, blue eyes.",
        ],
        ex: ["She has long dark hair.", "He has blue eyes and glasses."],
      },
      {
        form: "What does she look like?",
        claims: [
          "Ask 'What does she look like?' about appearance.",
          "This is different from 'What is she like?', which asks about personality.",
        ],
        ex: ["What does she look like?", "What does your brother look like?"],
      },
    ],
    ex: [
      fill("She ___ long dark hair.", ["has"]),
      mcq("Which sentence is correct?", [
        "He is tall and he has short hair.",
        "He has tall and he is short hair.",
        "He is tall and he is short hair.",
      ], 0),
      say("what / she / look like / question", ["What does she look like?"]),
    ],
    open: {
      // Ders 3. ŞAHIS betimlemeyi öğretiyor ("what does she look like") ama soru
      // birinci şahıs istiyordu — öğrenci ipucuna baktığında öğretilen yapıyı
      // hiç görmüyordu. Soru da örnek de 3. şahsa çevrildi.
      q: "A friend is meeting your sister at the station and has never seen her. Describe her.",
      must: ["he is tall", "she has long hair"],
      criteria: "The answer describes appearance with be and have correctly.",
      example: "My sister is tall and she has long hair. She usually wears a blue coat.",
    },
    success: "The learner describes people using be and have correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "She has green eyes.",
        "She is green eyes.",
        "She has got green eyes are.",
      ], 0),
      qfill("My brother ___ very tall, about two metres.", ["is", "'s"]),
      qmcq("Which question asks about appearance?", [
        "What does he look like?",
        "What does he like?",
        "How is he looking to?",
      ], 0),
    ],
    scenes: [
      sc("Fiona", "a friend meeting your cousin", "to recognise the person she is meeting",
        "Your cousin is arriving and your friend will meet her at the station.",
        "Describe the person so your friend can find her.",
        "I've never met your cousin. How will I recognise her?", "helpful"),
      sc("Marcus", "a receptionist expecting a visitor", "to know who to expect at reception",
        "A visitor is coming to your office and reception needs a description.",
        "Describe the visitor.",
        "I'll watch out for your guest. What do they look like?", "practical"),
      sc("Lila", "a tour guide looking for a lost group member", "to find the missing person",
        "Someone from your tour group is missing.",
        "Describe the person to the guide.",
        "We're one person short. Can you describe them for me?", "concerned"),
      sc("Mr. Haddad", "your teacher", "to practise describing people",
        "The class describes people in photos.",
        "Describe a person in detail.",
        "Look at this photo. Can you describe this person?", "warm"),
      sc("Ms. Novak", "the examiner", "to check that you can describe a person",
        "The examiner asks you to describe someone you know.",
        "Describe their appearance clearly.",
        "Could you describe a person in your family for me?", "neutral"),
    ],
  },

  {
    id: "a1-its-cold-today",
    topic: "the weather",
    objectives: ["Talk about today's weather.", "Ask what the weather is like."],
    goal: "Talk about the weather before going out.",
    target: "it's cold / it's raining / what's the weather like",
    correction: "Model the weather phrase and let the learner say it again.",
    summary: "You learned to talk about the weather and to ask what it is like.",
    minutes: 5,
    points: [
      {
        form: "it's cold / it's sunny",
        claims: [
          "Weather sentences start with 'it': it's cold, it's hot, it's windy.",
          "Never leave out 'it': say 'it's cold', not 'is cold'.",
        ],
        ex: ["It's cold today.", "It's very sunny this morning."],
      },
      {
        form: "it's raining",
        claims: [
          "For rain and snow happening now, use the -ing form: it's raining, it's snowing.",
        ],
        ex: ["Take an umbrella, it's raining.", "Look, it's snowing!"],
      },
      {
        form: "What's the weather like?",
        claims: [
          "Ask 'What's the weather like?' to find out about the weather in a place.",
        ],
        ex: ["What's the weather like today?", "What's the weather like in your city?"],
      },
    ],
    ex: [
      fill("Take a coat. ___ very cold outside.", ["It's", "It is"]),
      mcq("It is raining at this moment. What do you say?", [
        "It's raining.",
        "It rains now.",
        "It is rain now.",
      ], 0),
      say("what / the weather / be like / today", ["What's the weather like today?"]),
    ],
    open: {
      q: "Describe the weather today and say what people should wear.",
      must: ["it's cold", "what's the weather like"],
      criteria: "The answer describes the weather with it and gives simple advice.",
      example: "It's cold and it's raining, so take a warm coat and an umbrella.",
    },
    success: "The learner describes weather and asks about it at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", ["It's very windy today.", "Is very windy today.", "It very windy today."], 0),
      qfill("Look outside, it's ___ again! Get the umbrella.", ["raining"]),
      qmcq("How do you ask about the weather?", [
        "What's the weather like?",
        "How is the weather like it?",
        "What is like weather?",
      ], 0),
    ],
    scenes: [
      sc("Petra", "a friend calling from another city", "to compare the weather in two cities",
        "A friend calls you from a different city and the weather is very different.",
        "Describe your weather and ask about hers.",
        "You won't believe the weather here! What's it like where you are?", "chatty"),
      sc("Colin", "a colleague planning an outdoor event", "to decide whether to move the event indoors",
        "Your team is planning an outdoor event and the weather matters.",
        "Describe the forecast and give advice.",
        "We need to decide about tomorrow. What's the weather doing?", "practical"),
      sc("Aiko", "a hotel receptionist", "to advise a guest before a day out",
        "You are asking about the weather before a day of sightseeing.",
        "Ask about the weather and say what you will take.",
        "Are you going out today? Shall I tell you about the weather?", "helpful"),
      sc("Mr. Rahman", "your teacher", "to practise weather language",
        "The class talks about weather in different seasons.",
        "Describe the weather in your country.",
        "What is the weather like in your country in winter?", "warm"),
      sc("Ms. Beck", "the examiner", "to check that you can describe weather",
        "The examiner asks about weather and seasons.",
        "Describe today's weather and your favourite season.",
        "What is the weather like today?", "neutral"),
    ],
  },

  {
    id: "a1-what-should-i-wear",
    topic: "clothes and what to wear",
    objectives: ["Name common clothes.", "Ask and say what to wear for the day."],
    goal: "Decide what to wear for the day and explain why.",
    target: "I'm wearing / what should I wear / put on",
    correction: "Model the clothes phrase and let the learner say the sentence again.",
    summary: "You learned the names of clothes and how to ask and say what to wear.",
    minutes: 5,
    points: [
      {
        form: "I'm wearing",
        claims: [
          "Use 'I'm wearing' for the clothes on your body right now.",
          "Use 'I wear' for what you normally wear.",
        ],
        ex: ["I'm wearing a blue jacket today.", "I usually wear jeans at the weekend."],
      },
      {
        form: "What should I wear?",
        claims: [
          "'What should I wear?' asks for advice about clothes; learn it as one phrase.",
          "The answer often starts with 'Wear' or 'Take': Wear a coat. Take an umbrella.",
        ],
        ex: ["What should I wear tonight?", "Wear something warm."],
      },
      {
        form: "put on / take off",
        claims: [
          "'Put on' means to start wearing something, and 'take off' means to stop wearing it.",
        ],
        ex: ["Put on your coat, it's cold.", "Take off your shoes at the door."],
      },
    ],
    ex: [
      fill("It's cold, so ___ on your warm coat.", ["put"]),
      mcq("You are describing your clothes right now. What do you say?", [
        "I'm wearing a red shirt.",
        "I wear a red shirt now.",
        "I am wear a red shirt.",
      ], 0),
      say("what / I / should / wear / tomorrow", ["What should I wear tomorrow?"]),
    ],
    open: {
      q: "It is cold and rainy. Say what you are going to wear and why.",
      must: ["I'm wearing", "put on"],
      criteria: "The answer names clothes and connects them to the weather.",
      example: "It's freezing, so I'm wearing a thick jumper and I'll put on my boots.",
    },
    success: "The learner talks about clothes and gives advice about what to wear.",
    quiz: [
      qmcq("Which sentence is about right now?", [
        "I'm wearing black shoes.",
        "I wear black shoes every day.",
        "I wore black shoes yesterday.",
      ], 0),
      qfill("It's sunny. Don't forget to ___ on some sun cream.", ["put"]),
      qmcq("How do you ask for clothes advice?", [
        "What should I wear?",
        "What I must to wear?",
        "Which is wearing me?",
      ], 0),
    ],
    scenes: [
      sc("Sarah", "a friend going to the same party", "to agree on what to wear",
        "You and a friend are going to the same event tonight.",
        "Ask for advice and say what you are wearing.",
        "I have no idea what to wear tonight. Have you decided?", "cheerful"),
      sc("Ravi", "a colleague explaining the dress code", "to help you fit the office dress code",
        "It is your first week and you are unsure about the office dress code.",
        "Ask about clothes and describe what you usually wear.",
        "People sometimes ask about the dress code here. Any questions?", "friendly"),
      sc("Marta", "a guide before a mountain trip", "to make sure everyone is dressed properly",
        "You are going on a mountain excursion tomorrow.",
        "Ask what to wear and confirm your clothes.",
        "It gets cold up there. Do you know what to bring?", "practical"),
      sc("Mrs. Lopez", "your teacher", "to practise clothes vocabulary",
        "The class describes what people in pictures are wearing.",
        "Describe clothes in the pictures.",
        "Look at these photos. What are these people wearing?", "warm"),
      sc("Mr. Ellis", "the examiner", "to check that you can describe clothes",
        "The examiner asks about your clothes and habits.",
        "Describe what you wear on different days.",
        "What do you usually wear when you go out?", "neutral"),
    ],
  },

  {
    id: "a1-my-favourite-place",
    topic: "describing a place you like",
    objectives: ["Describe a room or place and what is in it.", "Say why I like a place."],
    goal: "Show someone around your favourite place.",
    target: "there is / on the left / I really like",
    correction: "Offer a phrase for position or opinion and let the learner continue the description.",
    summary: "You practised describing a place, saying what is in it and why you like it.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "on the left / on the right",
        claims: [
          "Use 'on the left' and 'on the right' to guide someone through a place.",
          "'In the corner' and 'in the middle' help you describe a room clearly.",
        ],
        ex: ["On the left there's a big window.", "The table is in the middle of the room."],
      },
      {
        form: "I really like it because",
        claims: [
          "Use 'because' to give the reason why you like a place.",
          "One reason is enough at this level, but it makes your answer much better.",
        ],
        ex: ["I really like it because it's quiet.", "I love this room because of the light."],
      },
    ],
    ex: [
      fill("___ the left you can see the kitchen.", ["On"]),
      mcq("Which sentence gives a reason?", [
        "I like this place because it's quiet.",
        "I like this place but it's quiet.",
        "I like this place so quiet is.",
      ], 0),
      say("there / be / a big window / in my room", [
        "There's a big window in my room.",
        "There is a big window in my room.",
      ]),
    ],
    open: {
      q: "Describe your favourite room or place. Say what is in it and why you like it.",
      must: ["there is", "I really like"],
      criteria: "The answer describes a place with positions and gives a reason.",
      example: "There's a small sofa on the left and a big window opposite. I really like it because it's very quiet.",
    },
    success: "The learner describes a place with positions and gives at least one reason.",
    quiz: [
      qmcq("Which phrase describes position?", ["in the corner", "because of it", "very often"], 0),
      qfill("There ___ two chairs and a small table in the room.", ["are"]),
      qmcq("Which sentence is correct?", [
        "I like it because it's near the sea.",
        "I like it because of it's near the sea.",
        "I like it why it's near the sea.",
      ], 0),
    ],
    scenes: [
      sc("Dilek", "a friend seeing your home for the first time", "to see the place you always talk about",
        "A friend is visiting your home for the first time.",
        "Show her around and describe the rooms.",
        "So this is your place! Will you show me around?", "excited"),
      sc("Frank", "a colleague joining your remote team", "to understand where you work from",
        "A colleague asks about your home office on a video call.",
        "Describe your working space and why you like it.",
        "Your background looks nice. What's the rest of the room like?", "curious"),
      sc("Yusuf", "a host showing you the city", "to hear about a place that matters to you",
        "You are telling a local host about your favourite place at home.",
        "Describe the place and why it matters to you.",
        "Everyone has a favourite place. What's yours?", "warm"),
      sc("Mrs. Peters", "your teacher", "to hear a longer descriptive answer",
        "In class you describe a place you like.",
        "Describe the place with details and reasons.",
        "Would you describe a place you love, in as much detail as you can?", "warm"),
      sc("Ms. Ahmed", "the examiner", "to hear you describe a place for a minute",
        "The examiner asks about a place you like.",
        "Describe the place, what is in it and why you like it.",
        "Could you describe your favourite place?", "neutral"),
    ],
  },

  {
    id: "a1-show-me-a-photo",
    topic: "talking about a photo",
    objectives: ["Say who is in a photo and where they are.", "Say what people in a photo are doing."],
    goal: "Show a photo on your phone and talk about it.",
    target: "in this photo / this is my / on the left",
    correction: "Give a phrase for describing photos and let the learner continue.",
    summary: "You practised describing a photo: the people, the place and what is happening.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "in this photo",
        claims: [
          "Start with 'in this photo' or 'here' to open your description.",
          "Then say who the people are and where they are.",
        ],
        ex: ["In this photo we're at the beach.", "Here you can see my whole family."],
      },
      {
        form: "she's smiling",
        claims: [
          "Use be plus the -ing form to say what people in a photo are doing.",
          "It describes the moment of the photo, so it fits perfectly.",
        ],
        ex: ["She's smiling because it was her birthday.", "They're all laughing."],
      },
    ],
    ex: [
      fill("___ this photo you can see my sister.", ["In"]),
      mcq("Which sentence describes what a person in a photo is doing?", [
        "He's holding a big cake.",
        "He hold a big cake.",
        "He is hold a big cake.",
      ], 0),
      say("this / be / my / brother", ["This is my brother."]),
    ],
    open: {
      q: "Describe a photo you like: who is in it, where it is and what is happening.",
      must: ["in this photo", "this is my"],
      criteria: "The answer identifies people, place and actions in the photo.",
      example: "In this photo we're in the mountains. This is my brother, and he's cooking outside.",
    },
    success: "The learner describes people, places and actions in a photo at least twice.",
    quiz: [
      qmcq("Which phrase opens a photo description?", ["In this photo...", "Because of that...", "At the end..."], 0),
      qfill("They ___ playing football in the park.", ["are", "'re"]),
      qmcq("Which sentence is correct?", [
        "On the left you can see my mother.",
        "On the left you can see my mother is.",
        "In the left you can see my mother.",
      ], 0),
    ],
    scenes: [
      sc("Lena", "a friend looking at your phone", "to hear the story behind the photos",
        "You are showing photos from a trip to a friend.",
        "Describe several photos: people, places and actions.",
        "Your trip photos look great! Can you talk me through them?", "curious"),
      sc("Ben", "a colleague on a coffee break", "to get to know you outside work",
        "A colleague asks about a photo on your desk.",
        "Describe the photo and the people in it.",
        "Nice photo on your desk. Who is in it?", "friendly"),
      sc("Sofia", "a host family member", "to see photos of your life at home",
        "Your host family asks to see photos of your family and home.",
        "Describe the photos in detail.",
        "We would love to see where you come from. Do you have photos?", "warm"),
      sc("Mr. Ncube", "your teacher", "to practise describing pictures",
        "In class you describe photographs.",
        "Describe a photo with people, place and actions.",
        "Choose a photo on your phone and describe it. Ready?", "warm"),
      sc("Ms. Vega", "the examiner", "to hear you describe a picture",
        "The examiner gives you a photo to describe.",
        "Describe the people, the place and what is happening.",
        "Look at this photo. What can you tell me about it?", "neutral"),
    ],
  },

  // --- Ünite 7 · Out and About ------------------------------------------------
  {
    id: "a1-two-coffees-please",
    topic: "ordering food and drink",
    objectives: ["Order food and drink politely.", "Answer the questions staff ask."],
    goal: "Order what you want in a cafe.",
    target: "I'd like / can I have / anything else",
    correction: "Model the ordering phrase and let the learner order again.",
    summary: "You learned how to order food and drink and how to answer common questions.",
    minutes: 5,
    points: [
      {
        form: "I'd like / Can I have",
        claims: [
          "'I'd like' and 'Can I have' are the two normal ways to order.",
          "'I want' sounds rude in a shop or a cafe, so avoid it.",
          "Add 'please' at the end of your order.",
        ],
        ex: ["I'd like a coffee, please.", "Can I have two teas, please?"],
      },
      {
        form: "Anything else?",
        claims: [
          "Staff often ask 'Anything else?' to check if your order is finished.",
          "Answer 'No, that's all, thanks' or add one more thing.",
        ],
        ex: ["Anything else? No, that's all, thanks.", "Yes, and a bottle of water, please."],
      },
    ],
    ex: [
      fill("___ like a coffee, please.", ["I'd", "I would"]),
      mcq("Which is the most polite way to order?", [
        "Can I have a tea, please?",
        "I want a tea now.",
        "Give me a tea.",
      ], 0),
      say("can / I / have / two coffees / please", ["Can I have two coffees, please?"]),
    ],
    open: {
      q: "You are in a cafe. Order two things and answer when the server asks if you want anything else.",
      must: ["I'd like", "can I have"],
      criteria: "The answer orders politely and responds to the follow-up question.",
      example: "I'd like a coffee and a sandwich, please. No, that's all, thanks.",
    },
    success: "The learner orders politely and answers the server's questions.",
    quiz: [
      qmcq("Which sentence is polite in a cafe?", [
        "I'd like a sandwich, please.",
        "I want a sandwich.",
        "Sandwich for me now.",
      ], 0),
      qfill("Can I ___ the bill, please?", ["have"]),
      qmcq("The server asks 'Anything else?' You are finished. What do you say?", [
        "No, that's all, thanks.",
        "Yes, nothing more thanks.",
        "No, anything else.",
      ], 0),
    ],
    scenes: [
      sc("Kim", "a server in a busy cafe", "to take your order quickly and correctly",
        "You are ordering at a busy cafe at lunchtime.",
        "Order drinks and food politely.",
        "Hi there! What can I get you?", "busy"),
      sc("Peter", "a colleague taking the coffee order", "to bring back the right drinks for the team",
        "A colleague is going to the cafe and takes orders.",
        "Order for yourself clearly.",
        "I'm doing a coffee run. What would you like?", "friendly"),
      sc("Nadia", "a waiter in a hotel restaurant", "to serve you breakfast",
        "You are having breakfast at your hotel.",
        "Order what you want and answer her questions.",
        "Good morning! Would you like to order something?", "polite"),
      sc("Mr. Vance", "your teacher", "to practise ordering",
        "In class you role play a cafe.",
        "Order politely with different phrases.",
        "Imagine I am the server in a cafe. What would you say?", "warm"),
      sc("Ms. Rahman", "the examiner", "to check that you can order politely",
        "The examiner role plays a cafe scene.",
        "Order two things politely.",
        "Imagine we are in a cafe and I work there. What would you order?", "neutral"),
    ],
  },

  {
    id: "a1-how-much-is-it",
    topic: "prices and shopping",
    objectives: ["Ask how much things cost.", "React to a price and decide to buy or not."],
    goal: "Buy something small and check the price first.",
    target: "how much is it / that's too expensive / I'll take it",
    correction: "Model the shopping phrase and let the learner use it again.",
    summary: "You learned to ask about prices, react to them and say what you will buy.",
    minutes: 5,
    points: [
      {
        form: "How much is it?",
        claims: [
          "Ask 'How much is it?' about one thing and 'How much are they?' about more than one.",
          "'How much does it cost?' means exactly the same.",
        ],
        ex: ["How much is it?", "How much are these?"],
      },
      {
        form: "That's too expensive",
        claims: [
          "'Too expensive' means more than you want to pay.",
          "'It's a good price' or 'That's cheap' show that you are happy with the price.",
        ],
        ex: ["That's too expensive for me.", "That's a good price."],
      },
      {
        form: "I'll take it",
        claims: [
          "Say 'I'll take it' when you decide to buy something.",
          "To say no politely, say 'I'll think about it, thanks'.",
        ],
        ex: ["I'll take it, thanks.", "I'll think about it, thank you."],
      },
    ],
    ex: [
      fill("___ much is this jacket?", ["How"]),
      mcq("The price is much higher than you expected. What do you say?", [
        "That's too expensive for me.",
        "That's too cheap for me.",
        "That's a very good price for me.",
      ], 0),
      say("I / take / it / please", ["I'll take it, please.", "I will take it, please."]),
    ],
    open: {
      q: "You are in a shop and like something, but it is expensive. Ask the price and decide.",
      must: ["how much is it", "I'll take it"],
      criteria: "The answer asks about a price, reacts to it and makes a decision.",
      example: "How much is it? Oh, that's a bit expensive, but it's lovely. I'll take it.",
    },
    success: "The learner asks about prices and decides whether to buy.",
    quiz: [
      qmcq("Which question asks about the price of two things?", [
        "How much are they?",
        "How much is they?",
        "How many is it?",
      ], 0),
      qfill("I like it, but it's too ___ for me. I can't pay that.", ["expensive"]),
      qmcq("You decide to buy something. What do you say?", [
        "I'll take it.",
        "I take him.",
        "I am taking it to me.",
      ], 0),
    ],
    scenes: [
      sc("Ella", "a seller at a clothes stall", "to sell you something from the stall",
        "You are looking at clothes at a market stall.",
        "Ask prices, react and decide.",
        "That one suits you! Would you like to know the price?", "cheerful"),
      sc("Onur", "a colleague buying office supplies", "to stay inside the office budget",
        "You are buying supplies with a colleague and comparing prices.",
        "Ask about prices and say what is too expensive.",
        "We have a small budget for this. What do you think of these prices?", "practical"),
      sc("Rita", "a shop assistant in a souvenir shop", "to help you find a souvenir in your budget",
        "You are buying souvenirs and watching your money.",
        "Ask prices and choose what to buy.",
        "Are you looking for something in particular today?", "helpful"),
      sc("Mr. Aslan", "your teacher", "to practise shopping language",
        "In class you role play a shop.",
        "Ask about prices and make a decision.",
        "Imagine I'm selling things at a market. What do you want to know?", "warm"),
      sc("Ms. Klein", "the examiner", "to check that you can handle a shop conversation",
        "The examiner role plays a shop assistant.",
        "Ask about prices and decide whether to buy.",
        "Imagine you are in a shop and I work there. How do you begin?", "neutral"),
    ],
  },

  {
    id: "a1-some-bread-any-milk",
    topic: "some and any",
    objectives: ["Use some and any correctly.", "Talk about food you can and cannot count."],
    goal: "Check what you need before going shopping.",
    target: "some bread / any milk / we need some",
    correction: "Model the sentence with some or any and let the learner repeat it.",
    summary: "You learned when to use some and any, and which food words you cannot count.",
    minutes: 6,
    points: [
      {
        form: "some",
        claims: [
          "Use 'some' in positive sentences for an amount you do not count: some bread, some water.",
          "'Some' also works with plural words: some apples, some eggs.",
        ],
        ex: ["We need some bread.", "There are some eggs in the fridge."],
      },
      {
        form: "any",
        claims: [
          "Use 'any' in negative sentences and most questions: we haven't got any milk.",
          "In offers and requests, 'some' is normal: Would you like some tea?",
        ],
        ex: ["Have we got any milk?", "There isn't any sugar left."],
      },
      {
        form: "countable and uncountable",
        claims: [
          "Words like bread, milk, rice and water have no plural: not 'breads', not 'milks'.",
          "For an amount, use a container or a measure: a bottle of water, a kilo of rice.",
        ],
        ex: ["I bought a bottle of water.", "We need a kilo of rice."],
      },
    ],
    ex: [
      fill("Have we got ___ milk left?", ["any"]),
      mcq("Which sentence is correct?", [
        "There isn't any bread.",
        "There isn't some bread.",
        "There aren't any bread's.",
      ], 0),
      say("we / need / some / bread", ["We need some bread."]),
    ],
    open: {
      q: "Check your kitchen before shopping. Say two things you have and two things you need.",
      must: ["some bread", "any milk"],
      criteria: "The answer uses some and any correctly with food words.",
      example: "We've got some rice and some eggs, but we haven't got any milk or any bread.",
    },
    success: "The learner uses some and any correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'd like some water, please.",
        "I'd like a water some, please.",
        "I'd like any water, please.",
      ], 0),
      qfill("We haven't got ___ sugar for the cake.", ["any"]),
      qmcq("Which is correct?", ["two bottles of water", "two waters bottle", "two waters of bottle"], 0),
    ],
    scenes: [
      sc("Ada", "a flatmate checking the kitchen", "to make a shopping list together",
        "You and your flatmate are checking what is missing in the kitchen.",
        "Say what you have and what you need.",
        "I'm going shopping in ten minutes. What are we missing?", "practical"),
      sc("Nick", "a colleague organising office supplies", "to restock the office kitchen",
        "The office kitchen needs restocking.",
        "Say what there is and what is missing.",
        "The kitchen looks empty. What should I order?", "busy"),
      sc("Sinem", "a host preparing dinner", "to cook a meal with what is in the house",
        "You are helping your host cook and checking ingredients.",
        "Say what there is and what you need to buy.",
        "Let's see what we can cook. What have we got?", "warm"),
      sc("Mrs. Owens", "your teacher", "to practise some and any",
        "In class you talk about food and shopping lists.",
        "Say what you need using some and any.",
        "Imagine your fridge at home. What is in it?", "warm"),
      sc("Mr. Nakada", "the examiner", "to check that you can talk about food",
        "The examiner asks about your shopping habits.",
        "Talk about food using some and any.",
        "What do you usually buy when you go shopping?", "neutral"),
    ],
  },

  {
    id: "a1-at-the-market",
    topic: "buying food by amount",
    objectives: ["Name common fruit and vegetables.", "Buy food by weight and number."],
    goal: "Buy fruit and vegetables at a market.",
    target: "how much is / two kilos of / anything else",
    correction: "Model the amount phrase and let the learner order again.",
    summary: "You learned food words and how to buy things by weight and number at a market.",
    minutes: 5,
    points: [
      {
        form: "two kilos of",
        claims: [
          "Use a number plus 'kilos of' or 'grams of' plus the food: two kilos of apples.",
          "For single items, just use the number: three lemons, six eggs.",
        ],
        ex: ["Two kilos of apples, please.", "Can I have six eggs?"],
      },
      {
        form: "how much is",
        claims: [
          "'How much is a kilo?' asks the price for one kilo.",
          "'How much is that altogether?' asks for the total price.",
        ],
        ex: ["How much is a kilo of tomatoes?", "How much is that altogether?"],
      },
    ],
    ex: [
      fill("Can I have two ___ of potatoes, please?", ["kilos"]),
      mcq("Which sentence is correct at a market?", [
        "How much is a kilo of oranges?",
        "How many is a kilo of oranges?",
        "How much are a kilo of oranges?",
      ], 0),
      say("I / would like / three / lemons", ["I'd like three lemons.", "I would like three lemons."]),
    ],
    open: {
      q: "Buy three things at a market: say the amounts and ask for the total price.",
      must: ["how much is", "two kilos of"],
      criteria: "The answer buys food with amounts and asks about price.",
      example: "Two kilos of apples and three lemons, please. How much is that altogether?",
    },
    success: "The learner buys food with amounts and asks about prices.",
    quiz: [
      qmcq("Which is correct?", ["half a kilo of cheese", "half kilo of cheeses", "a half kilos cheese"], 0),
      qfill("How much is that ___? I want the total.", ["altogether"]),
      qmcq("You want six eggs. What do you say?", [
        "Six eggs, please.",
        "Six egg, please.",
        "Six of egg, please.",
      ], 0),
    ],
    scenes: [
      sc("Gonca", "a market seller", "to sell you fresh fruit and vegetables",
        "You are shopping at a busy street market.",
        "Buy several things and ask for the total.",
        "Everything is fresh this morning! What can I get you?", "cheerful"),
      sc("Luis", "a colleague shopping for a team lunch", "to buy food for a team lunch",
        "You and a colleague are buying food for a team event.",
        "Decide the amounts and buy the food.",
        "We're feeding about ten people. How much should we get?", "practical"),
      sc("Amina", "a stallholder at a local market abroad", "to help a visitor buy local food",
        "You are trying local food at a market while travelling.",
        "Ask what things are and buy some.",
        "You look curious! Would you like to try something local?", "friendly"),
      sc("Mr. Duarte", "your teacher", "to practise market language",
        "In class you role play a market.",
        "Buy food using amounts and prices.",
        "I'm the market seller today. What would you like?", "warm"),
      sc("Ms. Hall", "the examiner", "to check that you can buy things",
        "The examiner role plays a market seller.",
        "Buy three things with correct amounts.",
        "Imagine I am selling fruit. What do you want to buy?", "neutral"),
    ],
  },

  {
    id: "a1-turn-left-at-the-corner",
    topic: "giving directions",
    objectives: ["Give simple directions.", "Ask how to get to a place."],
    goal: "Help someone find a place in your town.",
    target: "turn left / go straight on / it's on your right",
    correction: "Repeat the direction clearly and let the learner give it again.",
    summary: "You learned how to ask for and give simple directions in a town.",
    minutes: 5,
    points: [
      {
        form: "turn left / go straight on",
        claims: [
          "Directions use the plain verb with no person: turn left, go straight on, cross the road.",
          "Join the steps with 'then': go straight on, then turn right.",
        ],
        ex: ["Turn left at the corner.", "Go straight on for two minutes, then turn right."],
      },
      {
        form: "it's on your right",
        claims: [
          "Use 'on your left' or 'on your right' to say where the place will appear.",
          "'It's opposite the bank' and 'it's next to the cafe' also help.",
        ],
        ex: ["It's on your right, next to the pharmacy.", "It's opposite the station."],
      },
      {
        form: "How do I get to...?",
        claims: [
          "Ask 'How do I get to the station?' or 'Excuse me, where is the station?'",
          "Start with 'Excuse me' when you stop a stranger.",
        ],
        ex: ["Excuse me, how do I get to the station?", "Where is the nearest pharmacy?"],
      },
    ],
    ex: [
      fill("Go straight on, then ___ left at the lights.", ["turn"]),
      mcq("Which sentence gives a direction?", [
        "Go straight on for two minutes.",
        "You are going straight on two minutes.",
        "Straight on you go two minutes ago.",
      ], 0),
      say("it / be / on your right", ["It's on your right.", "It is on your right."]),
    ],
    open: {
      q: "Someone asks how to get from here to the nearest supermarket. Give directions in three steps.",
      must: ["turn left", "go straight on"],
      criteria: "The answer gives clear steps and says where the place will be.",
      example: "Go straight on to the lights, then turn left. It's on your right, next to the bank.",
    },
    success: "The learner gives clear directions in several steps.",
    quiz: [
      qmcq("Which is correct?", ["Turn right at the corner.", "You turn right the corner at.", "Turning right the corner."], 0),
      qfill("Go straight ___ until you see the church.", ["on"]),
      qmcq("How do you politely stop a stranger?", ["Excuse me...", "Hey, you there...", "Listen to me..."], 0),
    ],
    scenes: [
      sc("Karin", "a visitor who is lost", "to find the train station",
        "A visitor stops you in the street and needs the station.",
        "Give directions step by step.",
        "Excuse me, I think I'm lost. Could you help me?", "worried"),
      sc("Tomas", "a colleague coming to your office", "to reach your office from the metro",
        "A colleague is coming to your office for the first time.",
        "Explain the way from the metro station.",
        "I'm at the metro now. Which way do I go?", "hurried"),
      sc("Ines", "a tourist with a paper map", "to find the museum on foot",
        "A tourist with a map asks for help.",
        "Give directions and describe landmarks.",
        "I can't work out this map. Is the museum far from here?", "polite"),
      sc("Mr. Berg", "your teacher", "to practise giving directions",
        "In class you give directions using a simple map.",
        "Give directions from one place to another.",
        "Here is a map of a small town. Can you get me to the park?", "warm"),
      sc("Ms. Pace", "the examiner", "to check that you can give directions",
        "The examiner asks for directions to a place.",
        "Give clear directions in several steps.",
        "How would I get from here to the nearest bus stop?", "neutral"),
    ],
  },

  {
    id: "a1-getting-there",
    topic: "how you travel",
    objectives: ["Say how I travel with by.", "Say how long a journey takes."],
    goal: "Talk about how you get to work or school.",
    target: "by bus / I walk to work / it takes ten minutes",
    correction: "Model the travel phrase and let the learner say the sentence again.",
    summary: "You learned to say how you travel and how long the journey takes.",
    minutes: 5,
    points: [
      {
        form: "by bus / by train",
        claims: [
          "Use 'by' plus the transport with no 'a' or 'the': by bus, by car, by train.",
          "Walking is different: say 'on foot' or use the verb 'walk'.",
        ],
        ex: ["I go to work by bus.", "She travels by train every day."],
      },
      {
        form: "It takes ten minutes",
        claims: [
          "Use 'it takes' plus a time to say how long a journey is.",
          "Add the journey after it: it takes twenty minutes to get to the office.",
        ],
        ex: ["It takes ten minutes.", "It takes about half an hour by car."],
      },
    ],
    ex: [
      fill("I usually go to the office ___ bus.", ["by"]),
      mcq("Which sentence is correct?", [
        "I walk to work every morning.",
        "I go to work by walk.",
        "I go by foot to work.",
      ], 0),
      say("it / take / twenty minutes / by train", ["It takes twenty minutes by train."]),
    ],
    open: {
      q: "Explain how you get to work or school and how long it takes.",
      must: ["by bus", "it takes ten minutes"],
      criteria: "The answer says the means of transport and the journey time.",
      example: "I go by bus and then I walk. It takes about twenty minutes in total.",
    },
    success: "The learner explains transport and journey times at least twice.",
    quiz: [
      qmcq("Which is correct?", ["I travel by car.", "I travel by the car.", "I travel with car."], 0),
      qfill("It ___ about ten minutes to walk there.", ["takes"]),
      qmcq("How do you say you go on foot?", ["I walk.", "I go by walk.", "I make walking."], 0),
    ],
    scenes: [
      sc("Hilda", "a neighbour who takes the same route", "to compare ways of getting to the centre",
        "You and a neighbour are talking about getting into the city centre.",
        "Say how you travel and how long it takes.",
        "The traffic is terrible lately. How do you get into town?", "chatty"),
      sc("Sergio", "a colleague considering moving house", "to work out how long his commute would be",
        "A colleague is thinking about moving and asks about your commute.",
        "Describe your journey and the time.",
        "I might move to your area. How is the commute from there?", "curious"),
      sc("Farah", "a hotel receptionist", "to help a guest reach the airport",
        "You need to get to the airport and ask for options.",
        "Ask about transport and journey times.",
        "You need the airport tomorrow, right? Shall I explain the options?", "helpful"),
      sc("Mr. Silva", "your teacher", "to practise transport language",
        "In class you talk about how people travel.",
        "Explain your daily journey.",
        "How do you get here every week?", "warm"),
      sc("Ms. Oduya", "the examiner", "to check that you can describe a journey",
        "The examiner asks about your daily travel.",
        "Describe your journey and how long it takes.",
        "How do you usually travel to work or school?", "neutral"),
    ],
  },

  // --- Ünite 8 · Talking About the Past ---------------------------------------
  {
    id: "a1-i-was-there",
    topic: "was and were",
    objectives: ["Use was and were for the past.", "Say where I was and how it was."],
    goal: "Say where you were and what it was like.",
    target: "I was / we were / it wasn't",
    correction: "Model the past form of be and let the learner say the sentence again.",
    summary: "You learned the past of be: was and were, and their negatives.",
    minutes: 6,
    points: [
      {
        form: "was / were",
        claims: [
          "'Was' goes with I, he, she and it; 'were' goes with you, we and they.",
          "Use them for places, feelings and descriptions in the past.",
        ],
        ex: ["I was at home yesterday.", "We were very tired.", "It was a great day."],
      },
      {
        form: "wasn't / weren't",
        claims: [
          "The negatives are 'wasn't' and 'weren't'.",
          "Questions put the verb first: 'Were you there?' and the answer is 'Yes, I was.'",
        ],
        ex: ["It wasn't very expensive.", "Were you at the party? Yes, I was."],
      },
    ],
    ex: [
      fill("I ___ at home all day yesterday.", ["was"]),
      mcq("Which sentence is correct?", [
        "We were at the cinema last night.",
        "We was at the cinema last night.",
        "We are at the cinema last night.",
      ], 0),
      say("it / not be / very / expensive", ["It wasn't very expensive.", "It was not very expensive."]),
    ],
    open: {
      q: "Say where you were yesterday evening and how it was.",
      must: ["I was", "it wasn't"],
      criteria: "The answer uses was and were correctly to describe the past.",
      example: "I was at my sister's house. It was nice, but it wasn't a long visit.",
    },
    success: "The learner uses was and were correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "They were very happy.",
        "They was very happy.",
        "They are were very happy.",
      ], 0),
      qfill("The film ___ boring, so we left early.", ["was"]),
      qmcq("Someone asks 'Were you at work yesterday?' You were. What do you say?", [
        "Yes, I was.",
        "Yes, I were.",
        "Yes, I did.",
      ], 0),
    ],
    scenes: [
      sc("Bea", "a friend who called and got no answer", "to find out where you were",
        "Your friend called you several times yesterday and you did not answer.",
        "Explain where you were and how it was.",
        "I called you three times yesterday! Where were you?", "curious"),
      sc("Milan", "a colleague who missed a meeting", "to find out what the meeting was like",
        "A colleague missed a meeting and asks about it.",
        "Say who was there and how it was.",
        "I missed the meeting completely. Was it useful?", "practical"),
      sc("Rosa", "a hotel guest you met yesterday", "to compare yesterday's excursions",
        "You and another guest did different trips yesterday.",
        "Say where you were and how it was.",
        "You went on the boat trip, didn't you? How was it?", "friendly"),
      sc("Mrs. Ng", "your teacher", "to practise the past of be",
        "The class talks about last weekend.",
        "Say where you were and how it was.",
        "Where were you last Saturday?", "warm"),
      sc("Mr. Traore", "the examiner", "to check that you can talk about the past",
        "The examiner asks about your recent past.",
        "Say where you were and describe it.",
        "Where were you last weekend?", "neutral"),
    ],
  },

  {
    id: "a1-we-watched-a-film",
    topic: "past simple with -ed",
    objectives: ["Make past sentences with -ed.", "Say what I did yesterday."],
    goal: "Tell someone what you did last night.",
    target: "I watched / we visited / she worked late",
    correction: "Say the past form clearly and let the learner repeat the sentence.",
    summary: "You learned to talk about finished actions with the -ed ending.",
    minutes: 6,
    points: [
      {
        form: "verb + -ed",
        claims: [
          "Add -ed to most verbs for the past: watch becomes watched, work becomes worked.",
          "If the verb ends in -e, add only -d: live becomes lived.",
          "The form is the same for every person: I worked, she worked, they worked.",
        ],
        ex: ["We watched a film last night.", "She worked late yesterday.", "They lived here in 2019."],
      },
      {
        form: "yesterday / last night",
        claims: [
          "Time words like yesterday, last night and two days ago show the action is finished.",
          "They usually come at the end of the sentence.",
        ],
        ex: ["I visited my parents yesterday.", "We talked for hours last night."],
      },
    ],
    ex: [
      fill("We ___ a great film last night.", ["watched"]),
      mcq("Which sentence is correct?", [
        "She worked late yesterday.",
        "She worked late tomorrow.",
        "She works late yesterday.",
      ], 0),
      say("we / visit / my parents / last weekend", ["We visited my parents last weekend."]),
    ],
    open: {
      q: "Say three things you did yesterday, using -ed verbs.",
      must: ["I watched", "we visited"],
      criteria: "The answer uses regular past forms with time words.",
      example: "I worked until six, then I cooked dinner and I watched a film.",
    },
    success: "The learner describes past actions with -ed forms at least twice.",
    quiz: [
      qmcq("What is the past of 'live'?", ["lived", "lifed", "live"], 0),
      qfill("They ___ football in the park yesterday. (play)", ["played"]),
      qmcq("Which sentence is correct?", [
        "I finished the report last night.",
        "I finish the report last night.",
        "I was finish the report last night.",
      ], 0),
    ],
    scenes: [
      sc("Nour", "a friend catching up", "to hear what you did yesterday",
        "You meet a friend the day after a busy day.",
        "Say what you did, in order.",
        "You had a big day yesterday, didn't you? What happened?", "curious"),
      sc("Erik", "a colleague back from holiday", "to catch up on what happened while he was away",
        "A colleague was away and asks what happened last week.",
        "Say what you and the team did.",
        "I've been away a week. What did I miss?", "practical"),
      sc("Mona", "a fellow traveller", "to compare yesterday's activities",
        "You are comparing yesterday's plans with another traveller.",
        "Say what you did and where you went.",
        "You looked busy yesterday. What did you get up to?", "friendly"),
      sc("Mr. Dias", "your teacher", "to practise the past simple",
        "In class you talk about yesterday.",
        "Describe several things you did.",
        "Tell us about your day yesterday. What did you do?", "warm"),
      sc("Ms. Fisher", "the examiner", "to check that you can talk about the past",
        "The examiner asks about your day yesterday.",
        "Describe what you did with past forms.",
        "What did you do yesterday evening?", "neutral"),
    ],
  },

  {
    id: "a1-i-went-i-saw",
    topic: "common irregular past forms",
    objectives: ["Use the most common irregular past forms.", "Tell someone about a day out."],
    goal: "Tell someone about a day trip you took.",
    target: "I went / I saw / we had dinner",
    correction: "Say the irregular past form in a full sentence and let the learner repeat it.",
    summary: "You learned the most common irregular past forms: went, saw, had, ate and got.",
    minutes: 6,
    points: [
      {
        form: "went, saw, had",
        claims: [
          "Some very common verbs do not take -ed: go becomes went, see becomes saw, have becomes had.",
          "Other common ones: eat becomes ate, get becomes got, take becomes took.",
        ],
        ex: ["I went to the coast last Sunday.", "We saw a beautiful old town.", "We had dinner by the sea."],
      },
      {
        form: "and then",
        claims: [
          "Use 'and then' to join the events of your day in order.",
          "'After that' works in the same way and makes your story easy to follow.",
        ],
        ex: ["We went to the museum and then we had lunch.", "After that we took the train home."],
      },
    ],
    ex: [
      fill("Last Sunday I ___ to the beach with my family.", ["went"]),
      mcq("What is the past of 'see'?", ["saw", "seed", "sawed"], 0),
      say("we / have / dinner / at a small restaurant", ["We had dinner at a small restaurant."]),
    ],
    open: {
      q: "Tell me about a day trip you took. Say where you went and what you saw.",
      must: ["I went", "we had dinner"],
      criteria: "The answer uses irregular past forms to describe a trip.",
      example: "We went to the mountains, we saw a lovely village and we had dinner there.",
    },
    success: "The learner tells a short past story with irregular verbs at least twice.",
    quiz: [
      qmcq("What is the past of 'go'?", ["went", "goed", "gone yesterday"], 0),
      qfill("We ___ a lot of pasta in Italy. (eat)", ["ate"]),
      qmcq("Which sentence is correct?", [
        "I took the train at eight.",
        "I taked the train at eight.",
        "I take the train at eight yesterday.",
      ], 0),
    ],
    scenes: [
      sc("Ceren", "a friend who stayed at home", "to hear about the trip she missed",
        "You went on a day trip and your friend did not.",
        "Tell her where you went and what you saw.",
        "I stayed home all weekend. Tell me about your trip?", "curious"),
      sc("Anton", "a colleague planning the same trip", "to decide whether to make the same trip",
        "A colleague is thinking about the trip you made.",
        "Describe what you did and saw.",
        "I might do that trip next month. Was it worth it?", "practical"),
      sc("Layla", "a guide asking about yesterday", "to plan today around what you have seen",
        "Your guide wants to know what you saw yesterday.",
        "Say where you went and what you did.",
        "Before we plan today, where did you go yesterday?", "friendly"),
      sc("Mr. Kaya", "your teacher", "to practise irregular past forms",
        "In class you tell short stories about trips.",
        "Tell a short story with irregular verbs.",
        "Tell us about a trip you took. Where did you go?", "warm"),
      sc("Ms. Lindqvist", "the examiner", "to check that you can tell a short story",
        "The examiner asks about a recent trip.",
        "Tell the story with correct past forms.",
        "Tell me about a trip you enjoyed. What did you do?", "neutral"),
    ],
  },

  {
    id: "a1-did-you-like-it",
    topic: "past questions and negatives",
    objectives: ["Ask questions about the past with did.", "Make negative past sentences."],
    goal: "Ask a friend about an event you missed.",
    target: "did you / I didn't / did she go",
    correction: "Model the question with did plus the plain verb and let the learner ask it again.",
    summary: "You learned to ask about the past with did and to make negatives with didn't.",
    minutes: 6,
    points: [
      {
        form: "Did you...?",
        claims: [
          "Start past questions with 'did' for every person: did you, did she, did they.",
          "After 'did', the verb goes back to its plain form: 'Did you go?', not 'Did you went?'",
        ],
        ex: ["Did you like the concert?", "Did she go with you?"],
      },
      {
        form: "I didn't",
        claims: [
          "For negatives use 'didn't' plus the plain verb: I didn't see it.",
          "The past is already in 'didn't', so the main verb does not change.",
        ],
        ex: ["I didn't see the end of the film.", "We didn't stay long."],
      },
    ],
    ex: [
      fill("___ you enjoy the concert last night?", ["Did", "did"]),
      mcq("Which sentence is correct?", [
        "I didn't see the film.",
        "I didn't saw the film.",
        "I don't saw the film.",
      ], 0),
      say("did / she / go / to the party", ["Did she go to the party?"]),
    ],
    open: {
      q: "Your friend went to an event without you. Ask three questions about it.",
      must: ["did you", "did she go"],
      criteria: "The questions use did with the plain verb form.",
      example: "Did you enjoy it? Did she go with you? Did it finish late?",
    },
    success: "The learner asks past questions with did and answers with short answers.",
    quiz: [
      qmcq("Which question is correct?", [
        "Did they arrive on time?",
        "Did they arrived on time?",
        "Do they arrived on time?",
      ], 0),
      qfill("I ___ have time to call you yesterday.", ["didn't", "did not"]),
      qmcq("Someone asks 'Did you like it?' You did. What do you say?", [
        "Yes, I did.",
        "Yes, I liked did.",
        "Yes, I was.",
      ], 0),
    ],
    scenes: [
      sc("Tara", "a friend who went to the concert", "to tell you about the concert you missed",
        "Your friend went to a concert that you could not attend.",
        "Ask questions about the evening.",
        "The concert was amazing last night! Ask me anything about it?", "excited"),
      sc("Bruno", "a colleague who attended a conference", "to share what happened at the conference",
        "A colleague went to a conference and you want the details.",
        "Ask questions about what happened.",
        "I'm back from the conference. What do you want to know?", "friendly"),
      sc("Anja", "a traveller who did the tour yesterday", "to help you decide about the same tour",
        "Another traveller did a tour you are considering.",
        "Ask questions about her experience.",
        "I did that tour yesterday. Thinking of going?", "helpful"),
      sc("Mr. Berman", "your teacher", "to practise past questions",
        "In class you interview each other about the weekend.",
        "Ask questions with did.",
        "Ask me about my weekend. What would you like to know?", "warm"),
      sc("Ms. Kowal", "the examiner", "to check that you can ask about the past",
        "In the exam you interview the examiner about a trip.",
        "Ask three past questions.",
        "I went away last weekend. What would you like to ask me?", "neutral"),
    ],
  },

  {
    id: "a1-last-weekend",
    topic: "telling a short story about your weekend",
    objectives: ["Tell a short story about the past.", "Join events and give an opinion."],
    goal: "Share your weekend news with someone at work.",
    target: "last weekend / and then / it was great",
    correction: "Give a linking word or a reaction phrase and let the learner continue the story.",
    summary: "You practised telling a short story about your weekend, in order and with an opinion.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "last weekend",
        claims: [
          "Start your story with a time phrase: last weekend, on Saturday, yesterday evening.",
          "This tells the listener when the story happens before you begin.",
        ],
        ex: ["Last weekend I went to the coast.", "On Saturday we visited a market."],
      },
      {
        form: "and then / it was great",
        claims: [
          "Join the events with 'and then' or 'after that' so the story is easy to follow.",
          "Finish with a short opinion, for example that you enjoyed it or that it was boring.",
        ],
        ex: ["We had lunch and then we walked along the beach.", "It was great, really relaxing."],
      },
    ],
    ex: [
      fill("___ weekend I went to my parents' house.", ["Last"]),
      mcq("Which sentence gives an opinion about the past?", [
        "It was really great.",
        "It is really great tomorrow.",
        "It will be really great yesterday.",
      ], 0),
      say("we / have / lunch / and then / we / go / home", [
        "We had lunch and then we went home.",
      ]),
    ],
    open: {
      q: "Tell me about your last weekend: two or three things you did and how it was.",
      must: ["last weekend", "and then"],
      criteria: "The answer tells several past events in order and gives an opinion.",
      example: "Last weekend I met some friends, and then we went to a concert. It was great.",
    },
    success: "The learner tells a short past story in order and gives an opinion.",
    quiz: [
      qmcq("Which phrase starts a past story?", ["Last weekend...", "Next weekend...", "Every weekend..."], 0),
      qfill("We went for a walk ___ then we had coffee.", ["and"]),
      qmcq("Which sentence is correct?", [
        "It was a really nice day.",
        "It was a really nice day tomorrow.",
        "It is was a really nice day.",
      ], 0),
    ],
    scenes: [
      sc("Selin", "a colleague on Monday morning", "to catch up after the weekend",
        "It is Monday morning and you meet a colleague in the kitchen.",
        "Tell your weekend story and ask about hers.",
        "Morning! Did you do anything nice at the weekend?", "friendly"),
      sc("Owen", "a manager making small talk", "to start the week with a friendly chat",
        "Your manager makes small talk before a meeting.",
        "Tell a short weekend story.",
        "Before we start, how was your weekend?", "warm"),
      sc("Pia", "a friend from another city", "to hear your news on the phone",
        "You are on the phone with a friend who lives far away.",
        "Tell her about your weekend in detail.",
        "It's been ages! What have you been up to?", "cheerful"),
      sc("Mrs. Marek", "your teacher", "to hear a longer past story",
        "In class you tell weekend stories.",
        "Tell your story with linking words and an opinion.",
        "Who would like to tell us about their weekend?", "warm"),
      sc("Mr. Sandoval", "the examiner", "to hear you tell a short story",
        "The examiner asks about your last weekend.",
        "Tell the story in order with an opinion at the end.",
        "Could you tell me what you did last weekend?", "neutral"),
    ],
  },

  {
    id: "a1-lost-found",
    topic: "reporting something you lost",
    objectives: ["Say what I lost and where.", "Describe a lost item and answer questions."],
    goal: "Report a lost bag and describe it.",
    target: "I lost my / this morning / inside it",
    correction: "Give the phrase for describing the loss and let the learner explain again.",
    summary: "You practised reporting a lost item: what, where, when and what was inside.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "I lost my",
        claims: [
          "'Lost' is the past of 'lose': I lost my bag.",
          "Say what you lost first, then where and when.",
        ],
        ex: ["I lost my bag this morning.", "She lost her phone on the train."],
      },
      {
        form: "inside it",
        claims: [
          "Use 'inside it' or 'in it' to say what was in the bag.",
          "'There was' and 'there were' help you list the contents.",
        ],
        ex: ["Inside it there was a laptop.", "There were some keys in it."],
      },
    ],
    ex: [
      fill("I ___ my bag on the bus this morning.", ["lost"]),
      mcq("Which sentence is correct?", [
        "There was a book inside it.",
        "There was a book inside its.",
        "There were a book inside it.",
      ], 0),
      say("I / lose / my keys / this morning", ["I lost my keys this morning."]),
    ],
    open: {
      q: "You lost a bag today. Say what it looks like, where you lost it and what was inside.",
      must: ["I lost my", "inside it"],
      criteria: "The answer says what was lost, where and when, and describes the contents.",
      example: "I lost my black rucksack this morning on the number nine bus. Inside it there was a laptop.",
    },
    success: "The learner reports a loss with a description, place, time and contents.",
    quiz: [
      qmcq("What is the past of 'lose'?", ["lost", "losed", "loosed"], 0),
      qfill("___ it there was a small wallet and some keys.", ["Inside", "In"]),
      qmcq("Which sentence is correct?", [
        "I lost it this morning.",
        "I lost it this morning tomorrow.",
        "I am lost it this morning.",
      ], 0),
    ],
    scenes: [
      sc("Alina", "a friend helping you retrace your steps", "to help you find your missing bag",
        "You lost your bag and a friend is helping you think where it is.",
        "Describe what you lost, where and what was inside.",
        "Don't panic. When did you last have it?", "calm"),
      sc("Mehmet", "the office reception", "to log a lost item at reception",
        "You lost something in the office building.",
        "Report the loss and describe the item.",
        "Reception here. You said you lost something?", "practical"),
      sc("Grace", "a lost property officer at the station", "to match your description with items handed in",
        "You are at a station lost property office.",
        "Describe the item, the time and the contents.",
        "Several bags came in today. Can you describe yours?", "polite"),
      sc("Mrs. Ito", "your teacher", "to practise describing a problem",
        "In class you role play losing something.",
        "Report the loss with all the details.",
        "Imagine you lost something today. What would you tell me?", "warm"),
      sc("Mr. Duarte", "the examiner", "to check that you can report a problem",
        "The examiner role plays a lost property desk.",
        "Report what you lost with details.",
        "Imagine I work at lost property. How would you start?", "neutral"),
    ],
  },
];
