/** A1 · Ünite 3-4 — Things and Places · Everyday Life (16 ders, elle yazıldı). */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A1_U3_4: Authored[] = [
  // --- Ünite 3 · Things and Places -------------------------------------------
  {
    id: "a1-a-cat-or-an-apple",
    topic: "a and an",
    objectives: ["Choose between a and an.", "Name single things around me."],
    goal: "Name the things you can see around you.",
    target: "a / an before a single thing",
    correction: "Say the phrase with the right article and let the learner repeat it.",
    summary: "You learned when to use a and when to use an before a single thing.",
    minutes: 5,
    points: [
      {
        form: "a / an",
        claims: [
          "Use 'a' before a word that starts with a consonant sound: a book, a car.",
          "Use 'an' before a word that starts with a vowel sound: an apple, an email.",
          "Use a or an only for one single thing you can count.",
        ],
        ex: ["It's a book.", "It's an apple.", "I have a car."],
      },
      {
        form: "It's a...",
        claims: [
          "Answer the question 'What's this?' with 'It's a' or 'It's an' plus the word.",
          "Do not leave out a or an when you name one thing.",
        ],
        ex: ["What's this? It's a key.", "It's an old phone."],
      },
    ],
    ex: [
      fill("Look, it's ___ orange.", ["an"]),
      mcq("Which sentence is correct?", ["It's an umbrella.", "It's a umbrella.", "It's umbrella."], 0),
      say("it / be / a / new / bag", ["It's a new bag.", "It is a new bag."]),
    ],
    open: {
      q: "Look around you. Name three things you can see, using a or an.",
      must: ["it's a", "it's an"],
      criteria: "The answer names single things with the correct article.",
      example: "It's a table, it's a lamp and it's an old clock.",
    },
    success: "The learner names things with a and an correctly at least twice.",
    quiz: [
      qmcq("Which one is correct?", ["a hospital", "an hospital", "hospital a"], 0),
      qfill("This is ___ email from my boss.", ["an"]),
      qmcq("Which word needs 'an'?", ["apple", "banana", "car"], 0),
    ],
    scenes: [
      sc("Ella", "a friend helping you unpack", "to find out what is in all the boxes",
        "A friend is helping you unpack boxes in your new flat.",
        "Name the things you take out of the boxes.",
        "There are so many boxes! What have you got in this one?", "curious"),
      sc("Ryan", "a colleague showing you the supply room", "to explain what is in the office supply room",
        "Your colleague opens the office supply room and asks what you need.",
        "Name the things you can see and say what you need.",
        "Here we keep everything. What can you see that you need?", "helpful"),
      sc("Nora", "a security officer at the airport", "to check what is in your bag",
        "At the airport a security officer looks in your bag.",
        "Name the things in your bag one by one.",
        "Could you tell me what you have in this bag?", "polite"),
      sc("Mr. Duval", "your teacher", "to practise naming classroom objects",
        "Your teacher points at things in the classroom.",
        "Name each thing with a or an.",
        "Let's practise. What can you see on my desk?", "warm"),
      sc("Ms. Iles", "the examiner", "to check that you can name simple objects",
        "The examiner shows you a picture of a room.",
        "Name the things in the picture with a or an.",
        "Look at this picture. What can you see in the room?", "neutral"),
    ],
  },

  {
    id: "a1-one-book-two-books",
    topic: "one and more than one",
    objectives: ["Make plurals with -s and -es.", "Use the most common irregular plurals."],
    goal: "Count and describe more than one thing.",
    target: "regular and irregular plurals",
    correction: "Say the correct plural in a short sentence and let the learner repeat it.",
    summary: "You learned how to make plurals with -s and -es, and the common irregular ones.",
    minutes: 6,
    points: [
      {
        form: "-s and -es",
        claims: [
          "Add -s to most words for more than one: book, books.",
          "Add -es after s, sh, ch and x: box, boxes; watch, watches.",
          "A consonant plus y becomes -ies: city, cities.",
        ],
        ex: ["I have two books.", "There are three boxes here.", "We visited two cities."],
      },
      {
        form: "children, men, women",
        claims: [
          "Some words change completely: man becomes men, woman becomes women, child becomes children.",
          "A few words do not change at all: one fish, two fish.",
        ],
        ex: ["Three children are waiting outside.", "Two men and one woman came in."],
      },
    ],
    ex: [
      fill("One box, two ___.", ["boxes"]),
      mcq("What is the plural of 'child'?", ["children", "childs", "childes"], 0),
      say("there / be / two / women / here", ["There are two women here."]),
    ],
    open: {
      q: "Describe what you can see in a busy street. Use at least two plural words.",
      must: ["there are", "two"],
      criteria: "The answer uses plural forms correctly.",
      example: "There are a lot of cars and three buses in the street.",
    },
    success: "The learner uses plural forms correctly when counting things.",
    quiz: [
      qmcq("What is the plural of 'watch'?", ["watches", "watchs", "watch"], 0),
      qfill("I know three ___ who work here. (woman)", ["women"]),
      qmcq("Which sentence is correct?", [
        "There are five cities in this region.",
        "There are five citys in this region.",
        "There are five cityes in this region.",
      ], 0),
    ],
    scenes: [
      sc("Paula", "a friend at the market", "to count what you are buying together",
        "You and a friend are shopping at a busy market.",
        "Count and name the things you are buying.",
        "Right, we need a few things. What is on your list?", "cheerful"),
      sc("Ian", "a colleague doing a stock check", "to count what is left in the office",
        "You are helping a colleague count office supplies.",
        "Count the things and say the numbers out loud.",
        "I have to count everything today. Can you tell me what is on that shelf?", "busy"),
      sc("Rita", "a tour guide with a group", "to check that everyone in the group is present",
        "The guide is counting people and bags before the bus leaves.",
        "Help her count the people and things.",
        "Before we go, can you help me count everyone?", "cheerful"),
      sc("Mr. Weber", "your teacher", "to practise plurals with real objects",
        "Your teacher puts several objects on the table.",
        "Say how many of each thing there are.",
        "Look at my table. How many of each thing can you see?", "warm"),
      sc("Ms. Ford", "the examiner", "to check that you can use plurals",
        "The examiner shows you a picture of a park.",
        "Describe what you see using plural words.",
        "What can you see in this picture of a park?", "neutral"),
    ],
  },

  {
    id: "a1-this-that-these-those",
    topic: "this, that, these and those",
    objectives: ["Choose between this, that, these and those.", "Point at things and choose between them."],
    goal: "Point at things and say which one you mean.",
    target: "this / that / these / those",
    correction: "Model the right word for near or far and let the learner say the sentence again.",
    summary: "You learned to use this and these for things near you, and that and those for things far away.",
    minutes: 5,
    points: [
      {
        form: "this / these",
        claims: [
          "Use 'this' for one thing near you and 'these' for more than one near you.",
        ],
        ex: ["This is my seat.", "These are my keys."],
      },
      {
        form: "that / those",
        claims: [
          "Use 'that' for one thing far from you and 'those' for more than one far away.",
        ],
        ex: ["That is your bag over there.", "Those flowers are beautiful."],
      },
      {
        form: "this one / that one",
        claims: [
          "Say 'this one' or 'that one' when you choose between things, so you do not repeat the word.",
        ],
        ex: ["I like that one.", "I'll take this one, please."],
      },
    ],
    ex: [
      fill("Look at ___ mountains over there. They are beautiful.", ["those"]),
      mcq("You are holding a book in your hand. What do you say?", [
        "This is a good book.",
        "That is a good book.",
        "Those is a good book.",
      ], 0),
      say("these / be / mine", ["These are mine."]),
    ],
    open: {
      q: "You are choosing between two jackets in a shop. Say which one you want and why.",
      must: ["this one", "that one"],
      criteria: "The answer chooses between things with this or that and gives a reason.",
      example: "I like this one, but that one is cheaper. I'll take this one.",
    },
    success: "The learner uses this, that, these or those correctly when choosing.",
    quiz: [
      qmcq("Which sentence is correct for shoes on your feet?", [
        "These shoes are new.",
        "This shoes are new.",
        "Those shoes is new.",
      ], 0),
      qfill("Can you see the birds over there? ___ birds are very big.", ["Those", "those"]),
      qmcq("You want the item next to you, not the far one. What do you say?", [
        "I'll take this one.",
        "I'll take that one over there.",
        "I'll take those ones.",
      ], 0),
    ],
    scenes: [
      sc("Sam", "a seller at a market stall", "to sell you something from the stall",
        "You are at a market stall with many similar things.",
        "Choose between the things and say which one you want.",
        "Everything here is handmade. Which ones would you like to see?", "cheerful"),
      sc("Diana", "a colleague choosing office furniture", "to agree on furniture for the office",
        "You and a colleague are choosing furniture from a catalogue.",
        "Say which items you prefer and why.",
        "We have to pick two chairs today. Any preferences?", "practical"),
      sc("Omar", "a shop assistant in a souvenir shop", "to help you choose a souvenir",
        "You are choosing a souvenir in a small shop.",
        "Compare the things and choose one.",
        "We have a lot to choose from. Are you looking for something special?", "friendly"),
      sc("Mrs. Aydin", "your teacher", "to practise pointing and choosing",
        "The teacher has put objects near you and far from you.",
        "Say which things are near and which are far.",
        "Some things are on your desk and some are on mine. What can you see?", "warm"),
      sc("Mr. Cole", "the examiner", "to check that you can compare two options",
        "The examiner puts two pictures in front of you.",
        "Choose between them and explain your choice.",
        "Here are two options. Which would you choose?", "neutral"),
    ],
  },

  {
    id: "a1-whats-in-your-bag",
    topic: "everyday things and asking what they are",
    objectives: ["Name everyday objects.", "Ask what something is and answer."],
    goal: "Ask about things you do not know the name of and describe your own.",
    target: "what is this / it's my phone / I need my keys",
    correction: "Give the object word in a full short sentence and let the learner repeat it.",
    summary: "You learned the names of everyday objects and how to ask what something is.",
    minutes: 5,
    points: [
      {
        form: "What is this?",
        claims: [
          "Ask 'What's this?' about one thing near you and 'What are these?' about more than one.",
          "You can answer with 'It's' or 'They're' plus the word.",
        ],
        ex: ["What's this? It's a charger.", "What are these? They're my glasses."],
      },
      {
        form: "It's my phone",
        claims: [
          "Use 'my', 'your' or 'his' before the object to say whose it is.",
          "Everyday things you carry: phone, keys, wallet, charger, glasses, umbrella.",
        ],
        ex: ["It's my phone.", "These are her glasses."],
      },
      {
        form: "I need my keys",
        claims: [
          "Use 'I need' plus the thing when you want to say something is necessary.",
        ],
        ex: ["I need my keys.", "I need a charger for my phone."],
      },
    ],
    ex: [
      fill("___ this? It's a charger.", ["What's", "What is"]),
      mcq("You are pointing at two things next to you. What do you ask?", [
        "What are these?",
        "What is these?",
        "What are this?",
      ], 0),
      say("I / need / my / keys", ["I need my keys."]),
    ],
    open: {
      q: "Tell me three things you always carry with you and why you need them.",
      must: ["it's my", "I need"],
      criteria: "The answer names objects and says why they are needed.",
      example: "It's my wallet, my phone and my keys. I need my keys for the office door.",
    },
    success: "The learner names everyday objects and asks about unknown ones.",
    quiz: [
      qmcq("Which question asks about one thing near you?", [
        "What's this?",
        "What's those?",
        "What are this?",
      ], 0),
      qfill("I can't go home. I ___ my keys.", ["need"]),
      qmcq("Which answer is correct for 'What are these?'", [
        "They're my glasses.",
        "It's my glasses.",
        "These is my glasses.",
      ], 0),
    ],
    scenes: [
      sc("Bea", "a friend who found a lost bag", "to find out whose bag it is",
        "Your friend has found a bag and you look inside it together.",
        "Name the things you find and say what is yours.",
        "Someone left this bag here. Shall we see what's inside?", "curious"),
      sc("Leo", "a colleague at the lost property desk", "to help a colleague find lost items",
        "You have lost something at the office and go to lost property.",
        "Describe the objects you are looking for.",
        "A few things came in this week. What are you missing?", "helpful"),
      sc("Ana", "a security officer at the airport", "to check the contents of your bag",
        "A security officer asks you to empty your bag.",
        "Name each object as you take it out.",
        "Could you take everything out of your bag, please?", "polite"),
      sc("Mr. Baker", "your teacher", "to teach the names of classroom objects",
        "Your teacher holds up objects you may not know the names of.",
        "Ask what things are and name the ones you know.",
        "I have some things here. Do you know all their names?", "warm"),
      sc("Ms. Quinn", "the examiner", "to check that you can name everyday objects",
        "The examiner asks about the things you carry.",
        "Name your things and say what you need them for.",
        "What do you usually carry with you every day?", "neutral"),
    ],
  },

  {
    id: "a1-theres-a-cafe-nearby",
    topic: "there is and there are",
    objectives: ["Say what exists in a place.", "Make negative sentences with there isn't and there aren't."],
    goal: "Describe what there is in a place.",
    target: "there is a / there are two / there isn't any",
    correction: "Model the sentence with there is or there are and let the learner say it again.",
    summary: "You learned to say what there is in a place, and what there is not.",
    minutes: 6,
    points: [
      {
        form: "there is / there are",
        claims: [
          "Use 'there is' for one thing and 'there are' for more than one.",
          "In speaking, 'there is' often becomes 'there's'.",
        ],
        ex: ["There's a cafe near my house.", "There are two banks in this street."],
      },
      {
        form: "there isn't / there aren't",
        claims: [
          "For negatives, say 'there isn't' or 'there aren't'.",
          "Use 'any' after a negative with plural words: there aren't any shops.",
        ],
        ex: ["There isn't a supermarket here.", "There aren't any restaurants nearby."],
      },
    ],
    ex: [
      fill("___ a good bakery on my street.", ["There's", "There is"]),
      mcq("Which sentence is correct?", [
        "There are three hotels in the town.",
        "There is three hotels in the town.",
        "There are a three hotels in the town.",
      ], 0),
      say("there / not be / any / shops / near here", [
        "There aren't any shops near here.",
        "There are not any shops near here.",
      ]),
    ],
    open: {
      q: "Describe your street. Say two things that are there and one thing that is not.",
      must: ["there is a", "there isn't any"],
      criteria: "The answer uses there is and there are correctly, including one negative.",
      example: "There's a small park and there are two cafes, but there isn't any supermarket.",
    },
    success: "The learner describes a place with there is and there are, including a negative.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "There's a bus stop outside.",
        "There are a bus stop outside.",
        "There is bus stop outside.",
      ], 0),
      qfill("___ two windows in this room.", ["There are"]),
      qmcq("How do you say that a place has no shops?", [
        "There aren't any shops.",
        "There isn't any shops.",
        "There are not a shops.",
      ], 0),
    ],
    scenes: [
      sc("Tessa", "a friend who may move to your area", "to find out what the area is like",
        "A friend is thinking about moving to your part of town.",
        "Describe what there is and is not in your area.",
        "I'm thinking about moving near you. What's the area like?", "curious"),
      sc("Hugo", "a new colleague in the building", "to learn what is around the office",
        "A new colleague wants to know what is near the office.",
        "Describe the shops and places around the office.",
        "I'm new here. Is there anywhere good to go at lunchtime?", "friendly"),
      sc("Marie", "a hotel receptionist", "to help a guest find things nearby",
        "You ask the receptionist about the area around the hotel.",
        "Ask about places nearby and describe what you need.",
        "Welcome! Would you like to know what's around the hotel?", "helpful"),
      sc("Mr. Ferris", "your teacher", "to practise describing places",
        "In class you are describing your home town.",
        "Say what there is and is not in your town.",
        "Tell us about your town. What is there?", "warm"),
      sc("Ms. Doyle", "the examiner", "to check that you can describe a place",
        "The examiner shows you a picture of a small town.",
        "Describe what there is in the picture.",
        "Look at this town. What can you see?", "neutral"),
    ],
  },

  {
    id: "a1-is-there-a-bank-here",
    topic: "asking what there is",
    objectives: ["Ask questions with is there and are there.", "Give short answers about places."],
    goal: "Ask what there is in an area you do not know.",
    target: "is there a / are there any / yes there is",
    correction: "Model the question with the verb first and let the learner ask it again.",
    summary: "You learned how to ask what there is in a place and how to answer.",
    minutes: 5,
    points: [
      {
        form: "Is there...? / Are there...?",
        claims: [
          "Put 'is' or 'are' before 'there' to ask a question: 'Is there a bank near here?'",
          "Use 'any' in questions with plural words: 'Are there any shops?'",
        ],
        ex: ["Is there a bank near here?", "Are there any cash machines nearby?"],
      },
      {
        form: "Yes, there is. / No, there isn't.",
        claims: [
          "Answer short: Yes, there is. No, there isn't. Yes, there are. No, there aren't.",
          "You can add one detail after the short answer to be helpful.",
        ],
        ex: ["Yes, there is. It's next to the post office.", "No, there aren't, sorry."],
      },
    ],
    ex: [
      fill("___ there a pharmacy on this street?", ["Is", "is"]),
      mcq("Which question is correct?", [
        "Are there any restaurants near here?",
        "Is there any restaurants near here?",
        "Are there a restaurants near here?",
      ], 0),
      say("yes / there / be / one / near the station", [
        "Yes, there is one near the station.",
        "Yes, there's one near the station.",
      ]),
    ],
    open: {
      q: "You have just arrived in a new city. Ask three questions about what there is nearby.",
      must: ["is there a", "are there any"],
      criteria: "The questions use is there or are there with the correct word order.",
      example: "Is there a supermarket near here? Are there any good cafes? Is there a bus stop nearby?",
    },
    success: "The learner asks questions with is there and are there and answers them.",
    quiz: [
      qmcq("Which question is correct?", [
        "Is there a bank here?",
        "There is a bank here?",
        "Is it there a bank here?",
      ], 0),
      qfill("___ there any buses after ten o'clock?", ["Are", "are"]),
      qmcq("Someone asks 'Is there a lift?' The building has no lift. What do you say?", [
        "No, there isn't.",
        "No, there aren't.",
        "No, it isn't there.",
      ], 0),
    ],
    scenes: [
      sc("Greta", "a neighbour who knows the area well", "to help the new person settle in",
        "You have just moved in and meet a neighbour who knows the area.",
        "Ask questions about what there is nearby.",
        "Welcome to the street! Is there anything you'd like to know about the area?", "friendly"),
      sc("Felix", "a colleague showing you the building", "to help you find your way in the building",
        "It is your first week and you do not know the building.",
        "Ask what there is on each floor.",
        "Let me show you around. What do you need to find first?", "helpful"),
      sc("Salma", "a hotel receptionist", "to answer a guest's questions about the area",
        "You have arrived at a hotel in a city you do not know.",
        "Ask about places near the hotel.",
        "Here is your key. Do you have any questions about the area?", "polite"),
      sc("Mr. Ross", "the school office assistant", "to explain what the school has",
        "You are visiting a school for the first time.",
        "Ask what there is in the school building.",
        "Feel free to ask me anything about the school. What would you like to know?", "warm"),
      sc("Ms. Lane", "the examiner", "to check that you can ask about a place",
        "In the exam you role play arriving in a new town.",
        "Ask three questions about what there is.",
        "Imagine you have just arrived in my town. What would you ask me?", "neutral"),
    ],
  },

  {
    id: "a1-on-in-under",
    topic: "where things are",
    objectives: ["Say where things are with on, in, under and next to.", "Help someone find something."],
    goal: "Say exactly where something is.",
    target: "on the table / in my bag / next to the door",
    correction: "Model the place phrase and let the learner say the whole sentence again.",
    summary: "You learned the words for saying where things are: on, in, under, next to and behind.",
    minutes: 5,
    points: [
      {
        form: "on / in / under",
        claims: [
          "Use 'on' for a surface, 'in' for the inside of something, and 'under' for below it.",
          "The place word comes before the word 'the' or 'my': on the table, in my bag.",
        ],
        ex: ["Your keys are on the table.", "It's in my bag.", "The box is under the bed."],
      },
      {
        form: "next to / behind / in front of",
        claims: [
          "'Next to' means at the side of something, 'behind' means at the back of it.",
          "Use 'in front of' for the opposite of behind.",
        ],
        ex: ["The chair is next to the door.", "The car is behind the house."],
      },
    ],
    ex: [
      fill("Your phone is ___ the kitchen table.", ["on"]),
      mcq("The keys are inside your bag. What do you say?", [
        "They're in my bag.",
        "They're on my bag.",
        "They're under my bag.",
      ], 0),
      say("the chair / be / next to / the door", ["The chair is next to the door."]),
    ],
    open: {
      q: "Someone cannot find their glasses in your home. Tell them where to look.",
      must: ["on the table", "in my bag"],
      criteria: "The answer says where things are with place words.",
      example: "They're on the table in the kitchen, next to your book.",
    },
    success: "The learner says where things are using place words correctly.",
    quiz: [
      qmcq("Where is the milk, if it is inside the fridge?", [
        "It's in the fridge.",
        "It's on the fridge.",
        "It's under the fridge.",
      ], 0),
      qfill("The cat is sleeping ___ the sofa, so I can't see it.", ["under", "behind"]),
      qmcq("Which sentence is correct?", [
        "The bank is next to the post office.",
        "The bank is next the post office.",
        "The bank is next of the post office.",
      ], 0),
    ],
    scenes: [
      sc("Alice", "a flatmate who has lost her phone", "to find her phone before she leaves",
        "Your flatmate has lost her phone somewhere in the flat.",
        "Tell her where to look, using place words.",
        "I can't find my phone anywhere! Have you seen it?", "worried"),
      sc("Tom", "a colleague looking for a file", "to find a document he needs for a meeting",
        "A colleague cannot find a folder in the office.",
        "Explain where things are in the office.",
        "I need that blue folder for the meeting. Any idea where it is?", "busy"),
      sc("Lucia", "a hotel cleaner", "to return something a guest left behind",
        "You left something in your hotel room and describe where it was.",
        "Say exactly where you left the item.",
        "You called about something left in the room. Where exactly was it?", "polite"),
      sc("Mrs. Yilmaz", "your teacher", "to practise describing a room",
        "In class you describe where the things in the classroom are.",
        "Say where several objects are.",
        "Let's describe this room. Where is everything?", "warm"),
      sc("Mr. Novak", "the examiner", "to check that you can describe positions",
        "The examiner shows you a picture of a living room.",
        "Say where the things in the picture are.",
        "Look at this room. Where are the things you can see?", "neutral"),
    ],
  },

  {
    id: "a1-around-my-neighbourhood",
    topic: "describing your neighbourhood",
    objectives: ["Describe what is near your home.", "Say how near or far things are."],
    goal: "Tell a visitor what is worth seeing near where you live.",
    target: "there's a / it's near / just around the corner",
    correction: "Give a natural phrase for describing distance and let the learner use it again.",
    summary: "You practised describing your neighbourhood and saying how near things are.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "it's near / it's far",
        claims: [
          "Say 'it's near' or 'it's not far' for a short distance, and 'it's quite far' for a long one.",
          "Add 'from here' when it is not clear what you are measuring from.",
        ],
        ex: ["It's near the station.", "It's not far from here."],
      },
      {
        form: "just around the corner",
        claims: [
          "'Just around the corner' means very close, only a few steps away.",
          "'Five minutes on foot' is another natural way to say something is close.",
        ],
        ex: ["The bakery is just around the corner.", "It's five minutes on foot."],
      },
    ],
    ex: [
      fill("The pharmacy is just around the ___.", ["corner"]),
      mcq("Something is two minutes away. What do you say?", [
        "It's very near.",
        "It's very far.",
        "It's not here.",
      ], 0),
      say("there / be / a park / near my house", [
        "There's a park near my house.",
        "There is a park near my house.",
      ]),
    ],
    open: {
      q: "A visitor asks about your area. Describe two places and say how near they are.",
      must: ["there's a", "it's near"],
      criteria: "The answer names places and describes how near or far they are.",
      example: "There's a nice market near my house. It's just around the corner, five minutes on foot.",
    },
    success: "The learner describes places nearby and says how near they are at least twice.",
    quiz: [
      qmcq("Which phrase means 'very close'?", [
        "just around the corner",
        "on the other side of the city",
        "an hour away",
      ], 0),
      qfill("The bus stop is not ___ from my flat.", ["far"]),
      qmcq("Which sentence is correct?", [
        "There's a good cafe near my house.",
        "There have a good cafe near my house.",
        "It's a good cafe there near my house.",
      ], 0),
    ],
    scenes: [
      sc("Chloe", "a friend visiting for the weekend", "to plan what to see near your home",
        "A friend is staying with you for the weekend.",
        "Describe what is near your home and how near it is.",
        "I've never been to your area before. What's worth seeing?", "excited"),
      sc("Bruno", "a colleague relocating to your city", "to choose an area to live in",
        "A colleague is moving to your city and asks about your area.",
        "Describe your neighbourhood and the distances.",
        "I might move to your part of town. Would you recommend it?", "curious"),
      sc("Amara", "a guest at your home exchange", "to find her way around a new neighbourhood",
        "Someone is staying in your flat while you are away.",
        "Explain what is nearby and how to get there.",
        "Thanks for the keys! What should I know about the area?", "friendly"),
      sc("Mr. Sen", "your teacher", "to hear students describe where they live",
        "In class everyone describes their neighbourhood.",
        "Describe your area with details and distances.",
        "Tell the class about the place where you live. What is it like?", "warm"),
      sc("Ms. Cruz", "the examiner", "to hear you speak for a longer stretch",
        "The examiner asks you to describe your neighbourhood for a minute.",
        "Describe several places and how near they are.",
        "Could you describe the area where you live?", "neutral"),
    ],
  },

  // --- Ünite 4 · Everyday Life -----------------------------------------------
  {
    id: "a1-i-wake-up-at-seven",
    topic: "daily routine with I, you, we and they",
    objectives: ["Say what I do every day.", "Talk about routines with I, you, we and they."],
    goal: "Talk about the things you do every day.",
    target: "present simple with I, you, we and they",
    correction: "Say the sentence with the correct verb and let the learner repeat it.",
    summary: "You learned to talk about your daily routine with I, you, we and they.",
    minutes: 6,
    points: [
      {
        form: "I wake up / we start",
        claims: [
          "For things you do every day, use the plain verb after I, you, we and they.",
          "Do not add -s after these words: 'I work', not 'I works'.",
          "Use 'at' with a clock time: at seven, at half past eight.",
        ],
        ex: ["I wake up at seven.", "We start work at nine.", "They finish late on Fridays."],
      },
      {
        form: "every day / on Mondays",
        claims: [
          "Add 'every day', 'every morning' or 'on Mondays' to say how often something happens.",
          "These words usually come at the end of the sentence.",
        ],
        ex: ["I go to the gym every morning.", "We have a meeting on Mondays."],
      },
    ],
    ex: [
      fill("I ___ up at half past six every day.", ["wake"]),
      mcq("Which sentence is correct?", [
        "We start at nine.",
        "We starts at nine.",
        "We is start at nine.",
      ], 0),
      say("they / finish / late / on Fridays", ["They finish late on Fridays."]),
    ],
    open: {
      q: "Describe three things you do every morning, with the times.",
      must: ["I wake up", "we start at"],
      criteria: "The answer describes routine actions with the plain verb form and times.",
      example: "I wake up at six, I have breakfast at half past six and I leave at seven.",
    },
    success: "The learner describes daily routines with the correct verb form at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", ["I work in a bank.", "I works in a bank.", "I am work in a bank."], 0),
      qfill("We ___ dinner at eight in my family.", ["have", "eat"]),
      qmcq("Which sentence talks about every day?", [
        "They finish at five every day.",
        "They are finishing at five now.",
        "They finished at five yesterday.",
      ], 0),
    ],
    scenes: [
      sc("Nina", "a friend comparing routines", "to compare her day with yours",
        "You and a friend are comparing your daily routines.",
        "Describe your day and ask about hers.",
        "My mornings are so chaotic. What time does your day start?", "chatty"),
      sc("Kemal", "a colleague on a different shift", "to understand when you are available",
        "A colleague works different hours and wants to plan meetings.",
        "Explain when you start, work and finish.",
        "Our hours are different, aren't they? When do you usually work?", "practical"),
      sc("Ivy", "a host family member", "to fit the guest into the family routine",
        "You are staying with a family and they explain their routine.",
        "Describe your usual day and ask about theirs.",
        "We should talk about the daily routine here. Shall we start with yours?", "warm"),
      sc("Mr. Adams", "your teacher", "to hear about students' daily routines",
        "The class is talking about daily routines.",
        "Describe your normal weekday.",
        "Let's talk about a normal day. What happens in yours?", "warm"),
      sc("Ms. Bright", "the examiner", "to check that you can describe a routine",
        "The examiner asks about your typical day.",
        "Describe your daily routine with times.",
        "Could you describe a normal day for you?", "neutral"),
    ],
  },

  {
    id: "a1-she-works-at-night",
    topic: "he, she and it with -s",
    objectives: ["Add -s to the verb after he, she and it.", "Talk about what other people do."],
    goal: "Say what other people do in their daily life and work.",
    target: "present simple third person -s",
    correction: "Say the verb with -s in a full sentence and let the learner repeat it.",
    summary: "You learned to add -s to the verb when you talk about he, she or it.",
    minutes: 6,
    points: [
      {
        form: "he works / she lives",
        claims: [
          "Add -s to the verb after he, she and it: he works, she lives, it starts.",
          "Do not add -s after I, you, we or they.",
        ],
        ex: ["She works at night.", "He lives near the office.", "It starts at nine."],
      },
      {
        form: "-es and has",
        claims: [
          "Add -es after s, sh, ch, x and o: she watches, he goes, she does.",
          "'Have' is different: it becomes 'has' after he, she and it.",
        ],
        ex: ["He watches films every evening.", "She has two children."],
      },
    ],
    ex: [
      fill("My sister ___ in a hospital.", ["works"]),
      mcq("Which sentence is correct?", [
        "He goes to work by bus.",
        "He go to work by bus.",
        "He gos to work by bus.",
      ], 0),
      say("she / have / two children", ["She has two children."]),
    ],
    open: {
      q: "Describe what someone in your family does every day. Use he or she.",
      must: ["she works", "he lives"],
      criteria: "The answer uses -s on the verb after he or she.",
      example: "My brother works in a restaurant. He starts at four and finishes very late.",
    },
    success: "The learner uses the -s form correctly after he, she or it at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "She teaches English.",
        "She teach English.",
        "She teachs English.",
      ], 0),
      qfill("My father ___ a small shop. (have)", ["has"]),
      qmcq("Which sentence is correct?", [
        "It starts at eight o'clock.",
        "It start at eight o'clock.",
        "It is start at eight o'clock.",
      ], 0),
    ],
    scenes: [
      sc("Beatriz", "a neighbour asking about your family", "to learn what your family members do",
        "A neighbour is curious about the people in your household.",
        "Say what the people in your family do.",
        "Your family always seems busy! What does everyone do?", "curious"),
      sc("Jonas", "a colleague from another department", "to understand who does what in your team",
        "A colleague wants to know what your team members do.",
        "Explain what each person does.",
        "I never know who to ask in your team. Who does what?", "practical"),
      sc("Selma", "a guide talking about local life", "to explain how local people live and work",
        "A guide is telling you about daily life in the region.",
        "Ask about local routines and describe your own country.",
        "Life here follows the seasons. What is it like where you come from?", "warm"),
      sc("Mr. Price", "your teacher", "to practise talking about other people",
        "The class is describing the jobs of people they know.",
        "Describe what two people you know do.",
        "Tell us about someone you know. What do they do?", "warm"),
      sc("Ms. Ito", "the examiner", "to check that you can describe other people",
        "The examiner asks about a person in your life.",
        "Describe what that person does, using -s correctly.",
        "Could you tell me what someone in your family does?", "neutral"),
    ],
  },

  {
    id: "a1-i-dont-drink-coffee",
    topic: "saying what you do not do",
    objectives: ["Make negative sentences with don't and doesn't.", "Explain my habits politely."],
    goal: "Explain what you do not do when someone offers you something.",
    target: "I don't / she doesn't",
    correction: "Model the negative with the plain verb and let the learner say it again.",
    summary: "You learned to say what you do not do with don't and doesn't.",
    minutes: 6,
    points: [
      {
        form: "I don't / we don't",
        claims: [
          "Use 'don't' plus the plain verb after I, you, we and they: I don't drink coffee.",
          "'Don't' is short for 'do not'.",
        ],
        ex: ["I don't drink coffee.", "We don't work at weekends."],
      },
      {
        form: "she doesn't",
        claims: [
          "Use 'doesn't' after he, she and it: she doesn't eat meat.",
          "After doesn't, the verb has no -s: 'she doesn't work', not 'she doesn't works'.",
        ],
        ex: ["She doesn't eat meat.", "He doesn't live here any more."],
      },
    ],
    ex: [
      fill("Thanks, but I ___ drink coffee.", ["don't", "do not"]),
      mcq("Which sentence is correct?", [
        "She doesn't eat meat.",
        "She doesn't eats meat.",
        "She don't eats meat.",
      ], 0),
      say("we / not / work / at weekends", [
        "We don't work at weekends.",
        "We do not work at weekends.",
      ]),
    ],
    open: {
      q: "Someone offers you food and drink you do not want. Say no politely and explain.",
      must: ["I don't"],
      criteria: "The answer refuses politely with a negative present simple sentence.",
      example: "Thank you, but I don't drink coffee. I don't eat sugar either.",
    },
    success: "The learner explains habits with don't and doesn't correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "He doesn't like fish.",
        "He don't like fish.",
        "He doesn't likes fish.",
      ], 0),
      qfill("They ___ live in this city any more.", ["don't", "do not"]),
      qmcq("Someone offers you meat but you do not eat it. What do you say?", [
        "Thanks, but I don't eat meat.",
        "Thanks, but I no eat meat.",
        "Thanks, but I doesn't eat meat.",
      ], 0),
    ],
    scenes: [
      sc("Hana", "a host offering food and drinks", "to make her guest comfortable",
        "You are a guest at someone's home and they offer you food and drink.",
        "Say politely what you do not eat or drink.",
        "Please make yourself at home. What can I get you?", "warm"),
      sc("Erik", "a colleague organising a team lunch", "to book a place that suits everyone",
        "A colleague is choosing a restaurant for the team.",
        "Explain what you do not eat and suggest an alternative.",
        "I'm booking lunch for the team. Any preferences I should know about?", "practical"),
      sc("Pilar", "a waiter at a small restaurant", "to take an order that suits the guest",
        "You are ordering in a restaurant with a limited menu.",
        "Explain what you do not eat and ask about options.",
        "Good evening. Have you had a chance to look at the menu?", "polite"),
      sc("Mrs. Ali", "your teacher", "to practise talking about habits",
        "The class is talking about habits people do not have.",
        "Say three things you do not do.",
        "Let's talk about the things we don't do. Would you like to start?", "warm"),
      sc("Mr. Bloom", "the examiner", "to check that you can use negatives",
        "The examiner asks about things you avoid.",
        "Say what you do not do, using don't and doesn't.",
        "Is there anything you never do in your free time?", "neutral"),
    ],
  },

  {
    id: "a1-do-you-live-here",
    topic: "asking about habits",
    objectives: ["Ask questions with do and does.", "Give short answers like 'Yes, I do.'"],
    goal: "Ask someone about their everyday life.",
    target: "do you / does she / yes I do",
    correction: "Model the question with do or does and let the learner ask it again.",
    summary: "You learned how to ask questions about daily life and how to answer them short.",
    minutes: 6,
    points: [
      {
        form: "Do you...? / Does he...?",
        claims: [
          "Start the question with 'do' for I, you, we and they, and 'does' for he, she and it.",
          "After do or does, the verb has no -s: 'Does she work here?', not 'Does she works here?'",
        ],
        ex: ["Do you live near here?", "Does she work at the school?"],
      },
      {
        form: "Yes, I do. / No, I don't.",
        claims: [
          "Answer short with do or does: Yes, I do. No, she doesn't.",
          "Do not repeat the whole sentence unless you want to add information.",
        ],
        ex: ["Yes, I do.", "No, he doesn't.", "Yes, I do. I live in the next street."],
      },
    ],
    ex: [
      fill("___ you live near the station?", ["Do", "do"]),
      mcq("Which question is correct?", [
        "Does she work here?",
        "Does she works here?",
        "Do she work here?",
      ], 0),
      say("do / you / work / on Saturdays", ["Do you work on Saturdays?"]),
    ],
    open: {
      q: "You have met a new neighbour. Ask three questions about their everyday life.",
      must: ["do you", "does she"],
      criteria: "The questions use do or does with the plain verb.",
      example: "Do you live in this building? Do you work nearby? Does your family live here too?",
    },
    success: "The learner asks questions with do and does and answers with short answers.",
    quiz: [
      qmcq("Which question is correct?", [
        "Do they speak English?",
        "Do they speaks English?",
        "Does they speak English?",
      ], 0),
      qfill("___ he like his new job?", ["Does", "does"]),
      qmcq("Someone asks 'Do you drive?' You do. What do you say?", [
        "Yes, I do.",
        "Yes, I drive do.",
        "Yes, I am.",
      ], 0),
    ],
    scenes: [
      sc("Ruth", "a new neighbour", "to get to know the people in the building",
        "You meet a new neighbour in the entrance of your building.",
        "Ask her questions about her everyday life.",
        "Hello! I moved in last week. Anything you want to know about me?", "friendly"),
      sc("Pavel", "a colleague you rarely see", "to find out how your colleague works",
        "You are working with a colleague from another office for the first time.",
        "Ask about his working habits.",
        "We'll be working together this month. Ask me anything about how I work?", "practical"),
      sc("Naomi", "a host at a homestay", "to make sure her guest is comfortable",
        "You are staying with a host family and want to know about their habits.",
        "Ask questions about the household routine.",
        "Please ask me anything about how things work in our home?", "warm"),
      sc("Mr. Ozan", "your teacher", "to practise question forms",
        "The teacher asks you to interview a classmate.",
        "Ask questions with do and does.",
        "Let's practise questions. What would you like to ask me?", "warm"),
      sc("Ms. Reyes", "the examiner", "to check that you can ask about routines",
        "In the exam you interview the examiner.",
        "Ask three questions with do or does.",
        "Now it is your turn to ask me about my day. Ready?", "neutral"),
    ],
  },

  {
    id: "a1-what-time-is-it",
    topic: "telling the time",
    objectives: ["Tell the time in the usual way.", "Use at, on and in with time words."],
    goal: "Ask and say what time things happen.",
    target: "what time is it / it's half past / at six o'clock",
    correction: "Say the time correctly and ask the learner to repeat the whole phrase.",
    summary: "You learned how to tell the time and when to use at, on and in.",
    minutes: 6,
    points: [
      {
        form: "It's half past six",
        claims: [
          "Say 'o'clock' only for a full hour: it's six o'clock.",
          "Use 'half past', 'quarter past' and 'quarter to' for the parts of the hour.",
        ],
        ex: ["It's half past six.", "It's a quarter to nine."],
      },
      {
        form: "at / on / in",
        claims: [
          "Use 'at' with clock times: at six o'clock, at half past two.",
          "Use 'on' with days: on Monday, on Friday morning.",
          "Use 'in' with months, years and parts of the day: in July, in the morning.",
        ],
        ex: ["The shop opens at nine.", "We meet on Tuesday.", "It's very quiet in the morning."],
      },
    ],
    ex: [
      fill("The film starts ___ eight o'clock.", ["at"]),
      mcq("It is 7:30. What do you say?", [
        "It's half past seven.",
        "It's half to seven.",
        "It's seven and half.",
      ], 0),
      say("what / time / be / it", ["What time is it?"]),
    ],
    open: {
      q: "Tell me what time you start and finish work or school, and when you have lunch.",
      must: ["at six o'clock", "it's half past"],
      criteria: "The answer gives times with the correct time words.",
      example: "I start at eight o'clock, I have lunch at half past twelve and I finish at five.",
    },
    success: "The learner tells the time and uses at, on and in correctly.",
    quiz: [
      qmcq("Which is correct for 9:15?", [
        "It's a quarter past nine.",
        "It's a quarter to nine.",
        "It's nine and quarter.",
      ], 0),
      qfill("The meeting is ___ Monday morning.", ["on"]),
      qmcq("Which sentence is correct?", [
        "The train leaves at ten o'clock.",
        "The train leaves in ten o'clock.",
        "The train leaves on ten o'clock.",
      ], 0),
    ],
    scenes: [
      sc("Freya", "a friend planning a cinema trip", "to agree on a time to meet",
        "You and a friend are choosing a film and a time.",
        "Talk about times and agree when to meet.",
        "There are three showings tonight. When suits you?", "cheerful"),
      sc("Dieter", "a colleague booking a meeting", "to find a time everyone can attend",
        "A colleague is trying to book a meeting in a busy week.",
        "Say when you are free and agree on a time.",
        "I need to find a slot this week. When are you free?", "busy"),
      sc("Rosa", "a receptionist at the museum", "to explain opening and closing times",
        "You are asking about opening hours and tour times.",
        "Ask about the times and repeat them back.",
        "Welcome! Would you like to know our times for today?", "helpful"),
      sc("Mr. Lund", "your teacher", "to practise telling the time",
        "The teacher shows different clocks in class.",
        "Say the times and when you do things.",
        "Look at this clock. What time does it show?", "warm"),
      sc("Ms. Nakamura", "the examiner", "to check that you can talk about times",
        "The examiner asks about your daily timetable.",
        "Give the times of your day clearly.",
        "What time do you usually start your day?", "neutral"),
    ],
  },

  {
    id: "a1-always-sometimes-never",
    topic: "how often you do things",
    objectives: ["Use always, usually, sometimes and never.", "Put the frequency word in the right place."],
    goal: "Say how often you do the things in your life.",
    target: "I always / she never / we sometimes go",
    correction: "Repeat the sentence with the frequency word in the right place.",
    summary: "You learned the words always, usually, sometimes and never, and where to put them.",
    minutes: 6,
    points: [
      {
        form: "always, usually, sometimes, never",
        claims: [
          "These words go before the main verb: I always walk, she never drives.",
          "But they go after the verb 'be': he is always late.",
          "'Never' already means no, so do not add 'don't': say 'I never smoke'.",
        ],
        ex: ["I always walk to work.", "She never drinks tea.", "He is always late."],
      },
      {
        form: "once a week / twice a month",
        claims: [
          "Use 'once', 'twice' or a number plus 'a week' to say how many times.",
          "These phrases go at the end of the sentence.",
        ],
        ex: ["I go to the gym twice a week.", "We meet once a month."],
      },
    ],
    ex: [
      fill("I ___ walk to work, every single day.", ["always"]),
      mcq("Which sentence is correct?", [
        "She never eats breakfast.",
        "She doesn't never eat breakfast.",
        "She eats never breakfast.",
      ], 0),
      say("we / sometimes / go / to the cinema", ["We sometimes go to the cinema."]),
    ],
    open: {
      q: "Say how often you do three different things in your free time.",
      must: ["I always", "we sometimes go"],
      criteria: "The answer uses frequency words in the correct position.",
      example: "I always read before bed, I sometimes go swimming and I never watch TV in the morning.",
    },
    success: "The learner uses frequency words correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "He is always on time.",
        "He always is on time.",
        "He is on time always the meetings.",
      ], 0),
      qfill("I go to the gym twice ___ week.", ["a"]),
      qmcq("Which sentence is correct?", [
        "I never drink coffee at night.",
        "I don't never drink coffee at night.",
        "I drink never coffee at night.",
      ], 0),
    ],
    scenes: [
      sc("Milo", "a friend planning to get fit with you", "to find an activity you both do often",
        "A friend wants to start a regular activity with you.",
        "Say how often you do things and agree on a plan.",
        "I need to get more active. How often do you do sport?", "energetic"),
      sc("Sandra", "a colleague comparing work habits", "to learn how you organise your work",
        "A colleague is asking how often you do certain work tasks.",
        "Say how often you do each task.",
        "I'm trying to organise my week better. How often do you check emails?", "practical"),
      sc("Theo", "a fellow guest at the hostel", "to swap travel habits",
        "You are chatting with a traveller about travel habits.",
        "Say how often you travel and what you always do.",
        "Some people travel every month. How often do you get away?", "relaxed"),
      sc("Mrs. Costa", "your teacher", "to practise frequency words",
        "The class is talking about habits and how often people do things.",
        "Say how often you do several things.",
        "Let's talk about habits. What do you always do in the morning?", "warm"),
      sc("Mr. Lewis", "the examiner", "to check that you can say how often",
        "The examiner asks about your habits.",
        "Answer with frequency words in the right place.",
        "How often do you use English outside this room?", "neutral"),
    ],
  },

  {
    id: "a1-what-are-you-doing",
    topic: "what is happening now",
    objectives: ["Say what I am doing at this moment.", "Ask what someone is doing now."],
    goal: "Talk about what is happening right now on the phone.",
    target: "what are you doing / I'm working / right now",
    correction: "Model the be plus -ing form and let the learner say the sentence again.",
    summary: "You learned to talk about actions happening at this moment with am, is or are plus -ing.",
    minutes: 6,
    points: [
      {
        form: "am / is / are + verb-ing",
        claims: [
          "For an action happening now, use am, is or are plus the verb with -ing.",
          "Both parts are necessary: 'I am working', not 'I working' and not 'I am work'.",
          "Drop a final -e before -ing: make becomes making.",
        ],
        ex: ["I'm working right now.", "She's cooking dinner.", "They are waiting outside."],
      },
      {
        form: "What are you doing?",
        claims: [
          "Ask 'What are you doing?' about this moment, not about someone's job.",
          "Add 'right now' or 'at the moment' to make the time very clear.",
        ],
        ex: ["What are you doing right now?", "What is he doing at the moment?"],
      },
      {
        form: "now versus every day",
        claims: [
          "Use the -ing form for now, and the plain verb for every day.",
          "Compare: 'I usually work at home' and 'I'm working at the office today'.",
        ],
        ex: ["I usually walk, but today I'm taking the bus.", "He is not answering because he's driving."],
      },
    ],
    ex: [
      fill("Sorry, I can't talk. I ___ driving right now.", ["am", "'m"]),
      mcq("Your friend calls you while you are cooking. What do you say?", [
        "I'm cooking dinner right now.",
        "I cook dinner right now.",
        "I am cook dinner right now.",
      ], 0),
      say("what / you / do / right now", ["What are you doing right now?"]),
    ],
    open: {
      q: "A friend calls you. Say what you are doing right now and ask what they are doing.",
      must: ["I'm working", "what are you doing"],
      criteria: "The answer uses be plus -ing for a present action and asks the question back.",
      example: "I'm working at home right now. What are you doing?",
    },
    success: "The learner describes actions happening now with be plus -ing at least twice.",
    quiz: [
      qmcq("Which sentence is about this moment?", [
        "She's reading a book.",
        "She reads a book every night.",
        "She read a book yesterday.",
      ], 0),
      qfill("Be quiet, please. The baby ___ sleeping.", ["is", "'s"]),
      qmcq("Which sentence is correct?", [
        "They are waiting for the bus.",
        "They waiting for the bus.",
        "They are wait for the bus.",
      ], 0),
    ],
    scenes: [
      sc("Zoe", "a friend calling you", "to find out if you are free to talk",
        "A friend calls you in the middle of your day.",
        "Say what you are doing and ask what she is doing.",
        "Hi! Is this a bad moment to call?", "cheerful"),
      sc("Robert", "a colleague looking for people", "to find out where everyone is",
        "A colleague calls to ask where the team is and what they are doing.",
        "Say what people are doing right now.",
        "The meeting room is empty. What is everyone doing?", "busy"),
      sc("Sun", "a friend waiting for you at a cafe", "to find out how long she has to wait",
        "You are late and your friend calls to ask where you are.",
        "Explain what you are doing right now.",
        "I'm already at the cafe. Where are you?", "patient"),
      sc("Mr. Farah", "your teacher on a video call", "to check that students are working",
        "Your teacher calls during a group task.",
        "Say what you and your group are doing right now.",
        "Hello everyone. How is the task going?", "warm"),
      sc("Ms. Poole", "the examiner", "to check that you can describe a picture",
        "The examiner shows a picture of a busy street.",
        "Say what the people in the picture are doing.",
        "Look at this picture. What are the people doing?", "neutral"),
    ],
  },

  {
    id: "a1-my-morning",
    topic: "describing your whole morning",
    objectives: ["Describe my morning from start to finish.", "Join actions with then and after that."],
    goal: "Tell someone what a normal weekday morning looks like for you.",
    target: "I usually / after that / before work",
    correction: "Offer a linking word and let the learner say the next part of the story.",
    summary: "You practised describing your morning in order, using linking words.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "first, then, after that",
        claims: [
          "Use 'first', 'then' and 'after that' to put your actions in order.",
          "These words go at the start of the sentence, before the person.",
        ],
        ex: ["First I have a shower.", "Then I make coffee.", "After that I leave the house."],
      },
      {
        form: "before work / after lunch",
        claims: [
          "Use 'before' and 'after' plus a word for an event to say when something happens.",
        ],
        ex: ["I check my messages before work.", "We have a short break after lunch."],
      },
    ],
    ex: [
      fill("I have breakfast, and ___ that I take the bus.", ["after"]),
      mcq("Which sentence puts the actions in a clear order?", [
        "First I get up, then I have breakfast.",
        "First I have breakfast, first I get up.",
        "Then I get up, after that first I sleep.",
      ], 0),
      say("I / usually / start / work / at nine", ["I usually start work at nine."]),
    ],
    open: {
      q: "Describe your morning from waking up to arriving at work or school.",
      must: ["I usually", "after that"],
      criteria: "The answer describes several actions in a clear order with linking words.",
      example: "I usually wake up at six. First I have a shower, then I make coffee, and after that I leave.",
    },
    success: "The learner describes a morning routine in order with linking words at least twice.",
    quiz: [
      qmcq("Which word shows the next step?", ["after that", "because", "but"], 0),
      qfill("I check my emails ___ work, at about eight.", ["before"]),
      qmcq("Which sentence is correct?", [
        "I usually get up at seven.",
        "I get usually up at seven.",
        "Usually I am get up at seven.",
      ], 0),
    ],
    scenes: [
      sc("Kate", "a friend who wants to change her routine", "to get ideas for a better morning",
        "A friend says her mornings are stressful and asks about yours.",
        "Describe your morning step by step.",
        "My mornings are a disaster. How does yours go?", "curious"),
      sc("Ahmed", "a colleague starting a new schedule", "to plan his new working day",
        "A colleague is changing his hours and asks how you organise your morning.",
        "Describe your morning in order.",
        "I'm starting earlier from next week. How do you organise your mornings?", "practical"),
      sc("Bea", "a host family member", "to plan the household morning",
        "Your host family wants to know your morning habits.",
        "Describe your morning routine step by step.",
        "Mornings here can be busy. What does your morning look like?", "warm"),
      sc("Mrs. Iqbal", "your teacher", "to hear a longer connected answer",
        "In class you describe your daily routine in detail.",
        "Describe your morning with linking words.",
        "Take your time and tell us about your morning. Where do you start?", "warm"),
      sc("Mr. Solis", "the examiner", "to hear you speak for about a minute",
        "The examiner asks you to describe a typical morning.",
        "Describe your morning in order, with times.",
        "Could you describe a typical morning for you?", "neutral"),
    ],
  },
];
