/** A1 · Ünite 1-2 — Hello and Introductions · People Around Me (12 ders, elle yazıldı). */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A1_U1_2: Authored[] = [
  // --- Ünite 1 ---------------------------------------------------------------
  {
    id: "a1-hello-im",
    topic: "saying hello and giving your name",
    objectives: ["Introduce myself to someone new.", "Greet someone and ask how they are."],
    goal: "Meet someone for the first time and say who you are.",
    target: "my name is / nice to meet you / how are you",
    correction: "Model the whole phrase and invite the learner to say it again.",
    summary: "You learned how to say hello, give your name and ask someone how they are.",
    minutes: 5,
    points: [
      {
        form: "my name is",
        claims: [
          "Use 'my name is' and then your name to tell someone who you are.",
          "'I'm' plus your name means the same thing and is shorter.",
        ],
        ex: ["Hello, my name is Daniel.", "Hi, I'm Daniel."],
      },
      {
        form: "nice to meet you",
        claims: [
          "Say 'nice to meet you' the first time you meet someone.",
          "The other person usually answers 'Nice to meet you too.'",
        ],
        ex: ["Nice to meet you, Sara.", "Nice to meet you too."],
      },
      {
        form: "how are you",
        claims: [
          "Ask 'how are you' after hello, when you already know the person.",
          "Short answers are 'I'm fine, thanks' or 'Not bad, thanks.'",
        ],
        ex: ["Hello Sara, how are you?", "I'm fine, thanks. And you?"],
      },
    ],
    ex: [
      fill("Hi, ___ name is Omar.", ["my", "My"]),
      mcq("You are meeting this person for the very first time. What do you say?", [
        "Nice to meet you.",
        "Nice to meet you again.",
        "See you tomorrow.",
      ], 0),
      say("hello / my name is / Ana", ["Hello, my name is Ana.", "Hi, my name is Ana."]),
    ],
    open: {
      q: "Someone new says hello to you. Introduce yourself and ask how they are.",
      must: ["my name is", "how are you"],
      criteria: "The answer gives a name and asks a question back to the other person.",
      example: "Hello, my name is Ana. How are you?",
    },
    success: "The learner gives their name, greets the other person and asks a question back.",
    quiz: [
      qmcq("Which one do you say when you meet someone for the first time?", [
        "Nice to meet you.",
        "Nice to see you again.",
        "Good night.",
      ], 0),
      qfill("Hi, ___ name is Omar.", ["my", "My"]),
      qmcq("Someone asks you 'How are you?' What is a natural answer?", [
        "I'm fine, thanks.",
        "My name is Omar.",
        "Nice to meet you too.",
      ], 0),
    ],
    scenes: [
      sc("Lucy", "a neighbour you have never met", "to find out who the new person in the building is",
        "You meet a neighbour in the lift of your building for the first time.",
        "Say hello, tell her your name and ask how she is.",
        "Oh, hello! You must be new in this building, right?", "friendly"),
      sc("David", "a new colleague", "to get to know the people around him on his first day",
        "It is David's first morning in the office and he stops by your desk.",
        "Introduce yourself to him and ask him a question back.",
        "Hi! It's my first day here. Do you work on this floor?", "friendly"),
      sc("Marta", "another traveller at the gate", "to pass the time before boarding",
        "You are waiting at an airport gate next to another traveller.",
        "Introduce yourself and start a short friendly conversation.",
        "Excuse me, is this seat free?", "relaxed"),
      sc("Tom", "a classmate on the first day", "to make friends in a new class",
        "It is the first day of a course and the seat next to you is empty.",
        "Introduce yourself to your classmate and ask how he is.",
        "Hi there! Is anyone sitting here?", "curious"),
      sc("Ms. Green", "the examiner", "to hear you introduce yourself clearly",
        "You are at the start of a short speaking exam.",
        "Introduce yourself politely and answer the examiner.",
        "Good morning. Could you start by telling me who you are?", "calm"),
    ],
  },

  {
    id: "a1-am-is-are",
    topic: "am, is and are",
    objectives: ["Choose am, is or are correctly.", "Use short forms like I'm and she's when I speak."],
    goal: "Say who people are and where they are.",
    target: "am / is / are and their short forms",
    correction: "Say the correct form of 'be' in a full sentence and ask the learner to repeat it.",
    summary: "You learned when to use am, is and are, and how to say the short forms.",
    minutes: 6,
    points: [
      {
        form: "am, is, are",
        claims: [
          "Use 'am' after I, 'is' after he, she and it, and 'are' after you, we and they.",
          "An English sentence needs this verb, so never leave it out.",
        ],
        ex: ["I am a student.", "She is my sister.", "They are at home."],
      },
      {
        form: "I'm, she's, they're",
        claims: [
          "When you speak, join the two words: I'm, you're, he's, she's, it's, we're, they're.",
          "The short form means exactly the same as the long form.",
        ],
        ex: ["I'm from Spain.", "He's my teacher.", "We're in the same class."],
      },
    ],
    ex: [
      fill("My brother ___ a doctor.", ["is"]),
      mcq("Which sentence is correct?", [
        "We are in the same class.",
        "We is in the same class.",
        "We be in the same class.",
      ], 0),
      say("they / be / my friends", ["They are my friends.", "They're my friends."]),
    ],
    open: {
      q: "Tell me about two people you know. Use 'is' and 'are'.",
      must: ["is", "are"],
      criteria: "The answer uses is and are with the right subjects.",
      example: "My sister is a nurse. My parents are teachers.",
    },
    success: "The learner uses am, is and are with the right subject at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", ["I am ready.", "I is ready.", "I are ready."], 0),
      qfill("My parents ___ at work.", ["are"]),
      qmcq("What is the short form of 'she is'?", ["she's", "shes'", "she're"], 0),
    ],
    scenes: [
      sc("Sophie", "a friend looking at your photos", "to find out who the people in the photos are",
        "You are showing photos on your phone to a friend.",
        "Say who each person is and where they are.",
        "These photos are lovely! Who are all these people?", "curious"),
      sc("Martin", "a colleague from another office", "to learn who is who in your team",
        "A colleague from another city is visiting and sees your team photo.",
        "Explain who the people in your team are.",
        "I've only met you so far. Who is who in this team?", "friendly"),
      sc("Elena", "a fellow guest at the hotel", "to hear about the people you are travelling with",
        "You are having breakfast at a hotel and a guest asks about your group.",
        "Say who the people with you are.",
        "You are travelling in a group, aren't you? Who is with you?", "friendly"),
      sc("Mr. Hall", "your teacher", "to learn about his new students",
        "Your teacher is getting to know the class on the first day.",
        "Tell the teacher who you are and who your classmates are.",
        "Let's get to know each other. Who are you and who do you know here?", "warm"),
      sc("Ms. Reed", "the examiner", "to check that you can describe people simply",
        "The examiner shows you a picture of a family.",
        "Say who the people are, using am, is and are.",
        "Look at this family photo. Can you tell me about the people in it?", "neutral"),
    ],
  },

  {
    id: "a1-are-you-a-student",
    topic: "yes and no questions with be",
    objectives: ["Ask questions with am, is and are.", "Give short answers like 'Yes, I am.'"],
    goal: "Ask someone simple questions about themselves and answer them.",
    target: "are you...? / yes, I am / no, I'm not",
    correction: "Model the question with the verb first and ask the learner to say it again.",
    summary: "You learned how to ask questions with be and how to answer them short.",
    minutes: 6,
    points: [
      {
        form: "Are you...?",
        claims: [
          "To make a question, put am, is or are before the person: 'Are you a student?'",
          "Do not add do or does to a question with be.",
        ],
        ex: ["Are you a student?", "Is she your sister?", "Are they at home?"],
      },
      {
        form: "Yes, I am. / No, I'm not.",
        claims: [
          "Answer with the same verb: Yes, I am. No, she isn't. Yes, they are.",
          "Do not use the short form in a positive short answer: say 'Yes, I am', not 'Yes, I'm'.",
        ],
        ex: ["Yes, I am.", "No, I'm not.", "Yes, she is."],
      },
    ],
    ex: [
      fill("___ you from Italy?", ["Are", "are"]),
      mcq("Someone asks: 'Are you a teacher?' You are a teacher. What do you say?", [
        "Yes, I am.",
        "Yes, I'm.",
        "Yes, I do.",
      ], 0),
      say("be / she / your sister / question", ["Is she your sister?"]),
    ],
    open: {
      q: "You want to know three things about a new classmate. Ask three questions with be.",
      must: ["are you", "is"],
      criteria: "The questions put am, is or are before the person and do not use do.",
      example: "Are you a student? Is your family here? Are you from this city?",
    },
    success: "The learner asks questions with be and answers with short answers.",
    quiz: [
      qmcq("Which question is correct?", ["Are you tired?", "You are tired?", "Do you are tired?"], 0),
      qfill("___ she your teacher?", ["Is", "is"]),
      qmcq("Someone asks: 'Is he at home?' He is not. What do you say?", [
        "No, he isn't.",
        "No, he doesn't.",
        "No, he not.",
      ], 0),
    ],
    scenes: [
      sc("Anna", "someone waiting at the same bus stop", "to make small talk while waiting",
        "You are waiting at a bus stop and start talking to the person next to you.",
        "Ask her questions with be and answer her questions.",
        "This bus is really late today, isn't it?", "chatty"),
      sc("Peter", "a colleague you have just met", "to find out more about the new person",
        "You are having coffee with a colleague you met this morning.",
        "Ask him questions about himself using be.",
        "So, we finally have five minutes. What would you like to know about me?", "friendly"),
      sc("Nina", "a guide meeting the group", "to check who is in her tour group",
        "A guide is meeting your tour group for the first time.",
        "Answer her questions and ask her some of your own with be.",
        "Welcome, everyone! Are you all here for the city tour?", "cheerful"),
      sc("Mr. Diaz", "the course teacher", "to find out about a new student",
        "You are enrolling in a language course and the teacher asks about you.",
        "Answer his questions and ask two questions about the course.",
        "Nice to see you. Are you new to this school?", "warm"),
      sc("Ms. Park", "the examiner", "to check that you can ask and answer simple questions",
        "In the exam the examiner asks you to interview her.",
        "Ask the examiner three questions using be.",
        "Now I would like you to ask me some questions. Are you ready?", "neutral"),
    ],
  },

  {
    id: "a1-im-not-from-here",
    topic: "saying no with be",
    objectives: ["Make negative sentences with am, is and are.", "Correct wrong information politely."],
    goal: "Say what is not true and give the right information.",
    target: "I'm not / it isn't / we aren't",
    correction: "Model the negative form in a full sentence and let the learner repeat it.",
    summary: "You learned how to make negative sentences with be and correct a mistake politely.",
    minutes: 6,
    points: [
      {
        form: "I'm not / isn't / aren't",
        claims: [
          "Put 'not' after am, is or are: I am not, she is not, we are not.",
          "In speaking, use the short forms: I'm not, she isn't, we aren't.",
          "There is no short form for 'am not' on its own, so always say 'I'm not'.",
        ],
        ex: ["I'm not from this city.", "She isn't at work today.", "We aren't ready yet."],
      },
      {
        form: "No, but...",
        claims: [
          "When someone guesses wrong, say the negative first and then the true answer.",
          "This sounds friendly and clear at the same time.",
        ],
        ex: ["I'm not Spanish. I'm Italian.", "It isn't my bag. It's her bag."],
      },
    ],
    ex: [
      fill("She ___ at home today. She is at work.", ["isn't", "is not"]),
      mcq("Which sentence is correct?", [
        "They aren't in the office.",
        "They not are in the office.",
        "They doesn't in the office.",
      ], 0),
      say("I / not / from / this city", ["I'm not from this city.", "I am not from this city."]),
    ],
    open: {
      q: "Someone thinks you are a doctor, but you are not. Correct them and say what is true.",
      must: ["I'm not"],
      criteria: "The answer says what is not true and then gives the correct information.",
      example: "I'm not a doctor. I'm a teacher.",
    },
    success: "The learner corrects wrong information with a negative form of be.",
    quiz: [
      qmcq("Which sentence is correct?", ["He isn't ready.", "He not ready.", "He doesn't ready."], 0),
      qfill("I ___ tired at all today.", ["am not", "'m not"]),
      qmcq("Someone says you are from Brazil, but you are from Portugal. What do you say?", [
        "I'm not from Brazil. I'm from Portugal.",
        "I not from Brazil. I from Portugal.",
        "I don't from Brazil. I'm Portugal.",
      ], 0),
    ],
    scenes: [
      sc("Clara", "a neighbour who has got things wrong", "to work out who is who in the building",
        "Your neighbour thinks you are someone else from the building.",
        "Politely say what is not true and give the right information.",
        "You're the family from the third floor, aren't you?", "friendly"),
      sc("James", "a colleague with the wrong information", "to sort out who does what in the team",
        "A colleague thinks you work in a different department.",
        "Correct him politely and say what you really do.",
        "You're in the finance team, right?", "busy"),
      sc("Sofia", "a hotel receptionist", "to check the details of your booking",
        "The receptionist has the wrong details for your stay.",
        "Say what is not correct and give the right information.",
        "So you're leaving on Sunday and you asked for two rooms, yes?", "polite"),
      sc("Dr. Kim", "your course tutor", "to check she has the right student in front of her",
        "Your tutor has mixed you up with another student.",
        "Explain what is not true and correct it.",
        "You're the student who joined last week, aren't you?", "warm"),
      sc("Mr. Ellis", "the examiner", "to see whether you can correct information politely",
        "The examiner makes some wrong guesses about you on purpose.",
        "Correct each wrong guess with a negative sentence.",
        "Let me guess a few things about you. You're a student here, right?", "neutral"),
    ],
  },

  {
    id: "a1-where-are-you-from",
    topic: "countries and where you live",
    objectives: ["Say which country you are from.", "Ask someone where they are from and where they live."],
    goal: "Talk about where you come from and where you live now.",
    target: "I'm from / where are you from / I live in",
    correction: "Repeat the phrase correctly with the country name and let the learner say it again.",
    summary: "You learned how to say where you are from and where you live, and how to ask other people.",
    minutes: 5,
    points: [
      {
        form: "I'm from",
        claims: [
          "Use 'I'm from' plus a country or city to say where you come from.",
          "Country names in English start with a capital letter: Spain, Japan, Brazil.",
        ],
        ex: ["I'm from Japan.", "She's from a small town near Rome."],
      },
      {
        form: "Where are you from?",
        claims: [
          "Ask 'Where are you from?' to find out someone's country or city.",
          "The word 'where' comes first, then the verb, then the person.",
        ],
        ex: ["Where are you from?", "Where is your friend from?"],
      },
      {
        form: "I live in",
        claims: [
          "Use 'I live in' plus a city or country for the place where you are now.",
          "You can be from one place and live in another.",
        ],
        ex: ["I live in Berlin now.", "I'm from Poland, but I live in France."],
      },
    ],
    ex: [
      fill("I'm ___ Turkey, but I live in Germany.", ["from"]),
      mcq("Which question asks about someone's country?", [
        "Where are you from?",
        "Where are you go?",
        "From where you are?",
      ], 0),
      say("I / live / in Madrid / now", ["I live in Madrid now.", "I live in Madrid."]),
    ],
    open: {
      q: "A new person asks about you. Say where you are from and where you live now.",
      must: ["I'm from", "I live in"],
      criteria: "The answer names a place of origin and a place where the speaker lives.",
      example: "I'm from a small town in Italy, but I live in Milan now.",
    },
    success: "The learner says where they are from, where they live, and asks the other person too.",
    quiz: [
      qmcq("Which sentence is correct?", ["I'm from Mexico.", "I'm of Mexico.", "I from Mexico."], 0),
      qfill("I ___ in a small flat in the city centre.", ["live"]),
      qmcq("You want to know someone's country. What do you ask?", [
        "Where are you from?",
        "Where do you from?",
        "What are you from?",
      ], 0),
    ],
    scenes: [
      sc("Emily", "someone at a neighbourhood party", "to get to know new people in the area",
        "You are at a small party in your neighbourhood and meet someone new.",
        "Say where you are from and where you live, and ask her the same.",
        "I don't think we've met. How long have you been in this area?", "sociable"),
      sc("Ravi", "a colleague at an international office", "to learn where his new colleagues come from",
        "Your company has people from many countries and you meet a colleague at lunch.",
        "Talk about where you are from and where you live now.",
        "Our team is from all over the place. What about you?", "friendly"),
      sc("Hanna", "a traveller at the airport gate", "to chat while waiting for a delayed flight",
        "Your flight is delayed and the traveller next to you starts talking.",
        "Talk about your country and your city, and ask about hers.",
        "Two hours of waiting! Is this trip taking you home?", "relaxed"),
      sc("Mr. Owen", "the course teacher", "to learn where the students in the class come from",
        "On the first day the teacher asks students about their backgrounds.",
        "Say where you are from and where you live now.",
        "We have students from many countries this year. Would you like to start?", "warm"),
      sc("Ms. Blake", "the examiner", "to hear you talk about your background",
        "The examiner asks you a few simple questions about yourself.",
        "Say where you are from and where you live, in full sentences.",
        "Let's begin with where you come from. Can you tell me about that?", "neutral"),
    ],
  },

  {
    id: "a1-meeting-someone-new",
    topic: "a first conversation with someone new",
    objectives: ["Keep a short first conversation going.", "Ask a question back with 'What about you?'"],
    goal: "Have a short first conversation with a stranger and keep it going.",
    target: "nice to meet you / where are you from / what about you",
    correction: "Give the learner a natural phrase to use and let them try the exchange again.",
    summary: "You practised meeting someone new: greeting, giving information and asking back.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "What about you?",
        claims: [
          "After you answer a question, ask 'What about you?' to give the turn back.",
          "This short question keeps a conversation going without new words.",
        ],
        ex: ["I'm from Greece. What about you?", "I live near the station. What about you?"],
      },
      {
        form: "Really? / Me too!",
        claims: [
          "Short reactions like 'Really?' and 'Me too!' show that you are listening.",
          "Use 'Me too' when the same thing is true for you.",
        ],
        ex: ["Really? That's interesting.", "Me too! I live there as well."],
      },
    ],
    ex: [
      fill("I'm from Poland. What ___ you?", ["about"]),
      mcq("Your new friend says 'I'm a student.' You are a student too. What do you say?", [
        "Me too!",
        "Me also am!",
        "I too is!",
      ], 0),
      say("nice / to meet / you", ["Nice to meet you.", "It's nice to meet you."]),
    ],
    open: {
      q: "You meet someone at an event. Say hello, give one thing about yourself and ask them a question.",
      must: ["nice to meet you", "what about you"],
      criteria: "The answer greets, gives information and asks a question back.",
      example: "Hi, I'm Ana. Nice to meet you. I'm from Portugal. What about you?",
    },
    success: "The learner greets, gives information about themselves and asks questions back at least twice.",
    quiz: [
      qmcq("Which phrase gives the turn back to the other person?", [
        "What about you?",
        "Nice to meet you.",
        "See you later.",
      ], 0),
      qfill("I live in Rome. What ___ you?", ["about"]),
      qmcq("What do you say when you hear something surprising?", ["Really?", "Me too!", "Goodbye!"], 0),
    ],
    scenes: [
      sc("Julia", "another guest at a friend's party", "to meet new people at the party",
        "You are at a friend's party and you do not know many people.",
        "Meet Julia, tell her about yourself and ask her questions.",
        "Hi! I don't know many people here either. How do you know the host?", "sociable"),
      sc("Ben", "a colleague at a company event", "to network with people from other teams",
        "You are at a company event where people from different teams meet.",
        "Introduce yourself and keep the conversation going.",
        "Hi there! Which part of the company are you in?", "friendly"),
      sc("Carla", "a guest at the hostel kitchen", "to find travel company for the evening",
        "You are cooking in a hostel kitchen and another guest starts talking.",
        "Introduce yourself and find out about her trip.",
        "That smells good! Have you just arrived?", "cheerful"),
      sc("Adam", "a student at a welcome event", "to make friends at the start of the course",
        "You are at a welcome event for new students.",
        "Meet Adam and keep the conversation going with questions.",
        "Hi! Are you starting the same course as me?", "curious"),
      sc("Ms. Shaw", "the examiner", "to see how you handle a first conversation",
        "In the exam you role play meeting someone for the first time.",
        "Greet, give information about yourself and ask questions back.",
        "Imagine we have just met at an event. Shall we begin?", "neutral"),
    ],
  },

  // --- Ünite 2 ---------------------------------------------------------------
  {
    id: "a1-this-is-my-sister",
    topic: "my, your, his, her, our, their",
    objectives: ["Use my, your, his, her, our and their correctly.", "Introduce the people close to you."],
    goal: "Introduce your family and friends to someone.",
    target: "this is my / her name is / our teacher",
    correction: "Say the correct possessive word in a short sentence and let the learner repeat it.",
    summary: "You learned the words my, your, his, her, our and their, and how to introduce people.",
    minutes: 6,
    points: [
      {
        form: "my, your, his, her, our, their",
        claims: [
          "These words go before the thing or person: my sister, your bag, our teacher.",
          "Use 'his' for a man and 'her' for a woman, whatever the next word is.",
          "The word never changes for plural: 'my brothers', not 'mys brothers'.",
        ],
        ex: ["This is my sister.", "Her name is Maria.", "Our teacher is very kind."],
      },
      {
        form: "This is...",
        claims: [
          "Use 'This is' plus a person to introduce someone who is with you.",
          "For people who are not here, use 'That's my...' or just say the name.",
        ],
        ex: ["This is my friend Tom.", "This is my colleague from work."],
      },
    ],
    ex: [
      fill("That's Anna. ___ brother is a doctor.", ["Her", "her"]),
      mcq("Which sentence is correct?", [
        "This is our teacher.",
        "This is ours teacher.",
        "This is us teacher.",
      ], 0),
      say("this / be / my / sister", ["This is my sister."]),
    ],
    open: {
      q: "Introduce two people in your family. Say who they are and give one detail.",
      must: ["this is my", "her name is"],
      criteria: "The answer introduces people with a possessive word and gives a detail.",
      example: "This is my sister. Her name is Elena and she is a nurse.",
    },
    success: "The learner introduces people using possessive words correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", ["His name is Paul.", "He name is Paul.", "Him name is Paul."], 0),
      qfill("We are in the same class. ___ teacher is Mr. Ross.", ["Our", "our"]),
      qmcq("You are showing a photo of your parents. What do you say?", [
        "These are my parents.",
        "These are mine parents.",
        "This are my parents.",
      ], 0),
    ],
    scenes: [
      sc("Rosa", "a friend visiting your home", "to learn about the people in your family photos",
        "A friend is at your home and looks at the family photos on the wall.",
        "Introduce the people in the photos and give a detail about each one.",
        "Your wall is full of photos! Who is in them?", "curious"),
      sc("Karl", "a colleague at a family day", "to meet the families of his colleagues",
        "Your company has a family day and a colleague comes to say hello.",
        "Introduce the people who came with you.",
        "Great to see you outside the office! Who have you brought along?", "friendly"),
      sc("Ines", "a host family member", "to learn about her guest's family back home",
        "You are staying with a host family and they ask about your family.",
        "Introduce your family members and give a detail about each.",
        "We would love to hear about your family. Do you have any photos?", "warm"),
      sc("Mrs. Doyle", "your teacher", "to learn about the students' families",
        "In class you are talking about families.",
        "Tell the class about two people in your family.",
        "Today we are talking about families. Would you like to start?", "warm"),
      sc("Mr. Grant", "the examiner", "to hear you describe people close to you",
        "The examiner asks you about the people in your life.",
        "Introduce two people using my, his and her.",
        "Could you tell me about two people who are important to you?", "neutral"),
    ],
  },

  {
    id: "a1-he-she-they",
    topic: "he, she, it, we and they",
    objectives: ["Use he, she, it, we and they instead of names.", "Talk about other people with be."],
    goal: "Talk about other people without repeating their names.",
    target: "he / she / they with the correct form of be",
    correction: "Replace the name with the right pronoun in a full sentence and let the learner repeat.",
    summary: "You learned to use he, she, it, we and they with the right form of be.",
    minutes: 6,
    points: [
      {
        form: "he, she, it, we, they",
        claims: [
          "Use 'he' for a man, 'she' for a woman, and 'it' for a thing or a place.",
          "Use these words after you have said the name once, so you do not repeat it.",
          "Use 'they' for two or more people, women and men together.",
        ],
        ex: ["That's Peter. He's my colleague.", "This is Ana. She's new here.", "They're in my class."],
      },
      {
        form: "he's / she's / they're",
        claims: [
          "'He's' and 'she's' are short for 'he is' and 'she is'.",
          "'They're' is short for 'they are' and is used for more than one person.",
        ],
        ex: ["She's my best friend.", "They're students at my school."],
      },
    ],
    ex: [
      fill("This is Sara. ___ is my neighbour.", ["She", "she"]),
      mcq("Which sentence is correct?", [
        "They are my classmates.",
        "They is my classmates.",
        "Them are my classmates.",
      ], 0),
      say("he / be / new / here", ["He is new here.", "He's new here."]),
    ],
    open: {
      q: "Think of two people you know. Say who they are using he, she or they.",
      must: ["she's", "he's"],
      criteria: "The answer uses pronouns with the correct form of be.",
      example: "That's Marco. He's my neighbour. And those are the Ricci family. They're very kind.",
    },
    success: "The learner uses he, she or they with the correct form of be at least twice.",
    quiz: [
      qmcq("This is my mother. ___ is a teacher.", ["She", "Her", "Hers"], 0),
      qfill("Tom and Ana are here. ___ are in my class.", ["They", "they"]),
      qmcq("Which sentence is correct?", ["He's my brother.", "He my brother.", "His my brother."], 0),
    ],
    scenes: [
      sc("Nadia", "a friend at a coffee shop", "to hear about the people you have mentioned",
        "You are telling a friend about people from your daily life.",
        "Talk about two or three people using he, she and they.",
        "You keep mentioning people I don't know! Who are they?", "curious"),
      sc("Oscar", "a colleague new to the building", "to work out who is who in the office",
        "A colleague has just moved into your office and does not know anyone.",
        "Tell him who the people around you are.",
        "Everyone is new to me here. Can you help me out?", "friendly"),
      sc("Petra", "a fellow traveller in your group", "to learn about the other people on the tour",
        "You are on a group tour and a traveller asks about the others.",
        "Say who the other people in the group are.",
        "There are so many of us. Do you know anyone here?", "curious"),
      sc("Mr. Lang", "your teacher", "to learn about the people in his students' lives",
        "In class you are talking about the people around you.",
        "Describe two people using he, she or they.",
        "Tell us about someone you see every day. Who is it?", "warm"),
      sc("Ms. Vale", "the examiner", "to check that you can use pronouns naturally",
        "The examiner shows a picture of a group of people.",
        "Describe the people using he, she and they.",
        "Look at this picture of a group. What can you tell me about them?", "neutral"),
    ],
  },

  {
    id: "a1-have-you-got-a-pen",
    topic: "have got for things you own",
    objectives: ["Say what you have and do not have.", "Ask someone if they have something."],
    goal: "Ask for small things you need and say what you have.",
    target: "I've got / have you got / she hasn't got",
    correction: "Model the full form with 'got' and ask the learner to say the sentence again.",
    summary: "You learned to use have got to say what people have, and to ask for things you need.",
    minutes: 6,
    points: [
      {
        form: "I've got / she's got",
        claims: [
          "Use 'have got' after I, you, we and they, and 'has got' after he, she and it.",
          "In speaking, join the words: I've got, you've got, she's got.",
        ],
        ex: ["I've got two brothers.", "She's got a new phone."],
      },
      {
        form: "Have you got...?",
        claims: [
          "Put 'have' or 'has' first to make a question: 'Have you got a pen?'",
          "Answer with 'Yes, I have' or 'No, I haven't'.",
        ],
        ex: ["Have you got a pen?", "Yes, I have.", "Has she got the keys?"],
      },
      {
        form: "haven't got / hasn't got",
        claims: [
          "For negatives, put 'not' after have or has: I haven't got, she hasn't got.",
        ],
        ex: ["I haven't got any money with me.", "He hasn't got a car."],
      },
    ],
    ex: [
      fill("___ you got a pen I can borrow?", ["Have", "have"]),
      mcq("Which sentence is correct?", [
        "She's got a new bike.",
        "She've got a new bike.",
        "She has get a new bike.",
      ], 0),
      say("I / not / have got / my keys", ["I haven't got my keys.", "I have not got my keys."]),
    ],
    open: {
      q: "You need two small things for a class. Ask a classmate for them.",
      must: ["have you got"],
      criteria: "The answer asks for something with have got in question form.",
      example: "Have you got a pen? And have you got some paper too?",
    },
    success: "The learner asks for things with have got and answers about what they have.",
    quiz: [
      qmcq("Which question is correct?", [
        "Have you got a minute?",
        "Do you have got a minute?",
        "Are you got a minute?",
      ], 0),
      qfill("He ___ got any brothers or sisters.", ["hasn't", "has not"]),
      qmcq("Someone asks: 'Have you got the tickets?' You have them. What do you say?", [
        "Yes, I have.",
        "Yes, I've.",
        "Yes, I do got.",
      ], 0),
    ],
    scenes: [
      sc("Mia", "a flatmate looking for things", "to find the things she needs before going out",
        "Your flatmate is getting ready to leave and cannot find things.",
        "Say what you have and have not got, and ask her about other things.",
        "I can't find anything this morning! Can you help me look?", "hurried"),
      sc("Chris", "a colleague in a meeting room", "to set up the room before a meeting",
        "You are setting up a meeting room and something is missing.",
        "Ask your colleague if he has the things you need.",
        "Right, the meeting starts in five minutes. Are we missing anything?", "busy"),
      sc("Ayla", "a receptionist at the hostel", "to help guests with what they need",
        "You have just checked in and you need a few small things.",
        "Ask the receptionist if she has them.",
        "You're all checked in. Is there anything you need for your room?", "helpful"),
      sc("Mr. Silva", "your teacher before class", "to make sure students have what they need",
        "Class is starting and you do not have everything with you.",
        "Ask a classmate and the teacher for what you need.",
        "Before we start, is everyone ready to write?", "warm"),
      sc("Ms. Todd", "the examiner", "to check that you can ask for things",
        "The examiner asks you to role play borrowing things.",
        "Ask for three things using have got.",
        "Imagine you have forgotten your bag. What would you ask me?", "neutral"),
    ],
  },

  {
    id: "a1-whats-your-job",
    topic: "jobs and a / an",
    objectives: ["Say what your job is.", "Ask someone about their job."],
    goal: "Talk about jobs at a social event.",
    target: "I'm a teacher / what do you do / he's an engineer",
    correction: "Model the job phrase with a or an and let the learner say the sentence again.",
    summary: "You learned how to talk about jobs and when to use a or an before a job.",
    minutes: 6,
    points: [
      {
        form: "I'm a teacher",
        claims: [
          "In English you always need 'a' or 'an' before a job: 'I'm a teacher', not 'I'm teacher'.",
          "Use 'an' when the job starts with a vowel sound: an engineer, an artist, an accountant.",
        ],
        ex: ["I'm a nurse.", "He's an engineer.", "She's a shop assistant."],
      },
      {
        form: "What do you do?",
        claims: [
          "'What do you do?' is the normal way to ask about someone's job.",
          "Learn it as one whole phrase; it does not mean 'what are you doing now'.",
        ],
        ex: ["What do you do?", "I'm a designer. What do you do?"],
      },
    ],
    ex: [
      fill("My sister is ___ engineer.", ["an"]),
      mcq("Which sentence is correct?", [
        "I'm a teacher.",
        "I'm teacher.",
        "I am the teacher job.",
      ], 0),
      say("what / do / you / do / question", ["What do you do?"]),
    ],
    open: {
      q: "Someone at a party asks about your work. Answer and ask them the same question.",
      must: ["what do you do"],
      criteria: "The answer names a job with a or an and asks the question back.",
      example: "I'm a nurse at the city hospital. What do you do?",
    },
    success: "The learner names jobs with a or an correctly and asks about the other person's job.",
    quiz: [
      qmcq("Which sentence is correct?", ["She's an artist.", "She's a artist.", "She's artist."], 0),
      qfill("He works with computers. He's ___ programmer.", ["a"]),
      qmcq("How do you ask about someone's job?", [
        "What do you do?",
        "What are you doing your job?",
        "Which is your work now?",
      ], 0),
    ],
    scenes: [
      sc("Helen", "a guest at a friend's party", "to get to know the other guests",
        "You are at a friend's birthday party and start talking to another guest.",
        "Talk about jobs and ask her about hers.",
        "So, how do you know the birthday girl?", "sociable"),
      sc("Tarek", "someone at a company networking event", "to meet people from other companies",
        "You are at a networking event and someone starts a conversation.",
        "Say what you do and ask about his job.",
        "These events are always so busy! Is this your first one?", "friendly"),
      sc("Grace", "a guest at the hotel bar", "to chat with another traveller",
        "You are at a hotel bar and start talking to another guest.",
        "Talk about your job and ask about hers.",
        "Are you here on holiday or is this a work trip?", "relaxed"),
      sc("Mr. Novak", "a careers teacher", "to hear what jobs his students want",
        "Your class is talking about jobs and future plans.",
        "Say what job you have or want, and ask about others.",
        "Today we are talking about work. What would you like to tell us?", "warm"),
      sc("Ms. Hart", "the examiner", "to hear you talk about work simply",
        "The examiner asks about your work or studies.",
        "Talk about your job or the job you would like, using a or an.",
        "Can you tell me a little about your work or your studies?", "neutral"),
    ],
  },

  {
    id: "a1-how-old-are-you",
    topic: "numbers and age",
    objectives: ["Say and understand numbers up to one hundred.", "Ask and answer about age."],
    goal: "Give personal details like age and numbers when someone asks.",
    target: "how old are you / I'm twenty five / she's ten",
    correction: "Say the number or the age sentence correctly and let the learner repeat it.",
    summary: "You learned numbers up to one hundred and how to ask and answer about age.",
    minutes: 5,
    points: [
      {
        form: "How old are you?",
        claims: [
          "Ask about age with 'How old are you?' and answer with 'I'm' plus the number.",
          "Do not add the word 'years' unless you say 'years old': 'I'm thirty' or 'I'm thirty years old'.",
        ],
        ex: ["How old are you?", "I'm twenty five.", "She's ten years old."],
      },
      {
        form: "numbers up to one hundred",
        claims: [
          "The tens are twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety.",
          "Join tens and units with a hyphen when you write: twenty-one, forty-six.",
        ],
        ex: ["My number is forty-two.", "There are sixty people here."],
      },
    ],
    ex: [
      fill("___ old are you?", ["How", "how"]),
      mcq("Which answer is correct?", [
        "I'm thirty years old.",
        "I have thirty years.",
        "I'm thirty years.",
      ], 0),
      say("she / be / ten / years old", ["She is ten years old.", "She's ten years old."]),
    ],
    open: {
      q: "You are filling in a form with a receptionist. Give your age and one number, like a phone number.",
      must: ["how old are you", "I'm"],
      criteria: "The answer gives an age with the correct pattern and says a number clearly.",
      example: "I'm twenty-eight, and my number is six two four one.",
    },
    success: "The learner asks about age and gives ages and numbers correctly.",
    quiz: [
      qmcq("Which question asks about age?", [
        "How old are you?",
        "How many years you are?",
        "What is your old?",
      ], 0),
      qfill("My brother ___ twelve.", ["is", "'s"]),
      qmcq("Which number is 40?", ["forty", "fourty", "fourteen"], 0),
    ],
    scenes: [
      sc("Dana", "a neighbour with young children", "to talk about the children in the building",
        "Your neighbour is talking about her children in the playground.",
        "Ask about ages and give some numbers about your own family.",
        "The children love this playground. Do you have any little ones?", "friendly"),
      sc("Victor", "a colleague organising a team event", "to collect details for a team event",
        "A colleague is collecting simple details for a company event.",
        "Give the numbers he asks for and ask him a question back.",
        "I need a few details for the list. Have you got a minute?", "busy"),
      sc("Lena", "a receptionist at the sports centre", "to fill in a membership form",
        "You are joining a sports centre and the receptionist fills in a form.",
        "Give your age and other numbers she asks for.",
        "Welcome! Shall I start filling in your form?", "helpful"),
      sc("Mr. Bauer", "the school secretary", "to complete a student record",
        "You are enrolling in a course and the secretary needs your details.",
        "Give your age and numbers, and check the details.",
        "I just need a few details for your record. Ready?", "polite"),
      sc("Ms. Frost", "the examiner", "to check that you can give personal details",
        "The examiner asks for simple personal information.",
        "Give your age and repeat numbers clearly.",
        "Let's start with some simple details. How old are you?", "neutral"),
    ],
  },

  {
    id: "a1-people-in-my-life",
    topic: "talking about the people around you",
    objectives: ["Describe the people in your life in a few sentences.", "React to what someone tells you."],
    goal: "Tell someone about your family, friends and the people you work with.",
    target: "this is my / we're good friends / she's really nice",
    correction: "Offer a natural sentence the learner can copy and let them try again.",
    summary: "You practised talking about the people in your life and reacting to what others say.",
    minutes: 7,
    maxTurns: 10,
    points: [
      {
        form: "we're good friends",
        claims: [
          "Use 'we're' plus a phrase to describe a relationship: we're good friends, we're neighbours.",
          "Add one detail after it, so the other person can ask more.",
        ],
        ex: ["We're good friends from school.", "We're neighbours and we see each other every day."],
      },
      {
        form: "she's really nice",
        claims: [
          "Add 'really' before a describing word to make it stronger: really nice, really funny.",
          "One short opinion makes a description sound natural.",
        ],
        ex: ["She's really nice.", "He's really funny."],
      },
    ],
    ex: [
      fill("Ana and I met at school. ___ good friends.", ["We're", "We are"]),
      mcq("Which sentence sounds most natural when you describe a friend?", [
        "She's really nice.",
        "She's very much nice.",
        "She is nice too much.",
      ], 0),
      say("this / be / my / colleague", ["This is my colleague."]),
    ],
    open: {
      q: "Tell me about two people who are important to you and say one thing about each.",
      must: ["this is my", "we're good friends"],
      criteria: "The answer names two people, says who they are and adds one detail about each.",
      example: "This is my friend Lea. We're good friends from university and she's really funny.",
    },
    success: "The learner describes people, gives details and reacts to what the other person says.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We're good friends.",
        "We good friends.",
        "We are good friend's.",
      ], 0),
      qfill("He is my brother. ___ really kind.", ["He's", "He is"]),
      qmcq("Your friend says 'This is my sister.' What is a natural reaction?", [
        "Oh, nice to meet you!",
        "Nice to meet me!",
        "You are my sister too!",
      ], 0),
    ],
    scenes: [
      sc("Iris", "a friend looking through your photos", "to hear the stories behind the photos",
        "You are looking through photos with a friend who does not know your family.",
        "Talk about several people and add a detail about each.",
        "I love old photos! Who should we start with?", "curious"),
      sc("Marco", "a colleague at lunch", "to get to know you outside work",
        "You are having lunch with a colleague and the talk turns to families.",
        "Talk about the people close to you.",
        "We always talk about work. Tell me something about your life instead?", "friendly"),
      sc("Yara", "a host at a homestay", "to learn about her guest's life at home",
        "You are staying with a family abroad and they ask about your life at home.",
        "Describe the people in your life.",
        "We would love to know more about you. Who is waiting for you at home?", "warm"),
      sc("Mrs. Klein", "your teacher", "to hear a longer answer from her student",
        "In class you are describing people who matter to you.",
        "Talk about two or three people with details.",
        "Today I would like a longer answer. Who is important in your life?", "warm"),
      sc("Mr. Rossi", "the examiner", "to hear you speak for a longer stretch",
        "The examiner asks you to talk about people for about a minute.",
        "Describe two or three people with a detail for each.",
        "Could you tell me about the people who are close to you?", "neutral"),
    ],
  },
];
