/** A2 · Ünite 6-7 — Quantity and Detail · Reasons and Conditions (15 ders).
 *
 *  Ünite 6 miktarı ve kesinliği kuruyor: sayılabilir/sayılamaz ayrımı, küçük
 *  miktarlar, "too/enough" ile yetersizlik, some-/any-/no- bileşikleri ve iyelik.
 *  Hepsi tek bir pratik amaca hizmet ediyor — öğrencinin "bir şey" demek yerine
 *  NE KADAR olduğunu söyleyebilmesi.
 *
 *  Ünite 7 cümleleri birbirine bağlıyor: sebep (because/so), koşul (if), her zaman
 *  doğru olan (zero conditional), gelecekteki zaman bağlaçları, kesinlik derecesi
 *  ve amaç (to + fiil). `if` ile `when` ayrı derslerde çünkü A2'de en sık karışan
 *  yer burası: "if it rains" olası, "when water boils" her zaman.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3.
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A2_U6_7: Authored[] = [
  // --- Ünite 6 · Quantity and Detail -----------------------------------------
  {
    id: "a2-how-much-sugar",
    topic: "asking about amounts",
    objectives: [
      "Choose between much and many correctly.",
      "Ask how much of something there is.",
    ],
    goal: "Work out what is left in the kitchen and what you need to buy.",
    target: "much, many and a lot of",
    correction: "Repeat the question with the correct word and let the learner ask it again.",
    summary: "You learned to use much with things you cannot count and many with things you can.",
    minutes: 7,
    points: [
      {
        form: "how much / how many",
        claims: [
          "Use 'how many' with things you can count: apples, eggs, people.",
          "Use 'how much' with things you cannot count: sugar, water, time, money.",
        ],
        ex: ["How much sugar do we need?", "How many eggs are left?"],
      },
      {
        form: "a lot of",
        claims: [
          "'A lot of' works with both kinds and is very common in positive sentences.",
          "'Much' and 'many' sound more natural in questions and negatives.",
        ],
        ex: ["There's a lot of milk in the fridge.", "We have a lot of plates."],
      },
      {
        form: "not much / not many",
        claims: [
          "The negative keeps the same choice: not much sugar, not many eggs.",
          "'None' means zero and stands alone as an answer.",
        ],
        ex: ["There isn't much bread left.", "There aren't many clean cups."],
      },
    ],
    ex: [
      fill("___ much sugar do we need for this? (how)", ["How"]),
      mcq("Which question is correct?", [
        "How many eggs are left?",
        "How much eggs are left?",
        "How many egg are left?",
      ], 0),
      fill("There isn't ___ bread left, only one slice.", ["much"]),
      say("there / be / a lot of / milk", ["There is a lot of milk.", "There's a lot of milk."]),
    ],
    open: {
      q: "Look in your kitchen in your mind. Say what there is a lot of and what there is not much of.",
      must: ["how much", "how many", "not much"],
      criteria: "The answer uses much and many with the right kind of noun.",
      example: "There's a lot of rice, but not much milk. How much sugar is left, and how many eggs do we have?",
    },
    success: "The learner uses much and many correctly with the right nouns at least twice.",
    quiz: [
      qmcq("Which question is correct?", [
        "How much time do we have?",
        "How many time do we have?",
        "How much times do we have?",
      ], 0),
      qfill("There aren't ___ clean cups. (many)", ["many"]),
      qmcq("Which sentence is correct?", [
        "There's a lot of water in the bottle.",
        "There's a lot water in the bottle.",
        "There are a lot of water in the bottle.",
      ], 0),
    ],
    scenes: [
      sc("Rosalind", "a flatmate making a shopping list", "to find out what the kitchen needs",
        "Two flatmates are checking the cupboards before shopping.",
        "Say what there is a lot of and what is running out.",
        "I am writing the list now. What do we actually need?", "practical"),
      sc("Emeka", "a colleague organising a lunch", "to order the right amounts for the team",
        "Food has to be ordered for a team lunch.",
        "Say how much of each thing is needed.",
        "Twelve people are coming. How much should I order?", "organised"),
      sc("Chiara", "a host in a shared kitchen", "to plan a meal together",
        "You are cooking with a host and checking ingredients.",
        "Ask and answer about amounts.",
        "I want to cook tonight. Shall we see what we have?", "welcoming"),
      sc("Mr. Achterberg", "your teacher", "to practise much and many",
        "The class is describing what is in their kitchens.",
        "Describe amounts correctly.",
        "What is there a lot of in your kitchen right now?", "encouraging"),
      sc("Ms. Cardoso", "the examiner", "to check quantity words",
        "The examiner asks about your shopping habits.",
        "Describe amounts using much and many.",
        "Could you tell me what you usually buy and how much of it?", "neutral"),
    ],
  },

  {
    id: "a2-a-few-or-a-little",
    topic: "talking about small amounts",
    objectives: [
      "Choose between 'a few' and 'a little' correctly.",
      "Say an amount is small without sounding negative.",
    ],
    goal: "Say how much time or money something needs.",
    target: "a few and a little for small amounts",
    correction: "Repeat the phrase with the right word and let the learner build a new sentence.",
    summary: "You learned to use a few with countable things and a little with uncountable ones.",
    minutes: 7,
    points: [
      {
        form: "just a few",
        claims: [
          "'A few' goes with things you can count: a few days, a few people.",
          "'Just a few' makes the small amount sound deliberate rather than disappointing.",
        ],
        ex: ["It only takes a few minutes.", "I invited just a few friends."],
      },
      {
        form: "only a little",
        claims: [
          "'A little' goes with things you cannot count: a little time, a little money.",
          "'Only a little' stresses that the amount is small.",
        ],
        ex: ["I have only a little time today.", "Add a little salt at the end."],
      },
      {
        form: "quite a lot",
        claims: [
          "'Quite a lot' means a fairly large amount and works with both countable and uncountable nouns.",
          "'A few' and 'a little' are positive; 'few' and 'little' alone sound negative.",
        ],
        ex: ["It costs quite a lot.", "We still have quite a lot of time."],
      },
    ],
    ex: [
      fill("It only takes ___ few minutes.", ["a"]),
      mcq("Which sentence is correct?", [
        "I have only a little time today.",
        "I have only a few time today.",
        "I have only little a time today.",
      ], 0),
      fill("I invited just ___ few friends, not the whole office.", ["a"]),
      say("it / cost / quite a lot", ["It costs quite a lot.", "It cost quite a lot."]),
    ],
    open: {
      q: "Think of something you are planning. Say how much time and how much money it needs.",
      must: ["just a few", "only a little", "quite a lot"],
      criteria: "The answer uses 'a few' and 'a little' with the right kind of noun.",
      example: "It takes just a few days to organise, but it costs quite a lot if you book late, and I have only a little money.",
    },
    success: "The learner uses 'a few' and 'a little' correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "Add a little salt at the end.",
        "Add a few salt at the end.",
        "Add little a salt at the end.",
      ], 0),
      qfill("We have ___ few days before the deadline. (a)", ["a"]),
      qmcq("Which sentence is correct?", [
        "There are a few people waiting.",
        "There are a little people waiting.",
        "There is a few people waiting.",
      ], 0),
    ],
    scenes: [
      sc("Ottoline", "a friend planning a party", "to work out what the party needs",
        "A friend is planning a small gathering and needs a reality check.",
        "Say how much time and money it will take.",
        "I want to do this next weekend. Is that realistic?", "optimistic"),
      sc("Sebastian", "a colleague scoping a task", "to estimate the work involved",
        "A small task needs an honest estimate.",
        "Estimate the time and resources needed.",
        "Give me an honest estimate: how big is this really?", "direct"),
      sc("Noemi", "a guide pricing a trip", "to explain what the trip costs and takes",
        "You are asking about the practical side of a trip.",
        "Ask about time and cost.",
        "The trip is very popular. What would you like to know first?", "helpful"),
      sc("Mrs. Ekwueme", "your teacher", "to practise small quantity words",
        "The class is estimating time and cost for plans.",
        "Describe small amounts correctly.",
        "How much time do you need for your project?", "encouraging"),
      sc("Mr. Halvorsen", "the examiner", "to check quantity words",
        "The examiner asks about a plan of yours.",
        "Describe the amounts precisely.",
        "Could you tell me about something you are planning and what it will take?", "neutral"),
    ],
  },

  {
    id: "a2-too-small-not-big-enough",
    topic: "saying why something does not work",
    objectives: [
      "Use 'too' before a describing word.",
      "Use 'enough' after a describing word.",
    ],
    goal: "Explain why something does not fit or does not work for you.",
    target: "too and enough",
    correction: "Repeat the sentence with the word in the right position and let the learner try again.",
    summary: "You learned that 'too' comes before the describing word and 'enough' comes after it.",
    minutes: 7,
    points: [
      {
        form: "it's too small",
        claims: [
          "'Too' comes before the describing word and means more than you want.",
          "When 'too' means more than wanted or suitable, it describes a problem: too big, too noisy.",
        ],
        ex: ["This jacket is too small for me.", "The room was too noisy to work in."],
      },
      {
        form: "not big enough",
        claims: [
          "'Enough' comes after the describing word: big enough, warm enough.",
          "Before a noun the order changes: enough time, enough chairs.",
        ],
        ex: ["The table isn't big enough for six.", "We don't have enough chairs."],
      },
      {
        form: "too expensive",
        claims: [
          "'Too ... to ...' gives the consequence: too expensive to buy.",
          "'Enough to' works the same way: warm enough to sit outside.",
        ],
        ex: ["It's too expensive to buy today.", "It's warm enough to sit outside."],
      },
    ],
    ex: [
      fill("This jacket is ___ small for me. (more than I want)", ["too"]),
      mcq("Which sentence is correct?", [
        "The table isn't big enough for six.",
        "The table isn't enough big for six.",
        "The table isn't big too for six.",
      ], 0),
      fill("We don't have ___ chairs for everyone.", ["enough"]),
      say("it / be / too expensive", ["It is too expensive.", "It's too expensive."]),
    ],
    open: {
      q: "Think of something you decided not to buy or keep. Explain why it did not work for you.",
      must: ["it's too small", "not big enough", "too expensive"],
      criteria: "The answer explains a problem using 'too' or 'enough' in the correct position.",
      example: "I liked the flat, but it's too small for us. The kitchen isn't big enough for a table, and the rent is too expensive.",
    },
    success: "The learner uses 'too' and 'enough' in the correct positions at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "The coffee is too hot to drink.",
        "The coffee is hot too to drink.",
        "The coffee is enough hot to drink.",
      ], 0),
      qfill("It isn't warm ___ to sit outside.", ["enough"]),
      qmcq("Which sentence is correct?", [
        "We don't have enough time.",
        "We don't have time enough.",
        "We don't have too time.",
      ], 0),
    ],
    scenes: [
      sc("Fabio", "a shop assistant", "to find you something that fits",
        "You are trying things on and nothing is right.",
        "Explain why each one does not work.",
        "How did you get on with those?", "attentive"),
      sc("Greta", "a colleague viewing an office", "to judge whether the space works",
        "The team is considering a new office space.",
        "Say why the space does or does not work.",
        "It looks nice, but will it actually work for us?", "assessing"),
      sc("Youssef", "a hotel manager", "to fix a problem with your room",
        "Your room has a problem you need to explain.",
        "Explain what is wrong with the room.",
        "Reception said there was an issue with the room. What is it?", "attentive"),
      sc("Ms. Lindholm", "your teacher", "to practise too and enough",
        "The class is explaining why things do not fit.",
        "Explain a problem with too or enough.",
        "Think of something that did not fit you. What was wrong with it?", "encouraging"),
      sc("Mr. Delgado", "the examiner", "to check too and enough",
        "The examiner asks about a decision not to buy something.",
        "Explain the reason clearly.",
        "Could you tell me about something you decided not to buy, and why?", "neutral"),
    ],
  },

  {
    id: "a2-how-long-how-far",
    topic: "asking about time and distance",
    objectives: [
      "Ask how long a journey takes and how far it is.",
      "Give approximate answers.",
    ],
    goal: "Check the practical details of a journey before you set off.",
    // Katalog `focus`u "size"ı da anıyor ama `targetPhrases` üçü de süre/mesafe —
    // ölçülen şey bu, o yüzden hedef de onu söylüyor. Boyut öğretiliyor (p2'de
    // "how big"), sadece ölçüme girmiyor.
    target: "questions about duration and distance",
    correction: "Model the question in its natural form and let the learner ask it again.",
    summary: "You learned to ask about time, distance and size, and to answer approximately.",
    minutes: 6,
    points: [
      {
        form: "how long does it take",
        claims: [
          "'How long does it take?' asks about duration, not about length.",
          "The answer usually starts with 'it takes' plus a period of time.",
        ],
        ex: ["How long does it take to get there?", "It takes about forty minutes."],
      },
      {
        form: "how far is",
        claims: [
          "'How far' asks about distance and is usually answered in metres, kilometres or miles.",
          "'How big' and 'how deep' follow the same pattern.",
        ],
        ex: ["How far is the station from here?", "How big is the room?"],
      },
      {
        form: "about ten kilometres",
        claims: [
          "'About', 'around' and 'roughly' make an answer approximate.",
          "Exact numbers are rarely needed in everyday conversation.",
        ],
        ex: ["It's about ten kilometres.", "Roughly half an hour by bus."],
      },
    ],
    ex: [
      fill("How ___ does it take to get to the airport?", ["long"]),
      mcq("Which question asks about distance?", [
        "How far is the station?",
        "How long is the film?",
        "How often does it run?",
      ], 0),
      say("it / be / about ten kilometres", ["It's about ten kilometres.", "It is about ten kilometres."]),
    ],
    open: {
      q: "You are planning a journey with a friend. Ask about the duration and distance, then give one approximate answer.",
      must: ["how long does it", "how far is", "about ten kilometres"],
      criteria: "The answer asks correctly about duration and distance and includes an approximate answer.",
      example: "How long does it take by train? How far is the hotel from the station? It's about ten kilometres.",
    },
    success: "The learner asks at least two correct practical questions.",
    quiz: [
      qmcq("Which question is correct?", [
        "How long does it take to get there?",
        "How long it takes to get there?",
        "How long does it takes to get there?",
      ], 0),
      qfill("___ far is it from here to the beach?", ["How"]),
      qmcq("Which answer is approximate?", [
        "It's about ten kilometres.",
        "It's ten kilometres and forty metres.",
        "It's not far at all, exactly.",
      ], 0),
    ],
    scenes: [
      sc("Dorota", "a friend who knows the area", "to give you the practical details",
        "You are planning a trip to a place your friend knows well.",
        "Ask the practical questions you need answered.",
        "I know that route well. What do you want to know?", "helpful"),
      sc("Anders", "a colleague arranging travel", "to book the right connections",
        "A business trip needs planning and timings.",
        "Ask about times and distances.",
        "I am booking the tickets today. Any questions before I do?", "efficient"),
      sc("Kemal", "a taxi driver", "to tell you about the route",
        "You are in a taxi and want to know the details of the journey.",
        "Ask about duration and distance.",
        "We will be there soon enough. First time here?", "chatty"),
      sc("Mrs. Nyberg", "your teacher", "to practise practical questions",
        "The class is planning journeys in pairs.",
        "Ask about time and distance.",
        "You are planning a journey. What do you need to find out?", "encouraging"),
      sc("Mr. Rossi", "the examiner", "to check practical question forms",
        "The examiner asks you to plan a journey.",
        "Ask clear practical questions.",
        "Imagine you are travelling to a new city. What would you ask me?", "neutral"),
    ],
  },

  {
    id: "a2-something-anything-nothing",
    topic: "words built with some, any and no",
    objectives: [
      "Choose between something, anything and nothing.",
      "Use the compound word instead of a longer phrase.",
    ],
    goal: "Say what there is and is not, without naming it exactly.",
    target: "compounds with some-, any- and no-",
    correction: "Repeat the sentence with the correct compound and let the learner say it again.",
    summary: "You learned when to use something, anything and nothing, with a first look at related forms such as somebody and somewhere.",
    minutes: 7,
    points: [
      {
        form: "something to eat",
        claims: [
          "'Something' is used in positive sentences and in offers.",
          "The same rule gives somebody and somewhere.",
        ],
        ex: ["I need something to eat.", "Somebody left a bag here."],
      },
      {
        form: "anything else",
        claims: [
          "'Anything' is usual in questions and after a negative verb.",
          "'Would you like anything else?' is the standard shop question.",
        ],
        ex: ["Is there anything else?", "I didn't buy anything."],
      },
      {
        form: "nothing special",
        claims: [
          "'Nothing' already carries the negative, so the verb stays positive.",
          "Say 'there's nothing', not 'there isn't nothing'.",
        ],
        ex: ["There's nothing in the fridge.", "It was nothing special."],
      },
    ],
    ex: [
      fill("I need ___ to eat, I'm starving.", ["something"]),
      mcq("Which sentence is correct?", [
        "There's nothing in the fridge.",
        "There isn't nothing in the fridge.",
        "There's not nothing in the fridge.",
      ], 0),
      fill("Would you like ___ else with that?", ["anything"]),
      say("somebody / leave / a bag / here", ["Somebody left a bag here.", "Someone left a bag here."]),
    ],
    open: {
      q: "You open an almost empty fridge with a friend. Say what is there, what is missing and ask whether there is anything else.",
      must: ["something to eat", "anything else", "nothing special"],
      criteria: "The answer uses something, anything and nothing correctly with a single negative.",
      example: "There's nothing special in the fridge. I need something to eat. Is there anything else in the cupboard?",
    },
    success: "The learner uses these compound words correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I didn't buy anything.",
        "I didn't buy nothing.",
        "I don't bought anything.",
      ], 0),
      qfill("Is there ___ else you need? (any)", ["anything"]),
      qmcq("Which sentence is correct?", [
        "Somebody left a message for you.",
        "Anybody left a message for you.",
        "Nobody left a message for you, somebody did.",
      ], 0),
    ],
    scenes: [
      sc("Renske", "a flatmate looking for food", "to decide whether to order in",
        "Two flatmates are staring into an empty fridge.",
        "Say what there is and is not.",
        "Is there anything in there at all, or do we order?", "hungry"),
      sc("Julio", "a colleague at the end of a meeting", "to close the meeting properly",
        "The meeting is finishing and there is time for final points.",
        "Say whether there is anything left to raise.",
        "Before we finish, is there anything else?", "brisk"),
      sc("Hana", "a shop assistant", "to complete your purchase",
        "You are at the counter finishing a purchase.",
        "Answer and ask about what else you need.",
        "That's everything scanned. Would you like anything else?", "polite"),
      sc("Mr. Whitmore", "your teacher", "to practise compound words",
        "The class is describing what is and is not there.",
        "Use something, anything and nothing correctly.",
        "What is in your bag right now, and what is missing?", "encouraging"),
      sc("Ms. Ferreira", "the examiner", "to check compound words",
        "The examiner asks what you keep at home.",
        "Describe using the right compounds.",
        "Could you tell me what there is in your kitchen at the moment?", "neutral"),
    ],
  },

  {
    id: "a2-mine-yours-theirs",
    topic: "saying whose something is",
    objectives: [
      "Use possessive pronouns instead of repeating the noun.",
      "Ask whose something is.",
    ],
    goal: "Sort out whose things are whose after a shared trip.",
    target: "possessive pronouns and whose",
    correction: "Repeat the sentence with the pronoun alone and let the learner say it again.",
    summary: "You learned to say mine, yours and theirs, and to ask whose something is.",
    minutes: 7,
    points: [
      {
        form: "it's mine",
        claims: [
          "Possessive pronouns stand alone: mine, yours, his, hers, ours, theirs.",
          "They replace the noun, so nothing follows them.",
        ],
        ex: ["That bag is mine.", "The blue one is hers."],
      },
      {
        form: "my / mine",
        claims: [
          "'My' comes before a noun; 'mine' stands alone.",
          "Say 'my coat' or 'mine', never 'mine coat'.",
        ],
        ex: ["This is my coat.", "This coat is mine."],
      },
      {
        form: "whose is this",
        claims: [
          "'Whose' asks who owns something.",
          "It sounds the same as 'who's' but has a different meaning.",
        ],
        ex: ["Whose is this jacket?", "Whose keys are these?"],
      },
    ],
    ex: [
      fill("That bag is ___, I recognise it. (belongs to me)", ["mine"]),
      mcq("Which sentence is correct?", [
        "This coat is mine.",
        "This is mine coat.",
        "This coat is my.",
      ], 0),
      fill("___ keys are these? Nobody knows.", ["Whose"]),
      say("the blue one / be / hers", ["The blue one is hers."]),
    ],
    open: {
      q: "After a shared trip there are three items left behind. Ask whose they are and claim one.",
      must: ["it's mine", "that's yours", "whose is this"],
      criteria: "The answer uses possessive pronouns correctly and asks about ownership.",
      example: "Whose is this jacket? The grey scarf is mine, and I think that's yours on the chair.",
    },
    success: "The learner uses possessive pronouns and 'whose' correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "The blue one is hers.",
        "The blue one is her.",
        "The blue one is hers one.",
      ], 0),
      qfill("___ is this umbrella? (who owns it)", ["Whose"]),
      qmcq("Which sentence is correct?", [
        "These seats are ours.",
        "These seats are our.",
        "These are ours seats.",
      ], 0),
    ],
    scenes: [
      sc("Bettina", "a friend after a shared holiday", "to return the things left behind",
        "Several items are left in one bag after a group trip.",
        "Sort out what belongs to whom.",
        "There are three things here and I have no idea who owns them. Any ideas?", "puzzled"),
      sc("Ismail", "a colleague clearing a meeting room", "to find the owners of the items left",
        "Things were left behind after a long meeting.",
        "Ask and answer about ownership.",
        "Someone left all this in the room. Do you recognise any of it?", "practical"),
      sc("Solveig", "a hostel receptionist", "to reunite lost items with guests",
        "Items have been handed in at reception.",
        "Ask about and claim items.",
        "We have a box of lost property here. Have you lost something?", "helpful"),
      sc("Mrs. Osei", "your teacher", "to practise possessive pronouns",
        "The class is sorting out mixed-up belongings.",
        "Say what belongs to whom.",
        "Everything got mixed up. How do you say which is yours?", "encouraging"),
      sc("Mr. Larsen", "the examiner", "to check possessive forms",
        "The examiner asks about shared belongings.",
        "Use possessive pronouns correctly.",
        "Could you tell me about something you share with someone, and what is yours?", "neutral"),
    ],
  },

  {
    id: "a2-packing-for-a-trip",
    topic: "deciding what to take",
    objectives: [
      "Say what you need and do not need.",
      "Agree when you have enough of something.",
    ],
    goal: "Pack one suitcase with someone else and agree on what goes in.",
    target: "deciding quantities and necessity",
    correction: "Model the sentence about need and let the learner continue deciding.",
    summary: "You practised deciding what to take, what to leave and when enough is enough.",
    minutes: 6,
    points: [
      {
        form: "I don't need",
        claims: [
          "'I don't need' is followed by a noun or by 'to' plus a verb.",
          "It is softer than 'I won't take' when you are deciding together.",
        ],
        ex: ["I don't need three jumpers.", "I don't need to bring my laptop."],
      },
      {
        form: "we should take",
        claims: [
          "'We should take' suggests without deciding for the other person.",
          "'Shall we take ...?' turns the same idea into a question.",
        ],
        ex: ["We should take an umbrella.", "We should take something warm."],
      },
      {
        form: "that's enough",
        claims: [
          "'That's enough' closes a decision politely.",
          "'That should do it' means the same thing in a softer way.",
        ],
        ex: ["Two pairs are enough.", "That's enough for four days."],
      },
    ],
    ex: [
      fill("I ___ need three jumpers for two days. (do not)", ["don't", "do not"]),
      mcq("Which sentence suggests something?", [
        "We should take an umbrella.",
        "We took an umbrella.",
        "The umbrella is here.",
      ], 0),
      // YALNIZ çoğul: "Two pairs is enough" konuşmada duyulur ama standart değil,
      // A2'de öğretilecek biçim bu değil. Öğrenci yine de "is" derse deterministik
      // eşleşme kaçırır ve girdi judge'a gider — hoşgörü orada, listede değil.
      say("two pairs / be / enough", ["Two pairs are enough."]),
    ],
    open: {
      q: "You are packing one small suitcase for four days with a friend. Say what to take and what to leave.",
      must: ["I don't need", "we should take", "that's enough"],
      criteria: "The answer decides what is needed and what is not, and closes the decision.",
      example: "I don't need three pairs of shoes. We should take one warm jacket, and that's enough for four days.",
    },
    success: "The learner states needs and closes at least one decision.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I don't need to bring my laptop.",
        "I don't need bring my laptop.",
        "I don't need to bringing my laptop.",
      ], 0),
      qfill("That's ___ for four days, I think.", ["enough"]),
      qmcq("Which sentence closes a decision?", [
        "That should do it.",
        "What else is there?",
        "I am not sure yet.",
      ], 0),
    ],
    scenes: [
      sc("Konstantin", "a friend you are travelling with", "to fit everything into one case",
        "Two friends have one suitcase and too many things.",
        "Decide together what to take.",
        "One case, four days, two people. Where do we start?", "amused"),
      sc("Adaeze", "a colleague packing for a work trip", "to pack the right things for the meetings",
        "A short business trip needs careful packing.",
        "Decide what is necessary.",
        "Two days, three meetings. What do I actually need?", "practical"),
      sc("Lasse", "a fellow hiker", "to keep the packs light",
        "Two hikers are cutting weight from their packs.",
        "Decide what to leave behind.",
        "Every extra kilo counts tomorrow. What can we leave?", "focused"),
      sc("Ms. Villanueva", "your teacher", "to practise necessity language",
        "The class is packing an imaginary suitcase.",
        "Say what is needed and what is not.",
        "You have one small bag for a week. What goes in?", "encouraging"),
      sc("Mr. Kristensen", "the examiner", "to check necessity language",
        "The examiner asks about your packing habits.",
        "Say what you need and do not need.",
        "Could you tell me what you always take when you travel?", "neutral"),
    ],
  },

  // --- Ünite 7 · Reasons and Conditions --------------------------------------
  {
    id: "a2-because-and-so",
    topic: "giving reasons and results",
    objectives: [
      "Give a reason with because.",
      "Give a result with so.",
    ],
    goal: "Explain a decision you had to make quickly.",
    target: "because and so",
    correction: "Repeat the joined sentence and let the learner build their own.",
    summary: "You learned that because introduces the reason and so introduces the result.",
    minutes: 7,
    points: [
      {
        form: "because I was",
        claims: [
          "'Because' introduces the reason and answers the question why.",
          "The reason can come first or second, but the two parts stay in one sentence.",
        ],
        ex: ["I left early because I was tired.", "Because it was raining, we stayed in."],
      },
      {
        form: "so I decided",
        claims: [
          "'So' introduces the result of what came before.",
          "The order matters: reason first, then 'so', then result.",
        ],
        ex: ["The train was cancelled, so I decided to walk.", "It was late, so we went home."],
      },
      {
        form: "that's why",
        claims: [
          "'That's why' points back to the reason you have just given.",
          "It usually starts a new sentence.",
        ],
        ex: ["The road was closed. That's why I was late.", "That's why I called you."],
      },
    ],
    ex: [
      fill("I left early ___ I was tired.", ["because"]),
      mcq("Which sentence is correct?", [
        "The train was cancelled, so I walked.",
        "The train was cancelled, because I walked.",
        "So the train was cancelled, I walked.",
      ], 0),
      fill("The road was closed. ___ why I was late.", ["That's", "That is"]),
      say("because / it / be / raining / we / stay / in", ["Because it was raining, we stayed in.", "We stayed in because it was raining."]),
    ],
    open: {
      q: "Tell me about a decision you had to make quickly. Give the reason and the result.",
      must: ["because I was", "so I decided", "that's why"],
      criteria: "The answer joins a reason and a result correctly with because or so.",
      example: "I missed the last bus because I was late, so I decided to walk home. That's why I arrived after midnight.",
    },
    success: "The learner joins reason and result correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "It was late, so we went home.",
        "It was late, because we went home.",
        "So it was late, we went home.",
      ], 0),
      qfill("We stayed inside ___ it was raining.", ["because"]),
      qmcq("Which sentence gives a reason?", [
        "I was late because the road was closed.",
        "I was late, so the road was closed.",
        "The road was closed, that is late.",
      ], 0),
    ],
    scenes: [
      sc("Mirela", "a friend you kept waiting", "to hear why you were late",
        "You arrived very late and your friend waited.",
        "Explain the reason and what you decided.",
        "I was starting to worry! What happened?", "relieved"),
      sc("Patrick", "your manager", "to understand a decision you made alone",
        "You made a call without checking first and must explain.",
        "Give the reason and the result.",
        "You changed the plan yesterday. Talk me through it?", "even"),
      sc("Sara", "a fellow passenger", "to swap stories about the delay",
        "A cancelled connection has stranded several travellers.",
        "Explain what you did and why.",
        "Everyone here has a story about today. What did you do?", "commiserating"),
      sc("Mr. Boateng", "your teacher", "to practise because and so",
        "The class is joining reasons and results.",
        "Explain a decision fully.",
        "Tell us about a decision you made quickly. Why did you make it?", "encouraging"),
      sc("Ms. Aaltonen", "the examiner", "to check reason and result links",
        "The examiner asks about a past decision.",
        "Give reason and result clearly.",
        "Could you tell me about a decision you had to make in a hurry?", "neutral"),
    ],
  },

  {
    id: "a2-if-it-rains-well-stay",
    topic: "talking about a likely future situation",
    objectives: [
      "Use the present tense after 'if' when talking about the future.",
      "Use will in the other half of the sentence.",
    ],
    goal: "Plan an event around weather you cannot control.",
    target: "if plus present, will plus base verb",
    correction: "Repeat the whole sentence with the correct tenses and let the learner build another.",
    summary: "You learned to talk about a likely future situation with if plus the present and will.",
    minutes: 7,
    points: [
      {
        form: "if it rains, we'll stay",
        claims: [
          "After 'if' use the present tense, even though you mean the future.",
          "The other half uses will plus the base verb.",
        ],
        ex: ["If it rains, we'll stay inside.", "If she calls, I'll tell her."],
      },
      {
        form: "I'll call you",
        claims: [
          "Either half can come first; only the comma moves.",
          "Never put 'will' after 'if' in this pattern.",
        ],
        ex: ["I'll call you if there's a problem.", "If there's a problem, I'll call you."],
      },
      {
        form: "if you want",
        claims: [
          "'If you want' and 'if you like' soften an offer.",
          "'Unless' means the same as 'if not'.",
        ],
        ex: ["I'll book it if you want.", "We'll go ahead unless it snows."],
      },
    ],
    ex: [
      fill("If it ___ tomorrow, we'll stay inside. (rain)", ["rains"]),
      mcq("Which sentence is correct?", [
        "If she calls, I'll tell her.",
        "If she will call, I'll tell her.",
        "If she calls, I tell her will.",
      ], 0),
      fill("I'll call you if there ___ a problem. (be)", ["is", "'s"]),
      say("I / book / it / if you want", ["I'll book it if you want.", "I will book it if you want."]),
    ],
    open: {
      q: "You are planning an outdoor event next week. Say what you will do if the weather is bad.",
      must: ["if it rains", "I'll call you", "if you want"],
      criteria: "The answer uses the present after 'if' and will in the other half of the sentence.",
      example: "If it rains, we'll move everything indoors. I'll call you the evening before, and I'll book an indoor room if you want.",
    },
    success: "The learner produces at least two correct if-sentences about the future.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "If it snows, we will cancel.",
        "If it will snow, we will cancel.",
        "If it snows, we cancel will.",
      ], 0),
      qfill("If you ___ late, send me a message. (be)", ["are"]),
      qmcq("Which sentence is correct?", [
        "I'll help you if you need it.",
        "I'll help you if you will need it.",
        "I help you will if you need it.",
      ], 0),
    ],
    scenes: [
      sc("Ingrid", "a friend organising a picnic", "to have a backup plan for bad weather",
        "A picnic is planned and the forecast is uncertain.",
        "Agree what happens if the weather turns.",
        "The forecast keeps changing. What is our plan B?", "practical"),
      sc("Cormac", "a colleague running an outdoor event", "to prepare for every weather outcome",
        "A company event is outdoors next week.",
        "Plan for each possible outcome.",
        "Half of this is outside. What do we do if the weather turns?", "planning"),
      sc("Talia", "a trek leader", "to prepare the group for changing conditions",
        "The group is setting off and conditions may change.",
        "Ask and answer about what happens if things change.",
        "Mountain weather is unpredictable. What questions do you have?", "steady"),
      sc("Mr. Anand", "your teacher", "to practise if-sentences",
        "The class is making plans with conditions.",
        "Make plans that depend on a condition.",
        "What will you do if it rains at the weekend?", "encouraging"),
      sc("Ms. Berger", "the examiner", "to check conditional forms",
        "The examiner asks about a plan with a risk.",
        "Use conditional sentences correctly.",
        "Could you tell me about a plan you have and what you will do if it goes wrong?", "neutral"),
    ],
  },

  {
    id: "a2-when-water-boils",
    topic: "things that are always true",
    objectives: [
      "Use the present tense in both halves for things that always happen.",
      "Choose between if and when for general truths.",
    ],
    goal: "Explain how something works, step by step.",
    target: "if and when for general truths",
    correction: "Repeat the sentence with both halves in the present and let the learner explain again.",
    summary: "You learned to describe things that are always true with the present tense in both halves.",
    minutes: 7,
    points: [
      {
        form: "if you heat",
        claims: [
          "For things that are always true, both halves use the present tense.",
          "There is no 'will' here, because the result is not a prediction.",
        ],
        ex: ["If you heat water, it boils.", "If you press this, the machine stops."],
      },
      {
        form: "when it gets",
        claims: [
          "'When' presents the result as regular or certain; 'if' presents it as a condition.",
          "For general truths the two are often interchangeable.",
        ],
        ex: ["When it gets cold, the pipes freeze.", "When you press start, it beeps."],
      },
      {
        form: "it always happens",
        claims: [
          "Words like always, usually and never fit this pattern naturally.",
          "They usually come before most main verbs but after the verb 'be'.",
        ],
        ex: ["It always happens at the same time.", "The light usually comes on first."],
      },
    ],
    ex: [
      fill("If you heat water to a hundred degrees, it ___. (boil)", ["boils"]),
      mcq("Which sentence is correct?", [
        "When it gets cold, the pipes freeze.",
        "When it will get cold, the pipes freeze.",
        "When it gets cold, the pipes will froze.",
      ], 0),
      fill("If you press this button, the machine ___. (stop)", ["stops"]),
      say("the light / usually / come on / first", ["The light usually comes on first."]),
    ],
    open: {
      q: "Explain how something you use every day works. Use two steps that are always true.",
      must: ["if you heat", "when it gets", "it always happens"],
      criteria: "The answer describes a general truth with the present tense in both halves.",
      example: "If you heat the room, it gets warmer. When it gets dark, the light comes on automatically. It always happens at the same time.",
    },
    success: "The learner produces at least two correct general-truth sentences.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "If you mix blue and yellow, you get green.",
        "If you will mix blue and yellow, you get green.",
        "If you mix blue and yellow, you will got green.",
      ], 0),
      qfill("When the machine ___ hot, it stops automatically. (get)", ["gets"]),
      qmcq("Which sentence describes something always true?", [
        "Water freezes at zero degrees.",
        "Water will freeze tomorrow.",
        "Water froze last night.",
      ], 0),
    ],
    scenes: [
      sc("Aurelio", "a neighbour with a broken heater", "to understand how the heating works",
        "A neighbour cannot work out the building's heating.",
        "Explain how it works step by step.",
        "This thing makes no sense to me. How is it supposed to work?", "frustrated"),
      sc("Nkechi", "a new colleague", "to learn how a machine at work operates",
        "A new colleague needs to use a machine safely.",
        "Explain the steps that always happen.",
        "Nobody has shown me this yet. What happens when I switch it on?", "attentive"),
      sc("Ferran", "a host explaining the flat", "to show you how things work in the flat",
        "You are staying somewhere and need to know how things work.",
        "Ask and explain how the appliances work.",
        "A few things here are unusual. Shall I show you?", "friendly"),
      sc("Mrs. Iversen", "your teacher", "to practise general truths",
        "The class is explaining everyday processes.",
        "Explain a process that is always true.",
        "Explain something everyday. What happens if you do the first step?", "encouraging"),
      sc("Mr. Sasaki", "the examiner", "to check general-truth forms",
        "The examiner asks how something works.",
        "Explain with the present tense in both halves.",
        "Could you explain how something in your home works?", "neutral"),
    ],
  },

  {
    id: "a2-as-soon-as-i-arrive",
    topic: "future time links",
    objectives: [
      "Use the present tense after time words about the future.",
      "Say what happens first and what happens after.",
    ],
    goal: "Coordinate plans that depend on when things happen.",
    target: "as soon as, when, before and until with future meaning",
    correction: "Repeat the sentence with the present tense after the time word and let the learner try again.",
    summary: "You learned to use the present tense after as soon as, when, before and until when talking about the future.",
    minutes: 7,
    points: [
      {
        form: "as soon as",
        claims: [
          "After 'as soon as' use the present tense, even for the future.",
          "'As soon as' means immediately after, with no delay.",
        ],
        ex: ["I'll call you as soon as I arrive.", "As soon as she replies, I'll let you know."],
      },
      {
        form: "when I get home",
        claims: [
          "'When' works the same way and never takes 'will' in this pattern.",
          "The other half often uses 'will', but it can also be an instruction: 'Call me when you get home.'",
        ],
        ex: ["I'll do it when I get home.", "When the meeting finishes, I'll send the notes."],
      },
      {
        form: "before I leave",
        claims: [
          "'Before' and 'until' follow the same rule.",
          "'Until' means up to that moment and often goes with a negative.",
        ],
        ex: ["I'll finish it before I leave.", "We won't start until everyone arrives."],
      },
    ],
    ex: [
      fill("I'll call you as soon as I ___. (arrive)", ["arrive"]),
      mcq("Which sentence is correct?", [
        "I'll do it when I get home.",
        "I'll do it when I will get home.",
        "I do it when I will get home.",
      ], 0),
      fill("We won't start ___ everyone arrives.", ["until"]),
      say("I / finish / it / before I leave", ["I'll finish it before I leave.", "I will finish it before I leave."]),
    ],
    open: {
      q: "You are travelling tomorrow. Explain what you will do before you leave, when you arrive and when you get home.",
      must: ["as soon as", "when I get home", "before I leave"],
      criteria: "The answer uses the present tense after each future time expression.",
      example: "I'll check my ticket before I leave. As soon as I arrive, I'll call my friend. I'll unpack when I get home.",
    },
    success: "The learner uses future time links correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'll tell her as soon as she arrives.",
        "I'll tell her as soon as she will arrive.",
        "I tell her as soon as she will arrive.",
      ], 0),
      qfill("Call me when you ___ there. (get)", ["get"]),
      qmcq("Which sentence is correct?", [
        "We won't leave until it stops raining.",
        "We won't leave until it will stop raining.",
        "We don't leave until it will stop raining.",
      ], 0),
    ],
    scenes: [
      sc("Zofia", "a friend meeting you later", "to know when you will arrive",
        "You are travelling and your friend is waiting for news.",
        "Say what you will do and when.",
        "Just tell me the plan so I know when to leave. When will you get in?", "waiting"),
      sc("Rahim", "a colleague depending on your work", "to know when the next step can start",
        "Your colleague cannot start until you finish.",
        "Explain the order of what happens.",
        "I am blocked until your part is done. What is the sequence?", "patient"),
      sc("Elke", "a hotel receptionist", "to arrange your late arrival",
        "You are arriving after reception closes.",
        "Explain when you will arrive and what you will do.",
        "You are arriving late tonight. What time do you expect to get here?", "accommodating"),
      sc("Mr. Otieno", "your teacher", "to practise future time links",
        "The class is sequencing future plans.",
        "Say what happens first and next.",
        "What is the first thing you will do when you get home today?", "encouraging"),
      sc("Ms. Grimaldi", "the examiner", "to check future time links",
        "The examiner asks about your plans for tomorrow.",
        "Sequence them with time links.",
        "Could you tell me what you will do as soon as you get home tomorrow?", "neutral"),
    ],
  },

  {
    id: "a2-maybe-probably-definitely",
    topic: "saying how sure you are",
    objectives: [
      "Say how certain or uncertain you are.",
      "Give an honest answer when you cannot commit.",
    ],
    goal: "Answer a question honestly when you cannot give a firm yes or no.",
    target: "expressing degrees of certainty",
    correction: "Model the phrase with its natural certainty level and let the learner answer again.",
    summary: "You learned to show how sure you are, from 'definitely' down to 'probably not'.",
    minutes: 6,
    points: [
      {
        form: "I'm not sure",
        claims: [
          "'I'm not sure' is an honest answer, not a refusal.",
          "Add 'yet' or a reason to show you will decide later.",
        ],
        ex: ["I'm not sure yet.", "I'm not sure, I need to check first."],
      },
      {
        form: "probably / probably not",
        claims: [
          "'Probably' means likely but not certain.",
          "In the negative, 'probably' comes before 'not': probably not.",
        ],
        ex: ["I'll probably come.", "Probably not this week."],
      },
      {
        form: "almost certainly",
        claims: [
          "'Definitely' and 'almost certainly' are the strongest of these.",
          "They usually come before the main verb, after 'be', and after the first auxiliary or modal.",
        ],
        ex: ["I'll definitely be there.", "She's almost certainly right."],
      },
    ],
    ex: [
      fill("I'm not ___ yet, I need to check my diary.", ["sure"]),
      mcq("Which sentence is correct?", [
        "I'll probably come on Friday.",
        "I'll come probably not on Friday.",
        "Probably I will not come definitely.",
      ], 0),
      say("I / definitely / be / there", ["I'll definitely be there.", "I will definitely be there."]),
    ],
    open: {
      q: "Someone invites you to three events. Answer each one with a different level of certainty.",
      must: ["I'm not sure", "probably not", "almost certainly"],
      criteria: "The answer shows different degrees of certainty using the right expressions.",
      example: "I'll almost certainly come on Friday. Saturday is probably not possible, and I'm not sure about Sunday.",
    },
    success: "The learner expresses three different levels of certainty appropriately.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'll definitely be there.",
        "I'll be definitely there not.",
        "Definitely I will be there probably.",
      ], 0),
      qfill("___ not this week, I'm too busy. (probable)", ["Probably"]),
      qmcq("Which answer is the least certain?", ["I'm not sure yet.", "I'll definitely come.", "I'm almost certain."], 0),
    ],
    scenes: [
      sc("Marta", "a friend planning three events", "to get an answer for each date",
        "A friend needs answers about several invitations.",
        "Answer each one honestly.",
        "Three dates, three questions. Can you give me an answer for each?", "hopeful"),
      sc("Dimitri", "a colleague chasing confirmations", "to fill in a schedule",
        "Your colleague needs commitments for a planning sheet.",
        "Answer with honest certainty levels.",
        "I need something on this sheet even if it is not final. Where are you on each?", "practical"),
      sc("Yuki", "a tour organiser", "to know which activities you will join",
        "The group must confirm which activities they want.",
        "Answer with different levels of certainty.",
        "I need rough numbers for four activities. Which are you thinking about?", "flexible"),
      sc("Mrs. Larsson", "your teacher", "to practise certainty expressions",
        "The class is answering questions with different certainty.",
        "Answer with different levels of certainty.",
        "Will you be here next week? How sure are you?", "encouraging"),
      sc("Mr. Cabrera", "the examiner", "to check certainty expressions",
        "The examiner asks about your future plans.",
        "Show how sure you are of each.",
        "Could you tell me about your plans for next month and how certain they are?", "neutral"),
    ],
  },

  {
    id: "a2-i-came-here-to-learn",
    topic: "explaining why you do something",
    objectives: [
      "Use 'to' plus a verb to explain purpose.",
      "Distinguish a purpose ('to learn') from a cause or reason ('because I wanted to learn').",
    ],
    goal: "Explain your reasons for a big change in your life.",
    target: "to plus verb for purpose",
    correction: "Repeat the purpose phrase and let the learner explain again.",
    summary: "You learned to explain why you do something with 'to' plus a verb.",
    minutes: 7,
    points: [
      {
        form: "to learn English",
        claims: [
          "'To' plus the base verb explains the purpose of an action.",
          "It answers the question why without using 'because'.",
        ],
        ex: ["I came here to learn English.", "She called to ask about the flat."],
      },
      {
        form: "to get better",
        claims: [
          "'In order to' means the same thing and sounds more formal.",
          "'For' is followed by a noun, not by a verb: for a coffee, not for to drink.",
        ],
        ex: ["I practise every day to get better.", "We stopped for a coffee."],
      },
      {
        form: "I came here to",
        claims: [
          "The purpose usually comes after the main action.",
          "Both halves talk about the same person.",
        ],
        ex: ["I came here to find work.", "He moved to be closer to his family."],
      },
    ],
    ex: [
      fill("I came here ___ learn English.", ["to"]),
      mcq("Which sentence is correct?", [
        "She called to ask about the flat.",
        "She called for ask about the flat.",
        "She called to asking about the flat.",
      ], 0),
      fill("We stopped ___ a coffee on the way.", ["for"]),
      say("I / practise / every day / to get better", ["I practise every day to get better."]),
    ],
    open: {
      q: "Explain why you came to your current city or started learning English.",
      must: ["to learn English", "to get better", "I came here to"],
      criteria: "The answer explains purpose with 'to' plus a base verb.",
      example: "I came here to study. I joined an evening course to learn English, and I practise every day to get better.",
    },
    success: "The learner explains purpose with 'to' plus a verb at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "He moved to be closer to his family.",
        "He moved for be closer to his family.",
        "He moved to being closer to his family.",
      ], 0),
      qfill("I went to the shop ___ buy some bread.", ["to"]),
      qmcq("Which sentence explains a purpose?", [
        "I came here to find work.",
        "I came here last year.",
        "I came here with my brother.",
      ], 0),
    ],
    scenes: [
      sc("Larissa", "a new neighbour", "to learn why you moved here",
        "A neighbour is getting to know you.",
        "Explain why you made the change.",
        "You are new to the building, aren't you? What brought you here?", "warm"),
      sc("Mr. Ferreira", "an interviewer", "to understand your motivation",
        "You are explaining a career move in an interview.",
        "Explain your purpose clearly.",
        "You changed direction two years ago. What was behind that?", "professional"),
      sc("Ayaan", "a fellow student abroad", "to compare reasons for coming here",
        "Two people abroad are comparing why they came.",
        "Explain your reasons.",
        "Everyone here has a different story. Why did you come?", "curious"),
      sc("Ms. Karlsson", "your teacher", "to practise purpose clauses",
        "The class is explaining their reasons for studying.",
        "Explain your purpose.",
        "Why are you learning English? What do you want to do with it?", "encouraging"),
      sc("Mr. Adebayo", "the examiner", "to check purpose forms",
        "The examiner asks about a decision you made.",
        "Explain the purpose behind it.",
        "Could you tell me about a decision you made and what you hoped to achieve?", "neutral"),
    ],
  },

  {
    id: "a2-i-want-to-go-i-enjoy-going",
    topic: "which verbs take to and which take -ing",
    objectives: [
      "Use 'to' after want, need, decide and would like.",
      "Use -ing after enjoy, finish and mind.",
    ],
    goal: "Talk about what you want to do and what you enjoy doing.",
    target: "verb plus to versus verb plus -ing",
    correction: "Repeat the phrase with the correct form and let the learner build another.",
    summary: "You learned which common verbs are followed by 'to' and which by -ing.",
    minutes: 7,
    points: [
      {
        form: "I want to",
        claims: [
          "Want, need, decide, hope and would like are followed by 'to' plus the base verb.",
          "'Would like to' is a polite way of saying 'want to'.",
        ],
        ex: ["I want to travel more next year.", "We decided to stay another night."],
      },
      {
        form: "I enjoy",
        claims: [
          "Enjoy, finish, mind and practise are followed by the -ing form.",
          "Say 'I enjoy cooking', not 'I enjoy to cook'.",
        ],
        ex: ["I enjoy cooking at the weekend.", "I don't mind waiting."],
      },
      {
        form: "I'd like to",
        claims: [
          "When another verb follows, 'like' can take either form, but 'would like' takes a to-infinitive.",
          "After a preposition, the verb always takes -ing: good at cooking.",
        ],
        ex: ["I'd like to see that film.", "She's good at explaining things."],
      },
    ],
    ex: [
      fill("I want ___ travel more next year.", ["to"]),
      mcq("Which sentence is correct?", [
        "I enjoy cooking at the weekend.",
        "I enjoy to cook at the weekend.",
        "I enjoy cook at the weekend.",
      ], 0),
      fill("I don't mind ___ for ten minutes. (wait)", ["waiting"]),
      say("I / would like / to see / that film", ["I'd like to see that film.", "I would like to see that film."]),
    ],
    open: {
      q: "Say two things you want to do this year and two things you enjoy doing already.",
      must: ["I want to", "I enjoy", "I'd like to"],
      criteria: "The answer uses 'to' and -ing after the correct verbs.",
      example: "I want to learn to drive this year, and I'd like to travel more. I enjoy cooking and reading.",
    },
    success: "The learner uses both patterns correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We decided to stay another night.",
        "We decided staying another night.",
        "We decided stay another night.",
      ], 0),
      qfill("She's good at ___ things clearly. (explain)", ["explaining"]),
      qmcq("Which sentence is correct?", [
        "I don't mind waiting.",
        "I don't mind to wait.",
        "I don't mind wait.",
      ], 0),
    ],
    scenes: [
      sc("Pia", "a friend making plans for the year", "to compare your hopes for the year",
        "Two friends are talking about the year ahead.",
        "Say what you want to do and enjoy doing.",
        "It is a new year and I have a list. What is on yours?", "upbeat"),
      sc("Nathan", "a manager discussing development", "to understand what you want to work on",
        "A development conversation at work.",
        "Say what you want to do and enjoy.",
        "Let us talk about what you would like to develop. Where do you want to go?", "supportive"),
      sc("Rania", "a language exchange partner", "to plan how you will practise together",
        "Two people are agreeing how to practise together.",
        "Say what you want to practise and enjoy doing.",
        "We can do this any way you like. What do you want to focus on?", "flexible"),
      sc("Mr. Jankowski", "your teacher", "to practise verb patterns",
        "The class is talking about hopes and hobbies.",
        "Use both verb patterns correctly.",
        "What do you want to do this year, and what do you enjoy doing already?", "encouraging"),
      sc("Ms. Oyelaran", "the examiner", "to check verb patterns",
        "The examiner asks about your interests and plans.",
        "Use both patterns accurately.",
        "Could you tell me what you enjoy doing in your free time?", "neutral"),
    ],
  },

  {
    id: "a2-making-a-decision",
    topic: "talking a decision through",
    objectives: [
      "Present both sides of a decision.",
      "Say what will follow from each choice.",
    ],
    goal: "Weigh up a big decision out loud and reach a conclusion.",
    target: "weighing options and announcing a decision",
    correction: "Model the contrast sentence and let the learner continue weighing.",
    summary: "You practised presenting both sides of a decision and announcing your choice.",
    minutes: 6,
    points: [
      {
        form: "on the other hand",
        claims: [
          "'On the one hand ... on the other hand' presents two sides in order.",
          "'On the other hand' can also stand alone to introduce the second side.",
        ],
        ex: ["On the other hand, the rent is much higher.", "On the one hand it pays better."],
      },
      {
        form: "if I do that",
        claims: [
          "'If I do that' names the consequence of one option.",
          "With 'if' plus the present tense, the result usually uses 'will' plus the base verb.",
        ],
        ex: ["If I do that, I'll have to move.", "If I stay, I'll save money."],
      },
      {
        form: "I've decided to",
        claims: [
          "'I've decided to' announces the conclusion after the weighing.",
          "It is followed by 'to' plus the base verb.",
        ],
        ex: ["I've decided to take the job.", "I've decided to wait a month."],
      },
    ],
    ex: [
      fill("On the ___ hand, the rent is much higher there.", ["other"]),
      mcq("Which sentence is correct?", [
        "I've decided to take the job.",
        "I've decided taking the job.",
        "I've decided take the job.",
      ], 0),
      say("if I do that / I / have to / move", ["If I do that, I'll have to move.", "If I do that, I will have to move."]),
    ],
    open: {
      q: "You are thinking about moving to another city. Talk through both sides and say what you have decided.",
      must: ["on the other hand", "if I do that", "I've decided to"],
      criteria: "The answer presents two sides, names a consequence and announces a decision.",
      example: "The job pays more. On the other hand, if I do that, I'll be far from my family. I've decided to stay.",
    },
    success: "The learner presents both sides and announces a clear decision.",
    quiz: [
      qmcq("Which phrase introduces the second side?", [
        "On the other hand",
        "For example",
        "In the end",
      ], 0),
      qfill("I've decided ___ wait another month.", ["to"]),
      qmcq("Which sentence names a consequence?", [
        "If I do that, I'll have to move.",
        "I did that last year.",
        "That is a good idea.",
      ], 0),
    ],
    scenes: [
      sc("Georgios", "a close friend", "to help you think the move through",
        "You are considering moving to another city and need to talk.",
        "Weigh both sides out loud and decide.",
        "You have been going back and forth for weeks. Talk me through it?", "patient"),
      sc("Helena", "your mentor at work", "to help you weigh a career choice",
        "A career decision has to be made this week.",
        "Present both sides and reach a conclusion.",
        "Two paths, one week to decide. What are the arguments?", "thoughtful"),
      sc("Emre", "a friend who moved abroad", "to share experience of the same decision",
        "Someone who made the same move is offering perspective.",
        "Weigh the decision with their input.",
        "I made that exact move five years ago. What is holding you back?", "understanding"),
      sc("Mrs. Petrenko", "your teacher", "to practise weighing options",
        "The class is discussing difficult decisions.",
        "Present both sides and decide.",
        "Think of a hard decision. What are the two sides?", "encouraging"),
      sc("Mr. Almeida", "the examiner", "to check discussion language",
        "The examiner asks about a difficult decision.",
        "Present both sides and conclude.",
        "Could you tell me about a difficult decision and how you thought about it?", "neutral"),
    ],
  },
];
