/** A2 · Ünite 1-2 — Telling Stories · Plans and Predictions (15 ders, elle yazıldı).
 *
 *  A1'de geçmiş tek cümleydi ("I went, I saw"); burada ANLATIYA dönüşüyor: arka
 *  plandaki uzun eylem (past continuous) ile onu kesen kısa eylem (past simple)
 *  birlikte çalışıyor, sonra olaylar sıraya diziliyor. Ünite 2 aynı hareketi
 *  geleceğe uyguluyor: karar (going to), tahmin (will), anlık teklif (I'll) ve
 *  takvime yazılmış randevu (present continuous) — dördü ayrı ayrı öğretiliyor,
 *  çünkü A2'de en sık karışan yer burası.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3 (kullanıcı kararı).
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A2_U1_2: Authored[] = [
  // --- Ünite 1 · Telling Stories ---------------------------------------------
  {
    id: "a2-while-i-was-waiting",
    topic: "saying what was happening at a moment in the past",
    objectives: [
      "Say what was happening at a particular moment in the past.",
      "Make negative sentences with wasn't and weren't.",
    ],
    goal: "Describe what was going on around you at a moment in the past.",
    target: "past continuous: affirmative and negative",
    correction: "Say the full past continuous sentence and let the learner repeat it.",
    summary: "You learned to use was and were with an -ing verb to say what was happening.",
    minutes: 7,
    points: [
      {
        form: "was / were + -ing",
        claims: [
          "Use 'was' with I, he, she and it, and 'were' with you, we and they.",
          "Add -ing to the verb: this says the action was in the middle of happening.",
        ],
        ex: [
          "I was waiting outside the building.",
          "We were talking about the film.",
          "They were working late last night.",
        ],
      },
      {
        form: "wasn't / weren't",
        claims: [
          "For the negative, put 'not' after was or were: wasn't, weren't.",
          "The verb keeps -ing and never changes.",
        ],
        ex: ["The lift wasn't working yesterday.", "We weren't listening to the radio."],
      },
      {
        form: "at that moment",
        claims: [
          "A past time can identify a moment or a period: at seven o'clock, at that moment, all evening.",
          "The time expression can come at the start or at the end of the sentence.",
        ],
        ex: ["At seven o'clock I was cooking dinner.", "She was studying all evening."],
      },
    ],
    ex: [
      fill("At eight o'clock last night we ___ dinner. (have)", ["were having"]),
      mcq("Which sentence is correct?", [
        "They were watching TV when the power went off.",
        "They was watching TV when the power went off.",
        "They were watch TV when the power went off.",
      ], 0),
      fill("The lift ___ working, so we used the stairs. (be not)", ["wasn't", "was not"]),
      say("I / wait / outside / at six", ["I was waiting outside at six.", "At six I was waiting outside."]),
    ],
    open: {
      q: "Think about eight o'clock yesterday evening. Say what you were doing and what the people around you were doing.",
      must: ["I was", "we were"],
      criteria: "The answer uses both I was and we were with an -ing verb to describe actions in progress.",
      example: "At eight o'clock yesterday I was cooking dinner, and we were listening to music.",
    },
    success: "The learner uses both I was and we were with an -ing verb to describe what was happening.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We were talking about you.",
        "We was talking about you.",
        "We were talk about you.",
      ], 0),
      qfill("I ___ waiting for the bus when you called. (be)", ["was"]),
      qmcq("Which sentence is correct?", [
        "The heating wasn't working.",
        "The heating weren't working.",
        "The heating didn't working.",
      ], 0),
    ],
    scenes: [
      sc("Ana", "a neighbour from the flat downstairs", "to find out what happened during the power cut",
        "The lights went out in the whole building last night and everyone is talking about it.",
        "Say what you were doing when the power went off.",
        "The whole building went dark at about nine last night. Where were you at that moment?", "chatty"),
      sc("Tomas", "a colleague who was out of the office", "to hear what the team was doing when the power failed",
        "The office lost power for an hour yesterday afternoon.",
        "Describe what you and the team were doing at that time.",
        "I missed all the drama here yesterday. What was everyone doing when the lights went off?", "amused"),
      sc("Pilar", "the hotel receptionist", "to apologise and hear how the guests were affected",
        "The hotel had no electricity for two hours last night.",
        "Explain what you were doing in your room at the time.",
        "I am so sorry about last night. Were you in your room when it happened?", "apologetic"),
      sc("Mr. Adeyemi", "your teacher", "to practise describing actions in progress",
        "The class is describing where they were during a storm last week.",
        "Describe what you were doing during the storm.",
        "Last Tuesday there was a big storm at six in the evening. What were you doing then?", "warm"),
      sc("Ms. Novak", "the examiner", "to check that you can describe a past moment",
        "The examiner asks about an ordinary evening in your week.",
        "Describe what was happening around you at that time.",
        "Could you tell me what you were doing at this time yesterday?", "neutral"),
    ],
  },

  {
    id: "a2-what-were-you-doing",
    topic: "asking what someone was doing",
    objectives: [
      "Ask questions about what someone was doing in the past.",
      "Give short answers with was and were.",
    ],
    goal: "Ask people where they were and what they were doing at a past moment.",
    target: "past continuous questions and short answers",
    correction: "Repeat the question in the correct word order and invite the learner to ask it again.",
    summary: "You learned to ask questions with was and were and to answer them shortly.",
    minutes: 7,
    points: [
      {
        form: "were you + -ing?",
        claims: [
          "To ask a question, put was or were before the person.",
          "The verb still takes -ing and 'did' is never used here.",
        ],
        ex: ["Were you working late yesterday?", "Was she waiting outside?"],
      },
      {
        form: "what were you doing?",
        claims: [
          "Question words come first: what, where, who, why.",
          "The order is question word, then was or were, then the person.",
        ],
        ex: ["What were you doing at ten o'clock?", "Where were you sitting?"],
      },
      {
        form: "short answers and 'just'",
        claims: [
          "Answer with was or were, not with did: Yes, I was. No, we weren't.",
          "Add 'just' when the action was small or ordinary.",
        ],
        ex: ["Yes, I was.", "No, we weren't.", "I was just reading."],
      },
    ],
    ex: [
      fill("___ you working when I called? (be)", ["Were", "were"]),
      mcq("Which question is correct?", [
        "What were you doing at six?",
        "What you were doing at six?",
        "What did you doing at six?",
      ], 0),
      fill("Where ___ they going when you saw them? (be)", ["were"]),
      say("what / you / do / at nine last night", ["What were you doing at nine last night?"]),
    ],
    open: {
      q: "Ask me three questions about what I was doing yesterday evening.",
      must: ["what were you doing", "were you"],
      criteria: "The answer asks questions with was or were plus an -ing verb, in the correct order.",
      example: "What were you doing at seven? Were you working? Where were you sitting?",
    },
    success: "The learner asks three correct past continuous questions.",
    quiz: [
      qmcq("Which question is correct?", [
        "Were you sleeping when I rang?",
        "Was you sleeping when I rang?",
        "Did you sleeping when I rang?",
      ], 0),
      qfill("___ she waiting for us? (be)", ["Was"]),
      qmcq("Which answer is correct?", ["No, I wasn't.", "No, I didn't.", "No, I not was."], 0),
    ],
    scenes: [
      sc("Ruben", "a friend who could not reach you", "to find out why you did not answer the phone",
        "A friend called you three times last night and you never picked up.",
        "Ask your friend what they were doing too, and explain yourself.",
        "I rang you three times last night! What were you up to?", "teasing"),
      sc("Dana", "a colleague planning the team report", "to find out who was working on what yesterday",
        "The team is reconstructing what everyone did during a busy afternoon.",
        "Ask your colleague questions about the afternoon.",
        "Nobody wrote anything down yesterday. Can you help me work out who was doing what?", "practical"),
      sc("Kwame", "a tour guide", "to find out how the group spent the free afternoon",
        "The group had a free afternoon in the city and is meeting again in the evening.",
        "Ask the others about their afternoon.",
        "So, everyone disappeared for four hours! Where were you all this afternoon?", "cheerful"),
      sc("Mrs. Halvorsen", "your teacher", "to practise forming questions about the past",
        "The class is interviewing each other about last weekend.",
        "Interview your partner about Saturday evening.",
        "Your partner did something on Saturday evening. How can you find out what?", "encouraging"),
      sc("Mr. Laurent", "the examiner", "to check that you can ask questions correctly",
        "The examiner asks you to interview them about their week.",
        "Ask questions about what the examiner was doing.",
        "This time you ask the questions. What would you like to know about my week?", "neutral"),
    ],
  },

  {
    id: "a2-it-happened-while",
    topic: "a long action interrupted by a short one",
    objectives: [
      "Put a long past action and a short past action in one sentence.",
      "Use when before the short action and while before the long one.",
    ],
    goal: "Tell someone about a moment when something interrupted what you were doing.",
    target: "past simple and past continuous together, with when and while",
    correction: "Repeat the sentence with the two verbs in the right tenses and invite the learner to try again.",
    summary: "You learned to combine was doing and did in one sentence with when and while.",
    minutes: 7,
    points: [
      {
        form: "while I was ... , ... happened",
        claims: [
          "The long action in the background takes was or were plus -ing.",
          "The short action that cuts into it takes the past simple.",
        ],
        ex: ["While I was cooking, the phone rang.", "I was reading when the lights went out."],
      },
      {
        form: "when and while",
        claims: [
          "'While' usually introduces the longer background action.",
          "'When' often introduces the shorter event, but it can also introduce a background action.",
          "Use a comma when the time clause comes before the main clause.",
        ],
        ex: ["When it happened, I was standing in the kitchen.", "While we were talking, she arrived."],
      },
      {
        form: "suddenly I heard",
        claims: [
          "Words like suddenly and all of a sudden introduce the surprising short action.",
          "They usually come at the start of the clause.",
        ],
        ex: ["Suddenly I heard a loud noise.", "All of a sudden the door opened."],
      },
    ],
    ex: [
      fill("While I ___ dinner, the doorbell rang. (make)", ["was making"]),
      mcq("Which sentence is correct?", [
        "I was watching TV when the storm started.",
        "I was watch TV when the storm started.",
        "I were watching TV when the storm started.",
      ], 0),
      fill("She was walking home ___ she saw the accident.", ["when"]),
      say("suddenly / I / hear / a loud noise", ["Suddenly I heard a loud noise.", "Suddenly, I heard a loud noise."]),
    ],
    open: {
      q: "Describe an interruption. Use one sentence with while and another sentence with when.",
      must: ["while I was", "when"],
      criteria: "The answer combines past continuous and past simple correctly, using both while and when.",
      example: "While I was driving home, my phone rang. When I heard it, I pulled over safely.",
    },
    success: "The learner combines past continuous and past simple correctly with both while and when.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "While we were eating, the lights went out.",
        "While we were eat, the lights went out.",
        "While we was eating, the lights went out.",
      ], 0),
      qfill("I ___ sleeping when the alarm rang. (be)", ["was"]),
      qmcq("Which sentence is correct?", [
        "I was reading when the phone rang.",
        "I was reading while the phone rang.",
        "I read when the phone was ringing.",
      ], 0),
    ],
    scenes: [
      sc("Sofia", "a friend you meet for coffee", "to hear the story of your strange morning",
        "Something unexpected happened to you this morning and your friend wants the details.",
        "Tell the story of the interruption from beginning to end.",
        "You said your morning was chaos. Go on, what happened?", "curious"),
      sc("Marek", "your manager", "to understand how the meeting was interrupted",
        "Yesterday's meeting stopped halfway through and your manager was not there.",
        "Explain what people were doing and what interrupted them.",
        "I hear the meeting ended early yesterday. What was going on when it stopped?", "calm"),
      sc("Ines", "a fellow traveller at the airport", "to swap stories about delayed journeys",
        "Two travellers are waiting at the gate and comparing bad journeys.",
        "Tell the story of a journey that was interrupted.",
        "My flight was cancelled while I was queueing at the gate. Has anything like that happened to you?", "sympathetic"),
      sc("Dr. Bello", "your teacher", "to practise combining two past tenses",
        "The class is telling short stories about unexpected moments.",
        "Tell a short story with a long action and a short one.",
        "Everyone has one story about being interrupted. What is yours?", "warm"),
      sc("Ms. Fischer", "the examiner", "to check that you can combine the two past tenses",
        "The examiner asks for a short story about an unexpected event.",
        "Tell the story clearly, using both past tenses.",
        "Could you describe a time when something unexpected interrupted your day?", "neutral"),
    ],
  },

  {
    id: "a2-ago-last-yesterday",
    topic: "saying when something happened in the past",
    objectives: [
      "Say how long ago something happened.",
      "Use last and yesterday without extra words.",
    ],
    goal: "Place a past event in time so the other person knows when it was.",
    target: "past time expressions: ago, last, yesterday",
    correction: "Repeat the whole time expression inside a full sentence and let the learner say it again.",
    summary: "You learned to place a past event in time with ago, last and yesterday.",
    minutes: 6,
    points: [
      {
        form: "... ago",
        claims: [
          "Count back from now and put 'ago' at the end: two years ago, ten minutes ago.",
          "'Ago' always follows the length of time, never comes before it.",
        ],
        ex: ["I moved here two years ago.", "She called me ten minutes ago."],
      },
      {
        form: "last week / yesterday",
        claims: [
          "Use 'last' for the nearest past week, month, summer or year.",
          "Do not add 'the' or a preposition before last or yesterday.",
        ],
        ex: ["We met last summer.", "Last week I started a new course.", "I saw him yesterday."],
      },
      {
        form: "about a month ago",
        claims: [
          "Add 'about' or 'around' when you are not sure of the exact time.",
          "This is very common in conversation and sounds more natural than an exact date.",
        ],
        ex: ["I saw him about a month ago.", "It happened around ten years ago."],
      },
    ],
    ex: [
      fill("I started this job two years ___.", ["ago"]),
      mcq("Which sentence is correct?", [
        "I saw her last week.",
        "I saw her the last week.",
        "I saw her in last week.",
      ], 0),
      say("we / move / here / about six months ago", ["We moved here about six months ago."]),
    ],
    open: {
      q: "When did you last travel somewhere new? Say when it was.",
      must: ["ago", "last"],
      criteria: "The answer places the event in the past with ago, last or a similar expression.",
      example: "I went to the coast about three months ago, and before that I travelled last summer.",
    },
    success: "The learner uses at least two different past time expressions correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "He left ten minutes ago.",
        "He left ago ten minutes.",
        "He left before ten minutes.",
      ], 0),
      qfill("We went there ___ summer.", ["last"]),
      qmcq("Which sentence is correct?", [
        "I finished school about five years ago.",
        "I finished school about five years before.",
        "I finished school since five years.",
      ], 0),
    ],
    scenes: [
      sc("Leila", "a neighbour you rarely see", "to catch up on what you have both been doing",
        "Two neighbours meet in the hallway after a long time.",
        "Say when the things in your life happened.",
        "I feel like I never see you any more! When did you actually move into this building?", "friendly"),
      sc("Oscar", "a new colleague", "to learn how long people have been at the company",
        "A new colleague is getting to know the team over lunch.",
        "Say when you joined and when things changed.",
        "Everyone here seems to know everyone. When did you join the company?", "open"),
      sc("Nadia", "someone you meet at a hostel", "to swap travel histories",
        "Two travellers compare the trips they have taken.",
        "Say when you went to each place.",
        "You have been to a lot of places! When was your last big trip?", "relaxed"),
      sc("Mr. Okonjo", "your teacher", "to practise past time expressions",
        "The class is making a timeline of important moments.",
        "Say when three things in your life happened.",
        "Let us build a timeline together. When did something important happen in your life?", "warm"),
      sc("Mrs. Sandoval", "the examiner", "to check that you can place events in time",
        "The examiner asks about recent changes in your life.",
        "Say clearly when each thing happened.",
        "Could you tell me about something that changed in your life, and when it happened?", "neutral"),
    ],
  },

  {
    id: "a2-first-then-after-that",
    topic: "putting the events of a story in order",
    objectives: [
      "Open a story and move it forward step by step.",
      "Close a story with the result.",
    ],
    goal: "Tell a short story so the listener can follow the order of events.",
    target: "sequencing expressions: first of all, after that, in the end",
    correction: "Repeat the sentence with the sequencing expression at the front and let the learner continue.",
    summary: "You learned to order the events of a story from the first moment to the result.",
    minutes: 6,
    points: [
      {
        form: "first of all / to start with",
        claims: [
          "Open the story with the first event so the listener knows where it begins.",
          "These expressions come at the start of the sentence, followed by a comma.",
        ],
        ex: ["First of all, we missed the train.", "To start with, nobody answered the door."],
      },
      {
        form: "then / after that / a bit later",
        claims: [
          "Move the story forward one step at a time with then, after that or a bit later.",
          "'After that' looks back at the event you have just told.",
        ],
        ex: ["Then we waited for an hour.", "After that, the rain started."],
      },
      {
        form: "in the end / finally",
        claims: [
          "Close the story with the result using in the end or finally.",
          "'In the end' means after everything that happened, this was the result.",
        ],
        ex: ["In the end we took a taxi.", "Finally, everything was fine."],
      },
    ],
    ex: [
      fill("___ of all, I forgot my keys at home.", ["First"]),
      mcq("Which expression closes a story?", ["In the end", "First of all", "To start with"], 0),
      say("after that / we / go / to the station", ["After that we went to the station.", "After that, we went to the station."]),
    ],
    open: {
      q: "Tell me about a day when small things went wrong. Give the story a clear beginning, middle and end.",
      must: ["first of all", "after that", "in the end"],
      criteria: "The answer uses first of all, after that and in the end to organise the events clearly.",
      example: "First of all, I woke up late. After that, the bus did not come. In the end, I walked to work.",
    },
    success: "The learner tells an ordered story using first of all, after that and in the end correctly.",
    quiz: [
      qmcq("Which expression starts a story?", ["First of all", "In the end", "Finally"], 0),
      qfill("___ that, we went home.", ["After"]),
      qmcq("Which sentence is correct?", [
        "In the end, we found the keys.",
        "In the end, we finding the keys.",
        "In end, we found the keys.",
      ], 0),
    ],
    scenes: [
      sc("Bruno", "a friend who was not there", "to hear the whole story in order",
        "You had a small disaster on the way home and your friend wants the full story.",
        "Tell the story from the first moment to the result.",
        "You promised me the full story of last night. Where does it start?", "eager"),
      sc("Hana", "a colleague writing an incident note", "to record the events in the right order",
        "Something went wrong with a delivery and someone has to write it down clearly.",
        "Describe what happened, step by step.",
        "I have to write this up properly. Can you take me through it from the beginning?", "focused"),
      sc("Diego", "a fellow guest at breakfast", "to hear about your difficult journey",
        "Your journey to the hotel took much longer than planned.",
        "Tell the story of the journey in order.",
        "You arrived very late last night. What went wrong on the way?", "sympathetic"),
      sc("Ms. Grant", "your teacher", "to practise ordering events",
        "The class is retelling short everyday stories.",
        "Retell a small everyday disaster in order.",
        "Small disasters make the best stories. What is yours, and how did it start?", "encouraging"),
      sc("Mr. Yilmaz", "the examiner", "to check that you can order events clearly",
        "The examiner asks for a short story about a difficult day.",
        "Tell the story with a clear beginning, middle and end.",
        "Could you tell me about a day when several things went wrong?", "neutral"),
    ],
  },

  {
    id: "a2-my-best-holiday",
    topic: "telling the story of a past trip",
    objectives: [
      "Say where you went and where you stayed.",
      "Give your feeling about a trip and the moment you remember most.",
    ],
    goal: "Tell someone the story of the best trip you have taken.",
    target: "telling the full story of a past trip",
    correction: "Model the sentence about the trip in the past and let the learner carry on with the story.",
    summary: "You practised telling the whole story of a trip: where, where you stayed and how it felt.",
    minutes: 6,
    points: [
      {
        form: "we went to / we stayed in",
        claims: [
          "Say the place first and then where you stayed.",
          "Both verbs are in the past simple because the trip is finished.",
        ],
        ex: ["We went to the mountains last spring.", "We stayed in a small hotel near the beach."],
      },
      {
        form: "it was amazing",
        claims: [
          "Give your feeling with 'it was' and a strong adjective: amazing, awful, unforgettable.",
          "You can add 'but' to give the other side of the story.",
        ],
        ex: ["The food was amazing.", "The weather was awful, but we had a great time."],
      },
      {
        form: "I'll never forget",
        claims: [
          "Use 'I'll never forget' to introduce a moment or experience that you still remember clearly.",
          "It can be followed by a noun or by a verb ending in -ing.",
        ],
        ex: ["I'll never forget that evening.", "I'll never forget watching the sunrise."],
      },
    ],
    ex: [
      fill("We ___ in a small hotel by the sea. (stay)", ["stayed"]),
      mcq("Which sentence closes a story about a trip?", [
        "I'll never forget that day.",
        "We are going there next year.",
        "I usually travel in summer.",
      ], 0),
      say("it / be / amazing", ["It was amazing.", "It was amazing!"]),
    ],
    open: {
      q: "Tell me about your best trip. Say where you went, where you stayed and how you felt.",
      must: ["went", "stayed", "it was"],
      criteria: "The answer describes a past trip with a destination, accommodation and personal reaction.",
      example: "I went to the north for a week. I stayed in a small house near a lake. It was amazing.",
    },
    success: "The learner tells the story of a trip with a place, a stay and a personal reaction.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We stayed in a small hotel.",
        "We stay in a small hotel last year.",
        "We were stay in a small hotel.",
      ], 0),
      qfill("It ___ amazing. (be)", ["was"]),
      qmcq("Which sentence is correct?", [
        "I'll never forget that evening.",
        "I'll never forgetting that evening.",
        "I'll never forgot that evening.",
      ], 0),
    ],
    scenes: [
      sc("Marta", "a friend planning her own holiday", "to get ideas from your best trip",
        "A friend is deciding where to go this year and wants to hear about your favourite trip.",
        "Tell the story of your best trip.",
        "I have no idea where to go this year. What was the best trip you have ever taken?", "excited"),
      sc("Peter", "a colleague back from leave", "to swap holiday stories after the summer",
        "Two colleagues are catching up on the first morning back at work.",
        "Tell your holiday story and ask about theirs.",
        "Everyone is showing photos this morning. How was your holiday?", "relaxed"),
      sc("Aiko", "a guest at the same hotel", "to compare travel experiences",
        "Two travellers are talking on the hotel terrace in the evening.",
        "Describe the best trip you have taken.",
        "I love hearing where people have been. What is the best place you have travelled to?", "warm"),
      sc("Mr. Duarte", "your teacher", "to practise telling a longer story",
        "The class is presenting a favourite memory.",
        "Tell the class about your best trip.",
        "Today everyone shares one good memory. What is your best trip?", "encouraging"),
      sc("Ms. Bright", "the examiner", "to check that you can tell an extended story",
        "The examiner asks about a memorable journey.",
        "Describe the trip fully, with a beginning and an end.",
        "Could you tell me about a trip that you remember well?", "neutral"),
    ],
  },

  {
    id: "a2-two-photos-one-story",
    topic: "describing two photos and the story between them",
    objectives: [
      "Introduce a picture before describing it.",
      "Link two moments in time with a background action.",
    ],
    goal: "Describe two pictures from the same day and tell the story between them.",
    target: "comparing two photos and telling the story behind them",
    correction: "Model the sentence that introduces the picture and let the learner describe it again.",
    summary: "You practised describing two pictures and linking them into one story.",
    minutes: 6,
    points: [
      {
        form: "in the first photo",
        claims: [
          "Introduce each picture before you describe what is in it.",
          "Use 'the second one' instead of repeating the word photo.",
        ],
        ex: [
          "In the first photo, we are standing outside a station.",
          "In the second one, everybody is laughing.",
        ],
      },
      {
        form: "while we were",
        claims: [
          "Say what was happening around the moment the picture was taken.",
          "This uses was or were with an -ing verb, because the action was in progress.",
        ],
        ex: ["While we were waiting, someone took this photo.", "While we were walking, it started to rain."],
      },
      {
        form: "after that",
        claims: [
          "Link the two moments so the listener sees the order.",
          "'After that' tells the listener the second picture came later.",
        ],
        ex: ["After that, we found a cafe and sat down.", "After that the weather changed completely."],
      },
    ],
    ex: [
      fill("In the ___ photo, we are standing outside the station.", ["first"]),
      mcq("Which sentence describes what was happening?", [
        "While we were waiting, it started to rain.",
        "We wait for the bus every day.",
        "We will wait for the bus.",
      ], 0),
      say("after that / we / find / a small cafe", ["After that we found a small cafe.", "After that, we found a small cafe."]),
    ],
    open: {
      q: "Think of two photos from the same day. Describe both and say what happened between them.",
      must: ["in the first photo", "after that"],
      criteria: "The answer describes two moments and links them clearly in time.",
      example: "In the first photo we are waiting at the airport. After that we landed, and in the second one we are eating outside.",
    },
    success: "The learner describes two moments and connects them with a time link.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "While we were walking, it started to rain.",
        "While we walking, it started to rain.",
        "While we were walk, it started to rain.",
      ], 0),
      qfill("___ that, we went to the beach.", ["After"]),
      qmcq("Which sentence introduces a picture?", [
        "In the second one, we are at the beach.",
        "We go to the beach every summer.",
        "We will go to the beach.",
      ], 0),
    ],
    scenes: [
      sc("Camille", "a friend looking through your photos", "to hear the story behind two pictures",
        "A friend is scrolling through the photos from your last trip.",
        "Describe two photos and the story between them.",
        "These two pictures look like the same day. What was going on here?", "curious"),
      sc("Stefan", "a colleague making the team slideshow", "to caption the pictures correctly",
        "The team is putting photos from an event into a short presentation.",
        "Describe two photos so they can be captioned.",
        "I need a line for each picture. Can you tell me what is happening in these two?", "practical"),
      sc("Rosa", "another guest sharing travel photos", "to swap the stories behind the pictures",
        "Two travellers are showing each other pictures from their journeys.",
        "Describe two of your pictures and what happened between them.",
        "That looks like a good day. What happened between these two shots?", "warm"),
      sc("Mrs. Chen", "your teacher", "to practise describing and comparing pictures",
        "The class is doing a picture-description task.",
        "Describe the two pictures and link them.",
        "Look at these two moments from one day. Which one comes first, and why do you think so?", "encouraging"),
      sc("Mr. Ferreira", "the examiner", "to check that you can compare two pictures",
        "The examiner shows you two photographs from the same occasion.",
        "Describe both and explain the connection.",
        "Could you describe these two photographs and tell me what happened in between?", "neutral"),
    ],
  },

  // --- Ünite 2 · Plans and Predictions ---------------------------------------
  {
    id: "a2-im-going-to-move",
    topic: "talking about decisions you have already made",
    objectives: [
      "Use 'be going to' for a plan you have already decided.",
      "Keep the verb after 'going to' in its base form.",
    ],
    goal: "Tell someone about a decision you have already made about the future.",
    target: "'be going to' for plans and intentions",
    correction: "Say the full 'going to' sentence and let the learner repeat it.",
    summary: "You learned to use am, is and are with 'going to' for plans you have decided.",
    minutes: 7,
    points: [
      {
        form: "be going to + verb",
        claims: [
          "Use am, is or are with 'going to' and then the base verb.",
          "This form says the decision is already made, not that you are thinking about it.",
        ],
        ex: ["I'm going to move to another city.", "We're going to buy a bigger table."],
      },
      {
        form: "she's going to",
        claims: [
          "Only am, is and are change with the person; 'going to' never changes.",
          "The verb after 'going to' never takes -s or -ing.",
        ],
        ex: ["She's going to start a new job.", "They're going to travel in July."],
      },
      {
        form: "next month, soon",
        claims: [
          "A future time makes the plan clearer: next month, in the summer, soon.",
          "The time usually comes at the end of the sentence.",
        ],
        ex: ["We're going to redecorate next month.", "I'm going to call her soon."],
      },
    ],
    ex: [
      fill("I ___ going to look for a new flat. (be)", ["am", "'m"]),
      mcq("Which sentence is correct?", [
        "She's going to start a new job.",
        "She's going to starts a new job.",
        "She going to start a new job.",
      ], 0),
      fill("We ___ going to buy a car next year. (be)", ["are", "'re"]),
      say("they / going to / travel / in July", ["They're going to travel in July.", "They are going to travel in July."]),
    ],
    open: {
      q: "Tell me about two things you have already decided to do this year: one by yourself and one with someone else.",
      must: ["I'm going to", "we're going to"],
      criteria: "The answer uses going to with a base verb to describe two decided plans.",
      example: "I'm going to start a course in the autumn, and we're going to move closer to the centre.",
    },
    success: "The learner describes two decided plans using I'm going to and we're going to correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We're going to paint the kitchen.",
        "We're going to painting the kitchen.",
        "We going to paint the kitchen.",
      ], 0),
      qfill("She ___ going to call you later. (be)", ["is"]),
      qmcq("Which sentence talks about a plan?", [
        "I'm going to look for a new job.",
        "I looked for a new job.",
        "I look for a new job every year.",
      ], 0),
    ],
    scenes: [
      sc("Elif", "a close friend", "to hear about the big decision you have made",
        "You have decided something important and your friend does not know yet.",
        "Explain your decision and what you are going to do.",
        "You said you had news. What have you decided?", "supportive"),
      sc("Andres", "your team leader", "to understand your plans for the coming months",
        "The team is discussing what each person will take on this year.",
        "Say what you are going to do and when.",
        "Before we plan the quarter, what do you want to take on this year?", "attentive"),
      sc("Yuki", "a traveller you meet on the train", "to find out where you are heading next",
        "Two travellers are talking about the rest of their journeys.",
        "Say where you are going to go and what you are going to do there.",
        "This is my last stop. Where are you heading after this?", "friendly"),
      sc("Mr. Novotny", "your teacher", "to practise talking about decided plans",
        "The class is talking about goals for the coming year.",
        "Describe two plans you have decided.",
        "Everyone has one thing they have already decided for this year. What is yours?", "encouraging"),
      sc("Ms. Alvarez", "the examiner", "to check that you can describe future plans",
        "The examiner asks about your plans for the near future.",
        "Describe your plans clearly.",
        "Could you tell me about a plan you have already made?", "neutral"),
    ],
  },

  {
    id: "a2-are-you-going-to-come",
    topic: "asking about plans and saying what you will not do",
    objectives: [
      "Ask questions with 'going to' in the correct order.",
      "Make negative sentences with 'not going to'.",
    ],
    goal: "Find out other people's plans and say what you are not going to do.",
    target: "'be going to': questions and negatives",
    correction: "Repeat the question in the correct order and invite the learner to ask it again.",
    summary: "You learned to ask about plans and to say what you are not going to do.",
    minutes: 7,
    points: [
      {
        form: "are you going to ...?",
        claims: [
          "To ask, put am, is or are before the person.",
          "Never use 'do' or 'does' with 'going to'.",
        ],
        ex: ["Are you going to come on Saturday?", "Is he going to bring the car?"],
      },
      {
        form: "I'm not going to",
        claims: [
          "For the negative, put 'not' straight after am, is or are.",
          "The short forms are I'm not, isn't and aren't.",
        ],
        ex: ["I'm not going to stay long.", "We aren't going to book anything yet."],
      },
      {
        form: "what are you going to ...?",
        claims: [
          "Question words come first, then am, is or are, then the person.",
          "With 'who' as the subject, no extra word is needed: who is going to drive?",
        ],
        ex: ["What are you going to wear?", "Who is going to drive?"],
      },
    ],
    ex: [
      fill("___ you going to come to the party? (be)", ["Are", "are"]),
      mcq("Which question is correct?", [
        "What are you going to do tonight?",
        "What you are going to do tonight?",
        "What do you going to do tonight?",
      ], 0),
      fill("I'm ___ going to stay very long.", ["not"]),
      say("is / she / going to / bring / the car", ["Is she going to bring the car?"]),
    ],
    open: {
      q: "Ask me two questions about my plans for next weekend. Then say one thing you are not going to do.",
      must: ["are you going to", "what are you going to", "not going to"],
      criteria: "The answer forms going to questions correctly and includes one negative plan.",
      example: "What are you going to do on Saturday? Are you going to see anyone? I'm not going to stay at home.",
    },
    success: "The learner asks two correct going to questions and produces one correct negative sentence.",
    quiz: [
      qmcq("Which question is correct?", [
        "Is he going to join us?",
        "Does he going to join us?",
        "Is he going to joins us?",
      ], 0),
      qfill("___ they going to help? (be)", ["Are"]),
      qmcq("Which sentence is negative?", [
        "I'm not going to argue.",
        "I'm going to argue.",
        "Am I going to argue?",
      ], 0),
    ],
    scenes: [
      sc("Nour", "a friend organising a get-together", "to find out who is coming and what they are bringing",
        "A friend is putting together a small party and needs to know the details.",
        "Ask about the arrangements and say what you are and are not going to do.",
        "I am trying to work out numbers for Saturday. Do you have any questions before you decide?", "busy"),
      sc("Gareth", "a colleague planning the away day", "to collect everyone's intentions",
        "The team away day needs a rough plan and nobody has answered yet.",
        "Ask your colleague about the plans for the day.",
        "The away day is next month and nothing is fixed. What do you want to know?", "organised"),
      sc("Sanne", "a fellow traveller sharing a taxi", "to agree what each of you will do on arrival",
        "Two travellers are heading to the same town and comparing plans.",
        "Ask about their plans and explain yours.",
        "We are going to the same town but I have no plan at all. What about you?", "easy-going"),
      sc("Mr. Haddad", "your teacher", "to practise questions about future plans",
        "The class is interviewing each other about the holidays.",
        "Interview your partner about their plans.",
        "Find out three things about your partner's holiday. What will you ask first?", "encouraging"),
      sc("Mrs. Petrova", "the examiner", "to check that you can ask about plans",
        "The examiner asks you to interview them about the coming month.",
        "Ask clear questions about their plans.",
        "This time you interview me about next month. What would you like to know?", "neutral"),
    ],
  },

  {
    id: "a2-i-think-it-will-rain",
    topic: "making predictions about the future",
    objectives: [
      "Use will to say what you think will happen.",
      "Soften a prediction with 'I think' or 'probably'.",
    ],
    goal: "Say what you think will happen in the future and how sure you are.",
    target: "will for predictions",
    correction: "Repeat the prediction with will plus the base verb and let the learner say it again.",
    summary: "You learned to make predictions with will, won't and words like probably.",
    minutes: 7,
    points: [
      {
        form: "will + verb",
        claims: [
          "Use 'will' plus the base verb for what you think or guess about the future.",
          "'Will' is the same for every person: I will, she will, they will.",
        ],
        ex: ["It will rain tomorrow.", "The film will finish at ten."],
      },
      {
        form: "I think it will / it will probably",
        claims: [
          "Soften a guess with 'I think' at the start or 'probably' after will.",
          "'Probably' goes between will and the verb.",
        ],
        ex: ["I think it will be cold tonight.", "It will probably take an hour."],
      },
      {
        form: "it won't",
        claims: [
          "'Won't' is the short form of 'will not' and is very common in speech.",
          "The base verb follows won't with no changes.",
        ],
        ex: ["It won't be easy.", "They won't arrive before six."],
      },
    ],
    ex: [
      fill("I think it ___ rain this afternoon. (will)", ["will", "'ll"]),
      mcq("Which sentence is correct?", [
        "It will probably be cold tonight.",
        "It will probably is cold tonight.",
        "It will probably to be cold tonight.",
      ], 0),
      fill("Don't worry, it ___ take long. (will not)", ["won't", "will not"]),
      say("I think / she / will / like it", ["I think she will like it.", "I think she'll like it."]),
    ],
    open: {
      q: "What do you think your city will be like in ten years?",
      must: ["I think it will", "it will probably"],
      criteria: "The answer makes predictions with will or won't and says how sure the speaker is.",
      example: "I think it will be much bigger. It will probably have more traffic, but it won't lose its parks.",
    },
    success: "The learner makes at least two predictions using will or won't.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I think it will be sunny.",
        "I think it will to be sunny.",
        "I think it will sunny.",
      ], 0),
      qfill("It ___ be easy, but we can try. (will not)", ["won't"]),
      qmcq("Which sentence is a prediction?", [
        "The team will probably win.",
        "The team won yesterday.",
        "The team is winning now.",
      ], 0),
    ],
    scenes: [
      sc("Ivan", "a neighbour looking at the sky", "to guess what the weather will do",
        "The weather is changing and you are both deciding whether to go out.",
        "Say what you think the weather will do.",
        "Those clouds look serious. Do we go now or wait?", "doubtful"),
      sc("Priya", "a colleague reviewing next year's plan", "to hear your predictions about the business",
        "The team is guessing how the coming year will go.",
        "Predict what will and will not happen.",
        "Nobody really knows how next year will go. What is your guess?", "thoughtful"),
      sc("Mateo", "a guide preparing the group", "to warn the group about the conditions ahead",
        "The group is about to set off and the weather is uncertain.",
        "Predict the conditions and what the group will need.",
        "The mountain weather changes fast. What do you think we should expect today?", "practical"),
      sc("Dr. Sharma", "your teacher", "to practise talking about the future",
        "The class is discussing how life will change in ten years.",
        "Make predictions about the future.",
        "In ten years, what do you think will be completely different?", "curious"),
      sc("Mr. Kaufmann", "the examiner", "to check that you can make predictions",
        "The examiner asks how things will change in the coming years.",
        "Make clear predictions and say how sure you are.",
        "Could you tell me how you think your town will change in the next ten years?", "neutral"),
    ],
  },

  {
    id: "a2-tomorrow-next-week",
    topic: "saying when something will happen",
    objectives: [
      "Use next and in with future times correctly.",
      "Point to a part of the period you are already in.",
    ],
    goal: "Say clearly when something in the future will happen.",
    target: "future time expressions",
    correction: "Repeat the whole time expression inside a full sentence and let the learner say it again.",
    summary: "You learned to say when something will happen with next, in and later this.",
    minutes: 6,
    points: [
      {
        form: "tomorrow / next week",
        claims: [
          "Use 'next' with the coming week, month or year.",
          "Do not add 'the' or a preposition before next or tomorrow.",
        ],
        ex: ["I'll call you tomorrow.", "We're moving next week."],
      },
      {
        form: "in two weeks",
        claims: [
          "'In' plus a length of time counts forward from now.",
          "'In ten minutes' means ten minutes from now, not during ten minutes.",
        ],
        ex: ["The train leaves in ten minutes.", "She'll be back in two weeks."],
      },
      {
        form: "later this year",
        claims: [
          "Use 'later this' to point to a later part of the period you are currently in.",
          "'At the end of the month' is another useful expression for locating a future event.",
        ],
        ex: ["We'll decide later this year.", "I'm free at the end of the month."],
      },
    ],
    ex: [
      fill("She is starting the course ___ week.", ["next"]),
      mcq("Which sentence is correct?", [
        "The bus leaves in ten minutes.",
        "The bus leaves after ten minutes.",
        "The bus leaves since ten minutes.",
      ], 0),
      say("we / finish / it / later this year", ["We will finish it later this year.", "We'll finish it later this year."]),
    ],
    open: {
      q: "What are you doing later this week and next week? Say when.",
      must: ["next week", "later this"],
      criteria: "The answer places future events in time with clear expressions.",
      example: "I'm seeing a friend later this week, and next week I'm starting a new project.",
    },
    success: "The learner uses at least two different future time expressions correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We'll meet next month.",
        "We'll meet the next month.",
        "We'll meet in next month.",
      ], 0),
      qfill("The film starts ___ twenty minutes.", ["in"]),
      qmcq("Which expression means two weeks from now?", ["in two weeks", "two weeks ago", "last two weeks"], 0),
    ],
    scenes: [
      sc("Greta", "a friend with a long to-do list", "to agree when each job will get done",
        "You share a flat and several small jobs are waiting.",
        "Say when each thing will happen.",
        "We have four things on this list and none of them have a date. Where do we start?", "practical"),
      sc("Felipe", "a colleague scheduling the work", "to fix a date for each task",
        "The team has to put dates next to a list of tasks.",
        "Say when you can do each task.",
        "I need a date for each of these. When can you take the first one?", "organised"),
      sc("Amara", "the tour coordinator", "to confirm when the group activities happen",
        "The group is planning the rest of the week's activities.",
        "Ask and say when things will happen.",
        "We still have three free days to fill. When would you like to do what?", "helpful"),
      sc("Mr. Lindqvist", "your teacher", "to practise future time expressions",
        "The class is filling in a diary for the coming month.",
        "Say when three things in your diary will happen.",
        "Look at the coming month. What is happening, and when?", "encouraging"),
      sc("Ms. Rahman", "the examiner", "to check that you can talk about future times",
        "The examiner asks about your coming week.",
        "Say clearly when each thing will happen.",
        "Could you tell me what you have planned for the coming weeks?", "neutral"),
    ],
  },

  {
    id: "a2-ill-get-it",
    topic: "offering help and deciding at the moment of speaking",
    objectives: [
      "Offer help with I'll and shall I.",
      "Reassure someone before you offer.",
    ],
    goal: "Offer to help someone the moment you see they need it.",
    target: "will for offers and instant decisions",
    correction: "Model the offer with I'll or shall I and let the learner make the offer again.",
    summary: "You learned to offer help with I'll and shall I as you decide to do it.",
    minutes: 7,
    points: [
      {
        form: "I'll + verb",
        claims: [
          "Use 'I'll' when you decide to do something as you are speaking.",
          "This is not a plan you made before; you decide it in the moment.",
        ],
        ex: ["I'll get it.", "I'll do the washing up."],
      },
      {
        form: "shall I ...?",
        claims: [
          "In everyday offers, use 'shall I' or 'shall we' followed by the base verb.",
          "'Shall I' asks whether the other person wants you to help.",
        ],
        ex: ["Shall I help you with that?", "Shall I call a taxi?"],
      },
      {
        form: "don't worry, I'll ...",
        claims: [
          "Reassure the other person first, then make the offer.",
          "'Don't worry' and 'leave it to me' both sound friendly and natural.",
        ],
        ex: ["Don't worry, I'll take care of it.", "Don't worry about the bill, I'll pay."],
      },
    ],
    ex: [
      fill("That's the door. ___ get it! (I will)", ["I'll", "I will"]),
      mcq("Which sentence offers help?", [
        "Shall I carry that for you?",
        "I carried that for you.",
        "I'm carrying that for you.",
      ], 0),
      fill("___ worry, I'll fix it. (do not)", ["Don't", "Do not"]),
      say("I / will / do / it", ["I'll do it.", "I will do it."]),
    ],
    open: {
      q: "Your friend is carrying too many bags. Offer to help in two different ways.",
      must: ["I'll", "shall I"],
      criteria: "The answer offers help with I'll or shall I, using the base verb.",
      example: "Shall I take one of those? Don't worry, I'll carry the heavy one.",
    },
    success: "The learner makes at least two offers using I'll or shall I.",
    quiz: [
      qmcq("Which sentence is an offer?", [
        "Shall I open the window?",
        "I opened the window.",
        "I open the window every morning.",
      ], 0),
      qfill("The phone is ringing. ___ answer it. (I will)", ["I'll"]),
      qmcq("Which sentence is correct?", [
        "Don't worry, I'll sort it out.",
        "Don't worry, I'll to sort it out.",
        "Don't worry, I'll sorting it out.",
      ], 0),
    ],
    scenes: [
      sc("Bea", "a neighbour with her hands full", "to get through the door with the shopping",
        "Your neighbour is struggling with bags and keys in the hallway.",
        "Offer help in more than one way.",
        "Oh, this is impossible with two bags and a key. Could you give me a hand?", "flustered"),
      sc("Karim", "a colleague preparing for a visit", "to get the room ready before the guests arrive",
        "Visitors are arriving in fifteen minutes and several things are not ready.",
        "Offer to take some of the jobs.",
        "The guests are here in fifteen minutes and nothing is ready. What can you take?", "rushed"),
      sc("Lucia", "a traveller who has dropped her things", "to gather everything before the bus leaves",
        "Someone's bag has opened at the bus stop and the bus is coming.",
        "Offer help quickly and clearly.",
        "Oh no, everything is on the floor and that is my bus! Can you help?", "panicked"),
      sc("Mrs. Owusu", "your teacher", "to practise making offers",
        "The class is practising polite offers in everyday situations.",
        "Make offers in two different situations.",
        "Someone in the room needs help right now. What do you say?", "encouraging"),
      sc("Mr. Sorensen", "the examiner", "to check that you can offer help naturally",
        "The examiner describes a small problem and waits for your reaction.",
        "Offer help in a natural way.",
        "Imagine I am carrying a heavy box and I drop my keys. What would you say?", "neutral"),
    ],
  },

  {
    id: "a2-im-meeting-sam-at-six",
    topic: "talking about fixed arrangements",
    objectives: [
      "Use am, is or are plus -ing for arrangements that are already fixed.",
      "Ask about someone's diary with the same form.",
    ],
    goal: "Talk about what is already in your diary for the coming days.",
    target: "present continuous for fixed future arrangements",
    correction: "Repeat the arrangement with am, is or are plus -ing and let the learner say it again.",
    summary: "You learned to talk about fixed arrangements with am, is or are plus an -ing verb.",
    minutes: 7,
    points: [
      {
        form: "I'm meeting / we're leaving",
        claims: [
          "Use am, is or are plus -ing for something already fixed with another person.",
          "A time or a day is usually included, because the arrangement is real.",
        ],
        ex: ["I'm meeting Sam at six.", "We're leaving at half past seven."],
      },
      {
        form: "what are you doing on Friday?",
        claims: [
          "The same form asks what is already in someone's diary.",
          "'Are you doing anything?' is the natural way to check if someone is free.",
        ],
        ex: ["What are you doing on Friday?", "Are you doing anything on Sunday?"],
      },
      {
        form: "arrangement or intention",
        claims: [
          "Use the present continuous when you want to emphasise that an arrangement has fixed details.",
          "Use 'going to' when you want to emphasise an intention or plan; the time may already be known.",
        ],
        ex: ["I'm seeing the doctor at four.", "I'm going to see a doctor soon."],
      },
    ],
    ex: [
      fill("I ___ meeting Sam at six. (be)", ["am", "'m"]),
      mcq("Which sentence is a fixed arrangement?", [
        "We're leaving at seven tomorrow.",
        "We leave at seven every day.",
        "We left at seven yesterday.",
      ], 0),
      fill("What ___ you doing on Friday evening? (be)", ["are"]),
      say("we / leave / at half past eight", ["We're leaving at half past eight.", "We are leaving at half past eight."]),
    ],
    open: {
      q: "Say when you are meeting someone this week, and describe one arrangement you have made with another person.",
      must: ["I'm meeting", "we're"],
      criteria: "The answer gives two fixed arrangements using am, is or are plus -ing and includes their times.",
      example: "I'm meeting a friend at seven on Wednesday, and we're leaving for the coast early on Saturday.",
    },
    success: "The learner describes at least two fixed arrangements with a time.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'm seeing the dentist at four.",
        "I'm see the dentist at four.",
        "I seeing the dentist at four.",
      ], 0),
      qfill("What ___ you doing tonight? (be)", ["are"]),
      qmcq("Which sentence is an arrangement with another person?", [
        "We're meeting at the station at six.",
        "We meet at the station every Monday.",
        "We met at the station yesterday.",
      ], 0),
    ],
    scenes: [
      sc("Jonah", "a friend trying to find a free evening", "to compare diaries and find a gap",
        "Two friends are looking at their weeks to find an evening that works.",
        "Say what is already fixed in your week.",
        "My week is a disaster. What does yours look like?", "hopeful"),
      sc("Rita", "a colleague booking the meeting room", "to avoid clashing with your appointments",
        "The team is fixing a time for a long meeting.",
        "Say what is already in your diary.",
        "I have to book this room before someone else does. What is already fixed for you?", "efficient"),
      sc("Hugo", "a receptionist confirming your bookings", "to check the times you have arranged",
        "You are confirming the arrangements you made for the rest of the stay.",
        "Confirm your arrangements and their times.",
        "Let me check what you have booked. What times did you arrange?", "polite"),
      sc("Ms. Bianchi", "your teacher", "to practise talking about arrangements",
        "The class is comparing diaries for the coming week.",
        "Describe what is fixed in your week.",
        "Compare your week with your partner's. What is already fixed for you?", "encouraging"),
      sc("Mr. Tanaka", "the examiner", "to check that you can describe arrangements",
        "The examiner asks about the coming week.",
        "Describe your arrangements with times.",
        "Could you tell me what you have arranged for the coming week?", "neutral"),
    ],
  },

  {
    id: "a2-how-about-this",
    topic: "making and answering suggestions",
    objectives: [
      "Make suggestions with the correct form after each expression.",
      "Accept or refuse a suggestion politely.",
    ],
    goal: "Suggest ideas to a friend and react to their suggestions.",
    target: "suggestions with how about, why don't we and shall we",
    correction: "Repeat the suggestion with the correct verb form and let the learner suggest again.",
    summary: "You learned to make suggestions in three ways and to answer them.",
    minutes: 6,
    points: [
      {
        form: "how about / what about + -ing",
        claims: [
          "After 'how about' and 'what about', use a noun, an -ing form or a complete clause.",
          "Say 'How about going?' or 'How about we go?', but not 'How about go?'",
        ],
        ex: ["How about Saturday?", "What about going to the coast?", "How about we take the train?"],
      },
      {
        form: "why don't we / shall we + verb",
        claims: [
          "After 'why don't we' and 'shall we', use the base verb.",
          "Both are questions, so they end with a question mark.",
        ],
        ex: ["Why don't we eat first?", "Shall we take the train?"],
      },
      {
        form: "good idea / I'd rather not",
        claims: [
          "Accept with 'good idea' or 'that sounds great'.",
          "Refuse politely with 'I'd rather not' and a short reason.",
        ],
        ex: ["Good idea, let's do that.", "I'd rather not go so early."],
      },
    ],
    ex: [
      fill("Why ___ we meet a bit earlier? (do not)", ["don't", "do not"]),
      mcq("Which suggestion is correct?", [
        "How about going to the market?",
        "How about go to the market?",
        "How about we going to the market?",
      ], 0),
      say("shall / we / take / the train", ["Shall we take the train?"]),
    ],
    open: {
      q: "Make three weekend suggestions using different expressions. Then accept one idea and refuse another politely.",
      must: ["how about", "why don't we", "shall we"],
      criteria: "The answer makes three correctly formed suggestions and responds to suggestions politely.",
      example: "How about going to the market? Why don't we eat there? Shall we take the train? Good idea, but I'd rather not go too early.",
    },
    success: "The learner makes three correctly formed suggestions and gives at least one appropriate response.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "Why don't we ask her?",
        "Why don't we asking her?",
        "Why we don't ask her?",
      ], 0),
      qfill("How about ___ to the cinema? (go)", ["going"]),
      qmcq("Which answer accepts a suggestion?", ["Good idea, let's do that.", "I'd rather not.", "Sorry, I can't."], 0),
    ],
    scenes: [
      sc("Tessa", "a friend with a free weekend", "to decide together what to do",
        "Two friends have a free Saturday and no plan at all.",
        "Suggest ideas and react to hers.",
        "We finally have a free Saturday and I have zero ideas. What shall we do?", "playful"),
      sc("Viktor", "a colleague organising the team lunch", "to agree on a place and a time",
        "The team lunch needs a place and everyone has an opinion.",
        "Suggest a place and a time.",
        "Nobody can agree on the restaurant. What do you suggest?", "patient"),
      sc("Noor", "another guest planning the day", "to choose what the group does today",
        "Two travellers are deciding how to spend a free day in a new city.",
        "Suggest what to do and when.",
        "We have one day here and a long list. Where do we start?", "enthusiastic"),
      sc("Mr. Berg", "your teacher", "to practise making suggestions",
        "The class is planning an end-of-course outing.",
        "Suggest ideas for the outing.",
        "We are planning something for the end of the course. What do you suggest?", "encouraging"),
      sc("Mrs. Costa", "the examiner", "to check that you can suggest and respond",
        "The examiner asks you to plan an afternoon together.",
        "Make suggestions and respond to the examiner's ideas.",
        "Imagine we have a free afternoon in this city. What shall we do?", "neutral"),
    ],
  },

  {
    id: "a2-lets-make-a-plan",
    topic: "arranging to meet someone",
    objectives: [
      "Propose a day, a time and a place.",
      "Check that the other person agrees and close the arrangement.",
    ],
    goal: "Arrange to meet someone and agree on all the details.",
    target: "arranging to meet and agreeing on details",
    correction: "Model the sentence that proposes or confirms the detail and let the learner continue.",
    summary: "You practised arranging a meeting from the first idea to the final confirmation.",
    minutes: 6,
    points: [
      {
        form: "how about Thursday?",
        claims: [
          "Offer one detail at a time: first the day, then the time, then the place.",
          "One clear proposal is easier to answer than three at once.",
        ],
        ex: ["How about Thursday evening?", "How about the cafe near the station?"],
      },
      {
        form: "does that work for you?",
        claims: [
          "Check that the other person agrees before you move on.",
          "'Is that too early for you?' invites them to say no politely.",
        ],
        ex: ["Does that work for you?", "Is seven too early for you?"],
      },
      {
        form: "see you then",
        claims: [
          "Close by repeating the agreed detail, then say 'see you then'.",
          "Repeating the day and time prevents misunderstandings.",
        ],
        ex: ["Great, see you then.", "Perfect. See you on Thursday at seven."],
      },
    ],
    ex: [
      fill("___ about Thursday evening?", ["How"]),
      mcq("Which sentence checks that the other person agrees?", [
        "Does that work for you?",
        "I'm busy on Thursday.",
        "See you then.",
      ], 0),
      say("see / you / then", ["See you then.", "See you then!"]),
    ],
    open: {
      q: "Arrange to meet a friend. Suggest a day, time and place, check that they agree, and close the arrangement.",
      must: ["how about", "does that work", "see you then"],
      criteria: "The answer proposes a day, time and place, checks agreement and closes the arrangement.",
      example: "How about meeting at the cafe near the station at seven on Thursday? Does that work for you? Great, see you then.",
    },
    success: "The learner proposes all three details, checks agreement and closes the arrangement naturally.",
    quiz: [
      qmcq("Which sentence closes an arrangement?", ["See you then.", "How about Friday?", "Does that work?"], 0),
      qfill("___ that work for you? (do)", ["Does"]),
      qmcq("Which sentence suggests a time?", [
        "How about half past six?",
        "I saw him at half past six.",
        "It takes half an hour.",
      ], 0),
    ],
    scenes: [
      sc("Milena", "a friend you have not seen for months", "to finally fix a date to meet",
        "You have both been saying 'we should meet' for months without fixing anything.",
        "Agree on a day, a time and a place.",
        "We have been saying this for months. Let us actually fix it now. When are you free?", "determined"),
      sc("Samir", "a client you need to see", "to arrange a short meeting this week",
        "A short meeting has to happen this week and both diaries are full.",
        "Propose times and agree on the details.",
        "I have very little space this week, but we should meet. What do you propose?", "businesslike"),
      sc("Elena", "someone you met while travelling", "to meet again before you both leave",
        "Two travellers want to meet once more before their trips end.",
        "Arrange the meeting with day, time and place.",
        "I leave on Sunday and you leave on Monday. Can we make something work?", "warm"),
      sc("Mr. Fontaine", "your teacher", "to practise arranging a meeting",
        "The class is role-playing arrangements in pairs.",
        "Arrange a meeting with your partner.",
        "You and your partner need to meet this week. How do you start?", "encouraging"),
      sc("Ms. Iqbal", "the examiner", "to check that you can arrange a meeting",
        "The examiner asks you to arrange a meeting with them.",
        "Propose the details and confirm the arrangement.",
        "Let us say we need to meet this week. What would you suggest?", "neutral"),
    ],
  },
];
