/** A2 · Ünite 3-5 — Comparing · Rules and Advice · Experiences (22 ders, elle yazıldı).
 *
 *  Ünite 3 karşılaştırmayı üç ayrı biçimde kuruyor (-er / more / as...as) ve
 *  aralarına zarf ile aşırı sıfatları koyuyor: A2'de öğrenci "more better" ve
 *  "more cheap" hatalarını tam burada üretiyor, o yüzden kısa-uzun sıfat ayrımı
 *  ilk iki derste ayrı ayrı öğretiliyor.
 *
 *  Ünite 4 zorunluluk ile tavsiyeyi ayırıyor; `don't have to` ↔ `mustn't` farkına
 *  ayrı ders veriliyor çünkü bu ikisi bu seviyede en sık karışan çifttir.
 *
 *  Ünite 5 present perfect'i DENEYİM olarak açıyor (ever/never/been-gone/already-
 *  just/yet). Geçmiş zamanla karşıtlık ünite 1'de kurulduğu için burada "ne zaman"
 *  sorusu yok: deneyimin kendisi konuşuluyor.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3.
 *
 *  NOT — MCQ doğru şıkkı hep 0'da yazılır: şık sırası SERVİS ANINDA deterministik
 *  olarak karıştırılıyor (bkz. permuteChoices), yani kaynaktaki indeks öğrencinin
 *  gördüğü sırayı belirlemiyor. 0'da tutmak inceleme dökümünü okunur kılıyor.
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A2_U3_5: Authored[] = [
  // --- Ünite 3 · Comparing ---------------------------------------------------
  {
    id: "a2-bigger-and-better",
    topic: "comparing two things with short describing words",
    objectives: [
      "Add -er to short describing words to compare two things.",
      "Say how big the difference between them is.",
    ],
    goal: "Compare two things and say which one is better for you.",
    target: "comparatives with -er and than",
    correction: "Say the comparative form inside a full sentence and let the learner repeat it.",
    summary: "You learned to compare two things with -er and than, and to say how big the difference is.",
    minutes: 7,
    points: [
      {
        form: "-er than",
        claims: [
          "Add -er to short describing words and put 'than' before the second thing.",
          "After one vowel, the last letter doubles: big becomes bigger, hot becomes hotter.",
        ],
        ex: ["This flat is bigger than the other one.", "The second one is cheaper than the first."],
      },
      {
        form: "y becomes -ier",
        claims: [
          "Words ending in -y change the y to -ier: easy becomes easier, busy becomes busier.",
          "The rest of the sentence does not change.",
        ],
        ex: ["The journey is easier than I expected.", "This street is noisier than ours."],
      },
      {
        form: "much better",
        claims: [
          "Put 'much', 'a lot' or 'a bit' before the comparative to say how big the difference is.",
          "'Good' has an irregular comparative: better, not gooder.",
        ],
        ex: ["It's much better than the old one.", "This one is a bit smaller."],
      },
    ],
    ex: [
      fill("This flat is ___ than the old one. (big)", ["bigger"]),
      mcq("Which sentence is correct?", [
        "The second one is cheaper than the first.",
        "The second one is more cheap than the first.",
        "The second one is cheaper that the first.",
      ], 0),
      fill("The new station is ___ to reach than the old one. (easy)", ["easier"]),
      say("this one / be / much better", ["This one is much better.", "This one's much better."]),
    ],
    open: {
      q: "Compare two places you know well. Say which one is better and how big the difference is.",
      must: ["bigger than", "much better"],
      criteria: "The answer compares two places with a comparative form and says how big the difference is.",
      example: "My old flat was bigger than this one, but this one is much better for getting to work.",
    },
    success: "The learner compares two things with a comparative and 'than' at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "This box is heavier than that one.",
        "This box is more heavy than that one.",
        "This box is heavyer than that one.",
      ], 0),
      qfill("The red one is ___ than the blue one. (cheap)", ["cheaper"]),
      qmcq("Which sentence is correct?", [
        "It's much better than before.",
        "It's much more better than before.",
        "It's much gooder than before.",
      ], 0),
    ],
    scenes: [
      sc("Nadia", "a friend helping you decide", "to work out which of two flats you should take",
        "You have seen two flats and cannot decide between them.",
        "Compare the two flats and say which is better.",
        "You have seen both places now. Which one is winning, and why?", "practical"),
      sc("Ryan", "a colleague looking at two offices", "to choose between two possible team spaces",
        "The team has to pick one of two floors to move into.",
        "Compare the two spaces for the team.",
        "We can take the third floor or the fifth. What do you think of them?", "considering"),
      sc("Beatrix", "a travel agent", "to help you pick between two hotels",
        "Two hotels are available for the same dates and price range.",
        "Compare the two hotels and choose one.",
        "Both hotels are free that week. Shall I tell you about them?", "helpful"),
      sc("Ms. Oyelaran", "your teacher", "to practise comparing two things",
        "The class is comparing pairs of everyday objects and places.",
        "Compare two things you know well.",
        "Think of two places you know well. How are they different?", "encouraging"),
      sc("Mr. Bauer", "the examiner", "to check that you can compare two things",
        "The examiner asks you to compare two familiar places.",
        "Compare them clearly and say which you prefer.",
        "Could you compare two places you know and tell me which you prefer?", "neutral"),
    ],
  },

  {
    id: "a2-more-interesting-than",
    topic: "comparing with longer words and irregular forms",
    objectives: [
      "Use 'more' with longer describing words.",
      "Use the irregular comparisons better and worse.",
    ],
    goal: "Compare two places or things using longer describing words.",
    target: "comparatives with 'more' and the common irregulars",
    correction: "Repeat the sentence with the correct comparative form and invite the learner to try again.",
    summary: "You learned when to use 'more' instead of -er, and the forms better, worse and less.",
    minutes: 7,
    points: [
      {
        form: "more ... than",
        claims: [
          "Words of two or more syllables usually take 'more' instead of -er.",
          "Never use both together: 'more expensive', not 'more expensiver'.",
        ],
        ex: ["This city is more expensive than my hometown.", "The museum is more interesting than the castle."],
      },
      {
        form: "less ... than",
        claims: [
          "'Less' is the opposite of 'more' and works the same way.",
          "'Less crowded' means fewer people than the other place.",
        ],
        ex: ["The old town is less crowded in winter.", "This route is less tiring than the other one."],
      },
      {
        form: "better and worse",
        claims: [
          "'Good' and 'bad' are irregular: they become better and worse.",
          "These two never take -er or 'more'.",
        ],
        ex: ["The weather here is better than at home.", "The traffic was worse than yesterday."],
      },
    ],
    ex: [
      fill("This city is ___ expensive than my hometown.", ["more"]),
      mcq("Which sentence is correct?", [
        "The museum is more interesting than the castle.",
        "The museum is interestinger than the castle.",
        "The museum is more interestinger than the castle.",
      ], 0),
      fill("The traffic today was ___ than yesterday. (bad)", ["worse"]),
      say("the old town / be / less crowded", ["The old town is less crowded.", "The old town's less crowded."]),
    ],
    open: {
      q: "Compare two cities or towns you have visited. Use a longer describing word in your comparison.",
      must: ["more expensive than", "less crowded", "worse than"],
      criteria: "The answer compares two places using 'more', 'less' or an irregular comparative correctly.",
      example: "The capital is more expensive than my town, and the traffic there is worse than anything I know.",
    },
    success: "The learner uses 'more' or an irregular comparative correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "This film is more boring than the last one.",
        "This film is boringer than the last one.",
        "This film is more boringer than the last one.",
      ], 0),
      qfill("The food here is ___ than at the other place. (good)", ["better"]),
      qmcq("Which sentence is correct?", [
        "The second route is less tiring.",
        "The second route is less tiringer.",
        "The second route is more less tiring.",
      ], 0),
    ],
    scenes: [
      sc("Teodor", "a friend who has travelled a lot", "to compare the cities you have both seen",
        "Two friends are comparing places they have visited.",
        "Compare two cities you know.",
        "We have both been to a few of the same places. Which ones did you like most?", "curious"),
      sc("Marguerite", "a colleague planning a company trip", "to choose the better city for the event",
        "The team event can be held in one of two cities.",
        "Compare the two cities for the event.",
        "It is between the two cities we discussed. Which would work better?", "focused"),
      sc("Arjun", "another traveller at the hostel", "to swap opinions about the region",
        "Two travellers compare the towns they have passed through.",
        "Compare the places you have seen.",
        "I have three days left and two towns on my list. What are they like?", "open"),
      sc("Dr. Weiss", "your teacher", "to practise longer comparative forms",
        "The class is comparing cities and regions.",
        "Compare two places using longer describing words.",
        "Compare two cities for us. What makes one different from the other?", "encouraging"),
      sc("Mrs. Aoki", "the examiner", "to check longer comparative forms",
        "The examiner asks you to compare two places you know.",
        "Compare them using longer describing words.",
        "Could you compare two cities you have visited?", "neutral"),
    ],
  },

  {
    id: "a2-the-best-one",
    topic: "saying which is the top or bottom of a group",
    objectives: [
      "Use the superlative for the top or bottom of a group.",
      "Say why something is your favourite.",
    ],
    goal: "Pick the best or worst from a group and explain your choice.",
    target: "superlatives with the -est and the most",
    correction: "Say the superlative with 'the' in a full sentence and let the learner repeat it.",
    summary: "You learned to name the top or bottom of a group with the -est and the most.",
    minutes: 7,
    points: [
      {
        form: "the -est",
        claims: [
          "Short words take the -est and almost always need 'the' before them.",
          "The spelling rules are the same as the comparative: big becomes the biggest, easy becomes the easiest.",
        ],
        ex: ["That's the cheapest one in the shop.", "This is the easiest way to get there."],
      },
      {
        form: "the most",
        claims: [
          "Longer words take 'the most' instead of the -est.",
          "'Good' and 'bad' are irregular here too: the best and the worst.",
        ],
        ex: ["It's the most comfortable chair in the office.", "That was the best meal of the trip."],
      },
      {
        form: "my favourite one",
        claims: [
          "'My favourite' says which one you like most without a comparison word.",
          "Add 'because' to give the reason for your choice.",
        ],
        ex: ["This is my favourite one because it is light.", "The small one is my favourite."],
      },
    ],
    ex: [
      fill("That's ___ cheapest one in the shop.", ["the"]),
      mcq("Which sentence is correct?", [
        "It's the most comfortable chair here.",
        "It's the comfortablest chair here.",
        "It's the most comfortablest chair here.",
      ], 0),
      fill("That was ___ meal of the whole trip. (the / good)", ["the best"]),
      say("this one / be / my favourite", ["This one is my favourite.", "This one's my favourite."]),
    ],
    open: {
      q: "Think of three places you have eaten. Say which one is the best and why.",
      must: ["it's the best", "that's the cheapest", "my favourite one"],
      criteria: "The answer names the top of a group with a superlative and gives a reason.",
      example: "The small place near the station is my favourite one, because the food is fresh and it costs less.",
    },
    success: "The learner uses a superlative correctly and gives a reason for the choice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "This is the biggest room in the flat.",
        "This is the most big room in the flat.",
        "This is the bigest room in the flat.",
      ], 0),
      qfill("It was ___ worst day of the week.", ["the"]),
      qmcq("Which sentence is correct?", [
        "That was the most interesting part.",
        "That was the interestingest part.",
        "That was the most interestingest part.",
      ], 0),
    ],
    scenes: [
      sc("Paloma", "a friend asking for a recommendation", "to find the best place to eat nearby",
        "A friend wants one clear recommendation, not a long list.",
        "Name the best option and say why.",
        "I only have one evening here. Where should I eat?", "trusting"),
      sc("Declan", "a colleague comparing suppliers", "to choose the best of three offers",
        "Three offers are on the table and one has to be chosen.",
        "Say which offer is best and why.",
        "We have three quotes here. Which one stands out to you?", "analytical"),
      sc("Xiomara", "a hotel concierge", "to help you choose the best day trip",
        "Several day trips are available and you can only do one.",
        "Pick the best option and explain the choice.",
        "There are four trips this week. Shall I go through them?", "welcoming"),
      sc("Mr. Kovacs", "your teacher", "to practise superlative forms",
        "The class is ranking places and things.",
        "Name the best or worst of a group and explain.",
        "Think of three restaurants you know. Which is the best?", "encouraging"),
      sc("Ms. Reyes", "the examiner", "to check superlative forms",
        "The examiner asks you to choose the top of a group.",
        "Name it with a superlative and justify it.",
        "Could you tell me about the best place you have eaten, and why?", "neutral"),
    ],
  },

  {
    id: "a2-i-prefer-this-one",
    topic: "saying which of two things you prefer",
    objectives: [
      "Say which of two options you prefer.",
      "Give a short reason for your preference.",
    ],
    goal: "Choose between two options in a shop and explain your choice.",
    target: "expressing preference between two options",
    correction: "Model the preference sentence and let the learner say their own version.",
    summary: "You learned three ways to say which option you prefer and how to give a reason.",
    minutes: 6,
    points: [
      {
        form: "I prefer",
        claims: [
          "'I prefer' is followed by a noun or by a verb with -ing.",
          "Add 'to' before the other option when you compare them directly.",
        ],
        ex: ["I prefer the blue one.", "I prefer walking to driving."],
      },
      {
        form: "I like this one",
        claims: [
          "'This one' and 'that one' avoid repeating the name of the thing.",
          "'Better' turns a simple opinion into a comparison: I like this one better.",
        ],
        ex: ["I like this one better.", "I like the smaller one."],
      },
      {
        form: "I'd rather have",
        claims: [
          "'I'd rather' is followed by the base verb, with no 'to'.",
          "It sounds slightly softer than 'I want'.",
        ],
        ex: ["I'd rather have the black one.", "I'd rather pay a bit more for a good one."],
      },
    ],
    ex: [
      fill("I ___ the blue one, thanks.", ["prefer", "like"]),
      mcq("Which sentence is correct?", [
        "I'd rather have the black one.",
        "I'd rather to have the black one.",
        "I'd rather having the black one.",
      ], 0),
      say("I / like / this one / better", ["I like this one better."]),
    ],
    open: {
      q: "You are choosing between two jackets in a shop. Say which one you prefer and why.",
      must: ["I prefer", "I like this one", "I'd rather have"],
      criteria: "The answer states a preference between two options and gives a reason.",
      example: "I prefer the grey one because it goes with everything, and I'd rather have something simple.",
    },
    success: "The learner states a preference and supports it with a reason.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I prefer walking to driving.",
        "I prefer walking than driving.",
        "I prefer to walking than drive.",
      ], 0),
      qfill("I'd ___ have the smaller size.", ["rather"]),
      qmcq("Which sentence gives a preference?", [
        "I like this one better.",
        "This one is over there.",
        "They have two sizes.",
      ], 0),
    ],
    scenes: [
      sc("Sinead", "a shop assistant", "to help you choose between two items",
        "You are holding two similar items and cannot decide.",
        "Say which one you prefer and why.",
        "They both suit you. Which one are you leaning towards?", "patient"),
      sc("Omar", "a colleague choosing office equipment", "to agree on one option for the team",
        "Two models are within budget and the team must pick one.",
        "State your preference and give a reason.",
        "Both models fit the budget. Which would you go for?", "practical"),
      sc("Lena", "a market seller", "to sell you one of two similar items",
        "A market stall has two versions of the same thing.",
        "Say which one you prefer and why.",
        "This one is handmade, this one is lighter. Which do you like?", "friendly"),
      sc("Mrs. Dube", "your teacher", "to practise expressing preference",
        "The class is choosing between pairs of options.",
        "State a preference and justify it.",
        "Here are two options. Which would you choose, and why?", "encouraging"),
      sc("Mr. Ellery", "the examiner", "to check that you can express preference",
        "The examiner offers you a choice between two things.",
        "State your preference clearly with a reason.",
        "If you had to choose between living in a city and living in the countryside, which would you prefer?", "neutral"),
    ],
  },

  {
    id: "a2-as-cheap-as",
    topic: "saying two things are equal or not equal",
    objectives: [
      "Use 'as ... as' to say two things are the same.",
      "Use 'not as ... as' to say one is less than the other.",
    ],
    goal: "Argue that two options are closer than they look.",
    target: "as ... as and not as ... as",
    correction: "Repeat the full 'as ... as' sentence and let the learner build their own.",
    summary: "You learned to say two things are equal with 'as ... as' and unequal with 'not as ... as'.",
    minutes: 7,
    points: [
      {
        form: "as ... as",
        claims: [
          "Put the plain describing word between the two 'as' words, with no -er and no 'more'.",
          "This says the two things are the same in that way.",
        ],
        ex: ["This one is as good as the expensive one.", "The train is as fast as the bus."],
      },
      {
        form: "not as ... as",
        claims: [
          "'Not as ... as' means the first thing is less than the second.",
          "'It's not as expensive as that one' means it costs less.",
        ],
        ex: ["It's not as expensive as I thought.", "Today is not as cold as yesterday."],
      },
      {
        form: "just as nice",
        claims: [
          "'Just as' makes the equality stronger: exactly the same, not almost.",
          "'Almost as' says it is close but slightly less.",
        ],
        ex: ["The cheaper one is just as nice.", "This route is almost as quick."],
      },
    ],
    ex: [
      fill("This one is as ___ as the expensive one. (good)", ["good"]),
      mcq("Which sentence is correct?", [
        "It's not as expensive as I thought.",
        "It's not as expensiver as I thought.",
        "It's not so expensive than I thought.",
      ], 0),
      fill("Today is not ___ cold as yesterday.", ["as", "so"]),
      say("the cheaper one / be / just as nice", ["The cheaper one is just as nice."]),
    ],
    open: {
      q: "Think of a cheap option and an expensive one you know. Argue that they are closer than people think.",
      must: ["as good as", "not as expensive", "just as nice"],
      criteria: "The answer uses 'as ... as' or 'not as ... as' correctly to compare two options.",
      example: "The supermarket coffee is almost as good as the cafe one, and it's not as expensive at all.",
    },
    success: "The learner uses 'as ... as' or 'not as ... as' correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "The train is as fast as the bus.",
        "The train is as faster as the bus.",
        "The train is as fast than the bus.",
      ], 0),
      qfill("This bag is not ___ heavy as the other one.", ["as"]),
      qmcq("Which sentence says the two are equal?", [
        "The cheaper one is just as nice.",
        "The cheaper one is nicer.",
        "The cheaper one is not as nice.",
      ], 0),
    ],
    scenes: [
      sc("Gustavo", "a friend about to overspend", "to be talked out of the expensive option",
        "A friend is about to buy the most expensive version of something.",
        "Argue that the cheaper option is just as good.",
        "I was going to buy the top model. Do you think that is silly?", "hesitant"),
      sc("Priya", "your manager reviewing the budget", "to justify the cheaper supplier",
        "The cheaper supplier has to be defended in a meeting.",
        "Argue that the two options are equal in quality.",
        "Convince me the cheaper option will not cost us later. Can you?", "sceptical"),
      sc("Bram", "a fellow traveller comparing routes", "to decide between a train and a bus",
        "Two ways to reach the same city, different prices.",
        "Compare the two and argue they are close.",
        "The train costs double the bus. Is it worth it?", "curious"),
      sc("Ms. Farrow", "your teacher", "to practise equality comparisons",
        "The class is arguing that cheap options can match expensive ones.",
        "Argue two things are equal using 'as ... as'.",
        "Think of something cheap that is as good as an expensive version. What is it?", "encouraging"),
      sc("Mr. Ibrahim", "the examiner", "to check equality comparisons",
        "The examiner asks you to compare two similar things.",
        "Say how they are equal and how they differ.",
        "Could you compare two similar products and say whether one is really better?", "neutral"),
    ],
  },

  {
    id: "a2-absolutely-freezing",
    topic: "strong describing words",
    objectives: [
      "Use strong describing words instead of very plus a plain word.",
      "Choose the right intensifier for a strong word.",
    ],
    goal: "Tell an exaggerated story about weather or a place.",
    target: "extreme adjectives and their intensifiers",
    correction: "Say the strong word with its natural intensifier and let the learner use it again.",
    summary: "You learned strong describing words like freezing and huge, and how to make them stronger.",
    minutes: 6,
    points: [
      {
        form: "freezing / boiling / huge / tiny",
        claims: [
          "Strong words already contain 'very': freezing means very cold, huge means very big.",
          "Because of that, we do not usually say 'very freezing'.",
        ],
        ex: ["It was absolutely freezing outside.", "Their kitchen is tiny."],
      },
      {
        form: "absolutely / really",
        claims: [
          "Use 'absolutely' before strong words instead of 'very'.",
          "'Really' works with both strong and plain words.",
        ],
        ex: ["The room was absolutely boiling.", "The garden was really tiny."],
      },
      {
        form: "it was huge",
        claims: [
          "Strong words make a story livelier than a plain word plus 'very'.",
          "In speech the strong word usually carries the stress.",
        ],
        ex: ["The queue was huge.", "The bill was enormous."],
      },
    ],
    ex: [
      fill("It was absolutely ___ outside, about minus ten. (very cold)", ["freezing"]),
      mcq("Which sentence sounds natural?", [
        "The room was absolutely boiling.",
        "The room was very boiling.",
        "The room was more boiling.",
      ], 0),
      say("their kitchen / be / really tiny", ["Their kitchen is really tiny.", "Their kitchen's really tiny."]),
    ],
    open: {
      q: "Describe the coldest or hottest day you remember. Use strong describing words.",
      must: ["absolutely freezing", "it was huge", "really tiny"],
      criteria: "The answer uses at least one strong describing word with a suitable intensifier.",
      example: "One January it was absolutely freezing, and the queue outside the station was huge.",
    },
    success: "The learner uses strong describing words naturally at least twice.",
    quiz: [
      qmcq("Which sentence sounds natural?", [
        "It was absolutely freezing.",
        "It was very freezing.",
        "It was more freezing.",
      ], 0),
      qfill("Their flat is ___, only one small room. (very small)", ["tiny"]),
      qmcq("Which word means very big?", ["huge", "tiny", "narrow"], 0),
    ],
    scenes: [
      sc("Kasia", "a neighbour who loves a good story", "to swap exaggerated weather stories",
        "Two neighbours are outdoing each other with weather stories.",
        "Describe extreme weather with strong words.",
        "You think this is cold? Wait until you hear about my winter. What is the worst you have had?", "animated"),
      sc("Nils", "a colleague back from a trip", "to hear how extreme the conditions were",
        "A colleague is describing a difficult business trip.",
        "Describe the conditions with strong words.",
        "You looked exhausted when you got back. How bad was it?", "sympathetic"),
      sc("Rafaela", "a guide preparing you for the weather", "to warn you about the conditions",
        "The guide is describing what to expect on the trip.",
        "React and describe extremes you have experienced.",
        "It gets very extreme up there. Have you been anywhere like that before?", "warning"),
      sc("Mr. Sandoval", "your teacher", "to practise strong describing words",
        "The class is replacing plain words with strong ones.",
        "Describe something extreme.",
        "Instead of saying very cold, what could you say?", "encouraging"),
      sc("Mrs. Lindgren", "the examiner", "to check descriptive range",
        "The examiner asks about an extreme experience.",
        "Describe it with strong words.",
        "Could you describe the most extreme weather you have experienced?", "neutral"),
    ],
  },

  {
    id: "a2-he-drives-carefully",
    topic: "saying how someone does something",
    objectives: [
      "Form adverbs from describing words with -ly.",
      "Put the adverb in the right place in the sentence.",
    ],
    goal: "Describe how people do things at work or on the road.",
    target: "adverbs of manner",
    correction: "Repeat the sentence with the adverb in its natural place and let the learner say it again.",
    summary: "You learned to say how someone does something using adverbs ending in -ly.",
    minutes: 7,
    points: [
      {
        form: "-ly",
        claims: [
          "Most adverbs add -ly to the describing word: careful becomes carefully, slow becomes slowly.",
          "Words ending in -y change to -ily: easy becomes easily.",
        ],
        ex: ["He drives very carefully.", "She speaks slowly and clearly."],
      },
      {
        form: "fast, hard, well",
        claims: [
          "'Fast' and 'hard' do not change; 'good' becomes 'well'.",
          "'Hardly' is a different word and does not mean 'with effort'.",
        ],
        ex: ["He works hard and drives fast.", "She speaks English quite well."],
      },
      {
        form: "where the adverb goes",
        claims: [
          "The adverb of manner usually comes after the verb or after the object.",
          "It does not go between the verb and its object.",
        ],
        ex: ["She opened the door quietly.", "He answered the question politely."],
      },
    ],
    ex: [
      fill("He drives very ___. (careful)", ["carefully"]),
      mcq("Which sentence is correct?", [
        "She speaks English quite well.",
        "She speaks English quite good.",
        "She speaks well English quite.",
      ], 0),
      fill("She finished the task ___. (easy)", ["easily"]),
      say("he / speak / slowly", ["He speaks slowly."]),
    ],
    open: {
      q: "Describe how two people you know do something, at work or at home.",
      must: ["very carefully", "he speaks slowly", "quite well"],
      criteria: "The answer describes how someone does something using adverbs correctly.",
      example: "My colleague checks everything very carefully, and he speaks slowly so everyone understands.",
    },
    success: "The learner uses adverbs of manner correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "She opened the door quietly.",
        "She opened quietly the door.",
        "She opened the door quiet.",
      ], 0),
      qfill("He works very ___ and never complains. (hard)", ["hard"]),
      qmcq("Which sentence is correct?", [
        "He answered the question politely.",
        "He answered the question polite.",
        "He politely answered politely the question.",
      ], 0),
    ],
    scenes: [
      sc("Yara", "a neighbour talking about the street", "to compare how people drive around here",
        "Two neighbours are talking about traffic on their street.",
        "Describe how different people drive.",
        "Some people fly down this road. How do you find the drivers here?", "chatty"),
      sc("Hendrik", "a new team member", "to learn how the team works",
        "A new colleague wants to know how people here do things.",
        "Describe how your colleagues work.",
        "I am still learning how things run here. How do people usually work?", "curious"),
      sc("Amina", "a driving instructor abroad", "to check you understand local driving habits",
        "You are learning the local rules of the road.",
        "Describe how people drive here and at home.",
        "Driving here is different from most places. How do people drive where you come from?", "instructive"),
      sc("Mr. Novak", "your teacher", "to practise adverbs of manner",
        "The class is describing how people do everyday things.",
        "Describe how someone does something.",
        "Think of someone you know well. How do they speak?", "encouraging"),
      sc("Ms. Bright", "the examiner", "to check adverb use",
        "The examiner asks about someone's way of doing things.",
        "Describe it using adverbs.",
        "Could you describe how a person you know does their job?", "neutral"),
    ],
  },

  {
    id: "a2-which-one-would-you-pick",
    topic: "weighing two options and choosing",
    objectives: [
      "Weigh two real options against each other.",
      "Explain what your choice depends on.",
    ],
    goal: "Help someone choose between two offers and explain your reasoning.",
    target: "comparing two options and justifying a choice",
    correction: "Model the sentence that states the choice and let the learner continue the reasoning.",
    summary: "You practised weighing two options and explaining which one you would choose.",
    minutes: 6,
    points: [
      {
        form: "I'd rather",
        claims: [
          "'I'd rather' plus the base verb states your choice without sounding pushy.",
          "Add 'than' to name the option you are rejecting.",
        ],
        ex: ["I'd rather take the first one.", "I'd rather wait than pay that much."],
      },
      {
        form: "it depends on",
        claims: [
          "'It depends on' is followed by a noun or by a question word.",
          "It says your answer would change if the situation changed.",
        ],
        ex: ["It depends on the price.", "It depends on how much time you have."],
      },
      {
        form: "in my opinion",
        claims: [
          "'In my opinion' marks the next sentence as your view, not a fact.",
          "It usually stands at the start, followed by a comma.",
        ],
        ex: ["In my opinion, the second one is safer.", "In my opinion, it is worth waiting."],
      },
    ],
    ex: [
      fill("I'd ___ take the first offer.", ["rather"]),
      mcq("Which sentence is correct?", [
        "It depends on how much time you have.",
        "It depends of how much time you have.",
        "It depends how much time do you have.",
      ], 0),
      say("in my opinion / the second one / be / safer", ["In my opinion, the second one is safer.", "In my opinion the second one is safer."]),
    ],
    open: {
      q: "A friend has two job offers: one pays more, one is closer to home. Say which you would pick and why.",
      must: ["I'd rather", "it depends on", "in my opinion"],
      criteria: "The answer chooses between two options, gives a reason and names what the choice depends on.",
      example: "In my opinion the closer one is better. I'd rather have the time than the money, but it depends on the salary.",
    },
    success: "The learner states a choice, gives a reason and names a condition.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'd rather wait than pay that much.",
        "I'd rather to wait than pay that much.",
        "I'd rather waiting than pay that much.",
      ], 0),
      qfill("It depends ___ the price.", ["on"]),
      qmcq("Which phrase marks an opinion?", ["In my opinion", "As usual", "At the moment"], 0),
    ],
    scenes: [
      sc("Cassia", "a friend with two job offers", "to hear your honest opinion before deciding",
        "A friend has to answer both employers tomorrow.",
        "Weigh the two offers and say which you would pick.",
        "One pays more, one is ten minutes from my flat. What would you do?", "torn"),
      sc("Lucas", "a colleague choosing between two projects", "to decide which project to join",
        "Two projects need people and your colleague can pick one.",
        "Compare the projects and recommend one.",
        "I can join either team. Which one would you go for?", "thinking"),
      sc("Imani", "a fellow traveller with two routes", "to choose the better way to continue the trip",
        "Two routes lead to the same destination, one slower and cheaper.",
        "Compare the routes and choose.",
        "Cheap and slow, or fast and expensive? Which would you pick?", "relaxed"),
      sc("Mrs. Tanaka", "your teacher", "to practise justifying a choice",
        "The class is deciding between pairs of options.",
        "Choose one option and explain fully.",
        "Two offers, one choice. Which do you take, and why?", "encouraging"),
      sc("Mr. Okafor", "the examiner", "to check that you can justify a choice",
        "The examiner presents you with a decision.",
        "Choose and justify with clear reasons.",
        "If you had to choose between a better salary and a shorter journey, which would you take?", "neutral"),
    ],
  },

  {
    id: "a2-it-doesnt-fit",
    topic: "changing something you bought",
    objectives: [
      "Explain what is wrong with something you bought.",
      "Ask to change it for a different size or colour.",
    ],
    goal: "Go back to a shop and change something politely.",
    target: "exchanging a purchase in a shop",
    correction: "Model the polite request and let the learner make it again in their own words.",
    summary: "You practised explaining a problem with a purchase and asking to change it.",
    minutes: 6,
    points: [
      {
        form: "it doesn't fit",
        claims: [
          "Say what is wrong before you say what you want.",
          "'It doesn't fit' covers size; 'it doesn't suit me' is about how it looks.",
        ],
        ex: ["I bought this yesterday, but it doesn't fit.", "It's a bit too tight around the shoulders."],
      },
      {
        form: "can I change",
        claims: [
          "'Can I change this for ...?' asks for a different item, not money back.",
          "'Could I' sounds slightly more polite than 'can I'.",
        ],
        ex: ["Can I change this for a bigger one?", "Could I exchange it, please?"],
      },
      {
        form: "in a smaller size",
        claims: [
          "'In' introduces the size or colour you want instead.",
          "'Have you got this in ...?' is the usual way to ask what is available.",
        ],
        ex: ["Have you got this in a smaller size?", "Do you have it in blue?"],
      },
    ],
    ex: [
      fill("I bought this yesterday, but it ___ fit.", ["doesn't", "does not"]),
      mcq("Which sentence asks for a different size?", [
        "Have you got this in a smaller size?",
        "This is a smaller size.",
        "The smaller size was there.",
      ], 0),
      say("can / I / change / this", ["Can I change this?", "Could I change this?"]),
    ],
    open: {
      q: "You bought a jacket that is too big. Go back to the shop and explain what you want.",
      must: ["it doesn't fit", "can I change", "in a smaller size"],
      criteria: "The answer explains the problem and asks politely for a different item.",
      example: "I bought this on Saturday but it doesn't fit. Can I change it for one in a smaller size?",
    },
    success: "The learner explains the problem and makes a polite request.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "Can I change this for a bigger one?",
        "Can I change this for bigger one?",
        "Can I to change this for a bigger one?",
      ], 0),
      qfill("Have you got this ___ blue?", ["in"]),
      qmcq("Which sentence explains a problem?", [
        "It doesn't fit around the shoulders.",
        "I will take two of them.",
        "The shop opens at nine.",
      ], 0),
    ],
    scenes: [
      sc("Ffion", "a shop assistant", "to sort out the exchange for you",
        "You are at the counter with something you bought two days ago.",
        "Explain the problem and ask to change it.",
        "Hello, how can I help you today?", "helpful"),
      sc("Marcus", "the shop manager", "to handle a case without a receipt",
        "You want to exchange something but cannot find the receipt.",
        "Explain the situation and ask what is possible.",
        "My colleague says there is no receipt. Can you tell me what happened?", "formal"),
      sc("Sunita", "a market seller abroad", "to swap an item you bought yesterday",
        "You bought something at a market and it is the wrong size.",
        "Explain and ask for a different one.",
        "You came back! Was there a problem with it?", "warm"),
      sc("Ms. Petrova", "your teacher", "to practise shop language",
        "The class is role-playing returns and exchanges.",
        "Explain a problem and request an exchange.",
        "You bought something that does not fit. What do you say at the counter?", "encouraging"),
      sc("Mr. Halloran", "the examiner", "to check transactional language",
        "The examiner plays a shop assistant.",
        "Explain the problem and ask for an exchange.",
        "Good morning, is there something wrong with your purchase?", "neutral"),
    ],
  },

  // --- Ünite 4 · Rules and Advice --------------------------------------------
  {
    id: "a2-i-have-to-work",
    topic: "saying what is necessary",
    objectives: [
      "Use 'have to' and 'has to' for things that are necessary.",
      "Ask whether something is necessary.",
    ],
    goal: "Explain the rules of your job or your home.",
    target: "have to and has to for necessity",
    correction: "Say the full 'have to' sentence and let the learner repeat it.",
    summary: "You learned to say what is necessary with have to and has to.",
    minutes: 7,
    points: [
      {
        form: "have to / has to",
        claims: [
          "'Have to' is followed by the base verb and says something is necessary.",
          "After he, she and it it becomes 'has to'.",
        ],
        ex: ["I have to work on Saturday.", "She has to wear a uniform."],
      },
      {
        form: "do you have to?",
        claims: [
          "Questions use do or does before the person, and 'have to' does not change.",
          "The answer is usually short: yes, I do. No, I don't.",
        ],
        ex: ["Do you have to work at weekends?", "Does he have to be there early?"],
      },
      {
        form: "had to",
        claims: [
          "In the past both forms become 'had to' for every person.",
          "'Had to' says it was necessary then, not now.",
        ],
        ex: ["We had to wait an hour.", "She had to leave early yesterday."],
      },
    ],
    ex: [
      fill("I ___ to work on Saturday this week. (have)", ["have"]),
      mcq("Which sentence is correct?", [
        "She has to wear a uniform.",
        "She have to wear a uniform.",
        "She has to wears a uniform.",
      ], 0),
      fill("___ you have to start early tomorrow? (do)", ["Do"]),
      say("we / have to / wait / an hour", ["We had to wait an hour.", "We have to wait an hour."]),
    ],
    open: {
      q: "Describe two things you have to do in your job, your studies or at home.",
      must: ["I have to", "she has to"],
      criteria: "The answer describes necessary actions using have to or has to correctly.",
      example: "I have to start at eight every day, and my sister has to work every other weekend.",
    },
    success: "The learner describes at least two necessary actions with have to or has to.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "He has to leave at six.",
        "He have to leave at six.",
        "He has to leaves at six.",
      ], 0),
      qfill("___ she have to work on Sundays? (do)", ["Does"]),
      qmcq("Which sentence talks about the past?", [
        "We had to wait an hour.",
        "We have to wait an hour.",
        "We will have to wait an hour.",
      ], 0),
    ],
    scenes: [
      sc("Rosa", "a neighbour curious about your week", "to understand why you are never free",
        "A neighbour keeps inviting you and you keep saying no.",
        "Explain what you have to do.",
        "You are never around at weekends! What keeps you so busy?", "curious"),
      sc("Bastien", "a new colleague", "to learn the rules of the workplace",
        "A new colleague is finding out how things work here.",
        "Explain the rules of the job.",
        "Nobody has told me the basics yet. What do I need to know?", "eager"),
      sc("Aditi", "a host family member", "to explain the house rules to you",
        "You are staying with a host family and comparing rules.",
        "Explain the rules where you live.",
        "We have a few house rules here. Do you have rules like that at home?", "kind"),
      sc("Mr. Hassan", "your teacher", "to practise talking about obligations",
        "The class is comparing daily obligations.",
        "Describe what you have to do.",
        "What is one thing you have to do every week, whether you like it or not?", "encouraging"),
      sc("Mrs. Clark", "the examiner", "to check obligation forms",
        "The examiner asks about your responsibilities.",
        "Describe them with have to.",
        "Could you tell me about the things you have to do in a normal week?", "neutral"),
    ],
  },

  {
    id: "a2-you-dont-have-to-come",
    topic: "the difference between not necessary and not allowed",
    objectives: [
      "Say something is not necessary with 'don't have to'.",
      "Say something is not allowed with 'mustn't'.",
    ],
    goal: "Explain which rules are strict and which are optional.",
    target: "don't have to versus mustn't",
    correction: "Contrast the two forms in one sentence and let the learner choose the right one.",
    summary: "You learned that 'don't have to' means optional and 'mustn't' means not allowed.",
    minutes: 7,
    points: [
      {
        form: "you don't have to",
        claims: [
          "'Don't have to' means it is not necessary; you can if you want.",
          "It is not a prohibition, even though it contains 'not'.",
        ],
        ex: ["You don't have to come if you're busy.", "We don't have to book in advance."],
      },
      {
        form: "you mustn't",
        claims: [
          "'Mustn't' means it is not allowed; there is no choice.",
          "This is the opposite of 'don't have to', not the same thing.",
        ],
        ex: ["You mustn't park in front of the door.", "You mustn't tell anyone yet."],
      },
      {
        form: "we have to",
        claims: [
          "For the positive rule, 'have to' and 'must' are close in everyday speech.",
          "'Have to' is more common when the rule comes from outside you.",
        ],
        ex: ["We have to wear a badge in the building.", "You have to show your ticket at the gate."],
      },
    ],
    ex: [
      fill("You ___ have to come if you're busy. (do not)", ["don't", "do not"]),
      mcq("Which sentence means it is NOT allowed?", [
        "You mustn't park here.",
        "You don't have to park here.",
        "You don't need to park here.",
      ], 0),
      fill("We ___ to wear a badge in the building. (have)", ["have"]),
      say("you / mustn't / tell / anyone", ["You mustn't tell anyone.", "You must not tell anyone."]),
    ],
    open: {
      q: "Think of a place you know well. Name one thing that is optional there and one thing that is not allowed.",
      must: ["you don't have to", "you mustn't", "we have to"],
      criteria: "The answer distinguishes an optional rule from a prohibition using the correct forms.",
      example: "At my office you don't have to wear a suit, but you mustn't bring visitors in without asking.",
    },
    success: "The learner uses 'don't have to' and 'mustn't' with the correct meanings.",
    quiz: [
      qmcq("Which sentence means it is optional?", [
        "You don't have to stay until the end.",
        "You mustn't stay until the end.",
        "You have to stay until the end.",
      ], 0),
      qfill("You ___ smoke in here. (must not)", ["mustn't"]),
      qmcq("Which sentence is correct?", [
        "We don't have to book in advance.",
        "We don't have to booking in advance.",
        "We haven't to book in advance.",
      ], 0),
    ],
    scenes: [
      sc("Elif", "a friend worried about a dress code", "to find out what is really required",
        "A friend is nervous about an event and unsure what the rules are.",
        "Explain which things are optional and which are not.",
        "I have no idea what to wear or what the rules are. Can you help?", "anxious"),
      sc("Gerard", "a colleague explaining site rules", "to make sure you understand the safety rules",
        "You are visiting a site with strict safety rules.",
        "Repeat back which rules are strict and which are optional.",
        "Some of these rules are serious and some are not. Shall I run through them?", "serious"),
      sc("Malia", "a hostel receptionist", "to explain the house rules",
        "You have just checked in and are being told the rules.",
        "Check which rules are strict.",
        "There are a few rules here. Would you like me to explain them?", "friendly"),
      sc("Mrs. Adeyemi", "your teacher", "to practise the two forms",
        "The class is sorting rules into optional and forbidden.",
        "Give one example of each.",
        "Think of a place you know. What is optional there, and what is forbidden?", "encouraging"),
      sc("Mr. Vidal", "the examiner", "to check the distinction",
        "The examiner asks about rules in a place you know.",
        "Distinguish clearly between optional and forbidden.",
        "Could you tell me about the rules where you work or study?", "neutral"),
    ],
  },

  {
    id: "a2-you-should-rest",
    topic: "giving advice",
    objectives: [
      "Give advice with should and shouldn't.",
      "Soften advice so it does not sound like an order.",
    ],
    goal: "Give a friend advice about a problem.",
    target: "should and shouldn't for advice",
    correction: "Model the advice with should and let the learner give their own.",
    summary: "You learned to give advice with should and shouldn't, and to soften it.",
    minutes: 7,
    points: [
      {
        form: "you should",
        claims: [
          "'Should' is followed by the base verb, with no 'to'.",
          "It gives advice, not an order: the other person can still decide.",
        ],
        ex: ["You should rest for a few days.", "You should talk to your manager."],
      },
      {
        form: "you shouldn't",
        claims: [
          "'Shouldn't' advises against something.",
          "It is softer than 'mustn't', which is about rules rather than advice.",
        ],
        ex: ["You shouldn't work so late every night.", "You shouldn't worry about it."],
      },
      {
        form: "maybe you should",
        claims: [
          "'Maybe' or 'I think' before 'you should' makes the advice gentler.",
          "'Why don't you' is another friendly way to suggest the same thing.",
        ],
        ex: ["Maybe you should take a day off.", "I think you should call her."],
      },
    ],
    ex: [
      fill("You ___ rest for a few days. (should)", ["should"]),
      mcq("Which sentence is correct?", [
        "You should talk to your manager.",
        "You should to talk to your manager.",
        "You should talking to your manager.",
      ], 0),
      fill("You ___ work so late every night. (should not)", ["shouldn't", "should not"]),
      say("maybe / you / should / take a day off", ["Maybe you should take a day off."]),
    ],
    open: {
      q: "A friend is working too much and sleeping badly. Give them two pieces of advice.",
      must: ["you should", "you shouldn't", "maybe you should"],
      criteria: "The answer gives advice with should or shouldn't and sounds friendly rather than commanding.",
      example: "You should talk to your manager about the hours, and maybe you should take a day off this week.",
    },
    success: "The learner gives at least two pieces of advice using should or shouldn't.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "You shouldn't worry about it.",
        "You shouldn't to worry about it.",
        "You not should worry about it.",
      ], 0),
      qfill("Maybe you ___ ask for help. (should)", ["should"]),
      qmcq("Which sentence is advice, not a rule?", [
        "You should get more sleep.",
        "You mustn't enter this room.",
        "You have to show your badge.",
      ], 0),
    ],
    scenes: [
      sc("Tomas", "a friend who is exhausted", "to get some honest advice",
        "A friend has been working late every night for weeks.",
        "Give friendly advice.",
        "I have not slept properly in two weeks. What would you do?", "tired"),
      sc("Sonia", "a colleague under pressure", "to hear how to handle the workload",
        "A colleague has taken on too much work.",
        "Advise them without sounding bossy.",
        "I said yes to everything and now I cannot cope. Any ideas?", "stressed"),
      sc("Dr. Farah", "a doctor at a walk-in clinic", "to give you advice about resting",
        "You are being advised about a minor health problem.",
        "Ask questions and repeat the advice you are given.",
        "It is nothing serious, but you need to look after yourself. What is your routine like?", "calm"),
      sc("Mr. Lindqvist", "your teacher", "to practise giving advice",
        "The class is role-playing advice for common problems.",
        "Give advice about a problem.",
        "Your partner cannot sleep. What advice would you give?", "encouraging"),
      sc("Ms. Duarte", "the examiner", "to check advice forms",
        "The examiner describes a problem and asks for advice.",
        "Give clear, friendly advice.",
        "A friend of mine is always tired and works too much. What should they do?", "neutral"),
    ],
  },

  {
    id: "a2-can-i-ask-something",
    topic: "polite requests and permission",
    objectives: [
      "Ask for things politely with could and may.",
      "Ask for permission in a formal situation.",
    ],
    goal: "Ask for something politely in a formal situation.",
    target: "could and may for polite requests",
    correction: "Model the polite form and let the learner ask again more politely.",
    summary: "You learned to ask politely with could, may and softer phrases.",
    minutes: 7,
    points: [
      {
        form: "could you",
        claims: [
          "'Could you' plus the base verb asks someone to do something politely.",
          "It is softer than 'can you' and much softer than the plain imperative.",
        ],
        ex: ["Could you send me the file, please?", "Could you help me with this form?"],
      },
      {
        form: "may I",
        claims: [
          "'May I' asks for permission and is the most formal of these forms.",
          "'Could I' is slightly less formal and very common.",
        ],
        ex: ["May I ask you something?", "Could I use your phone for a moment?"],
      },
      {
        form: "would it be okay",
        claims: [
          "'Would it be okay if ...' softens a bigger request.",
          "Adding 'please' and a reason makes any request easier to accept.",
        ],
        ex: ["Would it be okay if I left early?", "Would it be okay to bring a friend?"],
      },
    ],
    ex: [
      fill("___ you send me the file, please? (could)", ["Could"]),
      mcq("Which request is the most formal?", [
        "May I ask you something?",
        "Can I ask you something?",
        "Ask you something?",
      ], 0),
      fill("Would it be ___ if I left a bit early?", ["okay", "ok"]),
      say("could / I / use / your phone", ["Could I use your phone?", "May I use your phone?"]),
    ],
    open: {
      q: "You need to leave a meeting early. Ask permission politely and give a short reason.",
      must: ["could you", "may I", "would it be okay"],
      criteria: "The answer asks for permission politely using could, may or a softening phrase.",
      example: "Would it be okay if I left at four today? May I explain the reason after the meeting?",
    },
    success: "The learner makes at least two polite requests with the correct forms.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "Could you help me with this form?",
        "Could you to help me with this form?",
        "Could you helping me with this form?",
      ], 0),
      qfill("___ I ask you a question? (may)", ["May"]),
      qmcq("Which request is polite?", [
        "Could I use your phone for a moment?",
        "Give me your phone.",
        "I use your phone now.",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Alonso", "your landlord", "to hear your request about the flat",
        "You need to ask your landlord for something.",
        "Make the request politely.",
        "You said you wanted to discuss something. What is it?", "formal"),
      sc("Mr. Reddy", "a senior manager", "to consider your request",
        "You need permission from someone senior.",
        "Ask politely and give a reason.",
        "You wanted a word before the meeting. What is it?", "busy"),
      sc("Ana Lucia", "a hotel receptionist", "to handle your request",
        "You need something from the hotel that is not standard.",
        "Ask politely.",
        "Good evening. Is there anything you need?", "professional"),
      sc("Mr. Bergstrom", "your teacher", "to practise polite requests",
        "The class is practising formal and informal requests.",
        "Make the same request politely.",
        "How would you ask a stranger for help with a heavy bag?", "encouraging"),
      sc("Ms. Whitfield", "the examiner", "to check polite request forms",
        "The examiner asks you to make a request.",
        "Ask politely and appropriately.",
        "Imagine you need to leave early. How would you ask me?", "neutral"),
    ],
  },

  {
    id: "a2-whats-the-matter",
    topic: "talking about health problems",
    objectives: [
      "Say how you feel and where it hurts.",
      "Understand simple advice from a doctor.",
    ],
    goal: "Explain a health problem at a clinic.",
    target: "describing health problems",
    correction: "Model the natural way to describe the problem and let the learner repeat it.",
    summary: "You learned to describe how you feel and where it hurts, and to follow simple advice.",
    minutes: 6,
    points: [
      {
        form: "I don't feel well",
        claims: [
          "'I don't feel well' is the usual general way to say you are ill.",
          "'I feel sick' in British English usually means you might vomit.",
        ],
        ex: ["I don't feel well today.", "I've felt tired all week."],
      },
      {
        form: "my head hurts",
        claims: [
          "Say the body part plus 'hurts' for one place, or 'I have a' plus the problem.",
          "'I have a headache' and 'my head hurts' mean the same thing.",
        ],
        ex: ["My head hurts and my throat is sore.", "I have a bad cough."],
      },
      {
        form: "you should see",
        claims: [
          "Advice at a clinic usually comes with 'you should' or 'try to'.",
          "'You should see a doctor' means go to a doctor about it.",
        ],
        ex: ["You should see a doctor if it continues.", "You should drink plenty of water."],
      },
    ],
    ex: [
      fill("I ___ feel well today. (do not)", ["don't", "do not"]),
      mcq("Which sentence describes a problem?", [
        "My head hurts and my throat is sore.",
        "My head is my favourite.",
        "I will head to the clinic.",
      ], 0),
      say("I / have / a bad cough", ["I have a bad cough.", "I've got a bad cough."]),
    ],
    open: {
      q: "You feel ill and are at a clinic. Describe your symptoms and how long you have felt like this.",
      must: ["I don't feel well", "my head hurts"],
      criteria: "The answer describes symptoms clearly and says how long they have lasted.",
      example: "I don't feel well. My head hurts and I have had a sore throat since Monday.",
    },
    success: "The learner describes at least two symptoms clearly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "My back hurts when I sit for a long time.",
        "My back hurt when I sit for a long time.",
        "My back is hurt when I sit for a long time.",
      ], 0),
      qfill("I have a ___ throat and I cannot swallow easily. (painful)", ["sore"]),
      qmcq("Which sentence is advice?", [
        "You should drink plenty of water.",
        "I drank plenty of water.",
        "The water is over there.",
      ], 0),
    ],
    scenes: [
      sc("Dr. Mensah", "the doctor at a walk-in clinic", "to work out what is wrong with you",
        "You have come to a clinic without an appointment.",
        "Describe your symptoms clearly.",
        "Come in and sit down. What seems to be the problem?", "calm"),
      sc("Iris", "the office first aider", "to decide whether you should go home",
        "You feel unwell at work and someone has noticed.",
        "Explain how you feel.",
        "You look pale. How are you feeling?", "concerned"),
      sc("Pedro", "a pharmacist abroad", "to find you something for your symptoms",
        "You are unwell while travelling and go to a pharmacy.",
        "Describe your symptoms and ask for something.",
        "Good morning. What can I get for you?", "helpful"),
      sc("Ms. Kowalski", "your teacher", "to practise health language",
        "The class is role-playing a clinic visit.",
        "Describe symptoms to a doctor.",
        "You are the patient today. What is wrong?", "encouraging"),
      sc("Mr. Serrano", "the examiner", "to check health vocabulary",
        "The examiner asks about a time you were unwell.",
        "Describe the symptoms clearly.",
        "Could you tell me about a time when you were ill and what you did?", "neutral"),
    ],
  },

  {
    id: "a2-a-friend-needs-help",
    topic: "listening to a problem and advising",
    objectives: [
      "Show that you understand someone's problem.",
      "Give advice from your own point of view.",
    ],
    goal: "Listen to a friend's problem and help them think it through.",
    target: "responding to a problem and giving advice",
    correction: "Model the sympathetic reply and let the learner continue advising.",
    summary: "You practised listening to a problem, showing sympathy and giving advice.",
    minutes: 6,
    points: [
      {
        form: "that sounds hard",
        claims: [
          "React to the problem before you advise; advice without sympathy sounds cold.",
          "'That sounds hard' and 'I'm sorry to hear that' both work well.",
        ],
        ex: ["That sounds hard.", "I'm sorry to hear that."],
      },
      {
        form: "have you tried",
        claims: [
          "'Have you tried' is followed by a verb with -ing.",
          "It suggests something without assuming the person has not thought of it.",
        ],
        ex: ["Have you tried talking to your manager?", "Have you tried writing it down?"],
      },
      {
        form: "if I were you",
        claims: [
          "'If I were you' introduces advice from your own point of view.",
          "It is usually followed by 'I would' plus the base verb.",
        ],
        ex: ["If I were you, I'd wait a week.", "If I were you, I would ask for more time."],
      },
    ],
    ex: [
      fill("That ___ hard. I'm sorry.", ["sounds"]),
      mcq("Which sentence is correct?", [
        "Have you tried talking to your manager?",
        "Have you tried talk to your manager?",
        "Have you tried to talking to your manager?",
      ], 0),
      say("if I were you / I / would / wait", ["If I were you, I would wait.", "If I were you, I'd wait."]),
    ],
    open: {
      q: "A friend is unsure whether to change jobs. React to their problem and give one piece of advice.",
      must: ["if I were you", "have you tried", "that sounds hard"],
      criteria: "The answer shows sympathy first and then gives advice in a friendly way.",
      example: "That sounds hard. Have you tried writing down the good and bad points? If I were you, I'd wait a month.",
    },
    success: "The learner reacts with sympathy and gives at least one piece of advice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "If I were you, I would ask for more time.",
        "If I were you, I will ask for more time.",
        "If I am you, I would ask for more time.",
      ], 0),
      qfill("Have you ___ speaking to her directly? (try)", ["tried"]),
      qmcq("Which sentence shows sympathy?", [
        "That sounds hard.",
        "That is your problem.",
        "I did that last year.",
      ], 0),
    ],
    scenes: [
      sc("Joaquin", "a friend thinking about quitting", "to talk the decision through with you",
        "A friend has been offered a new job and cannot decide.",
        "Listen, react and advise.",
        "I got the offer, but now I am terrified. Can I talk it through with you?", "uncertain"),
      sc("Renata", "a colleague struggling with workload", "to find a way forward",
        "A colleague is close to burning out.",
        "React with sympathy and suggest something.",
        "I am drowning in work and I do not know where to start. Any thoughts?", "overwhelmed"),
      sc("Kofi", "a fellow traveller who lost his bag", "to work out what to do next",
        "Someone you met while travelling has lost their documents.",
        "Sympathise and suggest steps.",
        "My bag is gone, with everything in it. What would you do?", "shaken"),
      sc("Mrs. Nowak", "your teacher", "to practise sympathetic advice",
        "The class is role-playing supportive conversations.",
        "React and advise about a problem.",
        "Your partner has a problem to share. How will you respond?", "encouraging"),
      sc("Mr. Delacroix", "the examiner", "to check advice and reaction language",
        "The examiner describes a personal dilemma.",
        "React appropriately and advise.",
        "I have been offered a job in another city but my family is here. What would you say?", "neutral"),
    ],
  },

  // --- Ünite 5 · Experiences -------------------------------------------------
  {
    id: "a2-have-you-ever-been",
    topic: "asking about life experience",
    objectives: [
      "Ask about someone's life experience with 'ever'.",
      "Answer with a short present perfect answer.",
    ],
    goal: "Find out what unusual things someone has done in their life.",
    target: "present perfect with ever for experience",
    correction: "Repeat the question in the correct form and let the learner ask it again.",
    summary: "You learned to ask about experience with 'have you ever' and to answer shortly.",
    minutes: 7,
    points: [
      {
        form: "have you ever + past participle",
        claims: [
          "Use have or has plus the third form of the verb: been, seen, tried, eaten.",
          "'Ever' means at any time in your life and goes before the verb.",
        ],
        ex: ["Have you ever been to Japan?", "Have you ever tried diving?"],
      },
      {
        form: "yes I have / no I haven't",
        claims: [
          "Short answers repeat have or haven't, not the main verb.",
          "'Yes, I have' is complete on its own.",
        ],
        ex: ["Yes, I have.", "No, I haven't."],
      },
      {
        form: "no time expression",
        claims: [
          "This use does not say WHEN something happened, only that it happened.",
          "If you add a past time like 'last year', use the past simple instead.",
        ],
        ex: ["I have been to Italy twice.", "I went there last summer."],
      },
    ],
    ex: [
      fill("___ you ever been to Japan? (have)", ["Have"]),
      mcq("Which question is correct?", [
        "Have you ever tried diving?",
        "Have you ever try diving?",
        "Did you ever have tried diving?",
      ], 0),
      fill("Yes, I ___. I went in 2019.", ["have"]),
      say("I / have / be / to Italy / twice", ["I have been to Italy twice.", "I've been to Italy twice."]),
    ],
    open: {
      q: "Ask me three questions about unusual things I might have done in my life.",
      must: ["have you ever", "yes I have", "I have been to"],
      criteria: "The answer asks experience questions with 'have you ever' and the correct verb form.",
      example: "Have you ever been to Asia? Have you ever tried skiing? I have been to Spain, but never further.",
    },
    success: "The learner asks at least two correct 'have you ever' questions.",
    quiz: [
      qmcq("Which question is correct?", [
        "Have you ever seen a whale?",
        "Have you ever saw a whale?",
        "Did you ever seen a whale?",
      ], 0),
      qfill("___ she ever worked abroad? (have)", ["Has"]),
      qmcq("Which answer is correct?", ["Yes, I have.", "Yes, I did have.", "Yes, I am."], 0),
    ],
    scenes: [
      sc("Valentina", "someone you just met at a party", "to find something interesting you have in common",
        "Two people are getting to know each other at a party.",
        "Ask about each other's experiences.",
        "I am terrible at small talk. Ask me something interesting instead?", "playful"),
      sc("Daniel", "an interviewer", "to learn about your professional experience",
        "You are being asked about what you have done before.",
        "Ask and answer about experience.",
        "Before we start, is there anything you would like to ask me about the role?", "professional"),
      sc("Marisol", "a tour guide", "to find out what the group has already done",
        "The guide wants to avoid repeating things people have done.",
        "Say what you have and have not done.",
        "Before I plan the day, has anyone been to this region before?", "organised"),
      sc("Mr. Owusu", "your teacher", "to practise experience questions",
        "The class is interviewing each other about experiences.",
        "Ask your partner about their experiences.",
        "Find three unusual things your partner has done. Where do you start?", "encouraging"),
      sc("Ms. Fontaine", "the examiner", "to check experience questions",
        "The examiner invites you to ask about their life.",
        "Ask clear experience questions.",
        "This time you may ask me. What would you like to know about my experiences?", "neutral"),
    ],
  },

  {
    id: "a2-ive-never-tried-that",
    topic: "saying what you have not done",
    objectives: [
      "Use 'never' to say something has not happened in your life.",
      "Avoid using two negatives together.",
    ],
    goal: "Admit the ordinary things you have somehow never done.",
    target: "present perfect with never",
    correction: "Repeat the sentence with a single negative and let the learner say it again.",
    summary: "You learned to say what you have never done, without doubling the negative.",
    minutes: 7,
    points: [
      {
        form: "I've never",
        claims: [
          "'Never' already makes the sentence negative, so 'have' stays positive.",
          "Say 'I have never been', not 'I haven't never been'.",
        ],
        ex: ["I've never tried sushi.", "I've never been to a football match."],
      },
      {
        form: "she's never",
        claims: [
          "After he, she and it the form is 'has never'.",
          "The third form of the verb does not change with the person.",
        ],
        ex: ["She's never worked abroad.", "He's never seen the sea."],
      },
      {
        form: "never in my life",
        claims: [
          "'Never in my life' adds emphasis to a surprising admission.",
          "'I still haven't' says you expected to do it by now.",
        ],
        ex: ["Never in my life have I broken a bone.", "I still haven't seen that film."],
      },
    ],
    ex: [
      fill("I've ___ tried sushi, believe it or not.", ["never"]),
      mcq("Which sentence is correct?", [
        "I've never been to a football match.",
        "I haven't never been to a football match.",
        "I've never been to a football match not.",
      ], 0),
      fill("She ___ never worked abroad. (have)", ["has", "'s"]),
      say("he / have / never / see / the sea", ["He has never seen the sea.", "He's never seen the sea."]),
    ],
    open: {
      q: "Name two ordinary things you have never done, and say whether you would like to.",
      must: ["I've never", "never in my life"],
      criteria: "The answer says what the speaker has never done, using a single negative correctly.",
      example: "I've never learned to swim, and never in my life have I been on a boat.",
    },
    success: "The learner uses 'never' with the present perfect correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I have never eaten octopus.",
        "I haven't never eaten octopus.",
        "I have never ate octopus.",
      ], 0),
      qfill("He ___ never driven a car. (have)", ["has"]),
      qmcq("Which sentence is correct?", [
        "She's never been abroad.",
        "She's never was abroad.",
        "She hasn't never been abroad.",
      ], 0),
    ],
    scenes: [
      sc("Bruna", "a friend who is easily surprised", "to discover what you have never done",
        "Two friends are confessing ordinary things they have never done.",
        "Admit things you have never done.",
        "I still cannot ride a bike. Please tell me you have a confession too?", "amused"),
      sc("Anton", "a colleague planning a team activity", "to pick an activity nobody has done",
        "The team wants an activity that is new to everyone.",
        "Say what you have and have not done.",
        "I want something new for everyone. What have you never done?", "planning"),
      sc("Sofia", "a guide offering activities", "to find something new for you to try",
        "The guide is offering several local experiences.",
        "Say which ones you have never tried.",
        "We offer five activities here. Which of them are new to you?", "encouraging"),
      sc("Mr. Baptiste", "your teacher", "to practise 'never' sentences",
        "The class is sharing surprising confessions.",
        "Say what you have never done.",
        "What is one ordinary thing you have somehow never done?", "warm"),
      sc("Mrs. Ilves", "the examiner", "to check negative experience forms",
        "The examiner asks about things you have not done.",
        "Answer using 'never' correctly.",
        "Could you tell me about something you have never done but would like to try?", "neutral"),
    ],
  },

  {
    id: "a2-been-or-gone",
    topic: "the difference between been and gone",
    objectives: [
      "Use 'has been to' for a completed visit.",
      "Use 'has gone to' for someone who is still away.",
    ],
    goal: "Explain where your colleagues are and where they have travelled.",
    target: "has been to versus has gone to",
    correction: "Contrast the two sentences and let the learner choose the right one.",
    summary: "You learned that 'been to' means came back and 'gone to' means still away.",
    minutes: 7,
    points: [
      {
        form: "I've been to",
        claims: [
          "'Been to' means the person visited the place and has returned.",
          "This is the form used for life experience.",
        ],
        ex: ["I've been to Paris three times.", "She's been there before."],
      },
      {
        form: "he's gone to",
        claims: [
          "'Gone to' means the person is on the way there or still there.",
          "You cannot say 'I've gone to' about yourself while you are here.",
        ],
        ex: ["He's gone to the bank, he'll be back at three.", "They've gone to the airport."],
      },
      {
        form: "been in / been to",
        claims: [
          "'Been to' points to the visit; 'been in' points to time spent inside a place.",
          "Both take the same verb form.",
        ],
        ex: ["I've been to the new office once.", "We've been in this building for two years."],
      },
    ],
    ex: [
      fill("He's ___ to the bank, he'll be back at three. (go)", ["gone"]),
      mcq("Which sentence means the person has returned?", [
        "She's been to Rome twice.",
        "She's gone to Rome.",
        "She goes to Rome.",
      ], 0),
      fill("I've ___ to Paris three times. (be)", ["been"]),
      say("they / have / go / to the airport", ["They have gone to the airport.", "They've gone to the airport."]),
    ],
    open: {
      q: "Say where a colleague or family member is right now, and one place they have visited before.",
      must: ["he's gone to", "I've been to", "she's been there"],
      criteria: "The answer uses 'gone to' for someone still away and 'been to' for a completed visit.",
      example: "My colleague has gone to the airport, so he isn't here. I've been to that airport once myself.",
    },
    success: "The learner uses 'been to' and 'gone to' with the correct meanings.",
    quiz: [
      qmcq("Which sentence is correct if the person is still away?", [
        "She's gone to the shops.",
        "She's been to the shops and is still there.",
        "She goes to the shops now.",
      ], 0),
      qfill("I've ___ to Italy twice. (be)", ["been"]),
      qmcq("Which sentence is correct?", [
        "They've gone to the airport, so they aren't here.",
        "They've been to the airport, so they aren't here.",
        "They've go to the airport, so they aren't here.",
      ], 0),
    ],
    scenes: [
      sc("Camila", "a colleague looking for someone", "to find out where a team member is",
        "Someone is looking for a colleague who is not at their desk.",
        "Explain where people are and where they have been.",
        "I cannot find anyone today. Do you know where they all are?", "hurried"),
      sc("Wouter", "your manager", "to know who is available this week",
        "Several people are travelling and the manager needs a picture.",
        "Report who is away and who has already returned.",
        "Half the team seems to be travelling. Can you give me the picture?", "practical"),
      sc("Nia", "a hotel receptionist", "to pass on a message to your colleague",
        "You are leaving a message for someone who is out.",
        "Explain where the person has gone.",
        "I am afraid your colleague is not here. Shall I take a message?", "polite"),
      sc("Mr. Farrell", "your teacher", "to practise been and gone",
        "The class is describing where people are.",
        "Use both forms correctly.",
        "Someone is away right now, and someone has returned. How do you say each?", "encouraging"),
      sc("Ms. Sorensen", "the examiner", "to check been and gone",
        "The examiner asks about people you know.",
        "Distinguish the two forms clearly.",
        "Could you tell me where someone you know is right now, and where they have travelled before?", "neutral"),
    ],
  },

  {
    id: "a2-tell-me-more",
    topic: "keeping a conversation going",
    objectives: [
      "Ask follow-up questions about someone's experience.",
      "Show interest so the other person keeps talking.",
    ],
    goal: "Keep a conversation going when someone shares news.",
    target: "follow-up questions about experience",
    correction: "Model the follow-up question and let the learner ask their own.",
    summary: "You learned follow-up questions that keep a conversation going.",
    minutes: 6,
    points: [
      {
        form: "what was it like",
        claims: [
          "'What was it like?' asks for a description, not a yes or no answer.",
          "It is the natural follow-up when someone mentions a place or event.",
        ],
        ex: ["What was it like?", "What was the food like there?"],
      },
      {
        form: "how long",
        claims: [
          "'How long' asks about duration and is answered with a period of time.",
          "'How long did you stay?' and 'How long have you been there?' ask about different times.",
        ],
        ex: ["How long did you stay?", "How long have you known each other?"],
      },
      {
        form: "tell me more",
        claims: [
          "'Tell me more about ...' invites the other person to continue.",
          "Short reactions like 'really?' and 'that sounds great' do the same job.",
        ],
        ex: ["Tell me more about the trip.", "Really? That sounds great."],
      },
    ],
    ex: [
      fill("What ___ it like? Was it busy?", ["was"]),
      mcq("Which question asks for a description?", [
        "What was it like?",
        "Did you go there?",
        "Was it Tuesday?",
      ], 0),
      say("tell me more / about / the trip", ["Tell me more about the trip."]),
    ],
    open: {
      q: "I just told you I came back from a long trip. Ask me three follow-up questions.",
      must: ["what was it like", "how long", "tell me more"],
      criteria: "The answer asks open follow-up questions that invite a longer reply.",
      example: "What was it like? How long were you there? Tell me more about the people you met.",
    },
    success: "The learner asks at least two open follow-up questions.",
    quiz: [
      qmcq("Which question invites a longer answer?", [
        "What was the weather like?",
        "Was the weather good?",
        "Did it rain?",
      ], 0),
      qfill("___ long did you stay there?", ["How"]),
      qmcq("Which phrase invites someone to continue?", [
        "Tell me more about it.",
        "That is all, thanks.",
        "I have to go now.",
      ], 0),
    ],
    scenes: [
      sc("Idris", "a friend back from a long trip", "to share the story if you ask the right questions",
        "A friend has just returned and is waiting to be asked.",
        "Ask follow-up questions to keep them talking.",
        "So, I am back! Three months on the road. Where do I start?", "excited"),
      sc("Freya", "a colleague who changed roles", "to talk about the new job",
        "A colleague has moved to a different department.",
        "Ask about the new role.",
        "I finished my first week in the new team. Do you want to hear about it?", "chatty"),
      sc("Tobias", "another guest with stories", "to tell you about the region",
        "Someone at the hostel has been travelling for months.",
        "Ask questions that keep them talking.",
        "I have been on this continent since March. What do you want to know?", "relaxed"),
      sc("Mrs. Gallagher", "your teacher", "to practise follow-up questions",
        "The class is practising keeping conversations alive.",
        "Ask open follow-up questions.",
        "Your partner just said they had an amazing weekend. What do you ask?", "encouraging"),
      sc("Mr. Nakamura", "the examiner", "to check conversational questions",
        "The examiner mentions something briefly and waits.",
        "Ask follow-up questions naturally.",
        "I spent last month in a very unusual place. Anything you want to ask?", "neutral"),
    ],
  },

  {
    id: "a2-ive-already-finished",
    topic: "saying something happened sooner than expected",
    objectives: [
      "Use 'already' for something finished sooner than expected.",
      "Use 'just' for something finished a moment ago.",
    ],
    goal: "Report progress on a task you share with someone.",
    target: "present perfect with already and just",
    correction: "Repeat the sentence with the word in its natural position and let the learner try again.",
    summary: "You learned to use already and just to say when something was finished.",
    minutes: 7,
    points: [
      {
        form: "I've already",
        claims: [
          "'Already' says the action happened sooner than the other person expected.",
          "It goes between have and the third form of the verb.",
        ],
        ex: ["I've already sent the email.", "We've already booked the room."],
      },
      {
        form: "I've just",
        claims: [
          "'Just' says the action finished a very short time ago.",
          "It sits in the same place as 'already', between have and the verb.",
        ],
        ex: ["I've just finished the report.", "She's just left the office."],
      },
      {
        form: "why the present perfect",
        claims: [
          "These sentences connect a past action to the situation right now.",
          "If you say exactly when it happened, switch to the past simple.",
        ],
        ex: ["I've already eaten, thanks.", "I ate at one o'clock."],
      },
    ],
    ex: [
      fill("I've ___ sent the email, so you don't need to. (already)", ["already"]),
      mcq("Which sentence is correct?", [
        "I've just finished the report.",
        "I've finished just the report.",
        "I just have finished the report.",
      ], 0),
      fill("She's ___ left the office, about two minutes ago. (just)", ["just"]),
      say("we / have / already / book / the room", ["We have already booked the room.", "We've already booked the room."]),
    ],
    open: {
      q: "Someone asks you to do three things. Say which ones you have already done and which you have just finished.",
      must: ["I've already", "I've just"],
      criteria: "The answer reports progress using already and just in the correct position.",
      example: "I've already sent the invitations, and I've just finished the list you asked for.",
    },
    success: "The learner uses already and just correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We've already booked the room.",
        "We've booked already the room.",
        "We already have book the room.",
      ], 0),
      qfill("She's ___ left, you missed her by a minute. (just)", ["just"]),
      qmcq("Which sentence says it happened a moment ago?", [
        "I've just spoken to her.",
        "I spoke to her last week.",
        "I speak to her every week.",
      ], 0),
    ],
    scenes: [
      sc("Halima", "a flatmate checking on chores", "to find out what still needs doing",
        "Two flatmates are working through a list of jobs.",
        "Report what you have already done.",
        "I made a list this morning. What is left?", "practical"),
      sc("Viktor", "your team leader", "to get a progress update",
        "Your team leader wants a quick status on three tasks.",
        "Report progress on each.",
        "Quick update before the call: where are we on the three items?", "brisk"),
      sc("Elodie", "a tour coordinator", "to check what the group has arranged",
        "The group is preparing for tomorrow's departure.",
        "Say what you have already arranged.",
        "We leave early tomorrow. Is everything sorted on your side?", "organised"),
      sc("Mr. Achebe", "your teacher", "to practise already and just",
        "The class is reporting on a shared project.",
        "Report progress with already and just.",
        "What have you already finished, and what have you just started?", "encouraging"),
      sc("Ms. Lindberg", "the examiner", "to check already and just",
        "The examiner asks about your recent progress.",
        "Report using already and just correctly.",
        "Could you tell me what you have already done today?", "neutral"),
    ],
  },

  {
    id: "a2-have-you-done-it-yet",
    topic: "asking whether something is finished",
    objectives: [
      "Ask whether something is finished with 'yet'.",
      "Say something has not happened so far.",
    ],
    goal: "Chase up things that were supposed to be done.",
    target: "present perfect questions and negatives with yet",
    correction: "Repeat the question with 'yet' at the end and let the learner ask again.",
    summary: "You learned to ask and answer about unfinished things using 'yet'.",
    minutes: 7,
    points: [
      {
        form: "have you finished ... yet?",
        claims: [
          "'Yet' usually goes at the end of a question or a negative sentence.",
          "It means up to now, and expects that the thing will happen.",
        ],
        ex: ["Have you finished the report yet?", "Has she replied yet?"],
      },
      {
        form: "not yet",
        claims: [
          "'Not yet' is a complete answer on its own.",
          "'Not yet, but soon' softens it and gives information.",
        ],
        ex: ["Not yet, I am still working on it.", "Not yet, but I'll do it this afternoon."],
      },
      {
        form: "I haven't ... yet",
        claims: [
          "The full negative is 'I haven't' plus the third form plus 'yet'.",
          "'Already' does not fit here; 'yet' belongs with questions and negatives.",
        ],
        ex: ["I haven't finished it yet.", "They haven't answered yet."],
      },
    ],
    ex: [
      fill("Have you finished the report ___?", ["yet"]),
      mcq("Which question is correct?", [
        "Has she replied yet?",
        "Has she yet replied already?",
        "Did she has replied yet?",
      ], 0),
      fill("I ___ finished it yet, sorry. (have not)", ["haven't", "have not"]),
      say("they / have not / answer / yet", ["They haven't answered yet.", "They have not answered yet."]),
    ],
    open: {
      q: "Three things were due today. Ask about two of them and admit one you have not done.",
      must: ["have you finished", "not yet", "I haven't yet"],
      criteria: "The answer asks about unfinished tasks with 'yet' and admits one unfinished task.",
      example: "Have you finished the summary yet? Has the client replied? I haven't sent mine yet, sorry.",
    },
    success: "The learner uses 'yet' correctly in a question and in a negative sentence.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I haven't sent it yet.",
        "I haven't yet sent already.",
        "I didn't have sent it yet.",
      ], 0),
      qfill("Have they arrived ___?", ["yet"]),
      qmcq("Which answer means it is not finished?", ["Not yet.", "Already done.", "Yes, this morning."], 0),
    ],
    scenes: [
      sc("Sanjay", "a flatmate waiting on you", "to find out whether the jobs are done",
        "Two flatmates agreed on jobs and one is behind.",
        "Ask and admit what is not done.",
        "The landlord is coming tomorrow. How are we doing?", "anxious"),
      sc("Petra", "your project manager", "to chase three outstanding items",
        "Three tasks were due and none have been confirmed.",
        "Ask about them and report honestly.",
        "I need a straight answer on the three items. Where are we?", "direct"),
      sc("Milo", "a travel companion", "to check the group is ready to leave",
        "The group has to leave in an hour and things are unfinished.",
        "Ask what is done and admit what is not.",
        "We leave in one hour. Is everyone packed?", "hurried"),
      sc("Mrs. Silva", "your teacher", "to practise 'yet' questions",
        "The class is chasing up unfinished homework.",
        "Ask and answer with 'yet'.",
        "Have you finished the task I set last week?", "encouraging"),
      sc("Mr. Andersson", "the examiner", "to check 'yet' forms",
        "The examiner asks about unfinished plans.",
        "Use 'yet' correctly in questions and negatives.",
        "Is there something you planned to do this year but have not done?", "neutral"),
    ],
  },

  {
    id: "a2-two-truths-and-a-lie",
    topic: "sharing unusual experiences",
    objectives: [
      "Share unusual experiences from your life.",
      "React with doubt when something sounds unlikely.",
    ],
    goal: "Play a guessing game about each other's experiences.",
    target: "sharing and questioning experiences",
    correction: "Model the experience sentence and let the learner produce their own.",
    summary: "You practised sharing unusual experiences and questioning the ones that sound unlikely.",
    minutes: 6,
    points: [
      {
        form: "I've never",
        claims: [
          "A surprising 'never' is often more interesting than a long story.",
          "Keep the sentence short so the listener can react.",
        ],
        ex: ["I've never eaten a banana.", "I've never travelled by plane."],
      },
      {
        form: "have you ever",
        claims: [
          "Turn the game back with a question about the other person.",
          "'Have you ever' keeps the conversation moving between you.",
        ],
        ex: ["Have you ever done anything like that?", "Have you ever met someone famous?"],
      },
      {
        form: "that can't be true",
        claims: [
          "'That can't be true' expresses strong doubt in a friendly way.",
          "'Really?' and 'You're joking' do the same job more softly.",
        ],
        ex: ["That can't be true!", "Really? I don't believe you."],
      },
    ],
    ex: [
      fill("I've ___ eaten a banana in my life.", ["never"]),
      mcq("Which sentence expresses doubt?", [
        "That can't be true!",
        "That is true.",
        "That was last year.",
      ], 0),
      say("have you ever / meet / someone famous", ["Have you ever met someone famous?"]),
    ],
    open: {
      q: "Tell me three things about your life: two true and one false. Then ask me a question.",
      must: ["I've never", "have you ever"],
      criteria: "The answer shares experiences with the present perfect and asks an experience question.",
      example: "I've been to four countries. I've met a famous singer. I've never learned to swim. Have you ever?",
    },
    success: "The learner shares experiences and asks at least one experience question.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I've never travelled by plane.",
        "I've never travel by plane.",
        "I never have travelled by plane not.",
      ], 0),
      qfill("Have you ___ met someone famous? (ever)", ["ever"]),
      qmcq("Which reply shows doubt?", ["That can't be true!", "That sounds right.", "I agree completely."], 0),
    ],
    scenes: [
      sc("Zeynep", "a new colleague at a team lunch", "to break the ice with a game",
        "New colleagues are playing a guessing game over lunch.",
        "Share experiences and question theirs.",
        "Let us play two truths and a lie. You go first?", "playful"),
      sc("Callum", "a colleague at an away day", "to get to know the team better",
        "The team is doing an icebreaker activity.",
        "Share and question experiences.",
        "The facilitator wants us to share something surprising. Ready?", "game"),
      sc("Ariana", "a traveller at a shared dinner", "to swap unusual travel stories",
        "Travellers at a hostel dinner are comparing stories.",
        "Share unusual experiences.",
        "Everyone here has one strange story. What is yours?", "curious"),
      sc("Mr. Kimura", "your teacher", "to practise experience forms in a game",
        "The class is playing an experience guessing game.",
        "Share three statements and question your partner.",
        "Two truths and one lie about your life. What are they?", "encouraging"),
      sc("Ms. Bianchi", "the examiner", "to check experience language",
        "The examiner invites you to share unusual experiences.",
        "Share them and ask one question back.",
        "Could you tell me about something unusual you have done?", "neutral"),
    ],
  },
];
