/** A2 · Ünite 8-9 — Getting Things Done · People and Things (14 ders).
 *
 *  Ünite 8'de TEK BİR gramer dersi yok ve bu kasıtlı: bu seviyede öğrenciyi
 *  kilitleyen şey gramer değil, işlem yapamamak. Rica etmek, kibarca reddetmek,
 *  rezervasyon, şikâyet, tekrar isteme ve baştan sona telefonla sorun çözme —
 *  hepsi kalıp ve uygulama dersi.
 *
 *  Ünite 9 betimlemeyi uzatıyor: ilgi cümlecikleri, dönüşlü zamirler, other/another,
 *  used to, görüş bildirme ve -ed/-ing sıfat çifti. A2'nin kapanışı bir tavsiye
 *  dersi — öğrenci artık bir şeyi anlatıp savunabiliyor.
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const A2_U8_9: Authored[] = [
  // --- Ünite 8 · Getting Things Done -----------------------------------------
  {
    id: "a2-would-you-mind",
    topic: "asking a stranger for a small favour",
    objectives: [
      "Make a polite request with 'would you mind'.",
      "Answer a 'would you mind' question correctly.",
    ],
    goal: "Ask a stranger for a small favour without sounding rude.",
    target: "polite requests with would you mind",
    correction: "Model the request and the natural answer, then let the learner try both.",
    summary: "You learned to ask politely with 'would you mind' and to answer it the right way.",
    minutes: 6,
    points: [
      {
        form: "would you mind + -ing",
        claims: [
          "'Would you mind' is followed by a verb with -ing, not by 'to'.",
          "It is one of the most polite ways to ask a stranger for something.",
        ],
        ex: ["Would you mind moving your bag?", "Would you mind waiting a moment?"],
      },
      {
        form: "not at all",
        claims: [
          "The question asks whether something bothers you, so 'no' means yes.",
          "'Not at all' and 'of course not' both mean you agree happily.",
        ],
        ex: ["Not at all, go ahead.", "Of course not, take your time."],
      },
      {
        form: "sorry, I'm afraid",
        claims: [
          "To refuse, start with 'sorry' and give a short reason.",
          "A bare 'no' sounds abrupt in this situation.",
        ],
        ex: ["Sorry, I'm afraid I need it.", "I'm afraid I can't right now."],
      },
    ],
    ex: [
      fill("Would you mind ___ your bag? (move)", ["moving"]),
      mcq("Which answer means yes, that is fine?", [
        "Not at all, go ahead.",
        "Yes, I mind.",
        "Yes, that is a problem.",
      ], 0),
      say("would you mind / wait / a moment", ["Would you mind waiting a moment?"]),
    ],
    open: {
      q: "Ask a stranger to move so you can pass. Give one reply that accepts the request and one that refuses politely.",
      must: ["would you mind", "not at all", "of course not"],
      criteria: "The answer makes a polite request with an -ing form, accepts it naturally and also gives a polite refusal.",
      example: "Would you mind moving along a little? An agreeing reply is: Not at all. A polite refusal is: Sorry, I'm afraid I need this seat.",
    },
    success: "The learner makes a correct 'would you mind' request and produces both an agreeing reply and a polite refusal.",
    quiz: [
      qmcq("Which request is correct?", [
        "Would you mind opening the window?",
        "Would you mind to open the window?",
        "Would you mind open the window?",
      ], 0),
      qfill("___ at all, go ahead.", ["Not"]),
      qmcq("Which answer refuses politely?", [
        "Sorry, I'm afraid I need it.",
        "No.",
        "That is impossible.",
      ], 0),
    ],
    scenes: [
      sc("Marisa", "a stranger on a busy train", "to sort out the seats without friction",
        "The train is full and bags are on the seats.",
        "Ask politely for what you need.",
        "Sorry, were you trying to get past?", "distracted"),
      sc("Theo", "a colleague in a shared office", "to agree on the shared space",
        "The shared office is noisy and you need to concentrate.",
        "Make a polite request.",
        "You look like you are trying to focus. Everything all right?", "considerate"),
      sc("Nala", "a stranger at a busy cafe", "to share a table with you",
        "Every table is taken and you need a seat.",
        "Ask politely to share.",
        "It is packed today. Are you looking for a seat?", "friendly"),
      sc("Mr. Duarte", "your teacher", "to practise polite requests",
        "The class is practising requests with strangers.",
        "Make and answer polite requests.",
        "How would you ask a stranger to move their bag?", "encouraging"),
      sc("Ms. Beaumont", "the examiner", "to check polite request forms",
        "The examiner sets up a small social situation.",
        "Make the request and answer correctly.",
        "Imagine my bag is on the seat you want. What would you say?", "neutral"),
    ],
  },

  {
    id: "a2-im-sorry-i-cant",
    topic: "saying no politely",
    objectives: [
      "Turn down an invitation without offending anyone.",
      "Leave the door open for another time.",
    ],
    goal: "Say no to an invitation you would like to accept.",
    target: "refusing politely and apologising",
    correction: "Model the softened refusal and let the learner refuse in their own words.",
    summary: "You learned to refuse politely, give a reason and suggest another time.",
    minutes: 6,
    points: [
      {
        form: "I'm afraid I can't",
        claims: [
          "'I'm afraid' softens bad news and is not about fear.",
          "It usually comes before the refusal, not after it.",
        ],
        ex: ["I'm afraid I can't make it on Friday.", "I'm afraid that won't work for me."],
      },
      {
        form: "sorry about that",
        claims: [
          "A short reason makes a refusal easier to accept.",
          "The reason does not need to be detailed or private.",
        ],
        ex: ["I have something on that evening, sorry about that.", "Sorry about that, it's a busy week."],
      },
      {
        form: "maybe next time",
        claims: [
          "'Maybe next time' keeps the relationship open.",
          "Offering another day shows the refusal is about timing, not the person.",
        ],
        ex: ["Maybe next time.", "Could we do it the following week instead?"],
      },
    ],
    ex: [
      fill("I'm ___ I can't make it on Friday. (afraid)", ["afraid"]),
      mcq("Which refusal is polite?", [
        "I'm afraid I can't because I have something on.",
        "No, I do not want to.",
        "That is not interesting to me.",
      ], 0),
      say("maybe / next time", ["Maybe next time.", "Maybe next time!"]),
    ],
    open: {
      q: "A friend invites you to dinner on a night you are busy. Refuse politely, give a short reason and suggest another day.",
      must: ["I'm afraid I can't", "sorry about that", "maybe next time"],
      criteria: "The answer refuses politely, gives a short reason and suggests a clear alternative.",
      example: "I'm afraid I can't come on Thursday because I have a class. Sorry about that. Could we do Friday instead, or maybe next time?",
    },
    success: "The learner refuses politely, gives a reason and suggests a clear alternative.",
    quiz: [
      qmcq("Which sentence is a polite refusal?", [
        "I'm afraid that won't work for me.",
        "That will not work and that is final.",
        "I will not be doing that.",
      ], 0),
      qfill("Maybe ___ time, when I am less busy.", ["next"]),
      qmcq("Which sentence keeps the door open?", [
        "Could we do it the following week instead?",
        "I never go out on weekdays.",
        "Please do not ask me again.",
      ], 0),
    ],
    scenes: [
      sc("Aurora", "a friend inviting you out", "to get an answer about Friday",
        "A friend has invited you somewhere you cannot go.",
        "Refuse politely and suggest another time.",
        "We are all going on Friday. You are coming, right?", "hopeful"),
      sc("Bernard", "a colleague organising an after-work event", "to know whether you will join",
        "A work social is planned for an evening you are busy.",
        "Refuse politely and explain briefly.",
        "Drinks on Thursday after work. Can I count you in?", "casual"),
      sc("Selin", "a host offering an activity", "to include you in the group plan",
        "The group is doing something you cannot join.",
        "Decline politely.",
        "We are all going to the old town tonight. Will you come?", "welcoming"),
      sc("Mrs. Okonkwo", "your teacher", "to practise polite refusals",
        "The class is practising saying no kindly.",
        "Refuse an invitation politely.",
        "Someone invites you out but you are busy. What do you say?", "encouraging"),
      sc("Mr. Halloran", "the examiner", "to check polite refusal language",
        "The examiner invites you to something.",
        "Refuse politely with a reason.",
        "Would you like to join a class trip this Saturday?", "neutral"),
    ],
  },

  {
    id: "a2-a-small-favour",
    topic: "asking people you know for favours",
    objectives: [
      "Ask a neighbour or colleague for a small favour.",
      "Agree to a favour naturally.",
    ],
    goal: "Ask the people around you for small favours and respond to theirs.",
    target: "asking for and granting small favours",
    correction: "Model the request and the natural agreement, then let the learner try again.",
    summary: "You practised asking for small favours and agreeing to them naturally.",
    minutes: 6,
    points: [
      {
        form: "would you mind",
        claims: [
          "With people you know, 'would you mind' still works and stays polite.",
          "Adding the reason first makes the favour easier to accept.",
        ],
        ex: [
          "I'll be away next week. Would you mind taking in any parcels for me?",
          "I have a meeting this afternoon. Would you mind keeping an eye on the front desk?",
        ],
      },
      {
        form: "could you please",
        claims: [
          "'Could you please' is direct but still polite among people who know each other.",
          "'Please' can go at the start or at the end of the request.",
        ],
        ex: ["Could you please water the plants?", "Could you send it to me, please?"],
      },
      {
        form: "no problem",
        claims: [
          "'No problem' and 'sure' agree to a favour without ceremony.",
          "'Any time' adds warmth after you have agreed.",
        ],
        ex: ["No problem, leave it with me.", "Sure, any time."],
      },
    ],
    ex: [
      fill("Would you mind ___ in any parcels for me? (take)", ["taking"]),
      mcq("Which reply agrees to a favour?", [
        "No problem, leave it with me.",
        "That is not my job.",
        "Why are you asking me?",
      ], 0),
      say("could you please / water / the plants", ["Could you please water the plants?", "Could you water the plants, please?"]),
    ],
    open: {
      q: "You will be away for a week. Ask a neighbour for two favours and give a natural agreeing reply.",
      must: ["would you mind", "could you please", "no problem"],
      criteria: "The answer makes two polite requests and includes a natural agreement.",
      example: "Would you mind taking in any parcels for me? Could you please water the plants too? A natural reply is: No problem.",
    },
    success: "The learner makes two polite requests and responds to a favour naturally.",
    quiz: [
      qmcq("Which request is correct?", [
        "Would you mind keeping an eye on it?",
        "Would you mind to keep an eye on it?",
        "Would you mind keep an eye on it?",
      ], 0),
      qfill("Could you ___ send it to me? (please)", ["please"]),
      qmcq("Which reply is a warm agreement?", ["Sure, any time.", "If I must.", "I suppose so."], 0),
    ],
    scenes: [
      sc("Fatima", "the neighbour across the hall", "to help you while you are away",
        "You are away for a week and need a hand.",
        "Ask for two small favours.",
        "I saw your suitcase in the hall. Going somewhere?", "neighbourly"),
      sc("Owen", "a colleague covering for you", "to take over a few small things",
        "You are on leave and a few tasks need covering.",
        "Ask a colleague to cover them.",
        "You are off next week, right? Anything I should pick up?", "willing"),
      sc("Camille", "someone at your guesthouse", "to help with a small practical problem",
        "You need a small favour from someone staying nearby.",
        "Ask politely and thank them.",
        "You look like you are trying to work something out. Need a hand?", "kind"),
      sc("Mr. Sorescu", "your teacher", "to practise asking for favours",
        "The class is role-playing favours between neighbours.",
        "Ask for a favour and respond to one.",
        "You are going away for a week. What do you ask your neighbour?", "encouraging"),
      sc("Ms. Nakagawa", "the examiner", "to check favour language",
        "The examiner asks you to make a request.",
        "Ask politely and respond naturally.",
        "Imagine you need a neighbour's help while you are away. What would you ask?", "neutral"),
    ],
  },

  {
    id: "a2-booking-a-room",
    topic: "booking a place to stay",
    objectives: [
      "Make a booking on the phone.",
      "Ask what is included in the price.",
    ],
    goal: "Book a room on the phone and check the details.",
    target: "booking accommodation",
    correction: "Model the booking sentence and let the learner make the booking again.",
    summary: "You learned to make a booking and check what is included.",
    minutes: 6,
    points: [
      {
        form: "I'd like to book",
        claims: [
          "'I'd like to book' opens a booking politely and clearly.",
          "Include the room type, the dates and the number of guests; the exact order can vary.",
        ],
        ex: ["I'd like to book a double room.", "I'd like to book a table for four."],
      },
      {
        form: "for two nights",
        claims: [
          "'For' introduces the length of the stay: for two nights, for a week.",
          "'From ... to ...' gives the exact dates.",
        ],
        ex: ["For two nights, please.", "From the fifth to the seventh."],
      },
      {
        form: "is breakfast included",
        claims: [
          "'Is ... included?' checks what the price covers.",
          "Ask before you confirm, not after.",
        ],
        ex: ["Is breakfast included?", "Is there a charge for parking?"],
      },
    ],
    ex: [
      fill("I'd like ___ book a room for two nights.", ["to"]),
      mcq("Which question asks what the price includes?", [
        "Is breakfast included?",
        "Is breakfast at eight?",
        "Where is breakfast served?",
      ], 0),
      say("for / two nights / please", ["For two nights, please.", "For two nights please."]),
    ],
    open: {
      q: "Call a small hotel. Book a room, give the dates and ask one question about what is included.",
      must: ["I'd like to book", "for two nights", "is breakfast included"],
      criteria: "The answer makes a clear booking with dates and asks what is included.",
      example: "Hello, I'd like to book a single room for two nights, from Friday the twelfth to Sunday the fourteenth. Is breakfast included?",
    },
    success: "The learner makes a complete booking and asks at least one question.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I'd like to book a double room.",
        "I'd like book a double room.",
        "I'd like to booking a double room.",
      ], 0),
      qfill("___ two nights, please.", ["For"]),
      qmcq("Which question checks the price?", [
        "Is there a charge for parking?",
        "Where is the car park?",
        "How do I get to the car park?",
      ], 0),
    ],
    scenes: [
      sc("Sofia", "the owner of a small hotel", "to take your booking over the phone",
        "You are calling a small family hotel to book.",
        "Make the booking and check the details.",
        "Good afternoon, how can I help you?", "welcoming"),
      sc("Mr. Grant", "a company travel coordinator", "to book your work trip correctly",
        "You need accommodation arranged for a work trip.",
        "Give the details and ask what is covered.",
        "I am booking your trip now. What do you need?", "efficient"),
      sc("Ilaria", "a hostel receptionist", "to arrange your stay",
        "You are booking a bed for a few nights.",
        "Book and ask what is included.",
        "Hello! Are you looking for a bed for tonight?", "casual"),
      sc("Mrs. Berg", "your teacher", "to practise booking language",
        "The class is role-playing phone bookings.",
        "Make a complete booking.",
        "You are calling a hotel. How do you start?", "encouraging"),
      sc("Mr. Pereira", "the examiner", "to check transactional language",
        "The examiner plays a receptionist.",
        "Make a clear booking with all the details.",
        "Good morning, Riverside Hotel. How may I help you?", "neutral"),
    ],
  },

  {
    id: "a2-something-went-wrong",
    topic: "complaining politely",
    objectives: [
      "Explain what is wrong with something you bought.",
      "Say what you would like the shop to do.",
    ],
    goal: "Take a faulty item back and get it sorted out.",
    target: "complaining politely and asking for a solution",
    correction: "Model the polite complaint and let the learner complain in their own words.",
    summary: "You learned to explain a fault politely and ask for a refund or replacement.",
    minutes: 6,
    points: [
      {
        form: "there's a problem",
        claims: [
          "Open with the problem, calmly and without blaming the person in front of you.",
          "'There's a problem with ...' is neutral and easy to answer.",
        ],
        ex: ["There's a problem with this kettle.", "There's a problem with my order."],
      },
      {
        form: "it doesn't work",
        claims: [
          "Say exactly what is wrong: it doesn't work, it's broken, a part is missing.",
          "A precise fault gets a faster answer than a general complaint.",
        ],
        ex: ["It doesn't work at all.", "It stopped working after two days."],
      },
      {
        form: "could I get a refund",
        claims: [
          "Say what you want: a refund, a replacement or a repair.",
          "'Could I' keeps the request polite even when you are annoyed.",
        ],
        ex: ["Could I get a refund, please?", "Could I exchange it for a new one?"],
      },
    ],
    ex: [
      fill("There's a ___ with this kettle, it stopped working.", ["problem"]),
      mcq("Which sentence describes the fault precisely?", [
        "It stopped working after two days.",
        "It is not very good.",
        "I do not like it much.",
      ], 0),
      say("could / I / get / a refund", ["Could I get a refund?", "Could I get a refund, please?"]),
    ],
    open: {
      q: "A kettle you bought last week has stopped working. Take it back and explain what you want.",
      must: ["there's a problem", "it doesn't work", "could I get a refund"],
      criteria: "The answer explains the fault politely and states what solution is wanted.",
      example: "There's a problem with this kettle. It doesn't work at all now. Could I get a refund, please?",
    },
    success: "The learner explains a fault and asks for a specific solution.",
    quiz: [
      qmcq("Which sentence is a polite complaint?", [
        "There's a problem with my order.",
        "Your shop is terrible.",
        "You sold me a broken thing on purpose.",
      ], 0),
      qfill("Could I ___ it for a new one? (exchange)", ["exchange"]),
      qmcq("Which sentence states what you want?", [
        "Could I get a refund, please?",
        "This is very disappointing.",
        "I bought it last Tuesday.",
      ], 0),
    ],
    scenes: [
      sc("Dilek", "a shop assistant", "to deal with your faulty item",
        "You are at the returns desk with something that broke.",
        "Explain the fault and ask for a solution.",
        "Hello, what can I do for you today?", "professional"),
      sc("Mr. Lowell", "a supplier on the phone", "to resolve a problem with a delivery",
        "A work order arrived damaged.",
        "Explain the problem and ask for a fix.",
        "You said there was an issue with the delivery. Tell me what happened?", "businesslike"),
      sc("Anouk", "a hotel manager", "to fix a problem in your room",
        "Something in your room is not working.",
        "Explain politely and ask for it to be fixed.",
        "I understand there is a problem with your room. What is it?", "apologetic"),
      sc("Ms. Kaur", "your teacher", "to practise complaint language",
        "The class is practising polite complaints.",
        "Explain a fault and ask for a solution.",
        "Something you bought is broken. What do you say at the counter?", "encouraging"),
      sc("Mr. Eriksen", "the examiner", "to check complaint language",
        "The examiner plays a shop assistant.",
        "Complain politely and state what you want.",
        "Good morning, is there a problem with your purchase?", "neutral"),
    ],
  },

  {
    id: "a2-can-you-say-that-again",
    topic: "asking someone to repeat or explain",
    objectives: [
      "Ask someone to repeat or slow down.",
      "Ask what a word means.",
    ],
    goal: "Keep a difficult phone conversation going when you cannot follow.",
    target: "asking for repetition and clarification",
    correction: "Model the clarification request and let the learner ask it again.",
    summary: "You learned to ask for repetition, slower speech and the meaning of words.",
    minutes: 6,
    points: [
      {
        form: "could you repeat that",
        claims: [
          "'Could you repeat that, please?' is polite and works in any situation.",
          "'Sorry?' alone also works, but only for short repetitions.",
        ],
        ex: ["Could you repeat that, please?", "Could you say that again?"],
      },
      {
        form: "sorry, I didn't catch",
        claims: [
          "'I didn't catch that' means you did not hear or understand something clearly.",
          "Naming the part you missed helps the speaker repeat the right information.",
        ],
        ex: ["Sorry, I didn't catch the last part.", "Sorry, I didn't catch your name."],
      },
      {
        form: "what does that mean",
        claims: [
          "'What does ... mean?' asks about a word you do not know.",
          "'Could you speak a bit more slowly?' asks about speed, not meaning.",
        ],
        ex: ["What does that word mean?", "Could you speak a bit more slowly, please?"],
      },
    ],
    ex: [
      fill("Could you ___ that, please? The line is bad.", ["repeat"]),
      mcq("Which sentence asks about a word?", [
        "What does that word mean?",
        "Could you speak more slowly?",
        "Could you repeat that?",
      ], 0),
      say("sorry / I / not catch / the last part", ["Sorry, I didn't catch the last part.", "Sorry, I did not catch the last part."]),
    ],
    open: {
      q: "You are on a bad phone line, the other person speaks quickly and uses a word you do not know. Ask for help in three different ways.",
      must: ["could you repeat that", "what does that mean", "sorry I didn't catch"],
      criteria: "The answer asks for repetition, slower speech and the meaning of an unfamiliar word.",
      example: "Sorry, I didn't catch that. Could you repeat it a bit more slowly? What does that word mean?",
    },
    success: "The learner asks for clarification naturally in three different ways.",
    quiz: [
      qmcq("Which request is polite?", [
        "Could you say that again, please?",
        "Say it again.",
        "What? I cannot hear.",
      ], 0),
      qfill("Sorry, I didn't ___ your name.", ["catch"]),
      qmcq("Which sentence asks about speed?", [
        "Could you speak a bit more slowly?",
        "What does that mean?",
        "Could you spell that?",
      ], 0),
    ],
    scenes: [
      sc("Gabriel", "someone calling from a noisy street", "to give you information over a bad line",
        "The line is poor and the caller is speaking fast.",
        "Ask for repetition and clarification.",
        "Hi, sorry about the noise, I am outside. Can you hear me?", "hurried"),
      sc("Ms. Prentice", "a caller from another company", "to pass on details you must get right",
        "You are taking important details on a phone call.",
        "Ask for repetition where you need it.",
        "I have the reference and the date for you. Ready?", "brisk"),
      sc("Joaquim", "a station announcer you meet at the desk", "to explain the announcement you missed",
        "You missed an announcement and need it explained.",
        "Ask what was said and what it means.",
        "You look confused. Did you catch the announcement?", "helpful"),
      sc("Mrs. Lindberg", "your teacher", "to practise clarification requests",
        "The class is practising asking for repetition.",
        "Ask for clarification in different ways.",
        "If you do not understand a word I say, what can you ask?", "encouraging"),
      sc("Mr. Vasquez", "the examiner", "to check clarification language",
        "The examiner speaks quickly on purpose.",
        "Ask for repetition politely.",
        "The registration deadline is the twenty-third, understood?", "neutral"),
    ],
  },

  {
    id: "a2-sorting-out-a-problem",
    topic: "solving a problem on the phone",
    objectives: [
      "Open a call by saying why you are calling.",
      "Work through a problem to a solution.",
    ],
    goal: "Call about an order that never arrived and get it sorted.",
    target: "handling a problem call from start to finish",
    correction: "Model the stage the learner is on and let them carry the call forward.",
    summary: "You practised opening a call, explaining a problem and closing it politely.",
    minutes: 6,
    points: [
      {
        form: "I'm calling about",
        claims: [
          "Open with the reason for the call before any detail.",
          "Give your name and a reference number if you have one.",
        ],
        ex: ["I'm calling about an order that hasn't arrived.", "I'm calling about last week's booking."],
      },
      {
        form: "let me check",
        claims: [
          "'Let me check' is what the other person says while they look.",
          "'Bear with me' and 'one moment' mean the same thing.",
        ],
        ex: ["Let me check that for you.", "One moment, I'll look it up."],
      },
      {
        form: "thanks for your help",
        claims: [
          "Close by confirming what will happen and when.",
          "'Thanks for your help' ends the call warmly.",
        ],
        ex: ["So it will arrive on Thursday. Thanks for your help.", "Thanks for your help, that's clear now."],
      },
    ],
    ex: [
      fill("I'm ___ about an order that hasn't arrived. (call)", ["calling"]),
      mcq("Which sentence opens a call properly?", [
        "I'm calling about last week's booking.",
        "Who is this?",
        "You have a problem.",
      ], 0),
      say("thanks / for / your help", ["Thanks for your help.", "Thanks for your help!"]),
    ],
    open: {
      q: "An order you paid for two weeks ago never arrived. Make the call from opening to closing and ask for a solution.",
      must: ["I'm calling about", "thanks for your help"],
      criteria: "The answer explains the reason for the call, describes the problem, requests a solution, confirms the outcome and closes politely.",
      example: "I'm calling about an order that hasn't arrived. Could you send a replacement? Thursday works for me. Thanks for your help.",
    },
    success: "The learner opens the call, explains the problem, requests and confirms a solution, and closes politely.",
    quiz: [
      qmcq("Which sentence opens a call?", [
        "I'm calling about my delivery.",
        "I called about my delivery.",
        "Call me about my delivery.",
      ], 0),
      qfill("One moment, ___ me check that for you.", ["let"]),
      qmcq("Which sentence closes a call?", [
        "Thanks for your help, that's clear now.",
        "I do not understand you.",
        "Who am I speaking to?",
      ], 0),
    ],
    scenes: [
      sc("Priscilla", "a customer service agent", "to trace your missing order",
        "You are calling about an order that never arrived.",
        "Explain the problem and reach a solution.",
        "Thank you for calling. How can I help today?", "professional"),
      sc("Mr. Osei", "a supplier's account manager", "to resolve a delivery failure",
        "A work delivery has not arrived and a client is waiting.",
        "Explain the situation and agree next steps.",
        "You said this is urgent. What has happened?", "attentive"),
      sc("Lucia", "an airline call centre agent", "to help with your delayed luggage",
        "Your luggage did not arrive with your flight.",
        "Explain and agree what happens next.",
        "Baggage services, how can I help you?", "calm"),
      sc("Mr. Wickham", "your teacher", "to practise a full problem call",
        "The class is role-playing complete phone calls.",
        "Handle the call from start to finish.",
        "You are calling about a problem. How do you open the call?", "encouraging"),
      sc("Ms. Roux", "the examiner", "to check a full transactional call",
        "The examiner plays a customer service agent.",
        "Open, explain and close the call.",
        "Customer service, good morning. How can I help?", "neutral"),
    ],
  },

  // --- Ünite 9 · People and Things -------------------------------------------
  {
    id: "a2-the-man-who-helped-me",
    topic: "joining sentences to describe people and things",
    objectives: [
      "Use who for people and which or that for things.",
      "Describe something you cannot name exactly.",
    ],
    goal: "Describe a person or a thing when you do not know the exact word.",
    target: "relative clauses with who, which and that",
    correction: "Repeat the joined sentence and let the learner describe again.",
    summary: "You learned to join two ideas with who, which and that to describe people and things.",
    minutes: 7,
    points: [
      {
        form: "someone who",
        claims: [
          "'Who' introduces defining information about a person.",
          "In informal defining clauses, 'that' can often replace 'who'.",
        ],
        ex: ["The man who helped me was very kind.", "I need someone who speaks Spanish."],
      },
      {
        form: "something that",
        claims: [
          "'Which' and 'that' introduce defining information about a thing.",
          "'That' is very common in everyday defining clauses.",
        ],
        ex: ["It's a thing that opens bottles.", "The bag which I lost was blue."],
      },
      {
        form: "people who live",
        claims: [
          "The describing part comes straight after the noun it describes.",
          "Do not repeat the noun with a pronoun inside the clause.",
        ],
        ex: ["People who live here know the shortcuts.", "The train that leaves at six is faster."],
      },
    ],
    ex: [
      fill("The man ___ helped me was very kind.", ["who", "that"]),
      mcq("Which sentence is correct?", [
        "It's a thing that opens bottles.",
        "It's a thing what opens bottles.",
        "It's a thing that it opens bottles.",
      ], 0),
      fill("I need someone ___ speaks Spanish.", ["who", "that"]),
      say("people who live here / know / the shortcuts", ["People who live here know the shortcuts."]),
    ],
    open: {
      q: "Describe an object without naming it, so I can guess what it is.",
      must: ["someone who", "something that", "people who live"],
      criteria: "The answer describes a person or thing using who, which or that correctly.",
      example: "It's something that you use in the kitchen and that helps you open bottles.",
    },
    success: "The learner uses a relative clause correctly at least twice.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "The train that leaves at six is faster.",
        "The train what leaves at six is faster.",
        "The train that it leaves at six is faster.",
      ], 0),
      qfill("I know a woman ___ works there. (who)", ["who"]),
      qmcq("Which sentence describes a thing?", [
        "The bag which I lost was blue.",
        "The man who I met was tall.",
        "The people who came were early.",
      ], 0),
    ],
    scenes: [
      sc("Ingeborg", "a friend playing a guessing game", "to guess the word you are describing",
        "You cannot remember a word and must describe it instead.",
        "Describe the thing without naming it.",
        "You have forgotten the word again! How would you describe it?", "amused"),
      sc("Rashid", "a colleague you need a contact from", "to find the right person for you",
        "You need to be introduced to someone with a specific skill.",
        "Describe the kind of person you need.",
        "You said you needed someone specific. What kind of person?", "helpful"),
      sc("Cecilia", "a shop assistant in a hardware shop", "to find the item you are describing",
        "You need a tool but do not know its name in English.",
        "Describe the object clearly.",
        "We have most things here. What are you looking for?", "patient"),
      sc("Mr. Tremblay", "your teacher", "to practise relative clauses",
        "The class is playing a describing game.",
        "Describe a person or thing with a relative clause.",
        "Describe something without saying its name. What is it?", "encouraging"),
      sc("Ms. Bianchi", "the examiner", "to check relative clauses",
        "The examiner asks you to describe something indirectly.",
        "Use who, which or that correctly.",
        "Could you describe a person who has been important to you?", "neutral"),
    ],
  },

  {
    id: "a2-dont-burn-yourself",
    topic: "myself, yourself and each other",
    objectives: [
      "Use reflexive pronouns when the action comes back to the person.",
      "Use 'each other' when people perform an action mutually.",
    ],
    goal: "Talk about doing things alone and looking after yourself.",
    target: "reflexive pronouns and each other",
    correction: "Repeat the sentence with the right pronoun and let the learner say it again.",
    summary: "You learned myself, yourself and each other, and when 'by myself' means alone.",
    minutes: 7,
    points: [
      {
        form: "myself / yourself",
        claims: [
          "Use these when the person doing the action and the person receiving it are the same.",
          "'Don't burn yourself' warns the listener about their own safety.",
        ],
        ex: ["Don't burn yourself, the pan is hot.", "I taught myself to cook."],
      },
      {
        form: "by myself",
        claims: [
          "'By myself' means alone, without help.",
          "'Enjoy yourself' means have a good time, not do something alone.",
        ],
        ex: ["I did it by myself.", "Enjoy yourself this weekend."],
      },
      {
        form: "each other",
        claims: [
          "'Each other' is used when two or more people perform an action mutually.",
          "'They helped each other' is different from 'they helped themselves'.",
        ],
        ex: ["We help each other at work.", "They have known each other for years."],
      },
    ],
    ex: [
      fill("Don't burn ___, the pan is very hot. (you)", ["yourself"]),
      mcq("Which sentence is correct?", [
        "We help each other at work.",
        "We help ourselves each other at work.",
        "We help us at work.",
      ], 0),
      fill("I fixed it ___ myself, with no help.", ["by"]),
      say("I / teach / myself / to cook", ["I taught myself to cook.", "I have taught myself to cook."]),
    ],
    open: {
      q: "Say one thing you learned by yourself and one thing you and a friend do for each other.",
      must: ["by myself", "each other"],
      criteria: "The answer uses a reflexive pronoun and 'each other' correctly.",
      example: "I learned to cook by myself, and my flatmate and I help each other with the shopping.",
    },
    success: "The learner uses reflexive pronouns and 'each other' correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "They have known each other for years.",
        "They have known themselves for years.",
        "They have known each other themselves for years.",
      ], 0),
      qfill("Enjoy ___ at the party! (you)", ["yourself"]),
      qmcq("Which sentence means alone?", [
        "I did it by myself.",
        "I did it myself proud.",
        "I did it to myself.",
      ], 0),
    ],
    scenes: [
      sc("Malena", "a friend in your kitchen", "to cook together without accidents",
        "Two friends are cooking together in a small kitchen.",
        "Warn and describe who does what.",
        "That pan looks dangerous. Shall I take over?", "playful"),
      sc("Stefan", "a colleague on a shared task", "to divide a job between you",
        "Two colleagues are splitting a task.",
        "Say what you will do alone and what together.",
        "We can split this. What do you want to take on your own?", "collaborative"),
      sc("Aya", "a host showing you the flat", "to make sure you can manage alone",
        "Your host is leaving and you will be alone in the flat.",
        "Say what you can do by yourself.",
        "I am away until Sunday. Will you be all right on your own?", "caring"),
      sc("Mrs. Petrov", "your teacher", "to practise reflexive pronouns",
        "The class is describing independent and mutual actions.",
        "Use both forms correctly.",
        "What is something you learned without any help?", "encouraging"),
      sc("Mr. Oduya", "the examiner", "to check reflexive pronouns",
        "The examiner asks about independence and friendship.",
        "Use the correct pronouns.",
        "Could you tell me about something you taught yourself?", "neutral"),
    ],
  },

  {
    id: "a2-the-other-one",
    topic: "other, another and the others",
    objectives: [
      "Choose between another and the other.",
      "Refer to the remaining items in a group.",
    ],
    goal: "Choose between things when the first one is not right.",
    target: "other, another and the others",
    correction: "Repeat the phrase with the right form and let the learner choose again.",
    summary: "You learned the difference between another, the other and the others.",
    minutes: 7,
    points: [
      {
        form: "another one",
        claims: [
          "'Another' means one more or a different one, and is written as one word.",
          "At this level, it is usually used before a singular countable noun: another shop, another one.",
        ],
        ex: ["Could I have another one, please?", "Let's try another shop."],
      },
      {
        form: "the other",
        claims: [
          "'The other one' means the remaining member of a pair.",
          "It avoids repeating the noun when both options are already known.",
        ],
        ex: ["I prefer the other one.", "The other shoe is under the bed."],
      },
      {
        form: "the others",
        claims: [
          "'The others' means all the remaining ones in a group.",
          "'Others' without 'the' means some more, not all the rest.",
        ],
        ex: ["What about the others?", "The others are waiting outside."],
      },
    ],
    ex: [
      fill("Could I have ___ one, please? This one is broken. (one more)", ["another"]),
      mcq("Which sentence is correct?", [
        "I prefer the other one.",
        "I prefer the another one.",
        "I prefer other one.",
      ], 0),
      fill("Two are here. What about ___ others?", ["the"]),
      say("let us / try / another shop", ["Let's try another shop.", "Let us try another shop."]),
    ],
    open: {
      q: "You are choosing between several items and the first is not right. Ask about the alternatives.",
      must: ["I prefer the other", "another one", "what about the others"],
      criteria: "The answer uses another, the other and the others with the right meanings.",
      example: "This one is too small. Could I see another one? I prefer the other colour. What about the others on that shelf?",
    },
    success: "The learner uses another, the other and the others correctly.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "The other shoe is under the bed.",
        "The another shoe is under the bed.",
        "Other shoe is under the bed.",
      ], 0),
      qfill("The ___ are waiting outside. (all the rest)", ["others"]),
      qmcq("Which sentence asks for one more?", [
        "Could I have another one?",
        "Could I have the other one?",
        "Could I have the others?",
      ], 0),
    ],
    scenes: [
      sc("Rosalie", "a shop assistant", "to show you the alternatives",
        "The first item you tried is not right.",
        "Ask about the alternatives.",
        "That one is not quite right, is it? Shall I bring you some other options?", "attentive"),
      sc("Tobias", "a colleague reviewing options", "to work through a list of candidates",
        "Several options are on the table and one has been ruled out.",
        "Talk about the remaining options.",
        "We can rule that one out. What about the rest?", "systematic"),
      sc("Amara", "a waiter", "to bring you something else",
        "Your first choice is not available.",
        "Choose from the alternatives.",
        "I am afraid that one is finished. Can I suggest something else?", "apologetic"),
      sc("Mr. Lindqvist", "your teacher", "to practise other and another",
        "The class is choosing between alternatives.",
        "Use the right form for each situation.",
        "You have two options and reject one. How do you talk about the second?", "encouraging"),
      sc("Ms. Farrell", "the examiner", "to check these forms",
        "The examiner offers you several choices.",
        "Use another, the other and the others correctly.",
        "If I offered you three options and you did not like the first, what would you say?", "neutral"),
    ],
  },

  {
    id: "a2-i-used-to-play-football",
    topic: "past habits and situations that have changed",
    objectives: [
      "Use 'used to' for repeated past actions and past situations that are no longer true.",
      "Form questions and negatives with 'use to'.",
    ],
    goal: "Talk about past habits and situations that are different now.",
    target: "used to for past habits and past states",
    correction: "Repeat the sentence with the correct form and let the learner say it again.",
    summary: "You learned to talk about past habits and past situations with used to, and to drop the -d in questions.",
    minutes: 7,
    points: [
      {
        form: "I used to",
        claims: [
          "'Used to' plus the base verb describes a repeated past action or a past situation that is no longer true.",
          "With actions it suggests something happened regularly; with state verbs it describes how things were before.",
        ],
        ex: ["I used to play football every Sunday.", "We used to live near the sea."],
      },
      {
        form: "didn't use to",
        claims: [
          "In questions and negatives the -d disappears: did you use to, didn't use to.",
          "This is because 'did' already carries the past.",
        ],
        ex: ["Did you use to play an instrument?", "I didn't use to like coffee."],
      },
      {
        form: "now versus then",
        claims: [
          "'Used to' contrasts with how things are now, so a 'but now' half often follows.",
          "For present habits use the present simple, not 'used to'.",
        ],
        ex: ["I used to smoke, but I stopped years ago.", "We used to walk, but now we drive."],
      },
    ],
    ex: [
      fill("I ___ to play football every Sunday. (use)", ["used"]),
      mcq("Which question is correct?", [
        "Did you use to play an instrument?",
        "Did you used to play an instrument?",
        "Do you used to play an instrument?",
      ], 0),
      fill("I ___ use to like coffee, but now I love it. (did not)", ["didn't", "did not"]),
      say("we / used to / live / near the sea", ["We used to live near the sea."]),
    ],
    open: {
      q: "Describe two habits or situations that were different in your life five years ago.",
      must: ["I used to", "we used to", "didn't use to"],
      criteria: "The answer describes past habits or situations with 'used to' and contrasts them with the present.",
      example: "I used to walk to work every day, and we used to live in a smaller flat. I didn't use to drive, but now I do.",
    },
    success: "The learner correctly describes at least two past habits or situations with 'used to'.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We used to walk, but now we drive.",
        "We use to walk, but now we drive.",
        "We used to walking, but now we drive.",
      ], 0),
      qfill("Did she ___ to work here? (use)", ["use"]),
      qmcq("Which sentence describes a stopped habit?", [
        "I used to smoke, but I stopped.",
        "I smoke every day.",
        "I will smoke less.",
      ], 0),
    ],
    scenes: [
      sc("Kwabena", "an old friend you have not seen for years", "to catch up on how life has changed",
        "Two old friends are catching up after a long time.",
        "Describe how your life used to be.",
        "It has been what, five years? What has changed for you?", "warm"),
      sc("Simone", "a colleague talking about the old office", "to compare how work used to be",
        "The company has changed a lot in recent years.",
        "Describe how things used to be.",
        "You have been here longest. What was it like before?", "curious"),
      sc("Emil", "a local showing you the changed town", "to describe how the area has changed",
        "A local is pointing out how the town used to look.",
        "Describe how your own town used to be.",
        "This whole street was different ten years ago. Is your town changing too?", "nostalgic"),
      sc("Mrs. Aguilar", "your teacher", "to practise past habits",
        "The class is comparing past and present lives.",
        "Describe past habits.",
        "What did you use to do that you do not do any more?", "encouraging"),
      sc("Mr. Nakamura", "the examiner", "to check 'used to'",
        "The examiner asks how your life has changed.",
        "Describe past habits accurately.",
        "Could you tell me how your daily life was different a few years ago?", "neutral"),
    ],
  },

  {
    id: "a2-what-do-you-think",
    topic: "giving an opinion and reacting to one",
    objectives: [
      "Give an opinion clearly.",
      "Agree or disagree without being rude.",
    ],
    goal: "Have a friendly disagreement about something everyday.",
    target: "giving opinions, agreeing and disagreeing",
    correction: "Model the softened disagreement and let the learner respond again.",
    summary: "You learned to give an opinion and to agree or disagree politely.",
    minutes: 6,
    points: [
      {
        form: "I think so",
        claims: [
          "'I think so' agrees with what was just said without repeating it.",
          "'I don't think so' is the usual negative, rather than 'I think not'.",
        ],
        ex: ["I think so, yes.", "I don't think so, actually."],
      },
      {
        form: "you're right",
        claims: [
          "'You're right' and 'exactly' agree strongly.",
          "'That's a good point' agrees with part of what was said.",
        ],
        ex: ["You're right, I didn't think of that.", "That's a good point."],
      },
      {
        form: "I don't agree",
        claims: [
          "Soften disagreement with 'I'm not sure' or 'I see what you mean, but'.",
          "A bare 'you are wrong' sounds harsh in most conversations.",
        ],
        ex: ["I don't agree, I'm afraid.", "I see what you mean, but I think it's different."],
      },
    ],
    ex: [
      fill("I ___ think so, actually. (do not)", ["don't", "do not"]),
      mcq("Which reply disagrees politely?", [
        "I see what you mean, but I think it's different.",
        "You are completely wrong.",
        "That is nonsense.",
      ], 0),
      say("you / be / right / I / not think of that", [
        "You're right, I didn't think of that.",
        "You are right, I did not think of that.",
      ]),
    ],
    open: {
      q: "I think working from home is always better than working in an office. Do you agree?",
      must: ["I think so", "I don't agree", "you're right"],
      criteria: "The answer gives an opinion and agrees or disagrees politely.",
      example: "I don't agree completely. You're right that it saves time, but I think people need contact too.",
    },
    success: "The learner gives an opinion and responds politely to another one.",
    quiz: [
      qmcq("Which reply agrees?", [
        "That's a good point.",
        "That makes no sense.",
        "I have no idea.",
      ], 0),
      qfill("I ___ think so, actually. (do not)", ["don't"]),
      qmcq("Which reply disagrees politely?", [
        "I'm not sure about that.",
        "You are wrong.",
        "Stop talking about it.",
      ], 0),
    ],
    scenes: [
      sc("Barbara", "a friend with strong opinions", "to argue a point with you over coffee",
        "Two friends are having a light disagreement.",
        "Give your opinion and respond to theirs.",
        "I still say the old way was better. Am I wrong?", "provocative"),
      sc("Ivan", "a colleague in a team discussion", "to reach a shared view on a small decision",
        "The team disagrees about a small process change.",
        "State your view and respond to others.",
        "Half the team wants to change it. Where do you stand?", "open"),
      sc("Zainab", "someone you meet at a dinner", "to discuss a light topic",
        "A friendly dinner conversation turns to opinions.",
        "Give and respond to opinions.",
        "Everyone here has a different view on this. What do you think?", "sociable"),
      sc("Mr. Steiner", "your teacher", "to practise opinion language",
        "The class is debating an everyday topic.",
        "Give your opinion and respond politely.",
        "Is it better to live in a city or in the countryside? What do you think?", "encouraging"),
      sc("Ms. Coelho", "the examiner", "to check opinion language",
        "The examiner states an opinion for you to respond to.",
        "Agree or disagree politely with reasons.",
        "I believe everyone should learn two languages at school. Do you agree?", "neutral"),
    ],
  },

  {
    id: "a2-boring-or-bored",
    topic: "the difference between -ing and -ed describing words",
    objectives: [
      "Use -ing words for the thing that causes the feeling.",
      "Use -ed words for the person who feels it.",
    ],
    goal: "Describe both a film and your reaction to it.",
    target: "-ed and -ing adjective pairs",
    correction: "Contrast the two forms in one sentence and let the learner choose again.",
    summary: "You learned that -ing describes the thing and -ed describes the person.",
    minutes: 7,
    points: [
      {
        form: "it was boring",
        claims: [
          "The -ing form describes the thing that causes the feeling.",
          "A film, a book or a job can be boring, interesting or tiring.",
        ],
        ex: ["The film was boring.", "That was a tiring journey."],
      },
      {
        form: "I was bored",
        claims: [
          "The -ed form describes the person who has the feeling.",
          "Saying 'I am boring' means other people find you dull.",
        ],
        ex: ["I was bored after ten minutes.", "We were all tired by the end."],
      },
      {
        form: "really interesting",
        claims: [
          "The same pair works for many words: interesting and interested, surprising and surprised.",
          "'Really' and 'quite' can go before either form.",
        ],
        ex: ["The talk was really interesting.", "I was very interested in the second part."],
      },
    ],
    ex: [
      fill("The film was ___, I nearly fell asleep. (bore)", ["boring"]),
      mcq("Which sentence describes the person?", [
        "I was bored after ten minutes.",
        "I was boring after ten minutes.",
        "I was bore after ten minutes.",
      ], 0),
      fill("I was very ___ in the second part. (interest)", ["interested"]),
      say("the talk / be / really interesting", ["The talk was really interesting."]),
    ],
    open: {
      q: "Think of a film or event you saw recently. Describe it and describe how you felt.",
      must: ["it was boring", "I was bored", "really interesting"],
      criteria: "The answer uses -ing for the thing and -ed for the person correctly.",
      example: "The first half was really interesting, but after that it was boring and I was bored by the end.",
    },
    success: "The learner uses both forms correctly in the same answer.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "We were all tired by the end.",
        "We were all tiring by the end.",
        "We were all tire by the end.",
      ], 0),
      qfill("That was a ___ journey, eight hours on a bus. (tire)", ["tiring"]),
      qmcq("Which sentence is correct?", [
        "I was surprised by the ending.",
        "I was surprising by the ending.",
        "I was surprise by the ending.",
      ], 0),
    ],
    scenes: [
      sc("Nikoletta", "a friend who saw the same film", "to compare reactions to it",
        "Two friends saw the same film and disagree about it.",
        "Describe the film and your reaction.",
        "So? I loved it. What did you make of it?", "eager"),
      sc("Piotr", "a colleague back from a conference", "to compare notes on the sessions",
        "Two colleagues attended the same event.",
        "Describe the sessions and your reactions.",
        "Three days of talks. Which ones stayed with you?", "reflective"),
      sc("Hana", "a fellow guest at a cultural evening", "to talk about the performance",
        "You both attended a local performance.",
        "Describe it and your reaction.",
        "That was something. What did you think of it?", "curious"),
      sc("Mrs. Weber", "your teacher", "to practise the adjective pair",
        "The class is describing films and reactions.",
        "Use both forms correctly.",
        "Describe a film you saw. How was it, and how did you feel?", "encouraging"),
      sc("Mr. Ozturk", "the examiner", "to check the adjective pair",
        "The examiner asks about a recent experience.",
        "Describe the event and your reaction.",
        "Could you tell me about a film or event you saw recently?", "neutral"),
    ],
  },

  {
    id: "a2-a-film-worth-watching",
    topic: "recommending something",
    objectives: [
      "Recommend a film or a book and say what it is about.",
      "Give a reason someone should try it.",
    ],
    goal: "Convince a friend to watch or read something.",
    target: "recommending and justifying",
    correction: "Model the recommendation and let the learner recommend in their own words.",
    summary: "You practised recommending something, saying what it is about and why it is worth it.",
    minutes: 6,
    points: [
      {
        form: "it's about",
        claims: [
          "'It's about' introduces the subject in one or two sentences.",
          "Keep it short: too much detail spoils the story.",
        ],
        ex: ["It's about a family that moves to another country.", "It's about how cities change."],
      },
      {
        form: "you should watch",
        claims: [
          "'You should watch' or 'you should read' makes a direct recommendation.",
          "'It's worth watching' is a softer way of saying the same thing.",
        ],
        ex: ["You should watch it before the sequel comes out.", "It's worth reading, even if it's long."],
      },
      {
        form: "I'd recommend it",
        claims: [
          "'I'd recommend it' can stand alone or be followed by 'to' plus a person.",
          "Add 'if you like ...' to help the other person judge.",
        ],
        ex: ["I'd recommend it to anyone.", "I'd recommend it if you like true stories."],
      },
    ],
    ex: [
      fill("It's ___ a family that moves to another country.", ["about"]),
      mcq("Which sentence recommends something?", [
        "You should watch it, it's excellent.",
        "I watched it last night.",
        "It starts at eight.",
      ], 0),
      say("I / would recommend / it / to anyone", ["I'd recommend it to anyone.", "I would recommend it to anyone."]),
    ],
    open: {
      q: "Recommend a film or a book to me. Say what it is about and why I should try it.",
      must: ["you should watch", "it's about", "I'd recommend it"],
      criteria: "The answer recommends something, briefly explains the story or subject and gives a clear reason.",
      example: "You should watch this film. It's about two brothers who lose touch. I'd recommend it because the story is simple but very moving.",
    },
    success: "The learner recommends something with a summary and a reason.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "It's worth reading, even if it's long.",
        "It's worth to read, even if it's long.",
        "It's worth read, even if it's long.",
      ], 0),
      qfill("It's ___ how cities change over time.", ["about"]),
      qmcq("Which sentence gives a reason to try it?", [
        "I'd recommend it if you like true stories.",
        "I saw it in the cinema.",
        "It is two hours long.",
      ], 0),
    ],
    scenes: [
      sc("Lorenzo", "a friend with nothing to watch", "to get a recommendation from you",
        "A friend cannot decide what to watch tonight.",
        "Recommend something and explain why.",
        "I have been scrolling for an hour. What should I watch?", "bored"),
      sc("Ndidi", "a colleague on a long commute", "to find something for the journey",
        "A colleague wants something to read on a long trip.",
        "Recommend something with reasons.",
        "Four hours on a train tomorrow. What should I take with me?", "practical"),
      sc("Jonas", "a fellow traveller swapping books", "to trade recommendations",
        "Travellers are exchanging books at a hostel.",
        "Recommend one and explain why.",
        "I have finished mine. What is worth swapping for?", "easy-going"),
      sc("Ms. Bergqvist", "your teacher", "to practise recommending",
        "The class is recommending books and films.",
        "Recommend something with a summary and reason.",
        "Recommend something to the class. What is it about?", "encouraging"),
      sc("Mr. Castellano", "the examiner", "to check recommendation language",
        "The examiner asks for a recommendation.",
        "Recommend clearly with a reason.",
        "Could you recommend a film or book to me and tell me why?", "neutral"),
    ],
  },
];
