/** B2 · Ünite 9-11 — Shades of Meaning · Formal and Informal · Real Issues (22 ders).
 *
 *  Ünite 9 ANLAM İNCELİĞİ: aynı şeyi söyleyen iki kelimenin farklı hissettirmesi.
 *  `remember to` ↔ `remember -ing` anlamı tersine çeviriyor; `slightly/fairly`
 *  gücü ayarlıyor; `barely/hardly` olumsuzu sessizce taşıyor; yüklü kelimeler
 *  aynı olayı farklı çerçeveliyor.
 *
 *  Ünite 10 REGİSTER: aynı mesajın resmî ve samimi hâli. Tek gramer dersi var
 *  (mesafe koyan dil), gerisi kalıp — çünkü buradaki beceri yapı değil, DOĞRU
 *  TONU seçebilmek. Kapanışta aynı mesaj iki kez söyleniyor.
 *
 *  Ünite 11'de HİÇ gramer dersi yok ve bu kasıtlı: B2'nin sonunda öğrenciyi
 *  kilitleyen şey yapı değil, uzun bir tartışmayı sürdürüp bitirebilmek.
 *  Ünite bir tartışmayı kapatma dersiyle bitiyor — seviyenin de kapanışı.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3.
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const B2_U9_11: Authored[] = [
  // --- Ünite 9 · Shades of Meaning -------------------------------------------
  {
    id: "b2-remember-to-do-remember-doing",
    topic: "verbs whose meaning flips with to or -ing",
    objectives: [
      "Use remember and forget with to for duties.",
      "Use remember and forget with -ing for memories.",
    ],
    goal: "Say clearly whether you mean a duty or a memory.",
    target: "remember and forget with to versus -ing",
    correction: "Contrast the two forms in one pair and let the learner choose the right one.",
    summary: "You learned that remember and forget change meaning with to and -ing.",
    minutes: 8,
    points: [
      {
        form: "remember to call",
        claims: [
          "'Remember to do' is about a duty that comes after the remembering.",
          "Depending on the tense, the action may still be ahead or already done: did you remember to call her?",
        ],
        ex: ["Remember to call her tomorrow.", "Did you remember to lock the door?"],
      },
      {
        form: "remember calling",
        claims: [
          "'Remember doing' is about a memory of something already done.",
          "'I remember calling her' means the call happened and you recall it.",
        ],
        ex: ["I remember calling her that evening.", "I don't remember saying that."],
      },
      {
        form: "I forgot to",
        claims: [
          "'I forgot to lock it' means I did not do the intended action; it says nothing about the current state.",
          "'I'll never forget meeting her' is a memory, not a duty.",
        ],
        ex: ["I forgot to lock the door.", "I'll never forget meeting her."],
      },
    ],
    ex: [
      fill("Please remember ___ call her tomorrow. (to)", ["to"]),
      mcq("Which sentence is about a memory?", [
        "I remember calling her that evening.",
        "I remember to call her every evening.",
        "Remember to call her this evening.",
      ], 0),
      fill("I don't remember ___ that at all. (say)", ["saying"]),
      say("I / forget / to lock / the door", ["I forgot to lock the door."]),
    ],
    open: {
      q: "Say one thing you must remember to do and one thing you clearly remember doing.",
      must: ["remember to call", "remember calling", "I forgot to"],
      criteria: "The answer uses 'to' for a duty and '-ing' for a memory, with the right meanings.",
      example: "I must remember to call the bank. I remember calling them last month. I forgot to write it down.",
    },
    success: "The learner uses both forms with the correct meanings.",
    quiz: [
      qmcq("Which sentence means the speaker failed to do the intended action?", [
        "I forgot to lock the door.",
        "I forgot locking the door.",
        "I remember locking the door.",
      ], 0),
      qfill("I'll never forget ___ her for the first time. (meet)", ["meeting"]),
      qmcq("Which sentence is about a duty?", [
        "Remember to send the form.",
        "I remember sending the form.",
        "I don't remember the form.",
      ], 0),
    ],
    scenes: [
      sc("Delphine", "a friend checking on arrangements", "to make sure nothing has been forgotten",
        "Several small tasks were shared out and some may have slipped.",
        "Say what you did and what you still have to do.",
        "We split the jobs last week. Where are we with them?", "organised"),
      sc("Rasheed", "a colleague reconstructing a conversation", "to establish what was actually said",
        "Two people remember a meeting differently.",
        "Say what you remember and what you were meant to do.",
        "You were in that meeting. What do you actually recall?", "probing"),
      sc("Astrid", "a travel companion before departure", "to check nothing has been left behind",
        "You are about to leave and things may be forgotten.",
        "Say what you remembered and what you forgot.",
        "We leave in ten minutes. Have we got everything?", "hurried"),
      sc("Dr. Ferreira", "your teacher", "to practise the two forms",
        "The class is sorting duties from memories.",
        "Use both forms correctly.",
        "What is the difference between 'remember to call' and 'remember calling'?", "encouraging"),
      sc("Ms. Whitlock", "the examiner", "to check the distinction",
        "The examiner asks about memory and duty.",
        "Distinguish the two forms clearly.",
        "Could you tell me something you must remember to do this week?", "neutral"),
    ],
  },

  {
    id: "b2-i-regret-to-tell-you",
    topic: "formal announcements",
    objectives: [
      "Announce good and bad news in formal language.",
      "Notice that regret to tell is a duty, not a memory.",
    ],
    goal: "Make a formal announcement in writing or in a meeting.",
    target: "regret to, be pleased to and be sorry to",
    correction: "Model the formal opener and let the learner announce their own news.",
    summary: "You learned to announce news formally with regret to, pleased to and sorry to.",
    minutes: 8,
    points: [
      {
        form: "I regret to",
        claims: [
          "'I regret to inform you' introduces bad news you are about to give.",
          "'Regret informing' is different: it regrets an act of telling that already happened.",
        ],
        ex: ["I regret to inform you that the post has been filled.", "We regret to say the event is cancelled."],
      },
      {
        form: "I'm pleased to",
        claims: [
          "'I'm pleased to' and 'I'm delighted to' introduce good news.",
          "'Delighted' is warmer and is common in offers and invitations.",
        ],
        ex: ["I'm pleased to confirm your booking.", "We're delighted to offer you the position."],
      },
      {
        form: "we're sorry to",
        claims: [
          "'We're sorry to' is softer than 'we regret to' and works in speech as well as writing.",
          "All three take 'to' plus a base verb; announcements usually use inform, say, confirm or announce, but others fit too.",
        ],
        ex: ["We're sorry to say there is a delay.", "We're sorry to hear about the problem."],
      },
    ],
    ex: [
      fill("I regret ___ inform you that the post has been filled. (to)", ["to"]),
      mcq("Which sentence introduces good news?", [
        "We're delighted to offer you the position.",
        "We regret to inform you of the decision.",
        "We're sorry to say there is a delay.",
      ], 0),
      fill("We're sorry ___ say there will be a delay. (to)", ["to"]),
      say("I / be pleased / to confirm / your booking", ["I'm pleased to confirm your booking.", "I am pleased to confirm your booking."]),
    ],
    open: {
      q: "Announce one piece of good news and one piece of bad news, formally.",
      must: ["I regret to", "I'm pleased to", "we're sorry to"],
      criteria: "The answer announces news formally with the correct opener for good and bad news.",
      example: "I'm pleased to confirm the date. I regret to say the venue has changed. We're sorry to give short notice.",
    },
    success: "The learner announces both good and bad news in appropriate formal language.",
    quiz: [
      qmcq("Which sentence introduces bad news the speaker is about to give?", [
        "I regret to inform you of the decision.",
        "I regret informing you of the decision yesterday.",
        "I regret to informing you of the decision.",
      ], 0),
      qfill("We're ___ to offer you the position. (delight)", ["delighted", "pleased"]),
      qmcq("Which opener is softest?", [
        "We're sorry to say there is a delay.",
        "We regret to inform you of the delay.",
        "There is a delay.",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Alonso", "an applicant awaiting a decision", "to hear the outcome of an application",
        "A decision must be communicated formally.",
        "Announce the news appropriately.",
        "You said you would call with a decision. What is the outcome?", "anxious"),
      sc("Mr. Reddy", "a client expecting an update", "to receive news about a delayed project",
        "A project has slipped and the client must be told.",
        "Announce the news formally.",
        "I have been waiting for an update. Where are we?", "formal"),
      sc("Ana Lucia", "a hotel guest expecting confirmation", "to have a booking confirmed or refused",
        "A booking request has an answer.",
        "Announce the outcome formally.",
        "Has my booking been confirmed for those dates?", "polite"),
      sc("Mr. Bergstrom", "your teacher", "to practise formal announcements",
        "The class is practising formal news.",
        "Announce good and bad news formally.",
        "How would you announce bad news to a client in writing?", "encouraging"),
      sc("Ms. Beaumont", "the examiner", "to check formal register",
        "The examiner asks for a formal announcement.",
        "Use the correct formal opener.",
        "How would you tell someone formally that their application was unsuccessful?", "neutral"),
    ],
  },

  {
    id: "b2-slightly-fairly-somewhat",
    topic: "softening how strong a description is",
    objectives: [
      "Use slightly, fairly and somewhat for different degrees and registers.",
      "Choose the right softener for the register.",
    ],
    goal: "Give an honest opinion without overstating it.",
    target: "downtoners: slightly, fairly, somewhat",
    correction: "Model the softened description and let the learner grade their own opinion.",
    summary: "You learned to soften a description with slightly, fairly and somewhat.",
    minutes: 8,
    points: [
      {
        form: "slightly better",
        claims: [
          "'Slightly' marks a very small difference and usually goes with a comparative.",
          "'Slightly better' means a little better, with only a small difference.",
        ],
        ex: ["It's slightly better than the old one.", "The second version is slightly clearer."],
      },
      {
        form: "fairly good",
        claims: [
          "'Fairly' usually gives a moderate assessment; its exact strength depends on the adjective and the tone.",
          "In British English 'quite' can express a similar moderate meaning, though its strength varies by context.",
        ],
        ex: ["The results are fairly good.", "It's fairly straightforward once you start."],
      },
      {
        form: "somewhat unusual",
        claims: [
          "'Somewhat' is more formal than 'fairly' and common in writing.",
          "'A bit' and 'a little' are the casual equivalents.",
        ],
        ex: ["The response was somewhat unusual.", "The figures are somewhat misleading."],
      },
    ],
    ex: [
      fill("It's ___ better than the old one, but not much. (slight)", ["slightly"]),
      mcq("Which sentence sounds most formal?", [
        "The response was somewhat unusual.",
        "The response was a bit odd.",
        "The response was pretty weird.",
      ], 0),
      fill("The results are ___ good, all things considered. (fair)", ["fairly"]),
      say("the figures / be / somewhat misleading", ["The figures are somewhat misleading."]),
    ],
    open: {
      q: "Give an honest but measured opinion on three things, softening each one differently.",
      must: ["slightly better", "fairly good", "somewhat unusual"],
      criteria: "The answer softens descriptions with slightly, fairly and somewhat appropriately.",
      example: "The new system is slightly better. The training was fairly good. The timing was somewhat unusual.",
    },
    success: "The learner softens at least two descriptions appropriately.",
    quiz: [
      qmcq("Which word marks the smallest difference?", ["slightly", "fairly", "considerably"], 0),
      qfill("It's ___ straightforward once you start. (fair)", ["fairly"]),
      qmcq("Which word is most formal?", ["somewhat", "a bit", "pretty"], 0),
    ],
    scenes: [
      sc("Corina", "a friend asking for an honest view", "to get a measured opinion",
        "A friend wants your honest but kind assessment.",
        "Soften your opinions appropriately.",
        "Be honest with me, but not brutal. What did you think?", "nervous"),
      sc("Malik", "a colleague reviewing your feedback", "to make written feedback less blunt",
        "Written feedback reads harsher than intended.",
        "Soften the descriptions.",
        "This reads quite harshly on the page. Can we soften it?", "editorial"),
      sc("Freya", "a host asking about the meal", "to hear an honest but polite reaction",
        "A host has cooked something unusual.",
        "React honestly but gently.",
        "Be honest, was it too strange for you?", "curious"),
      sc("Mr. Anand", "your teacher", "to practise downtoners",
        "The class is grading opinions.",
        "Soften opinions precisely.",
        "How do you say something is barely better than before?", "encouraging"),
      sc("Mrs. Boateng", "the examiner", "to check measured opinion",
        "The examiner asks for a balanced assessment.",
        "Grade the opinion carefully.",
        "Could you give me a measured opinion of something you use every day?", "neutral"),
    ],
  },

  {
    id: "b2-nearly-barely-hardly",
    topic: "near-negative words",
    objectives: [
      "Use barely and hardly to mean almost not.",
      "Avoid adding a second negative after them.",
    ],
    goal: "Say that something almost did not happen or almost is not true.",
    target: "nearly, barely and hardly",
    correction: "Rebuild the sentence with a single negative and let the learner say it again.",
    summary: "You learned that barely and hardly already carry the negative meaning.",
    minutes: 8,
    points: [
      {
        form: "barely enough",
        claims: [
          "'Barely' means only just, and it carries a negative feeling on its own.",
          "Say 'there was barely enough', not 'there wasn't barely enough'.",
        ],
        ex: ["There was barely enough time.", "I could barely hear her."],
      },
      {
        form: "hardly any",
        claims: [
          "'Hardly any' means almost none, and 'hardly ever' means almost never.",
          "The verb after them stays positive because the negative is already there.",
        ],
        ex: ["There were hardly any people.", "We hardly ever see them now."],
      },
      {
        form: "nearly finished",
        claims: [
          "'Nearly' and 'almost' do not work as negatives; they mean something came close to happening.",
          "The feeling comes from the situation, not the word: we nearly crashed is alarming, I am nearly finished is not.",
        ],
        ex: ["I'm nearly finished.", "We almost missed it."],
      },
    ],
    ex: [
      fill("There was ___ enough time to get there. (barely)", ["barely"]),
      mcq("Which sentence is correct?", [
        "There were hardly any people there.",
        "There weren't hardly any people there.",
        "There were hardly no people there.",
      ], 0),
      fill("We ___ ever see them these days. (hardly)", ["hardly"]),
      say("I / be / nearly finished", ["I'm nearly finished.", "I am nearly finished."]),
    ],
    open: {
      q: "Describe a situation where there was almost not enough of something, and one you almost completed.",
      must: ["barely enough", "hardly any", "nearly finished"],
      criteria: "The answer uses barely and hardly with a single negative, and nearly neutrally.",
      example: "There was barely enough time. We had hardly any warning. I was nearly finished when they arrived.",
    },
    success: "The learner uses barely or hardly correctly without doubling the negative.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "I could barely hear her.",
        "I couldn't barely hear her.",
        "I could barely not hear her.",
      ], 0),
      qfill("We ___ ever go there now. (hardly)", ["hardly"]),
      qmcq("Which word is neutral rather than negative?", ["nearly", "barely", "hardly"], 0),
    ],
    scenes: [
      sc("Priya", "a friend after a close call", "to hear how close it was",
        "Something was completed only just in time.",
        "Describe how close it was.",
        "You made it by minutes, didn't you? How bad was it?", "curious"),
      sc("Gareth", "a colleague reviewing resources", "to judge whether resources were adequate",
        "A project ran on very tight resources.",
        "Describe how little there was.",
        "Did we actually have what we needed on that job?", "assessing"),
      sc("Sandrine", "a fellow traveller after a tight connection", "to compare how close you both came",
        "A connection was made with almost no time to spare.",
        "Describe the margin.",
        "How much time did you actually have between flights?", "amazed"),
      sc("Mr. Dabiri", "your teacher", "to practise near-negatives",
        "The class is describing tight margins.",
        "Use barely and hardly correctly.",
        "How do you say there was almost not enough, in one word?", "encouraging"),
      sc("Ms. Halvorsen", "the examiner", "to check near-negatives",
        "The examiner asks about a close call.",
        "Use the forms accurately.",
        "Could you tell me about a time when you only just managed something?", "neutral"),
    ],
  },

  {
    id: "b2-close-enough",
    topic: "approximating without exact facts",
    objectives: [
      "Give a usable answer when you lack exact figures.",
      "Signal clearly that the figure is approximate.",
    ],
    goal: "Answer a factual question when you do not know the exact answer.",
    target: "approximating language",
    correction: "Model the approximation and let the learner answer again.",
    summary: "You learned to answer usefully when you do not have exact facts.",
    minutes: 7,
    points: [
      {
        form: "roughly speaking",
        claims: [
          "'Roughly speaking' opens an approximate answer and warns the listener.",
          "It usually starts the sentence, before the figure.",
        ],
        ex: ["Roughly speaking, about a third.", "Roughly speaking, it takes an hour."],
      },
      {
        form: "somewhere around",
        claims: [
          "'Somewhere around' or 'somewhere in the region of' softens a figure.",
          "The second is more formal and common in writing.",
        ],
        ex: ["Somewhere around fifty.", "Somewhere in the region of two thousand."],
      },
      {
        form: "give or take ten minutes",
        claims: [
          "'Give or take' introduces the size of the possible margin: give or take ten minutes.",
          "It is informal and follows the figure; 'give or take a bit' leaves the margin vague.",
        ],
        ex: ["An hour, give or take ten minutes.", "Three hundred, give or take a bit."],
      },
    ],
    ex: [
      fill("___ speaking, about a third of them agreed. (rough)", ["Roughly"]),
      mcq("Which phrase is most formal?", [
        "somewhere in the region of",
        "give or take a bit",
        "roughly speaking",
      ], 0),
      say("an hour / give or take a bit", ["An hour, give or take a bit."]),
    ],
    open: {
      q: "Someone asks you three factual questions you cannot answer exactly. Answer usefully anyway.",
      must: ["roughly speaking", "somewhere around", "give or take a bit"],
      criteria: "The answer gives approximate figures and marks them clearly as approximate.",
      example: "Roughly speaking, about half. Somewhere around forty people came. It lasted two hours, give or take a bit.",
    },
    success: "The learner gives at least two clearly marked approximations.",
    quiz: [
      qmcq("Which phrase opens an approximate answer?", [
        "Roughly speaking,",
        "Precisely,",
        "Exactly,",
      ], 0),
      qfill("Somewhere ___ fifty people came. (around)", ["around"]),
      qmcq("Which phrase follows the number?", [
        "give or take a bit",
        "roughly speaking",
        "somewhere around",
      ], 0),
    ],
    scenes: [
      sc("Stefan", "a friend asking about numbers", "to get a usable answer",
        "A friend wants figures you never counted.",
        "Answer approximately.",
        "How many people were actually there, roughly?", "casual"),
      sc("Aditi", "a colleague building an estimate", "to get workable figures",
        "An estimate needs numbers nobody has exactly.",
        "Give approximate figures.",
        "Nobody has the real numbers. What is your best guess?", "pragmatic"),
      sc("Mateus", "a fellow traveller planning timings", "to plan a route roughly",
        "Timings must be estimated for a journey.",
        "Approximate the timings.",
        "How long does that leg take, more or less?", "relaxed"),
      sc("Ms. Kowalski", "your teacher", "to practise approximation",
        "The class is answering without exact facts.",
        "Approximate clearly.",
        "How many hours a week do you study, roughly?", "encouraging"),
      sc("Mr. Ozturk", "the examiner", "to check approximation",
        "The examiner asks unanswerable factual questions.",
        "Approximate and mark it clearly.",
        "Roughly how many people live in your city?", "neutral"),
    ],
  },

  {
    id: "b2-loaded-words",
    topic: "words that describe similar behaviour with different evaluations",
    objectives: [
      "Choose between words that describe similar facts but carry different evaluations.",
      "Reframe something by renaming it.",
    ],
    goal: "Notice and choose the feeling a word carries.",
    target: "connotation and reframing",
    correction: "Offer the alternative wording and let the learner reframe their own description.",
    summary: "You learned that similar descriptions can frame the same behaviour positively or negatively.",
    minutes: 7,
    points: [
      {
        form: "I'd call it",
        claims: [
          "'I'd call it...' offers a different word for the same thing.",
          "It reframes without directly contradicting the other person.",
        ],
        ex: ["I'd call it careful rather than slow.", "I'd call it firm, not rude."],
      },
      {
        form: "you could say",
        claims: [
          "'You could say' introduces a milder or harsher alternative.",
          "It concedes that both words fit the same facts.",
        ],
        ex: ["You could say she's direct.", "You could say it was a mistake."],
      },
      {
        form: "that's putting it mildly",
        claims: [
          "'That's putting it mildly' says the real situation is stronger than the word used.",
          "It comments on someone else's choice of word rather than the facts.",
        ],
        ex: ["Difficult? That's putting it mildly.", "That's putting it mildly, to be honest."],
      },
    ],
    ex: [
      fill("I'd ___ it careful rather than slow. (call)", ["call"]),
      mcq("Which sentence reframes without contradicting?", [
        "I'd call it firm, not rude.",
        "You are completely wrong about that.",
        "That is not what happened.",
      ], 0),
      say("that / be / putting it mildly", ["That's putting it mildly.", "That is putting it mildly."]),
    ],
    open: {
      q: "Describe a person or situation twice: once with a critical word and once with a kinder one.",
      must: ["I'd call it", "you could say", "that's putting it mildly"],
      criteria: "The answer reframes the same facts with words carrying different feelings.",
      example: "You could say he's stubborn. I'd call it determined. Was it tense? That's putting it mildly.",
    },
    success: "The learner reframes the same facts with at least two different words.",
    quiz: [
      qmcq("Which phrase offers a different word?", [
        "I'd call it careful.",
        "It is what it is.",
        "That is the fact.",
      ], 0),
      qfill("You could ___ she's direct rather than blunt. (say)", ["say"]),
      qmcq("Which phrase says the reality is stronger?", [
        "That's putting it mildly.",
        "That's about right.",
        "That's an exaggeration.",
      ], 0),
    ],
    scenes: [
      sc("Ilse", "a friend describing someone harshly", "to see the same person differently",
        "A friend has described someone in unkind terms.",
        "Reframe the description.",
        "He is just difficult, isn't he? Or am I being unfair?", "irritated"),
      sc("Tomasz", "a colleague drafting a reference", "to word a reference fairly",
        "A reference must be honest but not damaging.",
        "Reframe the wording.",
        "This wording sounds harsh. How else could we put it?", "careful"),
      sc("Aiko", "a fellow traveller describing a place", "to compare impressions of a place",
        "Two travellers describe the same place very differently.",
        "Reframe the description.",
        "You called it charming and I called it run-down. Who is right?", "amused"),
      sc("Mr. Villanueva", "your teacher", "to practise connotation",
        "The class is comparing loaded and neutral words.",
        "Reframe a description.",
        "What is a kinder word for 'stubborn'?", "encouraging"),
      sc("Mrs. Sorensen", "the examiner", "to check awareness of connotation",
        "The examiner uses a loaded word deliberately.",
        "Reframe it.",
        "Would you describe your generation as lazy?", "neutral"),
    ],
  },

  {
    id: "b2-saying-it-kindly",
    topic: "delivering an unwelcome opinion",
    objectives: [
      "Prepare the listener before giving a hard opinion.",
      "Be honest without causing offence.",
    ],
    goal: "Tell someone something they will not want to hear.",
    target: "delivering unwelcome opinions",
    correction: "Model the preparing phrase and let the learner deliver their own opinion.",
    summary: "You practised giving an honest opinion without causing offence.",
    minutes: 7,
    points: [
      {
        form: "I hope you don't mind",
        claims: [
          "'I hope you don't mind me saying' warns the listener before the honesty arrives.",
          "It prepares the listener and can soften what follows, but the content and tone still have to be respectful.",
        ],
        ex: ["I hope you don't mind me saying this.", "I hope you don't mind, but it needs work."],
      },
      {
        form: "with respect",
        claims: [
          "'With respect' signals disagreement with someone senior or in public.",
          "In British English it can sound sharp, so the tone matters.",
        ],
        ex: ["With respect, I see it differently.", "With respect, the figures say otherwise."],
      },
      {
        form: "can I be frank",
        claims: [
          "'Can I be frank?' asks permission before speaking bluntly.",
          "It signals that a direct opinion is coming; it does not make an unkind comment acceptable.",
        ],
        ex: ["Can I be frank with you?", "Can I be honest? It isn't working."],
      },
    ],
    ex: [
      fill("I hope you don't ___ me saying this. (mind)", ["mind"]),
      mcq("Which phrase asks permission first?", [
        "Can I be frank with you?",
        "You are wrong about this.",
        "Let me tell you the truth.",
      ], 0),
      say("with respect / I / see it differently", ["With respect, I see it differently."]),
    ],
    open: {
      q: "You have to tell someone their work is not good enough. Prepare them, then say it honestly.",
      must: ["I hope you don't mind", "with respect", "can I be frank"],
      criteria: "The answer prepares the listener before delivering an honest, unwelcome opinion.",
      example: "Can I be frank? I don't think it's ready. I hope you don't mind me saying so; with respect, the argument needs work.",
    },
    success: "The learner prepares the listener and delivers the opinion honestly.",
    quiz: [
      qmcq("Which phrase prepares the listener?", [
        "I hope you don't mind me saying this.",
        "Here is what is wrong.",
        "You will not like this.",
      ], 0),
      qfill("Can I be ___ with you for a moment? (frank)", ["frank", "honest"]),
      qmcq("Which phrase signals disagreement with someone senior?", [
        "With respect,",
        "Obviously,",
        "As you know,",
      ], 0),
    ],
    scenes: [
      sc("Njeri", "a friend showing you their work", "to get an honest reaction",
        "A friend has shown you work that needs improvement.",
        "Prepare them and be honest.",
        "I have been working on this for weeks. What do you think?", "hopeful"),
      sc("Viktor", "a senior colleague you disagree with", "to hear a different view respectfully",
        "You disagree with someone more senior in a meeting.",
        "Disagree respectfully.",
        "I think the plan is sound. Does anyone see it differently?", "authoritative"),
      sc("Paloma", "a host asking about the arrangements", "to hear honest feedback about the stay",
        "A host wants genuine feedback about something imperfect.",
        "Be honest but kind.",
        "Please be honest, was everything all right for you?", "sincere"),
      sc("Ms. Adeyemi", "your teacher", "to practise diplomatic honesty",
        "The class is practising difficult feedback.",
        "Prepare and deliver honestly.",
        "How do you tell someone their work needs improving?", "encouraging"),
      sc("Mr. Castellano", "the examiner", "to check diplomatic language",
        "The examiner asks for honest criticism.",
        "Prepare the listener and be honest.",
        "How would you tell a colleague their idea will not work?", "neutral"),
    ],
  },

  // --- Ünite 10 · Formal and Informal ----------------------------------------
  {
    id: "b2-would-you-be-so-kind",
    topic: "formal requests",
    objectives: [
      "Make a request in formal language.",
      "Judge how formal a situation needs you to be.",
    ],
    goal: "Ask for something in a formal situation without sounding stiff.",
    target: "formal request forms",
    correction: "Model the formal request and let the learner ask again at the right level.",
    summary: "You learned to make requests in formal language and to judge how far to go.",
    minutes: 7,
    points: [
      {
        form: "would you be so kind",
        claims: [
          "'Would you be so kind as to' is at the very formal end of the scale.",
          "In everyday situations it can sound stiff or even sarcastic.",
        ],
        ex: ["Would you be so kind as to forward it?", "Would you be so kind as to confirm?"],
      },
      {
        form: "I wonder if you could",
        claims: [
          "'I wonder if you could' is formal but natural in speech and email.",
          "It is a broadly polite choice in professional or unfamiliar situations when you are unsure how formal to be.",
        ],
        ex: ["I wonder if you could check this.", "I wonder if you could spare a moment."],
      },
      {
        form: "if it's not too much",
        claims: [
          "'If it's not too much trouble' acknowledges that you are asking a favour.",
          "It usually comes after the request rather than before it.",
        ],
        ex: ["Could you send it, if it's not too much trouble?", "If it's not too much trouble, I'd appreciate it."],
      },
    ],
    ex: [
      fill("I ___ if you could check this for me. (wonder)", ["wonder"]),
      mcq("Which request is the most formal?", [
        "Would you be so kind as to confirm?",
        "Could you confirm?",
        "Confirm this, please.",
      ], 0),
      say("if it / not be / too much trouble", ["If it's not too much trouble.", "If it is not too much trouble."]),
    ],
    open: {
      q: "Make the same request three times: to a stranger, to a client and to a senior colleague.",
      must: ["would you be so kind", "I wonder if you could", "if it's not too much"],
      criteria: "The answer makes formal requests and adjusts the level to the situation.",
      example: "To a stranger: I wonder if you could check this. To a client: would you be so kind as to confirm, if it's not too much trouble?",
    },
    success: "The learner makes at least two formal requests at an appropriate level.",
    quiz: [
      qmcq("Which request is safest when unsure?", [
        "I wonder if you could check this.",
        "Would you be so kind as to check this?",
        "Check this for me.",
      ], 0),
      qfill("Would you be so ___ as to forward it? (kind)", ["kind"]),
      qmcq("Which phrase acknowledges the favour?", [
        "if it's not too much trouble",
        "as soon as possible",
        "at your earliest convenience",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Alonso", "a senior contact you barely know", "to consider your request",
        "You are asking a favour of someone senior and unfamiliar.",
        "Make the request at the right level.",
        "You wanted to ask me something?", "formal"),
      sc("Mr. Reddy", "a client you must not offend", "to grant a request",
        "A request must be made carefully to a client.",
        "Make it formally.",
        "You mentioned there was something you needed. What is it?", "reserved"),
      sc("Hugo", "an official at a government office", "to process your request",
        "An official process requires a formal request.",
        "Ask formally.",
        "Next, please. What can I do for you?", "brisk"),
      sc("Mr. Bergstrom", "your teacher", "to practise formal requests",
        "The class is grading requests by formality.",
        "Make requests at different levels.",
        "How would you ask a stranger for a favour, very politely?", "encouraging"),
      sc("Ms. Whitfield", "the examiner", "to check formal register",
        "The examiner plays a senior figure.",
        "Make a formal request.",
        "I understand you have a request. What is it?", "neutral"),
    ],
  },

  {
    id: "b2-give-us-a-hand",
    topic: "casual requests between people who know each other",
    objectives: [
      "Ask for help informally.",
      "Recognise where informal requests are appropriate.",
    ],
    goal: "Ask a friend or close colleague for help naturally.",
    target: "informal request forms",
    correction: "Model the casual request and let the learner ask again naturally.",
    summary: "You learned to ask for help casually between people who know each other.",
    minutes: 7,
    points: [
      {
        form: "give us a hand",
        claims: [
          "'Give us a hand' normally means help us; in informal British speech 'us' can also stand for 'me'.",
          "'Give me a hand' is the safe standard form when the help is for you alone.",
        ],
        ex: ["Give us a hand with these, would you?", "Can you give me a hand for a second?"],
      },
      {
        form: "can you grab",
        claims: [
          "'Grab' informally means fetch or get: can you grab the keys?",
          "'Can you' is enough between people who know each other well.",
        ],
        ex: ["Can you grab the keys on your way?", "Can you grab me a coffee?"],
      },
      {
        form: "do us a favour",
        claims: [
          "'Do us a favour' introduces a small request between friends.",
          "In a different tone it can mean disbelief, so context and voice matter.",
        ],
        ex: ["Do us a favour and lock up afterwards.", "Do me a favour and call them back."],
      },
    ],
    ex: [
      fill("___ us a hand with this, would you? (give)", ["Give"]),
      mcq("Which request is informal?", [
        "Can you grab the keys on your way?",
        "Would you be so kind as to fetch the keys?",
        "I wonder if you could locate the keys.",
      ], 0),
      say("do us a favour / and lock up / afterwards", ["Do us a favour and lock up afterwards."]),
    ],
    open: {
      q: "Ask a close colleague for three small favours, informally.",
      must: ["give us a hand", "can you grab", "do us a favour"],
      criteria: "The answer makes informal requests that suit a close working relationship.",
      example: "Give us a hand with this box. Can you grab the keys too? Do us a favour and lock up afterwards.",
    },
    success: "The learner makes at least two natural informal requests.",
    quiz: [
      qmcq("Which sentence is informal?", [
        "Do me a favour and call them back.",
        "I would be grateful if you would call them.",
        "Would you be so kind as to call them?",
      ], 0),
      qfill("Can you ___ me a coffee while you're up? (grab)", ["grab", "get"]),
      qmcq("Who would you say 'give us a hand' to?", [
        "a close colleague",
        "a new client",
        "a government official",
      ], 0),
    ],
    scenes: [
      sc("Emeka", "a close colleague", "to help you out quickly",
        "You need quick help from someone you work with daily.",
        "Ask informally.",
        "You look like you are struggling there. Need anything?", "friendly"),
      sc("Chiara", "a flatmate", "to share small household jobs",
        "Small household jobs need sharing.",
        "Ask casually.",
        "I am heading out in a minute. Anything you need?", "casual"),
      sc("Ferran", "a friend helping you move", "to be directed during a move",
        "A friend is helping you move furniture.",
        "Direct them informally.",
        "Right, where do you want me?", "willing"),
      sc("Mrs. Iversen", "your teacher", "to practise informal requests",
        "The class is comparing formal and informal requests.",
        "Ask informally.",
        "How would you ask a friend for help carrying something?", "encouraging"),
      sc("Mr. Sasaki", "the examiner", "to check register awareness",
        "The examiner asks you to adjust register.",
        "Ask informally where appropriate.",
        "How would you ask a close friend for a small favour?", "neutral"),
    ],
  },

  {
    id: "b2-i-am-writing-to-enquire",
    topic: "the language of a formal written message",
    objectives: [
      "Open and close a formal email correctly.",
      "State your purpose in the first line.",
    ],
    goal: "Write a formal email that gets a helpful reply.",
    target: "formal written conventions",
    correction: "Model the formal line and let the learner rewrite their own.",
    summary: "You learned the standard openings and closings of a formal written message.",
    minutes: 7,
    points: [
      {
        form: "I am writing to",
        claims: [
          "'I am writing to enquire about' states the purpose in the first line.",
          "In highly formal writing the full forms are preferred; in ordinary professional email contractions are acceptable.",
        ],
        ex: ["I am writing to enquire about the course.", "I am writing to confirm our order."],
      },
      {
        form: "I would be grateful",
        claims: [
          "'I would be grateful if you could' is the standard formal request.",
          "It is followed by 'could' plus a base verb, not by 'to'.",
        ],
        ex: ["I would be grateful if you could confirm.", "I would be grateful for any information."],
      },
      {
        form: "please find attached",
        claims: [
          "'Please find attached' introduces a document in a formal message.",
          "'I have attached' is more direct and often more natural in modern professional email.",
        ],
        ex: ["Please find attached the completed form.", "Please find attached our invoice."],
      },
    ],
    ex: [
      fill("I am ___ to enquire about the course dates. (write)", ["writing"]),
      mcq("Which sentence is correct?", [
        "I would be grateful if you could confirm.",
        "I would be grateful if you could to confirm.",
        "I would be grateful you confirm.",
      ], 0),
      fill("Please find ___ the completed form. (attach)", ["attached"]),
      say("I / be writing / to confirm / our order", ["I am writing to confirm our order."]),
    ],
    open: {
      q: "Write the opening of a formal email asking about a course, requesting information and attaching a form.",
      must: ["I am writing to", "I would be grateful", "please find attached"],
      criteria: "The answer opens formally, states the purpose and makes a formal request.",
      example: "I am writing to enquire about the course. I would be grateful if you could confirm. Please find attached my form.",
    },
    success: "The learner opens formally and makes a formal request.",
    quiz: [
      qmcq("Which opening is formal?", [
        "I am writing to enquire about the course.",
        "Just wondering about the course.",
        "Quick question about the course.",
      ], 0),
      qfill("I would be ___ for any information you can give. (grateful)", ["grateful"]),
      qmcq("Which sentence introduces a document?", [
        "Please find attached our invoice.",
        "Please see you soon.",
        "Please confirm the date.",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Petrov", "an admissions officer", "to answer a formal enquiry",
        "You are enquiring formally about a course.",
        "Make the enquiry formally.",
        "Thank you for contacting us. How can I help?", "professional"),
      sc("Mr. Osei", "a supplier's account team", "to process a formal request",
        "A formal written request is needed at work.",
        "State the purpose and request formally.",
        "We received your message. Could you confirm what you need?", "formal"),
      sc("Ana Lucia", "a consulate officer", "to handle a formal application",
        "A formal application requires careful wording.",
        "State your purpose formally.",
        "Good morning. What is the nature of your enquiry?", "official"),
      sc("Mr. Wickham", "your teacher", "to practise formal writing",
        "The class is drafting formal emails.",
        "Open and request formally.",
        "How do you open a formal email to someone you have never met?", "encouraging"),
      sc("Ms. Roux", "the examiner", "to check formal written register",
        "The examiner asks you to compose formally.",
        "Use formal conventions.",
        "How would you begin a formal email asking about a job?", "neutral"),
    ],
  },

  {
    id: "b2-just-a-quick-one",
    topic: "the language of a casual written message",
    objectives: [
      "Open and close a casual message naturally.",
      "Keep a short message short.",
    ],
    goal: "Write a short informal message that does not sound abrupt.",
    target: "informal written conventions",
    correction: "Model the casual line and let the learner shorten their own message.",
    summary: "You learned the conventions of a short informal written message.",
    minutes: 7,
    points: [
      {
        form: "quick one",
        claims: [
          "'Quick one' signals that the message is short and needs little effort to answer.",
          "It sets expectations, which is why it is common at work.",
        ],
        ex: ["Quick one: are we still on for Friday?", "Just a quick one about tomorrow."],
      },
      {
        form: "just checking",
        claims: [
          "'Just checking' softens a follow-up so it does not read as chasing.",
          "'Just' does the softening work here.",
        ],
        ex: ["Just checking you got my last message.", "Just checking the time hasn't changed."],
      },
      {
        form: "let me know",
        claims: [
          "'Let me know' closes an informal message without a formal sign-off.",
          "Adding a time makes it a real request: let me know by Thursday.",
        ],
        ex: ["Let me know when you can.", "Let me know either way."],
      },
    ],
    ex: [
      fill("Just a ___ one: are we still on for Friday? (quick)", ["quick"]),
      mcq("Which sentence softens a follow-up?", [
        "Just checking you got my last message.",
        "You have not replied to me.",
        "I am still waiting for your answer.",
      ], 0),
      say("let me know / either way", ["Let me know either way."]),
    ],
    open: {
      q: "Write a short informal message: ask a quick question, follow up on something and ask for a reply.",
      must: ["quick one", "just checking", "let me know"],
      criteria: "The answer is short, informal and does not read as abrupt.",
      example: "Quick one: are we still on for Friday? Just checking you saw my last message. Let me know either way.",
    },
    success: "The learner writes a short informal message that stays friendly.",
    quiz: [
      qmcq("Which opening is informal?", [
        "Quick one about tomorrow.",
        "I am writing to enquire about tomorrow.",
        "I would be grateful for information about tomorrow.",
      ], 0),
      qfill("Just ___ the time hasn't changed. (check)", ["checking"]),
      qmcq("Which closing is informal?", [
        "Let me know when you can.",
        "I look forward to your response.",
        "Yours faithfully.",
      ], 0),
    ],
    scenes: [
      sc("Halima", "a close colleague", "to answer a quick question",
        "A short question needs a quick answer.",
        "Write informally and briefly.",
        "You pinged me? What's up?", "casual"),
      sc("Konstantin", "a teammate on a shared task", "to confirm a small detail",
        "A small detail needs confirming quickly.",
        "Follow up casually.",
        "Sorry, I missed your message earlier. What did you need?", "apologetic"),
      sc("Lena", "a friend organising a meet-up", "to sort out the details quickly",
        "Plans need confirming between friends.",
        "Write a short casual message.",
        "Are we still doing Friday or has that changed?", "easy"),
      sc("Mrs. Dube", "your teacher", "to practise informal writing",
        "The class is comparing formal and informal messages.",
        "Write informally and briefly.",
        "How would you send a quick work message to a colleague you know well?", "encouraging"),
      sc("Mr. Ellery", "the examiner", "to check informal register",
        "The examiner asks for an informal message.",
        "Keep it short and friendly.",
        "How would you message a friend to check a plan?", "neutral"),
    ],
  },

  {
    id: "b2-softening-the-blow",
    topic: "distancing language for bad news",
    objectives: [
      "Use distancing language to make bad news land gently.",
      "Avoid stating a problem more bluntly than necessary.",
    ],
    goal: "Give bad news without making it worse.",
    target: "distancing and hedging in bad news",
    correction: "Model the softened version and let the learner deliver the news again.",
    summary: "You learned to soften bad news with distancing language.",
    minutes: 8,
    points: [
      {
        form: "unfortunately we",
        claims: [
          "'Unfortunately' signals bad news before the sentence delivers it.",
          "One signal is enough; stacking several sounds evasive.",
        ],
        ex: ["Unfortunately we can't confirm yet.", "Unfortunately the date has moved."],
      },
      {
        form: "I'm afraid there's",
        claims: [
          "'I'm afraid there's a problem' names the problem without blaming anyone.",
          "'There is' avoids naming who caused it, which lowers the temperature.",
        ],
        ex: ["I'm afraid there's been a delay.", "I'm afraid there's a small issue."],
      },
      {
        form: "it seems there may be",
        claims: [
          "'It seems there may be' adds two layers of distance: seems and may.",
          "Use it when the problem is not yet confirmed, not to avoid responsibility.",
        ],
        ex: ["It seems there may be a misunderstanding.", "It seems there may be an error."],
      },
    ],
    ex: [
      fill("___ we can't confirm the date yet. (unfortunate)", ["Unfortunately"]),
      mcq("Which sentence avoids blaming anyone?", [
        "I'm afraid there's been a delay.",
        "You have caused a delay.",
        "Your team delayed everything.",
      ], 0),
      fill("It ___ there may be a misunderstanding. (seem)", ["seems"]),
      say("I / be afraid / there be / a small issue", ["I'm afraid there's a small issue.", "I am afraid there is a small issue."]),
    ],
    open: {
      q: "Tell a client three pieces of bad news: a delay, an error and something you cannot confirm yet.",
      must: ["unfortunately we", "I'm afraid there's", "it seems there may be"],
      criteria: "The answer softens genuinely uncertain news, states confirmed problems clearly and avoids blaming others.",
      example: "Unfortunately we can't confirm yet. I'm afraid there's been a delay, and it seems there may be an error.",
    },
    success: "The learner delivers bad news with appropriate softening at least twice.",
    quiz: [
      qmcq("Which sentence adds the most distance?", [
        "It seems there may be an error.",
        "There is an error.",
        "You made an error.",
      ], 0),
      qfill("___ the date has moved again. (unfortunate)", ["Unfortunately"]),
      qmcq("Which sentence names a problem without blame?", [
        "I'm afraid there's a small issue.",
        "You created a small issue.",
        "Your side has an issue.",
      ], 0),
    ],
    scenes: [
      sc("Priscilla", "a client expecting good news", "to receive bad news as gently as possible",
        "A client must be told about a delay.",
        "Deliver the news gently.",
        "I assume everything is on track for next week?", "expectant"),
      sc("Mr. Lowell", "a supplier you must correct", "to be told about an error without conflict",
        "A supplier has made an error you must raise.",
        "Raise it without blaming.",
        "You said there was something about the last delivery?", "open"),
      sc("Anouk", "a guest whose booking has a problem", "to be told about a problem calmly",
        "A booking problem must be explained to a guest.",
        "Deliver the news gently.",
        "I am just checking in. Everything in order?", "cheerful"),
      sc("Ms. Kaur", "your teacher", "to practise softening bad news",
        "The class is delivering difficult messages.",
        "Soften the news appropriately.",
        "How do you tell a client there is a delay, without making it worse?", "encouraging"),
      sc("Mr. Eriksen", "the examiner", "to check hedging in bad news",
        "The examiner plays someone expecting good news.",
        "Deliver bad news with appropriate distance.",
        "Everything is ready for tomorrow, I hope?", "neutral"),
    ],
  },

  {
    id: "b2-a-difficult-email",
    topic: "raising a delicate matter in writing",
    objectives: [
      "Introduce a sensitive subject in writing.",
      "Acknowledge the other side before making your point.",
    ],
    goal: "Write to someone about something awkward.",
    target: "raising a delicate matter",
    correction: "Model the careful opening and let the learner raise their own matter.",
    summary: "You practised raising an awkward subject in writing.",
    minutes: 7,
    points: [
      {
        form: "I wanted to raise",
        claims: [
          "'I wanted to raise something with you' introduces the subject before the detail.",
          "The past 'wanted' is a distancing device, not a real past tense here.",
        ],
        ex: ["I wanted to raise something with you.", "I wanted to raise a small concern."],
      },
      {
        form: "I appreciate that",
        claims: [
          "'I appreciate that...' acknowledges the other side before your point.",
          "The acknowledgement must be genuine or the message reads as insincere.",
        ],
        ex: ["I appreciate that you've been busy.", "I appreciate that this is difficult."],
      },
      {
        form: "would it be possible",
        claims: [
          "'Would it be possible to...' asks for a change without demanding it.",
          "It leaves the other person room to say no.",
        ],
        ex: ["Would it be possible to review it again?", "Would it be possible to move the date?"],
      },
    ],
    ex: [
      fill("I ___ to raise something with you. (want)", ["wanted"]),
      mcq("Which sentence acknowledges the other side?", [
        "I appreciate that you've been busy.",
        "You have not replied at all.",
        "This has been ignored twice.",
      ], 0),
      say("would it / be possible / to move / the date", ["Would it be possible to move the date?"]),
    ],
    open: {
      q: "Write to someone about a delicate problem. Introduce it, acknowledge their side and ask for a change.",
      must: ["I wanted to raise", "I appreciate that", "would it be possible"],
      criteria: "The answer introduces the subject, acknowledges the other side and requests a change politely.",
      example: "I wanted to raise something. I appreciate that you've been busy. Would it be possible to review it again?",
    },
    success: "The learner raises the matter, acknowledges the other side and requests a change.",
    quiz: [
      qmcq("Which sentence introduces a subject carefully?", [
        "I wanted to raise a small concern.",
        "There is a serious problem here.",
        "This needs sorting out now.",
      ], 0),
      qfill("I ___ that this is difficult for you. (appreciate)", ["appreciate"]),
      qmcq("Which request leaves room for no?", [
        "Would it be possible to move the date?",
        "Move the date, please.",
        "The date must move.",
      ], 0),
    ],
    scenes: [
      sc("Ingeborg", "a friend who owes you money", "to be reminded without embarrassment",
        "A friend has forgotten to repay something.",
        "Raise it delicately.",
        "You sounded serious on the phone. What did you want to talk about?", "unaware"),
      sc("Rashid", "a colleague missing deadlines", "to understand there is a problem",
        "A colleague's late work is affecting others.",
        "Raise it carefully.",
        "You said you wanted a word. What's on your mind?", "receptive"),
      sc("Cecilia", "a landlord who has not fixed something", "to act on a repeated request",
        "A repair has been promised and not done.",
        "Raise it politely but firmly.",
        "You have emailed a few times now. What is the issue?", "defensive"),
      sc("Mr. Steiner", "your teacher", "to practise delicate writing",
        "The class is drafting difficult messages.",
        "Raise a delicate matter carefully.",
        "How would you write to someone about a problem they caused?", "encouraging"),
      sc("Ms. Coelho", "the examiner", "to check diplomatic writing",
        "The examiner asks you to raise something awkward.",
        "Introduce, acknowledge and request.",
        "How would you write to a colleague whose work is late?", "neutral"),
    ],
  },

  {
    id: "b2-same-thing-two-ways",
    topic: "one message in two registers",
    objectives: [
      "Say the same thing formally and casually.",
      "Notice what actually changes between the two.",
    ],
    goal: "Deliver one message at two different levels of formality.",
    target: "switching register",
    correction: "Give the message in one register and let the learner produce the other.",
    summary: "You practised saying one message formally and then casually.",
    minutes: 7,
    points: [
      {
        form: "formally you'd say",
        claims: [
          "The formal version uses full forms, longer verbs and no contractions.",
          "'I am writing to inform you' rather than 'just letting you know'.",
        ],
        ex: ["Formally you'd say 'I am unable to attend'.", "Formally you'd write 'please find attached'."],
      },
      {
        form: "but you'd tell a friend",
        claims: [
          "The casual version uses contractions, phrasal verbs and shorter sentences.",
          "'I can't make it' says the same as 'I am unable to attend'.",
        ],
        ex: ["But you'd tell a friend 'I can't make it'.", "But you'd tell a friend 'here it is'."],
      },
      {
        form: "same thing really",
        claims: [
          "The basic information can stay the same, but the wording changes the social meaning: distance, warmth and urgency.",
          "Choosing the wrong register is a social error, not a grammatical one.",
        ],
        ex: ["It's the same thing really.", "Same thing really, just said differently."],
      },
    ],
    ex: [
      fill("___ you'd say 'I am unable to attend'. (formal)", ["Formally"]),
      mcq("Which is the casual version of 'I am unable to attend'?", [
        "I can't make it.",
        "I regret to inform you of my absence.",
        "I shall be unable to be present.",
      ], 0),
      say("it / be / the same thing really", ["It's the same thing really.", "It is the same thing really."]),
    ],
    open: {
      q: "Take one message and say it twice: once formally and once as you would to a friend.",
      must: ["formally you'd say", "but you'd tell a friend", "same thing really"],
      criteria: "The answer gives the same message in two registers and notes what changed.",
      example: "Formally you'd say 'I am unable to attend'. But you'd tell a friend 'I can't make it'. Same thing really.",
    },
    success: "The learner delivers one message in both registers.",
    quiz: [
      qmcq("Which sentence is formal?", [
        "I am unable to attend.",
        "I can't make it.",
        "Can't come, sorry.",
      ], 0),
      qfill("___ thing really, just said differently. (same)", ["Same"]),
      qmcq("What usually changes between registers?", [
        "the wording and social tone, while the core message stays similar",
        "the basic facts only",
        "the grammar, from correct to incorrect",
      ], 0),
    ],
    scenes: [
      sc("Bruna", "a friend learning English with you", "to understand when to use which version",
        "A friend is confused about when to be formal.",
        "Give both versions of a message.",
        "I never know which version to use. Can you show me both?", "confused"),
      sc("Owen", "a colleague drafting two messages", "to send the right version to each person",
        "The same news must go to a client and a teammate.",
        "Produce both versions.",
        "Same news, two audiences. How do we word each?", "practical"),
      sc("Fatima", "a host curious about English registers", "to understand the difference",
        "A host is curious how English changes with formality.",
        "Demonstrate both registers.",
        "Is English very different when you are being polite?", "curious"),
      sc("Mr. Tremblay", "your teacher", "to practise register switching",
        "The class is converting between registers.",
        "Give both versions.",
        "How would you say 'I can't come' formally, and then casually?", "encouraging"),
      sc("Ms. Petrenko", "the examiner", "to check register control",
        "The examiner asks for both versions.",
        "Switch register cleanly.",
        "How would you decline an invitation formally, and then to a friend?", "neutral"),
    ],
  },

  // --- Ünite 11 · Discussing Real Issues -------------------------------------
  {
    id: "b2-on-the-rise",
    topic: "describing how numbers move",
    objectives: [
      "Describe a rise, a fall and a period of no change.",
      "Add an adverb to say how fast the change was.",
    ],
    goal: "Describe a trend in numbers clearly.",
    target: "describing trends",
    correction: "Model the trend sentence with its adverb and let the learner describe again.",
    summary: "You learned to describe how numbers rise, fall and level off.",
    minutes: 7,
    points: [
      {
        form: "has gone up",
        claims: [
          "The present perfect connects a past change to the situation now.",
          "'Has gone up' and 'has increased' say the same thing at different formality levels.",
        ],
        ex: ["The cost has gone up again.", "Numbers have increased since spring."],
      },
      {
        form: "risen sharply",
        claims: [
          "An adverb after the verb says how fast: sharply, steadily, slightly.",
          "'Sharply' describes a rapid or large change; 'steadily' describes change continuing at a fairly consistent rate.",
        ],
        ex: ["Prices have risen sharply.", "Attendance has fallen steadily."],
      },
      {
        form: "stayed the same",
        claims: [
          "'Stayed the same' means no change over the period; 'levelled off' means an earlier rise or fall stopped.",
          "That difference matters: one describes stability throughout, the other stability after movement.",
        ],
        ex: ["Numbers have stayed the same since June.", "It levelled off after the summer."],
      },
    ],
    ex: [
      fill("The cost ___ gone up again this year. (have)", ["has"]),
      mcq("Which sentence describes a fast, large change?", [
        "Prices have risen sharply.",
        "Prices have risen slightly.",
        "Prices have stayed the same.",
      ], 0),
      fill("Attendance has fallen ___ over three years. (steady)", ["steadily"]),
      say("numbers / have stay / the same / since June", ["Numbers have stayed the same since June."]),
    ],
    open: {
      q: "Describe how something in your life or work has changed over the last few years.",
      must: ["has gone up", "risen sharply", "stayed the same"],
      criteria: "The answer describes rises, falls and stability with suitable adverbs.",
      example: "Rent has gone up every year. Costs have risen sharply since 2022, though my salary has stayed the same.",
    },
    success: "The learner describes at least two trends with suitable adverbs.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "Numbers have increased since spring.",
        "Numbers have increase since spring.",
        "Numbers has increased since spring.",
      ], 0),
      qfill("It ___ off after the summer. (level)", ["levelled"]),
      qmcq("Which adverb describes change at a consistent rate?", ["steadily", "sharply", "suddenly"], 0),
    ],
    scenes: [
      sc("Kwabena", "a neighbour discussing the cost of living", "to compare how costs have changed",
        "Everyday costs have changed noticeably.",
        "Describe the trends.",
        "Everything seems more expensive lately. Have you noticed it too?", "concerned"),
      sc("Simone", "a colleague presenting figures", "to describe a chart clearly",
        "A chart must be described in a meeting.",
        "Describe the trends precisely.",
        "Can you talk us through what these numbers are doing?", "focused"),
      sc("Emil", "a local explaining changes in the town", "to describe how a place has changed",
        "A town has changed measurably over years.",
        "Describe the changes.",
        "This area is unrecognisable now. How much has it changed?", "reflective"),
      sc("Mrs. Aguilar", "your teacher", "to practise trend language",
        "The class is describing charts and changes.",
        "Describe a trend with an adverb.",
        "How would you describe something that got more expensive quickly?", "encouraging"),
      sc("Mr. Nakamura", "the examiner", "to check trend description",
        "The examiner asks about change over time.",
        "Describe trends accurately.",
        "Could you describe how something has changed in your country recently?", "neutral"),
    ],
  },

  {
    id: "b2-backing-up-an-opinion",
    topic: "supporting a claim with evidence",
    objectives: [
      "Introduce an example that supports a claim.",
      "Point to evidence beyond your own experience.",
    ],
    goal: "Make an opinion convincing by supporting it.",
    target: "supporting claims with examples",
    correction: "Model the example-introducing phrase and let the learner support their own claim.",
    summary: "You learned to support a claim with examples and evidence.",
    minutes: 7,
    points: [
      {
        form: "for instance",
        claims: [
          "'For instance' and 'for example' introduce one specific case.",
          "One well-chosen example persuades more than three vague ones.",
        ],
        ex: ["For instance, the shop on the corner closed.", "For instance, look at last winter."],
      },
      {
        form: "take ... for example",
        claims: [
          "'Take... for example' puts the example itself at the front of the sentence.",
          "It works well when the example is well known to both of you.",
        ],
        ex: ["Take the bus service, for example: it now runs hourly.", "Take last year, for example."],
      },
      {
        form: "that's borne out by",
        claims: [
          "'That's borne out by' points to evidence beyond your own view.",
          "It is formal and belongs in discussion rather than casual chat.",
        ],
        ex: ["That's borne out by the figures.", "That's borne out by what we saw."],
      },
    ],
    ex: [
      fill("___ instance, the shop on the corner closed last month. (for)", ["For"]),
      mcq("Which sentence points to outside evidence?", [
        "That's borne out by the figures.",
        "I feel that quite strongly.",
        "Everyone I know agrees.",
      ], 0),
      say("take / the bus service / for example", ["Take the bus service, for example."]),
    ],
    open: {
      q: "State an opinion about your town and support it with an example and some evidence.",
      // "take X for example" araya nesne alır, birebir geçemez → ölçüte konmaz
      must: ["for instance", "for example", "that's borne out by"],
      criteria: "The answer introduces a specific case with for instance or take ... for example, then supports it with evidence.",
      example: "Services have declined. For instance, two shops closed. Take the buses, for example: hourly now, and that's borne out by the timetable.",
    },
    success: "The learner supports a claim with at least one specific example and one piece of evidence.",
    quiz: [
      qmcq("Which phrase introduces one specific case?", ["For instance,", "In general,", "On the whole,"], 0),
      qfill("That's ___ out by the figures. (bear)", ["borne"]),
      qmcq("Which sentence puts the example first?", [
        "Take last year, for example.",
        "Last year was difficult.",
        "It was difficult last year.",
      ], 0),
    ],
    scenes: [
      sc("Zofia", "a friend who wants proof", "to be persuaded by more than opinion",
        "A friend is unconvinced by opinions alone.",
        "Support your claim with examples.",
        "You keep saying that, but where is your evidence?", "sceptical"),
      sc("Ravi", "a colleague challenging a claim", "to test whether a claim is supported",
        "A claim in a meeting needs support.",
        "Support it with examples and evidence.",
        "That is a strong claim. What is it based on?", "probing"),
      sc("Elif", "a local defending their town", "to hear a fair, supported view",
        "A conversation about a town's decline needs evidence.",
        "Support your view carefully.",
        "People always say this place is going downhill. Is that fair?", "protective"),
      sc("Mr. Delacroix", "your teacher", "to practise supporting claims",
        "The class is supporting opinions with evidence.",
        "Support a claim properly.",
        "What claim would you make about your town, and how would you back it up?", "encouraging"),
      sc("Ms. Bianchi", "the examiner", "to check supported argument",
        "The examiner asks for a supported opinion.",
        "Support the claim with examples.",
        "Could you give me an opinion about your city and support it?", "neutral"),
    ],
  },

  {
    id: "b2-where-do-you-stand",
    topic: "taking and defending a position",
    objectives: [
      "State where you stand on a contested question.",
      "Defend the position when it is challenged.",
    ],
    goal: "Take a clear position on something people disagree about.",
    target: "stating and defending a position",
    correction: "Model the position statement and let the learner state and defend their own.",
    summary: "You practised taking a clear position and defending it.",
    minutes: 7,
    points: [
      {
        form: "I come down on",
        claims: [
          "'I come down on the side of' states which side you have chosen after weighing both.",
          "It implies you considered the alternative, which makes the position stronger.",
        ],
        ex: ["I come down on the side of caution.", "I come down on the side of change."],
      },
      {
        form: "where I stand is",
        claims: [
          "'Where I stand is...' states the position plainly, without hedging.",
          "It works best after a long discussion, when the other person needs a clear answer.",
        ],
        ex: ["Where I stand is simple.", "Where I stand is that we should wait."],
      },
      {
        form: "I feel strongly that",
        claims: [
          "'I feel strongly that' marks the position as important to you, not just held.",
          "Overusing it weakens it, so save it for one point.",
        ],
        ex: ["I feel strongly that it's the wrong approach.", "I feel strongly about this one."],
      },
    ],
    ex: [
      fill("I come ___ on the side of caution here. (down)", ["down"]),
      mcq("Which sentence states a position plainly?", [
        "Where I stand is that we should wait.",
        "It is complicated, isn't it?",
        "There are many views on this.",
      ], 0),
      say("I / feel strongly / that it be / the wrong approach", ["I feel strongly that it's the wrong approach.", "I feel strongly that it is the wrong approach."]),
    ],
    open: {
      q: "Take a clear position on something people disagree about, and defend it against one objection.",
      must: ["I come down on", "where I stand is", "I feel strongly that"],
      criteria: "The answer states a clear position and defends it against an objection.",
      example: "Where I stand is clear: I come down on the side of change. Some say waiting is safer, but I feel strongly that delay costs more.",
    },
    success: "The learner states a clear position and defends it.",
    quiz: [
      qmcq("Which phrase implies you weighed both sides?", [
        "I come down on the side of caution.",
        "I have always thought this.",
        "Everyone knows this already.",
      ], 0),
      qfill("Where I ___ is that we should wait. (stand)", ["stand"]),
      qmcq("Which phrase should be used sparingly?", [
        "I feel strongly that",
        "I think that",
        "It seems that",
      ], 0),
    ],
    scenes: [
      sc("Rahim", "a friend pressing for your view", "to get a straight answer",
        "A friend wants your real position, not a balanced summary.",
        "State and defend your position.",
        "Enough on the one hand and on the other. Where do you actually stand?", "direct"),
      sc("Elke", "a colleague in a decision meeting", "to hear a clear recommendation",
        "A meeting needs someone to commit to a view.",
        "State the position and defend it.",
        "Everyone is hedging. Somebody has to say it. You?", "expectant"),
      sc("Georgios", "a fellow traveller in a real debate", "to have a genuine argument",
        "A genuine debate has started over dinner.",
        "Take a position and defend it.",
        "Nobody at this table will commit to anything. Will you?", "challenging"),
      sc("Mrs. Petrenko", "your teacher", "to practise taking positions",
        "The class is debating a contested topic.",
        "State and defend a position.",
        "Take a side on this and defend it. Which side?", "encouraging"),
      sc("Mr. Almeida", "the examiner", "to check position-taking",
        "The examiner asks for a committed view.",
        "Take a position and defend it.",
        "Should university education be free? Where do you stand?", "neutral"),
    ],
  },

  {
    id: "b2-scrolling-too-much",
    topic: "screen habits",
    objectives: [
      "Describe a habit you would like to change.",
      "Say what you are doing about it.",
    ],
    goal: "Talk honestly about your screen habits.",
    target: "discussing habits and change",
    correction: "Model the honest admission and let the learner describe their own habit.",
    summary: "You practised discussing a habit you would like to change.",
    minutes: 7,
    points: [
      {
        form: "I spend too much",
        claims: [
          "'I spend too much time on' admits the problem plainly.",
          "'Too much' already carries the judgement, so no extra criticism is needed.",
        ],
        ex: ["I spend too much time on my phone.", "I spend too much of the evening scrolling."],
      },
      {
        form: "can't help checking",
        claims: [
          "'I can't help doing' describes something you do without deciding to.",
          "It is followed by an -ing form, never by 'to'.",
        ],
        ex: ["I can't help checking it every few minutes.", "I can't help looking when it buzzes."],
      },
      {
        form: "cut down on",
        claims: [
          "'Cut down on' means reduce rather than stop completely.",
          "'Cut out' means stop entirely, which is a different claim.",
        ],
        ex: ["I'm trying to cut down on it.", "I've cut down on evening screen time."],
      },
    ],
    ex: [
      fill("I spend ___ much time on my phone in the evening. (too)", ["too"]),
      mcq("Which sentence is correct?", [
        "I can't help checking it every few minutes.",
        "I can't help to check it every few minutes.",
        "I can't help check it every few minutes.",
      ], 0),
      fill("I'm trying to cut ___ on evening screen time. (down)", ["down"]),
      say("I / have cut down / on evening screen time", ["I've cut down on evening screen time.", "I have cut down on evening screen time."]),
    ],
    open: {
      q: "Describe your screen habits honestly and say what, if anything, you are doing about them.",
      must: ["I spend too much", "can't help checking", "cut down on"],
      criteria: "The answer describes a habit honestly and says what is being done about it.",
      example: "I spend too much time scrolling. I can't help checking when it buzzes, but I'm trying to cut down on it.",
    },
    success: "The learner describes a habit honestly and mentions an attempt to change it.",
    quiz: [
      qmcq("Which phrase means reduce rather than stop?", ["cut down on", "cut out", "give up"], 0),
      qfill("I can't help ___ when it buzzes. (look)", ["looking"]),
      qmcq("Which sentence admits the problem plainly?", [
        "I spend too much time on my phone.",
        "Everyone uses their phone a lot.",
        "Phones are designed to be addictive.",
      ], 0),
    ],
    scenes: [
      sc("Ana", "a friend with the same habit", "to compare habits honestly",
        "Two friends admit the same habit.",
        "Describe yours honestly.",
        "I checked my screen time this morning and nearly cried. Dare you check yours?", "rueful"),
      sc("Tomas", "a colleague discussing focus at work", "to work out how to concentrate better",
        "Concentration at work has become difficult.",
        "Describe the habit and any changes.",
        "Nobody in this office can focus any more. Is it just me?", "frustrated"),
      sc("Pilar", "a host curious about your habits", "to compare habits across countries",
        "A conversation about daily life turns to phones.",
        "Describe your habits honestly.",
        "Are people glued to their phones where you come from too?", "curious"),
      sc("Mr. Adeyemi", "your teacher", "to practise discussing habits",
        "The class is discussing screen habits.",
        "Describe a habit and a change.",
        "How much time do you spend on your phone, honestly?", "encouraging"),
      sc("Ms. Novak", "the examiner", "to check extended discussion",
        "The examiner asks about modern habits.",
        "Discuss honestly and at length.",
        "Do you think people spend too much time on screens?", "neutral"),
    ],
  },

  {
    id: "b2-whats-for-dinner",
    topic: "food habits and cooking",
    objectives: [
      "Describe your general food habits.",
      "Compare cooking at home with eating out.",
    ],
    goal: "Talk at length about how you eat and cook.",
    target: "discussing food habits",
    correction: "Model the habit sentence and let the learner extend their own description.",
    summary: "You practised talking at length about food habits and cooking.",
    minutes: 7,
    points: [
      {
        form: "I tend to",
        claims: [
          "'I tend to' describes a general habit without claiming it is always true.",
          "It is softer and more accurate than 'I always'.",
        ],
        ex: ["I tend to cook at the weekend.", "I tend to eat late."],
      },
      {
        form: "eating out",
        claims: [
          "'Eating out' means eating in a restaurant; 'ordering in' means having it delivered.",
          "'Takeaway' is the British word for food collected or delivered.",
        ],
        ex: ["We only go out for special occasions.", "We eat out about once a month."],
      },
      {
        form: "cook from scratch",
        claims: [
          "'From scratch' means using raw ingredients rather than anything ready-made.",
          "'Ready meal' and 'convenience food' are the usual opposites.",
        ],
        ex: ["I cook from scratch most evenings.", "I rarely cook from scratch on weekdays."],
      },
    ],
    ex: [
      fill("I ___ to cook properly at the weekend. (tend)", ["tend"]),
      mcq("Which phrase means using raw ingredients?", [
        "cook from scratch",
        "order in",
        "heat it up",
      ], 0),
      say("we / eat out / about once a month", ["We eat out about once a month."]),
    ],
    open: {
      q: "Describe how you eat during the week and at weekends, and how much you cook yourself.",
      must: ["I tend to", "eating out", "cook from scratch"],
      criteria: "The answer describes food habits with general tendencies rather than absolutes.",
      example: "I tend to cook from scratch at weekends. During the week I make something quick. Eating out is a monthly treat.",
    },
    success: "The learner describes food habits at length using general tendencies.",
    quiz: [
      qmcq("Which phrase describes a general habit?", ["I tend to", "I always", "I never"], 0),
      qfill("I rarely cook from ___ on weekdays. (scratch)", ["scratch"]),
      qmcq("Which word is British for collected or delivered food?", ["takeaway", "takeout", "delivery"], 0),
    ],
    scenes: [
      sc("Camille", "a friend planning to cook for you", "to know what you eat",
        "A friend is cooking for you and wants to know your habits.",
        "Describe your food habits.",
        "I am cooking on Saturday. What do you actually eat?", "warm"),
      sc("Stefan", "a colleague organising a team meal", "to choose somewhere everyone will like",
        "A team meal must suit everyone.",
        "Describe your preferences and habits.",
        "I am booking somewhere for the team. What works for you?", "practical"),
      sc("Rosa", "a host cooking for guests", "to cook something you will enjoy",
        "A host is planning meals for your stay.",
        "Describe how you normally eat.",
        "I am shopping this afternoon. What do you usually have?", "hospitable"),
      sc("Mrs. Chen", "your teacher", "to practise extended description",
        "The class is discussing daily habits.",
        "Describe food habits at length.",
        "How do you usually eat during the week?", "encouraging"),
      sc("Mr. Ferreira", "the examiner", "to check extended everyday discussion",
        "The examiner asks about daily life.",
        "Describe habits at length.",
        "Could you tell me about how you eat and cook?", "neutral"),
    ],
  },

  {
    id: "b2-love-it-or-hate-it-tech",
    topic: "weighing what technology gives and takes",
    objectives: [
      "Say what you could not manage without.",
      "Say what you find genuinely annoying.",
    ],
    goal: "Give a balanced view of technology in your life.",
    target: "balanced discussion of technology",
    correction: "Model the strong-reaction sentence and let the learner weigh their own view.",
    summary: "You practised weighing what technology gives you against what it takes.",
    minutes: 7,
    points: [
      {
        form: "couldn't live without",
        claims: [
          "'I couldn't live without it' is a strong claim about dependence, not literal survival.",
          "Naming one specific thing is more convincing than a general statement.",
        ],
        ex: ["I couldn't live without maps on my phone.", "I couldn't live without messaging apps."],
      },
      {
        form: "drives me crazy",
        claims: [
          "'It drives me crazy' names a specific irritation strongly.",
          "'Drives me mad' is the more common British version.",
        ],
        ex: ["The notifications drive me crazy.", "Automatic updates drive me mad."],
      },
      {
        form: "best thing about",
        claims: [
          "'The best thing about it is' picks one advantage rather than listing several.",
          "'The worst thing about it is' does the same for disadvantages.",
        ],
        ex: ["The best thing about it is the convenience.", "The worst thing about it is the noise."],
      },
    ],
    ex: [
      fill("I ___ live without maps on my phone. (could not)", ["couldn't", "could not"]),
      mcq("Which sentence names a specific irritation?", [
        "The notifications drive me crazy.",
        "Technology is generally annoying.",
        "Everything is complicated now.",
      ], 0),
      say("the best thing about it / be / the convenience", ["The best thing about it is the convenience."]),
    ],
    open: {
      q: "Give a balanced view of technology: one thing you depend on and one thing that annoys you.",
      must: ["couldn't live without", "drives me crazy", "best thing about"],
      criteria: "The answer names a specific dependence and a specific irritation.",
      example: "I couldn't live without maps. The constant buzzing drives me crazy. The best thing about it is convenience.",
    },
    success: "The learner names both a specific dependence and a specific irritation.",
    quiz: [
      qmcq("Which sentence is a strong claim about dependence?", [
        "I couldn't live without messaging apps.",
        "I use messaging apps sometimes.",
        "Messaging apps exist.",
      ], 0),
      qfill("Automatic updates drive me ___. (mad)", ["mad", "crazy"]),
      qmcq("Which phrase picks one advantage?", [
        "The best thing about it is",
        "There are many good things",
        "It has various advantages",
      ], 0),
    ],
    scenes: [
      sc("Nikoletta", "a friend who dislikes technology", "to hear the other side",
        "A friend is sceptical about technology.",
        "Give a balanced view.",
        "I would throw my phone in a river. Am I mad?", "exasperated"),
      sc("Piotr", "a colleague discussing new tools", "to decide whether new tools help",
        "New tools have been introduced at work.",
        "Weigh what they give and take.",
        "Are these new systems actually helping anyone?", "sceptical"),
      sc("Hana", "a fellow traveller without a smartphone", "to compare how you each manage",
        "One traveller manages without a smartphone.",
        "Compare and weigh.",
        "I travel without a phone. Could you do that?", "curious"),
      sc("Mrs. Weber", "your teacher", "to practise balanced discussion",
        "The class is discussing technology.",
        "Weigh both sides.",
        "What could you not live without, and what drives you mad?", "encouraging"),
      sc("Mr. Ozturk", "the examiner", "to check balanced discussion",
        "The examiner asks about technology.",
        "Give a balanced view.",
        "Has technology improved daily life, in your view?", "neutral"),
    ],
  },

  {
    id: "b2-finding-common-ground",
    topic: "moving a disagreement towards agreement",
    objectives: [
      "Name what both sides already agree on.",
      "Isolate the real point of difference.",
    ],
    goal: "Move a disagreement towards something both sides can accept.",
    target: "finding common ground",
    correction: "Model the common-ground sentence and let the learner narrow the disagreement.",
    summary: "You practised moving a disagreement towards something both sides accept.",
    minutes: 7,
    points: [
      {
        form: "we both agree that",
        claims: [
          "Naming the agreement first makes the disagreement smaller than it looked.",
          "It also shows you have listened, which lowers the temperature.",
        ],
        ex: ["We both agree that something has to change.", "We both agree that the cost matters."],
      },
      {
        form: "where we differ",
        claims: [
          "'Where we differ is...' isolates the real disagreement precisely.",
          "Most disagreements are narrower than they appear once this is done.",
        ],
        ex: ["Where we differ is on the timing.", "Where we differ is on how fast we should move."],
      },
      {
        form: "can we settle on",
        claims: [
          "'Can we settle on...?' proposes a specific compromise.",
          "A concrete proposal moves a discussion further than a general appeal.",
        ],
        ex: ["Can we settle on a trial period?", "Can we settle on reviewing it in a month?"],
      },
    ],
    ex: [
      fill("We both ___ that something has to change. (agree)", ["agree"]),
      mcq("Which sentence isolates the disagreement?", [
        "Where we differ is on the timing.",
        "We disagree about everything.",
        "You are wrong about all of it.",
      ], 0),
      say("can we / settle on / a trial period", ["Can we settle on a trial period?"]),
    ],
    open: {
      q: "You disagree with someone. Name what you agree on, isolate the difference and propose a compromise.",
      must: ["we both agree that", "where we differ", "can we settle on"],
      criteria: "The answer names common ground, isolates the difference and proposes a specific compromise.",
      example: "We both agree that it has to change. Where we differ is the timing. Can we settle on a review in a month?",
    },
    success: "The learner names common ground and proposes a specific compromise.",
    quiz: [
      qmcq("Which sentence lowers the temperature?", [
        "We both agree that the cost matters.",
        "You never listen to anyone.",
        "This is a waste of time.",
      ], 0),
      qfill("Where we ___ is how fast to move. (differ)", ["differ"]),
      qmcq("Which sentence proposes a compromise?", [
        "Can we settle on a trial period?",
        "I refuse to change my mind.",
        "We will never agree on this.",
      ], 0),
    ],
    scenes: [
      sc("Marta", "a friend you keep arguing with", "to stop having the same argument",
        "The same disagreement keeps recurring.",
        "Find common ground and propose a compromise.",
        "We have had this argument three times now. Can we not settle it?", "tired"),
      sc("Dimitri", "a colleague in a stuck negotiation", "to break a deadlock",
        "A negotiation has stalled.",
        "Name agreement and propose a compromise.",
        "We are going nowhere. What can we actually agree on?", "pragmatic"),
      sc("Yuki", "a travel companion disagreeing on plans", "to agree a plan you both accept",
        "Two travellers want different things from a trip.",
        "Find common ground.",
        "You want cities and I want mountains. What do we do?", "cooperative"),
      sc("Mrs. Larsson", "your teacher", "to practise finding common ground",
        "The class is resolving disagreements.",
        "Narrow the disagreement and propose a compromise.",
        "How do you make a disagreement smaller than it looks?", "encouraging"),
      sc("Mr. Cabrera", "the examiner", "to check negotiation language",
        "The examiner disagrees with you deliberately.",
        "Find common ground and propose a compromise.",
        "I think exams should be abolished entirely. Can we find any agreement?", "neutral"),
    ],
  },

  {
    id: "b2-wrapping-up-a-discussion",
    topic: "closing a discussion cleanly",
    objectives: [
      "Summarise what was said.",
      "Close without forcing agreement.",
    ],
    goal: "End a long discussion cleanly, agreed or not.",
    target: "summarising and closing",
    correction: "Model the closing move and let the learner summarise their own discussion.",
    summary: "You practised summarising a discussion and closing it cleanly.",
    minutes: 7,
    points: [
      {
        form: "to sum up",
        claims: [
          "'To sum up' signals that you are about to condense, not add.",
          "Adding new points after it confuses the listener.",
        ],
        ex: ["To sum up, we agree on the problem.", "To sum up, nothing is decided yet."],
      },
      {
        form: "so where does that leave",
        claims: [
          "'So where does that leave us?' invites the other person to help close.",
          "It is a question, so it hands the turn over rather than ending alone.",
        ],
        ex: ["So where does that leave us?", "So where does that leave the plan?"],
      },
      {
        form: "let's leave it there",
        claims: [
          "'Let's leave it there' closes without forcing agreement.",
          "'For now' softens it further and keeps the subject open.",
        ],
        ex: ["Let's leave it there for now.", "Shall we leave it there?"],
      },
    ],
    ex: [
      fill("To ___ up, we agree on the problem but not the fix. (sum)", ["sum"]),
      mcq("Which sentence hands the turn over?", [
        "So where does that leave us?",
        "That is my final word.",
        "I have said everything.",
      ], 0),
      say("let us / leave it there / for now", ["Let's leave it there for now.", "Let us leave it there for now."]),
    ],
    open: {
      q: "Close a long discussion: summarise what was said, ask where it leaves you and close cleanly.",
      must: ["to sum up", "so where does that leave", "let's leave it there"],
      criteria: "The answer summarises the discussion and closes it without forcing agreement.",
      example: "To sum up, we agree on the problem but not the fix. So where does that leave us? If we can't decide today, let's leave it there.",
    },
    success: "The learner summarises the discussion and closes it cleanly.",
    quiz: [
      qmcq("Which phrase signals a summary?", ["To sum up,", "In addition,", "Furthermore,"], 0),
      qfill("So where does that ___ us? (leave)", ["leave"]),
      qmcq("Which sentence closes without forcing agreement?", [
        "Let's leave it there for now.",
        "So you agree with me then.",
        "That settles it completely.",
      ], 0),
    ],
    scenes: [
      sc("Barbara", "a friend after a long conversation", "to end the conversation well",
        "A long conversation has run its course.",
        "Summarise and close.",
        "We have been at this for an hour. Where have we got to?", "tired"),
      sc("Ivan", "a colleague chairing a meeting", "to close a meeting cleanly",
        "A meeting must end without a decision.",
        "Summarise and close.",
        "We are out of time. Can you pull it together for us?", "brisk"),
      sc("Zainab", "someone you met at a debate", "to end a debate on good terms",
        "A debate has been enjoyable but must end.",
        "Summarise and close warmly.",
        "This has been the best conversation I have had all week. Shall we call it?", "warm"),
      sc("Mr. Steiner", "your teacher", "to practise closing discussions",
        "The class is ending a long debate.",
        "Summarise and close.",
        "We are nearly out of time. How would you wrap this up?", "encouraging"),
      sc("Ms. Coelho", "the examiner", "to check summarising and closing",
        "The examiner ends a long discussion.",
        "Summarise and close cleanly.",
        "We have covered a lot. How would you sum it all up?", "neutral"),
    ],
  },
];
