/** C1 · Ünite 5-7 — Building an Argument · Narrative Craft · Precision (20 ders).
 *
 *  Ünite 5'te HİÇ gramer dersi yok ve bu kasıtlı: argüman kurmak bir yapı sorunu
 *  değil, sıralama sorunu. Adımı işaretlemek, ödün vermek, nedensellik iddiasını
 *  ölçülü tutmak, karşı görüşü DÜRÜSTÇE kurmak, itirazı önceden karşılamak.
 *  Ünite baskı altında savunmayla kapanıyor.
 *
 *  Ünite 6 anlatı zanaatı: tek gramer dersi devrik açılış (`little did they know`),
 *  gerisi tempo, ayıklama ve başkasının sözünü canlı aktarma. Aynı hikâye iki kez
 *  anlatılıyor — bu ünitenin sınavı o.
 *
 *  Ünite 7 kesinlik: karıştırılan kelime çiftleri, onay ölçeği, iddiaya ne kadar
 *  mesafe koyacağın, eğilim ifade etme, ve doğru kelimeyi ARARKEN konuşmayı
 *  sürdürebilmek. Son ders aynı içeriği üç register'da veriyor.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3.
 *
 *  PARTİ 1 İNCELEMESİNDEN: öğretim örnekleri TAM CÜMLE olur; örnek cevap kendi
 *  kriterini karşılar; "üç ifadeye cevap ver" diyen görev o ifadeleri VERİR;
 *  iddialar kanıtlanabilir olur (etki iddiası değil, kullanım iddiası).
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const C1_U5_7: Authored[] = [
  // --- Ünite 5 · Building an Argument ----------------------------------------
  {
    id: "c1-given-that-it-follows",
    topic: "signalling the steps of an argument",
    objectives: [
      "Mark the premise and the conclusion of a step.",
      "Make the logical move visible to the listener.",
    ],
    goal: "Take a listener through your reasoning one step at a time.",
    target: "signalling logical steps",
    correction: "Model the step marker and let the learner move to the next step.",
    summary: "You learned to mark each step of an argument so the reasoning can be followed.",
    minutes: 8,
    points: [
      {
        form: "given that",
        claims: [
          "'Given that' introduces a premise the speaker treats as established, or assumes for the argument.",
          "It does not prove the premise; it sets it aside so the reasoning can proceed.",
        ],
        ex: ["Given that the deadline is fixed, we must cut scope.", "Given that nobody objected, we proceeded."],
      },
      {
        form: "it follows that",
        claims: [
          "'It follows that' marks the conclusion as forced by the premise.",
          "If the listener can accept the premise but reject the conclusion, the phrase is too strong.",
        ],
        ex: ["It follows that we need a second option.", "It follows that the original plan will not work."],
      },
      {
        form: "which means that",
        claims: [
          "'Which means that' draws a consequence without claiming logical necessity.",
          "It is the softer of the two and fits most everyday reasoning.",
        ],
        ex: ["The budget is frozen, which means that hiring stops.", "She has resigned, which means that we are short-staffed."],
      },
    ],
    ex: [
      fill("___ that the deadline is fixed, we must cut scope. (give)", ["Given"]),
      mcq("Which phrase claims the conclusion is forced?", [
        "It follows that we need a second option.",
        "Which means that we need a second option.",
        "So we probably need a second option.",
      ], 0),
      say("the budget / be frozen / which mean that / hiring / stop", ["The budget is frozen, which means that hiring stops."]),
    ],
    open: {
      q: "Take a decision you disagree with and show, step by step, where the reasoning goes wrong.",
      must: ["given that", "it follows that", "which means that"],
      criteria: "The answer marks each premise and conclusion so the reasoning can be checked.",
      example: "Given that demand falls, they say it follows that we cut staff, which means that hiring stops. But it may recover.",
    },
    success: "The learner marks premises and conclusions so the steps can be followed.",
    quiz: [
      qmcq("Which phrase marks a premise?", ["Given that", "It follows that", "Which means that"], 0),
      qfill("It ___ that the original plan will not work. (follow)", ["follows"]),
      qmcq("When is 'it follows that' too strong?", [
        "when the premise can be accepted but the conclusion rejected",
        "when the sentence is long",
        "when there are two premises",
      ], 0),
    ],
    scenes: [
      sc("Rasheed", "a friend who disagrees with your conclusion", "to see where the reasoning goes",
        "A friend accepts your facts but not your conclusion.",
        "Show the steps between them.",
        "I agree with all of that, but not with where you end up. Show me the steps?", "engaged"),
      sc("Halima", "a colleague reviewing a proposal", "to check the reasoning behind a proposal",
        "A proposal's reasoning must be made explicit.",
        "Mark each step.",
        "The conclusion may be right, but I cannot see how you got there. Walk me through?", "rigorous"),
      sc("Anders", "an official assessing a case", "to follow a case that must be justified",
        "A case must be justified step by step to an official.",
        "Make each step visible.",
        "I need to see the reasoning, not just the request. Take me through it?", "procedural"),
      sc("Professor Osei", "your tutor", "to practise explicit reasoning",
        "The seminar is examining argument structure.",
        "Signal each logical step.",
        "How do you show a listener exactly where your reasoning turns?", "probing"),
      sc("Ms. Reyes", "the examiner", "to check argument structure",
        "The examiner asks for a reasoned position.",
        "Mark each step clearly.",
        "Could you argue a position and show me each step of the reasoning?", "neutral"),
    ],
  },

  {
    id: "c1-granted-however",
    topic: "conceding in order to strengthen",
    objectives: [
      "Concede a point genuinely before answering it.",
      "Return to your own case without dismissing theirs.",
    ],
    goal: "Give ground on one point to hold ground on the main one.",
    target: "concession as an argumentative move",
    correction: "Model the concession and let the learner return to their own case.",
    summary: "You learned to concede a point genuinely in order to strengthen your own.",
    minutes: 8,
    points: [
      {
        form: "granted that",
        claims: [
          "'Granted that' accepts a point without accepting the conclusion drawn from it.",
          "A concession that costs you nothing is usually spotted as a tactic.",
        ],
        ex: ["Granted that the cost is high, the alternative is higher.", "Granted that it is unusual, it is not unprecedented."],
      },
      {
        form: "I'll admit that",
        claims: [
          "'I'll admit that' concedes a point openly; whether it truly weakens your case depends on what you concede.",
          "Conceding a real weakness makes the rest of the case more credible.",
        ],
        ex: ["I'll admit that the evidence is thin.", "I'll admit that we underestimated the timeline."],
      },
      {
        form: "that notwithstanding",
        claims: [
          "'That notwithstanding' returns to your case after the concession.",
          "It is formal; 'even so' does the same work in ordinary speech.",
        ],
        ex: ["That notwithstanding, the case still holds.", "That notwithstanding, I would proceed."],
      },
    ],
    ex: [
      fill("___ that the cost is high, the alternative is higher. (grant)", ["Granted"]),
      mcq("Which concession genuinely weakens the speaker's case?", [
        "I'll admit that the evidence is thin.",
        "I'll admit that some people disagree.",
        "I'll admit that nothing is ever certain.",
      ], 0),
      say("that notwithstanding / the case / still hold", ["That notwithstanding, the case still holds."]),
    ],
    open: {
      q: "Argue a position, conceding one point that genuinely weakens it before returning to your case.",
      must: ["granted that", "I'll admit that", "that notwithstanding"],
      criteria: "The answer concedes a real weakness and then returns to the main case.",
      example: "Granted that it is expensive, and I'll admit that the evidence is limited, that notwithstanding a pilot is justified.",
    },
    success: "The learner concedes a real point and returns to the main case.",
    quiz: [
      qmcq("Which phrase returns to your case?", [
        "That notwithstanding,",
        "Granted that,",
        "I'll admit that,",
      ], 0),
      qfill("___ that it is unusual, it is not unprecedented. (grant)", ["Granted"]),
      qmcq("Why concede a real weakness?", [
        "It makes the rest of the case more credible.",
        "It shortens the argument.",
        "It is required in formal English.",
      ], 0),
    ],
    scenes: [
      sc("Ottoline", "a friend who has spotted a flaw", "to see whether you will admit the flaw",
        "A friend has found a genuine weakness in your position.",
        "Concede it and return to your case.",
        "You know that objection is fair, don't you? What do you say to it?", "direct"),
      sc("Viktor", "a sceptical board member", "to hear an honest case",
        "A board member is testing whether you will oversell.",
        "Concede the real weakness.",
        "Every proposal has a weak point. What is yours?", "testing"),
      sc("Selin", "an academic reviewer", "to assess intellectual honesty",
        "A reviewer is testing the honesty of an argument.",
        "Concede and return.",
        "What is the strongest objection to your own position?", "rigorous"),
      sc("Mr. Achebe", "your tutor", "to practise concession",
        "The seminar is examining concessive argument.",
        "Concede genuinely and return.",
        "What does a concession cost you, and what does it buy?", "probing"),
      sc("Ms. Berger", "the examiner", "to check concessive argument",
        "The examiner challenges a position.",
        "Concede fairly and return to the case.",
        "Your position has an obvious weakness. Will you acknowledge it?", "neutral"),
    ],
  },

  {
    id: "c1-correlation-and-cause",
    topic: "being careful about causal claims",
    objectives: [
      "Reject a causal claim without rejecting the evidence.",
      "Offer an alternative explanation for the same pattern.",
    ],
    goal: "Challenge a causal claim without dismissing the data.",
    target: "distinguishing correlation from cause",
    correction: "Model the careful rejection and let the learner challenge the claim again.",
    summary: "You learned to challenge a causal claim while accepting the evidence behind it.",
    minutes: 8,
    points: [
      {
        form: "that doesn't prove",
        claims: [
          "'That doesn't prove' rejects the inference, not the observation.",
          "Separating the two keeps the disagreement narrow and answerable.",
        ],
        ex: ["That doesn't prove the policy caused it.", "That doesn't prove one led to the other."],
      },
      {
        form: "it may simply reflect",
        claims: [
          "'It may simply reflect' offers a rival explanation for the same pattern.",
          "An alternative explanation shows the pattern is compatible with more than one cause.",
        ],
        ex: ["It may simply reflect who was asked.", "It may simply reflect the time of year."],
      },
      {
        form: "correlation isn't causation",
        claims: [
          "'Correlation isn't causation' names the error but does not explain why it applies here.",
          "A plausible alternative shows why the pattern alone does not establish causation.",
        ],
        ex: ["Correlation isn't causation, after all.", "Correlation isn't causation, as we both know."],
      },
    ],
    ex: [
      fill("That ___ prove the policy caused it. (do not)", ["doesn't", "does not"]),
      mcq("Which sentence offers a rival explanation?", [
        "It may simply reflect who was asked.",
        "That is obviously wrong.",
        "I do not believe the figures.",
      ], 0),
      say("correlation / not be / causation / after all", ["Correlation isn't causation, after all.", "Correlation is not causation, after all."]),
    ],
    open: {
      q: "Someone claims that a new policy caused a rise in numbers. Challenge the causal claim without rejecting the data.",
      must: ["that doesn't prove", "it may simply reflect", "correlation isn't causation"],
      criteria: "The answer rejects the inference while accepting the observation and offers an alternative.",
      example: "The numbers are real, but that doesn't prove the policy did it. It may simply reflect the season; correlation isn't causation.",
    },
    success: "The learner rejects a causal inference while accepting the evidence.",
    quiz: [
      qmcq("Which sentence rejects the inference, not the data?", [
        "That doesn't prove one led to the other.",
        "Those figures are simply wrong.",
        "Nobody should trust that survey.",
      ], 0),
      qfill("It may simply ___ the time of year. (reflect)", ["reflect"]),
      qmcq("Why offer an alternative explanation?", [
        "It shows the pattern alone does not establish causation.",
        "It is required by formal argument.",
        "It makes the objection shorter.",
      ], 0),
    ],
    scenes: [
      sc("Bruna", "a friend convinced by a headline", "to reconsider a causal claim",
        "A friend has accepted a causal claim from a headline.",
        "Challenge the inference, not the data.",
        "The numbers went up right after the policy. That proves it, surely?", "confident"),
      sc("Owen", "a colleague presenting results", "to test the causal claim in a report",
        "A report claims a cause from a correlation.",
        "Challenge it carefully.",
        "The correlation is strong. Are you doubting the data?", "defensive"),
      sc("Priya", "a researcher discussing findings", "to examine a causal claim rigorously",
        "Findings are being discussed among researchers.",
        "Separate correlation from cause.",
        "The association is clear. How far would you push it?", "rigorous"),
      sc("Professor Anand", "your tutor", "to practise causal reasoning",
        "The seminar is examining inference from data.",
        "Reject the inference carefully.",
        "How do you doubt a conclusion without doubting the evidence?", "probing"),
      sc("Mr. Larsen", "the examiner", "to check careful reasoning",
        "The examiner asserts a causal link.",
        "Challenge it without rejecting the data.",
        "Reading more clearly makes people more successful. Do you agree?", "neutral"),
    ],
  },

  {
    id: "c1-the-counterargument",
    topic: "stating the opposing view fairly",
    objectives: [
      "State an opposing view in its strongest form.",
      "Answer it after stating it, not before.",
    ],
    goal: "Present the case against your position honestly.",
    target: "constructing a fair counterargument",
    correction: "Model the fair statement of the opposing view and let the learner answer it.",
    summary: "You learned to state the opposing view fairly before answering it.",
    minutes: 8,
    points: [
      {
        form: "one might argue",
        claims: [
          "'One might argue' introduces the opposing case in neutral language.",
          "Stating it weakly is easy to spot and damages your credibility.",
        ],
        ex: ["One might argue that the cost outweighs the benefit.", "One might argue the opposite entirely."],
      },
      {
        form: "critics would say",
        claims: [
          "'Critics would say' attributes the objection to a general opposing group.",
          "To avoid a straw man, the objection must still be one critics actually make.",
        ],
        ex: ["Critics would say this rewards failure.", "Critics would say we have tried this before."],
      },
      {
        form: "against that",
        claims: [
          "'Against that' marks the point where you begin your answer.",
          "Answering before the objection is fully stated looks evasive.",
        ],
        ex: ["Against that, the evidence points the other way.", "Against that, the cost of inaction is higher."],
      },
    ],
    ex: [
      fill("One might ___ that the cost outweighs the benefit. (argue)", ["argue"]),
      mcq("Which sentence states an objection fairly?", [
        "Critics would say this rewards failure.",
        "Some people just dislike any change.",
        "Nobody sensible disagrees with this.",
      ], 0),
      say("against that / the evidence / point / the other way", ["Against that, the evidence points the other way."]),
    ],
    open: {
      q: "State the strongest case against a position you hold, then answer it.",
      must: ["one might argue", "critics would say", "against that"],
      criteria: "The answer states the opposing view in its strongest form before answering it.",
      example: "One might argue the cost is too high. Critics would say earlier trials failed. Against that, this one is cheaper and evaluated.",
    },
    success: "The learner states the opposing case fairly and then answers it.",
    quiz: [
      qmcq("Which phrase marks the start of your answer?", ["Against that,", "One might argue", "Critics would say"], 0),
      qfill("One might ___ the opposite entirely. (argue)", ["argue"]),
      qmcq("Why state the objection at its strongest?", [
        "A weak version damages your credibility.",
        "It makes the argument longer.",
        "It is grammatically required.",
      ], 0),
    ],
    scenes: [
      sc("Kwabena", "a friend testing your fairness", "to see whether you can state the other side",
        "A friend suspects you are caricaturing the opposition.",
        "State the opposing case fairly.",
        "Can you actually state the other side without mocking it?", "challenging"),
      sc("Simone", "a colleague preparing for a hard meeting", "to prepare for objections",
        "A meeting will contain strong opposition.",
        "Rehearse the opposing case.",
        "They will come at us hard. What will they actually say?", "strategic"),
      sc("Emil", "an academic examiner", "to assess intellectual fairness",
        "An academic setting rewards fair representation.",
        "State and answer the counterargument.",
        "What is the best argument against your own thesis?", "rigorous"),
      sc("Mrs. Aguilar", "your tutor", "to practise counterargument",
        "The seminar is examining fair representation.",
        "State the opposing case at its strongest.",
        "Why is a weak version of your opponent dangerous to you?", "probing"),
      sc("Mr. Nakamura", "the examiner", "to check fair argument",
        "The examiner asks you to argue against yourself.",
        "State the counterargument fairly.",
        "Could you make the strongest case against your own view?", "neutral"),
    ],
  },

  {
    id: "c1-anticipating-objections",
    topic: "pre-empting the reply you expect",
    objectives: [
      "Raise an objection before the other person does.",
      "Answer it without sounding defensive.",
    ],
    goal: "Disarm an objection by raising it yourself.",
    target: "pre-empting objections",
    correction: "Model the pre-emptive move and let the learner raise their own objection.",
    summary: "You practised raising an objection yourself before the other person could.",
    minutes: 8,
    points: [
      {
        form: "you might object that",
        claims: [
          "'You might object that' raises the objection in the other person's voice.",
          "Raising it first shows you have considered it rather than missed it.",
        ],
        ex: ["You might object that this has been tried.", "You might object that the sample is small."],
      },
      {
        form: "some will say",
        claims: [
          "'Some will say' raises a common objection without attributing it to the listener.",
          "This avoids putting words in the other person's mouth.",
        ],
        ex: ["Some will say it is too early.", "Some will say the risk is unacceptable."],
      },
      {
        form: "I'd answer that by",
        claims: [
          "'I'd answer that by pointing to...' gives the answer a shape before the content.",
          "Announcing the shape of the answer stops it sounding improvised.",
        ],
        ex: ["I'd answer that by pointing to the pilot.", "I'd answer that by separating the two cases."],
      },
    ],
    ex: [
      fill("You might ___ that this has been tried before. (object)", ["object"]),
      mcq("Which phrase avoids putting words in the listener's mouth?", [
        "Some will say it is too early.",
        "You clearly think it is too early.",
        "You are going to say it is too early.",
      ], 0),
      say("I / would answer / that / by pointing / to the pilot", ["I'd answer that by pointing to the pilot.", "I would answer that by pointing to the pilot."]),
    ],
    open: {
      q: "Make a proposal and raise the two objections you most expect, answering each.",
      must: ["you might object that", "some will say", "I'd answer that by"],
      criteria: "The answer raises expected objections first and answers them without defensiveness.",
      example: "You might object that the sample is small; I'd answer that by pointing to three sites. Some will say it costs too much.",
    },
    success: "The learner raises and answers at least two expected objections.",
    quiz: [
      qmcq("Why raise an objection yourself?", [
        "It shows you have considered it rather than missed it.",
        "It makes the proposal shorter.",
        "It prevents the other person from speaking.",
      ], 0),
      qfill("Some ___ say the risk is unacceptable. (will)", ["will"]),
      qmcq("What does announcing the shape of an answer do?", [
        "It stops the answer sounding improvised.",
        "It shortens the answer.",
        "It makes the objection disappear.",
      ], 0),
    ],
    scenes: [
      sc("Ingeborg", "a friend who always finds the flaw", "to have her objections answered first",
        "A friend reliably spots the weakness in any plan.",
        "Raise the objections before she does.",
        "Go on then. I am sure you have thought of everything?", "wry"),
      sc("Rashid", "a decision-maker with limited time", "to hear a proposal with its risks",
        "A proposal must survive scrutiny in one hearing.",
        "Pre-empt the objections.",
        "I have ten minutes and a long list of doubts. Where do you want to start?", "brisk"),
      sc("Cecilia", "a panel member at a funding hearing", "to test a proposal",
        "A funding panel will probe hard.",
        "Raise and answer the likely objections.",
        "We will ask difficult questions. Would you like to go first?", "impartial"),
      sc("Mr. Steiner", "your tutor", "to practise pre-emption",
        "The seminar is examining anticipatory argument.",
        "Raise and answer objections.",
        "What do you gain by making your opponent's case for them?", "probing"),
      sc("Ms. Coelho", "the examiner", "to check anticipatory argument",
        "The examiner will object to whatever you propose.",
        "Pre-empt the objections.",
        "Propose something. What am I about to object to?", "neutral"),
    ],
  },

  {
    id: "c1-a-structured-case",
    topic: "arguing from opening to conclusion",
    objectives: [
      "Number the parts of an argument out loud.",
      "Close by tying the parts together.",
    ],
    goal: "Argue a position from a clear opening to a clear conclusion.",
    target: "structuring an extended argument",
    correction: "Model the structural marker and let the learner move to the next part.",
    summary: "You practised structuring an extended argument from opening to conclusion.",
    minutes: 8,
    points: [
      {
        form: "my first point",
        claims: [
          "Numbering the parts tells the listener how much is still to come.",
          "It also makes it obvious if you never reach the second point.",
        ],
        ex: ["My first point is about cost.", "My first point concerns timing."],
      },
      {
        form: "which brings me to",
        claims: [
          "'Which brings me to' links one part to the next rather than just stopping.",
          "The link shows how the parts connect; the content still has to do the arguing.",
        ],
        ex: ["Which brings me to the second issue.", "Which brings me to my main concern."],
      },
      {
        form: "for these reasons",
        claims: [
          "'For these reasons' ties the parts to the conclusion.",
          "A conclusion that does not refer back to the parts leaves them unused.",
        ],
        ex: ["For these reasons, I would delay.", "For these reasons, the proposal should be rejected."],
      },
    ],
    ex: [
      fill("My ___ point is about cost. (one)", ["first"]),
      mcq("Which phrase links one part to the next?", [
        "Which brings me to the second issue.",
        "Also, there is a second issue.",
        "There is another issue too.",
      ], 0),
      say("for these reasons / I / would delay", ["For these reasons, I would delay."]),
    ],
    open: {
      q: "Argue a position in three parts, linking each to the next and tying them together at the end.",
      must: ["my first point", "which brings me to", "for these reasons"],
      criteria: "The answer numbers its parts, links them and ties them to the conclusion.",
      example: "My first point is that delays have doubled, which brings me to cost: they now exceed replacement. For these reasons, replace it.",
    },
    success: "The learner structures an argument and ties the parts to the conclusion.",
    quiz: [
      qmcq("Why number the parts?", [
        "It tells the listener how much is still to come.",
        "It makes the argument shorter.",
        "It is required in formal English.",
      ], 0),
      qfill("Which ___ me to my main concern. (bring)", ["brings"]),
      qmcq("What happens if the conclusion ignores the parts?", [
        "The parts are left unused.",
        "The grammar becomes incorrect.",
        "The argument becomes shorter.",
      ], 0),
    ],
    scenes: [
      sc("Marisol", "a friend who loses the thread", "to follow a long argument",
        "A friend has trouble following long arguments.",
        "Structure it so the parts are obvious.",
        "You lost me halfway through last time. Try again, slowly?", "patient"),
      sc("Hendrik", "a manager hearing a case", "to be persuaded by a structured case",
        "A manager wants a case, not a ramble.",
        "Structure the argument.",
        "Give me the case in parts, not as a story. What is your first point?", "exacting"),
      sc("Nala", "a panel chair", "to hear a structured submission",
        "A formal submission must be structured.",
        "Argue from opening to conclusion.",
        "You have the floor. How is your case organised?", "formal"),
      sc("Professor Villanueva", "your tutor", "to practise extended argument",
        "The seminar is examining argument architecture.",
        "Structure and conclude.",
        "What separates a structured case from a list of complaints?", "probing"),
      sc("Ms. Sorensen", "the examiner", "to check extended argument",
        "The examiner asks for a structured case.",
        "Structure it and tie it together.",
        "Could you argue a position in three connected parts?", "neutral"),
    ],
  },

  {
    id: "c1-defending-under-pressure",
    topic: "holding up when challenged hard",
    objectives: [
      "Distinguish a real objection from a misreading.",
      "Restate a position without repeating it word for word.",
    ],
    goal: "Hold your position when it is attacked directly.",
    target: "defending an argument under pressure",
    correction: "Model the separation of misreading from objection and let the learner defend again.",
    summary: "You practised holding a position under direct challenge.",
    minutes: 8,
    points: [
      {
        form: "I stand by that",
        claims: [
          "'I stand by that' refuses to retreat without escalating the exchange.",
          "It works only if you then give a reason; alone it sounds stubborn.",
        ],
        ex: ["I stand by that, and here is why.", "I stand by the figure I gave."],
      },
      {
        form: "that misses my point",
        claims: [
          "'That misses my point' names a misreading rather than a disagreement.",
          "Answering a misreading as though it were an objection concedes ground you never lost.",
        ],
        ex: ["That misses my point, which was about timing.", "That misses what I actually claimed."],
      },
      {
        form: "let me clarify",
        claims: [
          "'Let me clarify' restates the position in different words.",
          "Repeating the same words rarely resolves a misunderstanding.",
        ],
        ex: ["Let me clarify what I mean by that.", "Let me clarify the distinction."],
      },
    ],
    ex: [
      fill("I ___ by that, and here is why. (stand)", ["stand"]),
      mcq("Which sentence names a misreading rather than a disagreement?", [
        "That misses my point, which was about timing.",
        "That is simply not true at all.",
        "You are wrong about the timing.",
      ], 0),
      say("let me / clarify / the distinction", ["Let me clarify the distinction."]),
    ],
    open: {
      q: "Answer these two: the misreading 'you say it can never work', and the objection 'the alternative costs too much'.",
      must: ["I stand by that", "that misses my point", "let me clarify"],
      criteria: "The answer separates a misreading from a real objection and answers each appropriately.",
      example: "That misses my point: I said not within this deadline. Let me clarify. On cost, I stand by that — delay costs more.",
    },
    success: "The learner separates a misreading from an objection and holds the position.",
    quiz: [
      qmcq("Why is 'I stand by that' weak on its own?", [
        "Without a reason it sounds stubborn.",
        "It is grammatically incomplete.",
        "It concedes the argument.",
      ], 0),
      qfill("Let me ___ what I mean by that. (clarify)", ["clarify"]),
      qmcq("What goes wrong if you answer a misreading as an objection?", [
        "You concede ground you never lost.",
        "You run out of time.",
        "You repeat yourself.",
      ], 0),
    ],
    scenes: [
      sc("Gustavo", "a friend attacking your view head on", "to break your position",
        "A friend is pressing hard and partly misreading you.",
        "Separate the misreading from the objection.",
        "You are basically saying nobody should ever try. Aren't you?", "forceful"),
      sc("Priyanka", "a hostile questioner at work", "to expose a weakness",
        "A questioner is looking for a weakness rather than an answer.",
        "Hold the position and clarify.",
        "This has failed everywhere it has been tried. Why would we?", "aggressive"),
      sc("Bram", "a journalist pressing a point", "to get a quotable retraction",
        "A journalist is pressing for a retraction.",
        "Hold the position without escalating.",
        "So you accept the whole thing was a mistake?", "persistent"),
      sc("Mrs. Farrow", "your tutor", "to practise defence under pressure",
        "The seminar is examining argument under challenge.",
        "Defend without escalating.",
        "How do you tell a misreading from a real objection in the moment?", "probing"),
      sc("Mr. Ibrahim", "the examiner", "to check composure under challenge",
        "The examiner attacks your position directly.",
        "Defend it calmly.",
        "I think your entire position collapses under scrutiny. Well?", "neutral"),
    ],
  },

  // --- Ünite 6 · Narrative Craft ---------------------------------------------
  {
    id: "c1-little-did-they-know",
    topic: "inverted openers that hint at what is coming",
    objectives: [
      "Open with an inversion that signals dramatic irony.",
      "Position the reader ahead of the characters.",
    ],
    goal: "Signal to your listener that something is about to go wrong.",
    target: "narrative inversion",
    correction: "Rebuild the inverted opener and let the learner set up their own story.",
    summary: "You learned to open a story with an inversion that hints at what is coming.",
    minutes: 9,
    points: [
      {
        form: "little did they know",
        claims: [
          "'Little did they know' tells the listener something the characters do not know.",
          "It creates dramatic irony: the listener is now ahead of the story.",
        ],
        ex: ["Little did they know it was the last time.", "Little did we know what was coming."],
      },
      {
        form: "unbeknown to them",
        claims: [
          "'Unbeknown to them' does the same job in a more literary register.",
          "'Unbeknownst' is an accepted variant of the same word.",
        ],
        ex: ["Unbeknown to them, the road was closed.", "Unbeknown to us, the meeting had moved."],
      },
      {
        form: "what nobody realised",
        claims: [
          "'What nobody realised was...' delays the revelation to the end of the sentence.",
          "Because it is a what-clause, it does not need inversion.",
        ],
        ex: ["What nobody realised was how late it was.", "What nobody realised was that he had already left."],
      },
    ],
    ex: [
      fill("___ did they know it was the last time. (little)", ["Little"]),
      mcq("Which sentence is correct?", [
        "Little did we know what was coming.",
        "Little we did know what was coming.",
        "Little knew we what was coming.",
      ], 0),
      fill("___ to them, the road was closed. (unbeknown)", ["Unbeknown", "Unbeknownst"]),
      say("what nobody / realise / be / how late it be", ["What nobody realised was how late it was."]),
    ],
    open: {
      q: "Open a story with a line that tells the listener something the people in it do not know.",
      must: ["little did they know", "unbeknown to them", "what nobody realised"],
      criteria: "The answer creates dramatic irony by putting the listener ahead of the characters.",
      example: "Little did they know the road was shut. Unbeknown to them, so was the bridge — what nobody realised was why.",
    },
    success: "The learner opens a narrative with dramatic irony.",
    quiz: [
      qmcq("What does 'little did they know' create?", [
        "dramatic irony",
        "a change of tense",
        "a formal register",
      ], 0),
      qfill("___ to us, the meeting had moved. (unbeknown)", ["Unbeknown"]),
      qmcq("Which sentence needs no inversion?", [
        "What nobody realised was how late it was.",
        "Little did anyone realise how late it was.",
        "Never had anyone realised how late it was.",
      ], 0),
    ],
    scenes: [
      sc("Zofia", "a friend who loves a good build-up", "to be kept in suspense",
        "A friend enjoys a story that builds.",
        "Open with dramatic irony.",
        "Set it up properly this time. How does it start?", "expectant"),
      sc("Ravi", "a colleague at a retrospective", "to understand what nobody saw coming",
        "A retrospective is describing what nobody knew at the time.",
        "Signal what was hidden.",
        "Nobody saw it coming. Take us back to the morning of it?", "reflective"),
      sc("Elif", "a fellow traveller telling stories", "to hear a story told well",
        "Travellers are telling stories over a long evening.",
        "Open with dramatic irony.",
        "You said this one is worth hearing. How does it begin?", "settled"),
      sc("Professor Kimura", "your tutor", "to practise narrative openings",
        "The seminar is examining narrative technique.",
        "Open with dramatic irony.",
        "How do you put the listener ahead of your characters?", "probing"),
      sc("Ms. Bianchi", "the examiner", "to check narrative technique",
        "The examiner asks for a story opening.",
        "Create dramatic irony.",
        "Could you begin a story so I know something the characters do not?", "neutral"),
    ],
  },

  {
    id: "c1-pacing-a-story",
    topic: "speeding up and slowing down",
    objectives: [
      "Compress a long dull stretch into one clause.",
      "Slow down at the moment that matters.",
    ],
    goal: "Control the speed of a story so the important part lands.",
    target: "narrative pacing",
    correction: "Model the pacing shift and let the learner speed up or slow down their own story.",
    summary: "You learned to compress the dull parts and slow down at the moment that matters.",
    minutes: 8,
    points: [
      {
        form: "for weeks nothing",
        claims: [
          "'For weeks nothing happened' compresses a long stretch into one clause.",
          "Time spent on a dull stretch is time taken from the important part.",
        ],
        ex: ["For weeks nothing happened at all.", "For months nothing changed."],
      },
      {
        form: "and then out of nowhere",
        claims: [
          "'And then, out of nowhere' marks a sudden turn; slowing down comes from the detail you add after it.",
          "Expand the moment with immediate actions or sensory detail to make it feel slow.",
        ],
        ex: ["And then, out of nowhere, the phone rang.", "And then out of nowhere it stopped."],
      },
      {
        form: "then everything shifted",
        claims: [
          "'Then everything shifted' names the turning point without detailing it yet.",
          "Naming the turn before describing it buys the listener's attention.",
        ],
        ex: ["Then everything shifted at once.", "Then everything shifted, and quickly."],
      },
    ],
    ex: [
      fill("For weeks ___ happened at all. (nothing)", ["nothing"]),
      mcq("Which sentence marks a change of pace?", [
        "And then, out of nowhere, the phone rang.",
        "The phone rang at some point.",
        "There was a phone call that day.",
      ], 0),
      say("then everything / shift / at once", ["Then everything shifted at once."]),
    ],
    open: {
      q: "Tell a short story with a long dull stretch and one sudden turn. Compress the first, slow down at the second.",
      must: ["for weeks nothing", "and then out of nowhere", "then everything shifted"],
      criteria: "The answer compresses the dull stretch and slows the pace at the turn.",
      example: "For weeks nothing happened. And then, out of nowhere, the phone rang. I let it ring twice. Then everything shifted.",
    },
    success: "The learner compresses one stretch and slows down at the turn.",
    quiz: [
      qmcq("Why compress a dull stretch?", [
        "Time on it is taken from the important part.",
        "It is grammatically simpler.",
        "It avoids the past tense.",
      ], 0),
      qfill("For months ___ changed at all. (nothing)", ["nothing"]),
      qmcq("What does naming the turn before describing it do?", [
        "It buys the listener's attention.",
        "It shortens the story.",
        "It removes the need for detail.",
      ], 0),
    ],
    scenes: [
      sc("Njeri", "a friend hearing a long story", "to stay engaged through a long story",
        "A story has a long slow middle and a sharp turn.",
        "Pace it so the turn lands.",
        "How long does this story take? Can we get to the good bit?", "impatient"),
      sc("Konstantin", "a colleague at a leaving speech", "to hear an anecdote that lands",
        "An anecdote must land in a short speech.",
        "Pace it for effect.",
        "You have two minutes and one story. Which one?", "amused"),
      sc("Sanne", "a fellow traveller round a fire", "to be told a story well",
        "A long evening and a good story.",
        "Pace it deliberately.",
        "We have all night. How does yours start?", "relaxed"),
      sc("Mr. Delacroix", "your tutor", "to practise pacing",
        "The seminar is examining narrative rhythm.",
        "Control the pace deliberately.",
        "How do you make a listener feel a long wait in one sentence?", "probing"),
      sc("Ms. Grimaldi", "the examiner", "to check narrative control",
        "The examiner asks for a paced story.",
        "Compress and slow down deliberately.",
        "Could you tell me a story where nothing happens, then everything does?", "neutral"),
    ],
  },

  {
    id: "c1-the-detail-that-matters",
    topic: "choosing what to include",
    objectives: [
      "Signal which detail the listener needs.",
      "Cut what does not serve the point.",
    ],
    goal: "Tell a story without burying the point in detail.",
    target: "selecting narrative detail",
    correction: "Model the selecting phrase and let the learner cut their own story down.",
    summary: "You learned to select the detail that matters and cut the rest.",
    minutes: 8,
    points: [
      {
        form: "what you need to know",
        claims: [
          "'What you need to know is...' tells the listener which detail carries the story.",
          "It gives permission to forget everything else.",
        ],
        ex: ["What you need to know is that he had the only key.", "What you need to know is the timing."],
      },
      {
        form: "I'll spare you",
        claims: [
          "'I'll spare you the details' cuts a stretch while acknowledging it existed.",
          "Cutting openly is better than trailing off mid-story.",
        ],
        ex: ["I'll spare you the paperwork.", "I'll spare you the three hours in between."],
      },
      {
        form: "here's the part",
        claims: [
          "'Here's the part that matters' focuses attention just before the payoff.",
          "It works best used once; twice, the listener stops believing the first.",
        ],
        ex: ["Here's the part that matters.", "Here's the part I still think about."],
      },
    ],
    ex: [
      fill("___ you need to know is that he had the only key. (what)", ["What"]),
      mcq("Which sentence cuts a stretch openly?", [
        "I'll spare you the paperwork.",
        "Anyway, where was I?",
        "It went on for ages, honestly.",
      ], 0),
      say("here be / the part / that matter", ["Here's the part that matters.", "Here is the part that matters."]),
    ],
    open: {
      q: "Tell a story with a lot of irrelevant detail, cutting it openly and marking the part that matters.",
      must: ["what you need to know", "I'll spare you", "here's the part"],
      criteria: "The answer cuts irrelevant material openly and marks the detail that carries the story.",
      example: "I'll spare you the first hour. What you need to know is he had the only key. Here's the part: he had vanished.",
    },
    success: "The learner cuts openly and marks the significant detail.",
    quiz: [
      qmcq("Why cut openly rather than trail off?", [
        "Trailing off leaves the listener unsure what was skipped.",
        "It is grammatically required.",
        "It makes the story longer.",
      ], 0),
      qfill("I'll ___ you the three hours in between. (spare)", ["spare"]),
      qmcq("Why use 'here's the part that matters' only once?", [
        "A second use makes the listener doubt the first.",
        "It is only correct once per story.",
        "It cannot open a sentence twice.",
      ], 0),
    ],
    scenes: [
      sc("Camille", "a friend short of time", "to get the story in two minutes",
        "A friend has two minutes and you have a long story.",
        "Cut it down and mark the key detail.",
        "I have to leave in two minutes. Can you do the short version?", "rushed"),
      sc("Stefan", "a colleague needing the essentials", "to get only what is relevant",
        "A colleague needs the relevant facts, not the narrative.",
        "Select the detail that matters.",
        "What do I actually need to know here?", "practical"),
      sc("Rosa", "a fellow guest at a dinner", "to enjoy a well-told anecdote",
        "A dinner anecdote must not outstay its welcome.",
        "Cut and mark the payoff.",
        "You promised us a story earlier. Shall we hear it?", "expectant"),
      sc("Mrs. Chen", "your tutor", "to practise selection",
        "The seminar is examining narrative economy.",
        "Select and cut deliberately.",
        "How do you decide which detail earns its place?", "probing"),
      sc("Mr. Ferreira", "the examiner", "to check narrative economy",
        "The examiner asks for a compact story.",
        "Cut openly and mark the key detail.",
        "Could you tell me a story in under a minute?", "neutral"),
    ],
  },

  {
    id: "c1-bringing-people-to-life",
    topic: "reporting speech vividly",
    objectives: [
      "Report speech in the present for immediacy.",
      "Convey reaction without quoting words.",
    ],
    goal: "Make the people in your story sound like people.",
    target: "vivid reported speech",
    correction: "Model the vivid report and let the learner bring their own character to life.",
    summary: "You learned to report speech and reaction vividly inside a story.",
    minutes: 8,
    points: [
      {
        form: "and he goes",
        claims: [
          "'And he goes' is informal spoken narrative for 'and he said'.",
          "The present tense inside a past story creates immediacy; it is not an error.",
        ],
        ex: ["And he goes, completely straight-faced, \"No.\"", "And she goes, \"Well, that is that.\""],
      },
      {
        form: "she just looked",
        claims: [
          "'She just looked at me' reports a reaction without any words at all.",
          "Silence often carries more than reported speech does.",
        ],
        ex: ["She just looked at me.", "He just looked at the floor."],
      },
      {
        form: "you could see it",
        claims: [
          "'You could see it on her face' reports what was visible rather than said.",
          "It invites the listener to picture the moment instead of being told about it.",
        ],
        ex: ["You could see it on her face.", "You could see it coming."],
      },
    ],
    ex: [
      fill("And he ___, completely straight-faced, \"No.\" (go)", ["goes"]),
      mcq("Which sentence reports a reaction without words?", [
        "She just looked at me.",
        "She said she disagreed.",
        "She told me it was wrong.",
      ], 0),
      say("you / could see / it / on her face", ["You could see it on her face."]),
    ],
    open: {
      q: "Retell a short exchange, reporting one line of speech vividly and one reaction without words.",
      must: ["and he goes", "she just looked", "you could see it"],
      criteria: "The answer reports speech vividly and conveys a reaction without quoting words.",
      example: "And he goes, completely calmly, \"No.\" She just looked at him — you could see it on her face.",
    },
    success: "The learner reports speech vividly and conveys a wordless reaction.",
    quiz: [
      qmcq("Why is the present tense used inside a past story?", [
        "It creates immediacy and is not an error.",
        "It is required after 'and'.",
        "The story must be in the present.",
      ], 0),
      qfill("He just ___ at the floor. (look)", ["looked"]),
      qmcq("What does reporting a look achieve?", [
        "It invites the listener to picture the moment.",
        "It shortens the story.",
        "It avoids reported speech rules.",
      ], 0),
    ],
    scenes: [
      sc("Yusuf", "a friend who was not there", "to feel like they were there",
        "An exchange your friend missed needs retelling.",
        "Bring the people to life.",
        "I wish I had seen it. What did they actually say?", "eager"),
      sc("Ottoline", "a colleague hearing about a meeting", "to picture how the meeting went",
        "A tense meeting must be described.",
        "Report speech and reaction vividly.",
        "The minutes say nothing. What was it actually like in there?", "curious"),
      sc("Noor", "a fellow traveller swapping encounters", "to hear a good encounter story",
        "Travellers are describing memorable encounters.",
        "Bring the people to life.",
        "You met someone unforgettable. How did it go?", "delighted"),
      sc("Mr. Halvorsen", "your tutor", "to practise vivid reporting",
        "The seminar is examining reported speech in narrative.",
        "Report vividly.",
        "How do you make a reported line sound like a person speaking?", "probing"),
      sc("Ms. Cardoso", "the examiner", "to check narrative liveliness",
        "The examiner asks for a retold exchange.",
        "Report speech and reaction vividly.",
        "Could you retell a conversation so I can hear the people in it?", "neutral"),
    ],
  },

  {
    id: "c1-a-story-that-lands",
    topic: "telling an anecdote that gets a reaction",
    objectives: [
      "Aim an anecdote at a specific reaction.",
      "Close it without explaining the point.",
    ],
    goal: "Tell a story that gets the reaction you were aiming for.",
    target: "landing an anecdote",
    correction: "Model the closing line and let the learner land their own story.",
    summary: "You practised telling an anecdote that gets the reaction you intended.",
    minutes: 8,
    points: [
      {
        form: "you had to be there",
        claims: [
          "'You had to be there' acknowledges that a retelling cannot capture the moment itself.",
          "Used before the end it signals you do not trust the story; used after, it is affectionate.",
        ],
        ex: ["You had to be there, honestly.", "I know, you had to be there."],
      },
      {
        form: "I'll never forget it",
        claims: [
          "'I'll never forget it' tells the listener the story mattered to you.",
          "It works as a close rather than an opening.",
        ],
        ex: ["I'll never forget it.", "I'll never forget the look on his face."],
      },
      {
        form: "still makes me laugh",
        claims: [
          "'It still makes me laugh' cues the reaction without demanding it.",
          "Explaining why something was funny usually weakens it, especially after the punchline.",
        ],
        ex: ["It still makes me laugh now.", "That still makes me laugh."],
      },
    ],
    ex: [
      fill("You had to ___ there, honestly. (be)", ["be"]),
      mcq("Which line works as a close?", [
        "I'll never forget the look on his face.",
        "Anyway, that is the background.",
        "So that is where it starts.",
      ], 0),
      say("it / still make / me / laugh / now", ["It still makes me laugh now."]),
    ],
    open: {
      q: "Tell a short anecdote aimed at making me laugh, and close it without explaining the joke.",
      must: ["you had to be there", "I'll never forget it", "still makes me laugh"],
      criteria: "The answer aims at a reaction and closes without explaining the point.",
      example: "I'll never forget it — he answered the wrong phone entirely. It still makes me laugh; you had to be there.",
    },
    success: "The learner lands an anecdote without explaining it.",
    quiz: [
      qmcq("What usually happens if you explain why something was funny?", [
        "The humour is weakened.",
        "The story becomes clearer.",
        "The listener laughs harder.",
      ], 0),
      qfill("I'll never ___ the look on his face. (forget)", ["forget"]),
      qmcq("When does 'you had to be there' weaken a story?", [
        "when used before you have finished it",
        "when used at the very end",
        "when used with a past tense",
      ], 0),
    ],
    scenes: [
      sc("Beatriz", "a friend who wants cheering up", "to be genuinely amused",
        "A friend has had a bad day and needs a story.",
        "Aim the anecdote at a laugh.",
        "I need something ridiculous today. Have you got one?", "flat"),
      sc("Andres", "a colleague at an informal lunch", "to hear a good work story",
        "An informal lunch invites anecdotes.",
        "Land the story.",
        "Go on — will you tell them the phone story?", "encouraging"),
      sc("Selin", "a fellow guest at a long dinner", "to enjoy a well-aimed story",
        "A dinner table expects a story.",
        "Aim and land it.",
        "Everyone has told one except you. Your turn?", "expectant"),
      sc("Mr. Achebe", "your tutor", "to practise landing an anecdote",
        "The seminar is examining anecdote structure.",
        "Land the story without explaining it.",
        "Why does explaining the point of a story destroy it?", "probing"),
      sc("Ms. Lindberg", "the examiner", "to check anecdote delivery",
        "The examiner asks for an amusing anecdote.",
        "Land it without explanation.",
        "Could you tell me something that still makes you laugh?", "neutral"),
    ],
  },

  {
    id: "c1-retelling-for-effect",
    topic: "the same story for two audiences",
    objectives: [
      "Give a compressed version of a story.",
      "Change the emphasis for a different listener.",
    ],
    goal: "Tell one story two ways for two different listeners.",
    target: "adapting a story to its audience",
    correction: "Model the compressed version and let the learner produce the other.",
    summary: "You practised telling one story two ways for two different audiences.",
    minutes: 8,
    points: [
      {
        form: "short version is",
        claims: [
          "'The short version is...' offers compression before the listener asks for it.",
          "Offering it first signals you know their time is limited.",
        ],
        ex: ["The short version is that nobody checked.", "The short version is we lost a week."],
      },
      {
        form: "long story short",
        claims: [
          "'Long story short' compresses mid-telling when you sense the listener drifting.",
          "Using it and then continuing at length is a common and noticeable failure.",
        ],
        ex: ["Long story short, it worked.", "Long story short, we started again."],
      },
      {
        form: "to put it another way",
        claims: [
          "'To put it another way' changes the framing for a listener who did not follow.",
          "It reframes rather than repeats, which is what makes it useful.",
        ],
        ex: ["To put it another way, we ran out of time.", "To put it another way, nobody owned it."],
      },
    ],
    ex: [
      fill("The ___ version is that nobody checked. (short)", ["short"]),
      mcq("Which phrase compresses mid-telling?", [
        "Long story short,",
        "As I was saying,",
        "To begin with,",
      ], 0),
      say("to put it / another way / we / run out of time", ["To put it another way, we ran out of time."]),
    ],
    open: {
      q: "Take one event and tell it twice: once in a sentence for a busy colleague, once reframed for someone who did not follow.",
      must: ["short version is", "long story short", "to put it another way"],
      criteria: "The answer compresses for one audience and reframes for another.",
      example: "For my boss: short version is we lost a week. For a colleague: long story short, nobody owned it — to put it another way, nobody checked.",
    },
    success: "The learner compresses for one audience and reframes for another.",
    quiz: [
      qmcq("What is the common failure with 'long story short'?", [
        "continuing at length afterwards",
        "using it at the end",
        "using it with a past tense",
      ], 0),
      qfill("Long story ___, it worked in the end. (short)", ["short"]),
      qmcq("What does 'to put it another way' do?", [
        "It reframes rather than repeats.",
        "It repeats the same words slowly.",
        "It ends the conversation.",
      ], 0),
    ],
    scenes: [
      sc("Teodor", "a friend with plenty of time", "to hear the full version",
        "A friend has time and wants the whole story.",
        "Give the long version, then compress it.",
        "We have all afternoon. Start at the beginning?", "settled"),
      sc("Marguerite", "a manager between meetings", "to get the essentials in one line",
        "A manager has thirty seconds.",
        "Compress it to a sentence.",
        "I have thirty seconds before my next call. Can you summarise?", "rushed"),
      sc("Arjun", "someone who did not follow the first time", "to finally understand",
        "A listener did not follow your first telling.",
        "Reframe rather than repeat.",
        "I did not follow any of that. Can you try again differently?", "confused"),
      sc("Mrs. Osei", "your tutor", "to practise audience adaptation",
        "The seminar is examining audience design.",
        "Compress and reframe.",
        "How does the same story change for two different listeners?", "probing"),
      sc("Mr. Kovacs", "the examiner", "to check audience adaptation",
        "The examiner asks for two versions.",
        "Compress and reframe.",
        "Could you tell me an event twice, for two different listeners?", "neutral"),
    ],
  },

  // --- Ünite 7 · Precision and Nuance ----------------------------------------
  {
    id: "c1-imply-and-infer",
    topic: "commonly confused word pairs",
    objectives: [
      "Distinguish imply from infer.",
      "Correct a confusion without embarrassing anyone.",
    ],
    goal: "Use commonly confused pairs correctly and correct them tactfully.",
    target: "commonly confused pairs",
    correction: "State the distinction and let the learner use the right word.",
    summary: "You learned to distinguish imply from infer and to correct the confusion tactfully.",
    minutes: 8,
    points: [
      {
        form: "what I'm implying",
        claims: [
          "The speaker implies; the meaning is put into the words by the person speaking.",
          "'What I'm implying' is therefore about your own intention.",
        ],
        ex: ["What I'm implying is that nobody checked.", "I'm not implying anything of the sort."],
      },
      {
        form: "what you inferred",
        claims: [
          "The listener infers; the meaning is taken out of the words by the person hearing.",
          "'What you inferred' is about their reading, not your intention.",
        ],
        ex: ["What you inferred is not what I meant.", "You inferred more than I said."],
      },
      {
        form: "there's a difference",
        claims: [
          "'There's a difference between X and Y' corrects without accusing anyone of error.",
          "Correcting a word choice directly can derail the discussion it belongs to.",
        ],
        ex: ["There's a difference between implying and inferring.", "There's a difference worth keeping."],
      },
    ],
    ex: [
      fill("What I'm ___ is that nobody checked. (imply)", ["implying"]),
      mcq("Who infers?", [
        "the listener",
        "the speaker",
        "both equally in every case",
      ], 0),
      say("there be / a difference / between implying / and inferring", ["There's a difference between implying and inferring.", "There is a difference between implying and inferring."]),
    ],
    open: {
      q: "Someone says you implied they were careless. Explain that this was their inference, not your implication, tactfully.",
      must: ["what I'm implying", "what you inferred", "there's a difference"],
      criteria: "The answer distinguishes speaker meaning from listener reading and corrects tactfully.",
      example: "What I'm implying is narrower than what you inferred. There's a difference, and it matters here.",
    },
    success: "The learner distinguishes the pair and corrects tactfully.",
    quiz: [
      qmcq("Which sentence is correct?", [
        "You inferred more than I said.",
        "You implied more than I said, from my words.",
        "You inferred it into my words.",
      ], 0),
      qfill("What I'm ___ is not what you heard. (imply)", ["implying"]),
      qmcq("Why correct a word choice indirectly?", [
        "A direct correction can derail the discussion.",
        "Indirect corrections are more accurate.",
        "It is grammatically required.",
      ], 0),
    ],
    scenes: [
      sc("Ilse", "a friend who has read too much into you", "to correct a misreading",
        "A friend has taken more from your words than you put in.",
        "Correct the reading tactfully.",
        "So you are saying I was wrong the whole time?", "hurt"),
      sc("Tomasz", "a colleague after a tense email", "to clear up a misreading",
        "An email has been read as an accusation.",
        "Separate meaning from reading.",
        "Your email implied I dropped the ball. Did it not?", "defensive"),
      sc("Aiko", "an academic in discussion", "to keep terms precise",
        "A discussion turns on a term used loosely.",
        "Correct the usage tactfully.",
        "You are inferring a great deal from one sentence, aren't you?", "precise"),
      sc("Professor Novak", "your tutor", "to practise precision",
        "The seminar is examining confused pairs.",
        "Distinguish and correct tactfully.",
        "Who implies and who infers, and why does it matter?", "probing"),
      sc("Ms. Alvarez", "the examiner", "to check precision",
        "The examiner uses one of the pair loosely.",
        "Correct it tactfully.",
        "I infer from your answer that you disagree. Or do I imply it?", "neutral"),
    ],
  },

  {
    id: "c1-degrees-of-approval",
    topic: "the scale of approval",
    objectives: [
      "Place an assessment on the scale from adequate to excellent.",
      "Damn with faint praise deliberately.",
    ],
    goal: "Say exactly how good something is.",
    target: "calibrating approval",
    correction: "Model the calibrated assessment and let the learner place their own.",
    summary: "You learned to place an assessment precisely on the scale of approval.",
    minutes: 8,
    points: [
      {
        form: "perfectly decent",
        claims: [
          "'Perfectly decent' means adequate; in context it often frames the thing as acceptable but not exceptional.",
          "In this collocation 'perfectly' tends to mark the limit of the praise rather than raise it.",
        ],
        ex: ["It was perfectly decent.", "The food was perfectly decent, if unremarkable."],
      },
      {
        form: "genuinely outstanding",
        claims: [
          "'Genuinely' emphasises that the praise is sincere rather than polite; it is optional.",
          "Unqualified praise is often read as courtesy, so the marker separates the two.",
        ],
        ex: ["The second half was genuinely outstanding.", "It was genuinely outstanding work."],
      },
      {
        form: "not without merit",
        claims: [
          "'Not without merit' is faint praise: it concedes some value and implies little more.",
          "Double negatives of this kind usually lower rather than raise the assessment.",
        ],
        ex: ["The proposal is not without merit.", "It was not without merit, but it was not enough."],
      },
    ],
    ex: [
      fill("It was ___ decent, if unremarkable. (perfect)", ["perfectly"]),
      mcq("Which phrase is faint praise?", [
        "not without merit",
        "genuinely outstanding",
        "exceptionally good",
      ], 0),
      say("the second half / be / genuinely outstanding", ["The second half was genuinely outstanding."]),
    ],
    open: {
      q: "Assess three things you have seen recently: one adequate, one excellent, one you can only faintly praise.",
      must: ["perfectly decent", "genuinely outstanding", "not without merit"],
      criteria: "The answer places each assessment precisely on the scale of approval.",
      example: "The venue was perfectly decent. The second speaker was genuinely outstanding. The rest was not without merit.",
    },
    success: "The learner places at least two assessments precisely on the scale.",
    quiz: [
      qmcq("What does 'perfectly' tend to do in 'perfectly decent'?", [
        "It marks the limit of the praise.",
        "It raises the praise considerably.",
        "It makes the praise sarcastic.",
      ], 0),
      qfill("It was ___ without merit, but not enough. (not)", ["not"]),
      qmcq("What does 'genuinely' add?", [
        "It marks the praise as sincere rather than polite.",
        "It is grammatically required before adjectives.",
        "It makes the sentence formal.",
      ], 0),
    ],
    scenes: [
      sc("Ravenna", "a friend who performed", "to hear an honest assessment",
        "A friend performed and wants your real view.",
        "Calibrate the praise honestly.",
        "Be honest. Was it any good?", "nervous"),
      sc("Idris", "a colleague reviewing submissions", "to rank submissions accurately",
        "Several submissions must be ranked.",
        "Calibrate each assessment.",
        "We have to rank these. How would you place them?", "exacting"),
      sc("Solveig", "an editor asking for a verdict", "to receive a usable verdict",
        "An editor needs a precise verdict.",
        "Place the assessment precisely.",
        "I need more than 'quite good'. Where does it sit?", "precise"),
      sc("Professor Adeyemi", "your tutor", "to practise calibration",
        "The seminar is examining evaluative language.",
        "Calibrate assessments precisely.",
        "How do you praise something faintly without being unkind?", "probing"),
      sc("Ms. Whitlock", "the examiner", "to check evaluative precision",
        "The examiner asks for an assessment.",
        "Calibrate it precisely.",
        "Could you assess something you saw recently, precisely?", "neutral"),
    ],
  },

  {
    id: "c1-hedged-and-blunt",
    topic: "distance between yourself and a claim",
    objectives: [
      "Increase the distance between yourself and a claim.",
      "Drop the hedges when directness is needed.",
    ],
    goal: "Choose how much you commit to what you are saying.",
    target: "hedging and directness",
    correction: "Contrast the hedged and blunt versions and let the learner choose.",
    summary: "You learned to control how much distance you put between yourself and a claim.",
    minutes: 9,
    points: [
      {
        form: "it would appear",
        claims: [
          "'It would appear that' creates more distance than a direct assertion.",
          "Overusing it can read as evasion rather than caution.",
        ],
        ex: ["It would appear that nobody was informed.", "It would appear the figures were wrong."],
      },
      {
        form: "one could argue",
        claims: [
          "'One could argue' presents a view tentatively, without fully committing you to it.",
          "It raises a view without attributing it to you, which keeps the discussion open.",
        ],
        ex: ["One could argue the opposite.", "One could argue that the decision was premature."],
      },
      {
        form: "quite frankly",
        claims: [
          "'Quite frankly' signals candour and that directness is coming.",
          "Overuse makes it lose force or sound confrontational.",
        ],
        ex: ["Quite frankly, it will not work.", "Quite frankly, I disagree."],
      },
    ],
    ex: [
      fill("It ___ appear that nobody was informed. (will)", ["would"]),
      mcq("Which sentence presents a view without owning it?", [
        "One could argue the opposite.",
        "I argue the opposite.",
        "The opposite is obviously true.",
      ], 0),
      fill("___ frankly, it will not work. (quite)", ["Quite"]),
      say("one / could argue / that the decision / be premature", ["One could argue that the decision was premature."]),
    ],
    open: {
      q: "State the same view three times: at maximum distance, unattributed, and completely directly.",
      must: ["it would appear", "one could argue", "quite frankly"],
      criteria: "The answer varies the distance between the speaker and the claim deliberately.",
      example: "It would appear the plan failed. One could argue it was doomed. Quite frankly, it was never going to work.",
    },
    success: "The learner varies the distance between themselves and a claim deliberately.",
    quiz: [
      qmcq("What is the risk of overusing 'it would appear'?", [
        "It reads as evasion rather than caution.",
        "It becomes grammatically incorrect.",
        "It sounds too informal.",
      ], 0),
      qfill("One ___ argue that the decision was premature. (can)", ["could"]),
      qmcq("What is the risk of overusing 'quite frankly'?", [
        "It loses force or starts to sound confrontational.",
        "It becomes grammatically incorrect.",
        "It changes the tense of the verb.",
      ], 0),
    ],
    scenes: [
      sc("Marek", "a friend asking for your real view", "to get past the hedging",
        "A friend senses you are hedging.",
        "Move from hedged to direct.",
        "You have been very diplomatic. What do you actually think?", "probing"),
      sc("Renata", "a colleague in a minuted meeting", "to hear a view that can be recorded",
        "A meeting is being minuted and wording matters.",
        "Hedge appropriately, then be direct.",
        "This is being recorded. How would you like it noted?", "careful"),
      sc("Kofi", "a journalist seeking a quote", "to get an attributable quote",
        "A journalist wants something quotable.",
        "Control the distance deliberately.",
        "Can I quote you on that, or shall we say 'sources'?", "persistent"),
      sc("Mrs. Nowak", "your tutor", "to practise hedging",
        "The seminar is examining epistemic distance.",
        "Vary the distance deliberately.",
        "When does hedging protect you and when does it discredit you?", "probing"),
      sc("Mr. Delacroix", "the examiner", "to check hedging control",
        "The examiner asks for an opinion.",
        "Vary the distance deliberately.",
        "Could you give me the same view cautiously and then bluntly?", "neutral"),
    ],
  },

  {
    id: "c1-tends-to-has-a-habit-of",
    topic: "describing tendencies",
    objectives: [
      "Describe a tendency without claiming it is invariable.",
      "Signal disapproval through the choice of expression.",
    ],
    goal: "Describe what usually happens with the right degree of commitment.",
    target: "expressing tendencies",
    correction: "Model the tendency expression and let the learner describe their own.",
    summary: "You learned to describe tendencies with the right degree of commitment.",
    minutes: 9,
    points: [
      {
        form: "tends to",
        claims: [
          "'Tends to' describes a pattern without claiming it holds every time.",
          "It is neutral: it carries no approval or disapproval on its own.",
        ],
        ex: ["The system tends to slow down in the afternoon.", "He tends to arrive late."],
      },
      {
        form: "has a habit of",
        claims: [
          "'Has a habit of' usually carries mild disapproval.",
          "The same fact stated with 'tends to' sounds neutral by comparison.",
        ],
        ex: ["He has a habit of interrupting.", "She has a habit of leaving things until the last minute."],
      },
      {
        form: "more often than not",
        claims: [
          "'More often than not' means in a majority of cases, without specifying the proportion.",
          "It states a majority explicitly, where 'usually' is read very differently by different listeners.",
        ],
        ex: ["More often than not, it works.", "More often than not, nobody replies."],
      },
    ],
    ex: [
      fill("The system ___ to slow down in the afternoon. (tend)", ["tends"]),
      mcq("Which expression carries mild disapproval?", [
        "He has a habit of interrupting.",
        "He tends to interrupt.",
        "He sometimes interrupts.",
      ], 0),
      fill("More often than ___, it works. (not)", ["not"]),
      say("she / have / a habit of / leave things / late", ["She has a habit of leaving things late."]),
    ],
    open: {
      q: "Describe two tendencies you have noticed: one neutrally and one where you want disapproval to show.",
      must: ["tends to", "has a habit of", "more often than not"],
      criteria: "The answer describes tendencies with the right degree of commitment and attitude.",
      example: "The system tends to slow down after lunch. He has a habit of ignoring it; more often than not, nothing happens.",
    },
    success: "The learner describes tendencies with appropriate commitment and attitude.",
    quiz: [
      qmcq("Which explicitly indicates a majority of cases?", [
        "More often than not",
        "Usually",
        "Quite often",
      ], 0),
      qfill("He ___ to arrive late on Mondays. (tend)", ["tends"]),
      qmcq("What does 'tends to' carry?", [
        "no approval or disapproval on its own",
        "mild disapproval",
        "strong approval",
      ], 0),
    ],
    scenes: [
      sc("Bruna", "a friend asking about a mutual acquaintance", "to hear an honest but fair description",
        "A mutual acquaintance is being described.",
        "Describe tendencies with the right attitude.",
        "What is he actually like to work with?", "curious"),
      sc("Priya", "a manager writing a reference", "to word a reference fairly",
        "A reference must be honest without being damaging.",
        "Calibrate the attitude.",
        "I have to be truthful but fair. How would you put it?", "careful"),
      sc("Hugo", "a colleague describing a system", "to characterise a system accurately",
        "A system behaves inconsistently.",
        "Describe the tendency precisely.",
        "Does it always do that, or just sometimes?", "technical"),
      sc("Mr. Boateng", "your tutor", "to practise tendency expressions",
        "The seminar is examining degrees of generalisation.",
        "Describe tendencies precisely.",
        "How does 'has a habit of' differ from 'tends to'?", "probing"),
      sc("Ms. Aaltonen", "the examiner", "to check generalisation",
        "The examiner asks about patterns you have noticed.",
        "Describe them with the right commitment.",
        "Could you describe a pattern you have noticed, without overstating it?", "neutral"),
    ],
  },

  {
    id: "c1-almost-the-right-word",
    topic: "narrowing down to the exact term",
    objectives: [
      "Reject a near-miss word and keep searching.",
      "Keep the conversation moving while you search.",
    ],
    goal: "Find the exact word without stopping the conversation.",
    target: "searching for the precise word",
    correction: "Model the narrowing move and let the learner keep searching aloud.",
    summary: "You practised narrowing down to the exact word without losing the conversation.",
    minutes: 8,
    points: [
      {
        form: "not quite that",
        claims: [
          "'Not quite that' rejects a near-miss without dismissing the help.",
          "It keeps the other person offering rather than stopping.",
        ],
        ex: ["Not quite that, but close.", "Not quite that — something sharper."],
      },
      {
        form: "closer to",
        claims: [
          "'Closer to' moves towards the target by comparison rather than definition.",
          "Comparing is often faster than defining when you are searching.",
        ],
        ex: ["Closer to reluctant than unwilling.", "Closer to tired than bored."],
      },
      {
        form: "what I'm reaching for",
        claims: [
          "'What I'm reaching for is...' names the search itself and buys time.",
          "Naming the search is better than stopping mid-sentence.",
        ],
        ex: ["What I'm reaching for is something like resignation.", "What I'm reaching for is more specific."],
      },
    ],
    ex: [
      fill("___ quite that, but close. (not)", ["Not"]),
      mcq("Which phrase moves towards the target by comparison?", [
        "Closer to reluctant than unwilling.",
        "It means something else entirely.",
        "That is the wrong word.",
      ], 0),
      say("what I / be reaching for / be / more specific", ["What I'm reaching for is more specific.", "What I am reaching for is more specific."]),
    ],
    open: {
      q: "Describe a feeling you cannot name precisely, rejecting two near-misses before you land on it.",
      must: ["not quite that", "closer to", "what I'm reaching for"],
      criteria: "The answer rejects near-misses and keeps the search moving without stopping.",
      example: "Frustration? Not quite that. Closer to resignation than anger. What I'm reaching for is resigned acceptance.",
    },
    success: "The learner searches aloud without losing the conversation.",
    quiz: [
      qmcq("Why name the search itself?", [
        "It is better than stopping mid-sentence.",
        "It is grammatically required.",
        "It ends the conversation politely.",
      ], 0),
      qfill("___ to tired than bored, I think. (close)", ["Closer"]),
      qmcq("What does 'not quite that' preserve?", [
        "the other person's willingness to keep offering",
        "the grammatical subject",
        "the formality of the exchange",
      ], 0),
    ],
    scenes: [
      sc("Ingrid", "a friend helping you find a word", "to help you land on the right word",
        "You are struggling to name something precisely.",
        "Reject near-misses and keep searching.",
        "Angry? Frustrated? Can you give me something to work with?", "helpful"),
      sc("Owen", "a colleague drafting wording", "to find the right term for a document",
        "A document needs exactly the right term.",
        "Narrow it down aloud.",
        "None of these words is right. What are we actually trying to say?", "focused"),
      sc("Camille", "an interpreter helping you", "to convey a shade of meaning",
        "An interpreter needs the precise shade you mean.",
        "Narrow it down.",
        "There are three possible words here. Which shade do you mean?", "precise"),
      sc("Ms. Kowalski", "your tutor", "to practise lexical searching",
        "The seminar is examining vocabulary precision.",
        "Search aloud without stopping.",
        "What do you say while you are still looking for the word?", "probing"),
      sc("Mr. Ozturk", "the examiner", "to check fluency under lexical strain",
        "The examiner asks about something hard to name.",
        "Keep speaking while you search.",
        "Could you describe a feeling you have never found the word for?", "neutral"),
    ],
  },

  {
    id: "c1-describing-something-complicated",
    topic: "an accurate account of something messy",
    objectives: [
      "Acknowledge that a situation has several layers.",
      "Give a compact summary after the complexity.",
    ],
    goal: "Describe something genuinely complicated without oversimplifying it.",
    target: "describing complexity accurately",
    correction: "Model the layering sentence and let the learner describe the complexity.",
    summary: "You practised describing something complicated without flattening it.",
    minutes: 8,
    points: [
      {
        form: "there are several layers",
        claims: [
          "'There are several layers to this' warns the listener not to expect one cause.",
          "The warning protects an accurate answer from sounding evasive.",
        ],
        ex: ["There are several layers to this.", "There are several layers, and they interact."],
      },
      {
        form: "it's tangled up with",
        claims: [
          "'It's tangled up with' names a connection you cannot separate cleanly.",
          "Admitting the tangle is more accurate than pretending it is separable.",
        ],
        ex: ["It's tangled up with a much older dispute.", "It's tangled up with funding."],
      },
      {
        form: "in short",
        claims: [
          "'In short' delivers a compact summary after the complexity, not instead of it.",
          "Here the summary follows the detail; in a written brief an executive summary may reasonably come first.",
        ],
        ex: ["In short, nobody owns the decision.", "In short, it is unresolved."],
      },
    ],
    ex: [
      fill("There are several ___ to this, unfortunately. (layer)", ["layers"]),
      mcq("Which sentence names an inseparable connection?", [
        "It's tangled up with a much older dispute.",
        "It is separate from the older dispute.",
        "The older dispute is unrelated.",
      ], 0),
      say("in short / nobody / own / the decision", ["In short, nobody owns the decision."]),
    ],
    open: {
      q: "Describe a genuinely complicated situation you know, then summarise it in one sentence at the end.",
      must: ["there are several layers", "it's tangled up with", "in short"],
      criteria: "The answer preserves the complexity and closes with a compact summary.",
      example: "There are several layers: unclear ownership, funding cuts, an old dispute. It's tangled up with that. In short, it is stalled.",
    },
    success: "The learner preserves the complexity and closes with a summary.",
    quiz: [
      qmcq("Why warn about layers first?", [
        "It protects an accurate answer from sounding evasive.",
        "It shortens the explanation.",
        "It avoids the passive voice.",
      ], 0),
      qfill("It's ___ up with funding, unfortunately. (tangle)", ["tangled"]),
      qmcq("Why does 'in short' come last here?", [
        "It closes the account rather than replacing it.",
        "It cannot open a sentence.",
        "It requires a past tense before it.",
      ], 0),
    ],
    scenes: [
      sc("Rashid", "a friend expecting a simple answer", "to understand why there is no simple answer",
        "A friend wants a one-line answer to something complicated.",
        "Preserve the complexity and summarise.",
        "Just tell me who is at fault. It cannot be that complicated?", "impatient"),
      sc("Halima", "a new colleague joining a messy project", "to understand a tangled situation",
        "A new colleague needs the real picture.",
        "Describe the layers and summarise.",
        "Everyone tells me a different version. What is actually going on?", "bewildered"),
      sc("Anders", "an official assessing a case", "to grasp a complicated case",
        "An official needs an accurate account.",
        "Describe accurately without evasion.",
        "Take your time — I would rather have it accurate than short. What happened?", "patient"),
      sc("Professor Osei", "your tutor", "to practise describing complexity",
        "The seminar is examining accurate description.",
        "Preserve complexity and summarise.",
        "How do you stay accurate without sounding evasive?", "probing"),
      sc("Ms. Reyes", "the examiner", "to check descriptive accuracy",
        "The examiner asks about something complicated.",
        "Preserve complexity and close with a summary.",
        "Could you describe a complicated situation without oversimplifying it?", "neutral"),
    ],
  },

  {
    id: "c1-choosing-the-register",
    topic: "the same content at three levels",
    objectives: [
      "Deliver one message at three levels of formality.",
      "Judge which level a situation needs.",
    ],
    goal: "Say the same thing formally, casually and somewhere between.",
    target: "controlling register deliberately",
    correction: "Give one version and let the learner produce the other two.",
    summary: "You practised delivering one message at three levels of formality.",
    minutes: 8,
    points: [
      {
        form: "formally I'd say",
        claims: [
          "The formal version avoids contractions and colloquialisms; clear verbs still beat unnecessary nominalisation.",
          "'I am unable to attend' rather than 'I can't come'.",
        ],
        ex: ["Formally I'd say that attendance is not possible.", "Formally I'd say we are unable to proceed."],
      },
      {
        form: "casually it's just",
        claims: [
          "The casual version uses contractions, phrasal verbs and short sentences.",
          "'I can't make it' carries the same information with a different social meaning.",
        ],
        ex: ["Casually it's just: I can't make it.", "Casually it's just: we're not going ahead."],
      },
      {
        form: "somewhere in between",
        claims: [
          "The middle register is where most professional communication actually sits.",
          "Choosing the extreme when the middle fits is itself a register error.",
        ],
        ex: ["Somewhere in between: I'm afraid I can't attend.", "Somewhere in between works best here."],
      },
    ],
    ex: [
      fill("___ I'd say that attendance is not possible. (formal)", ["Formally"]),
      mcq("Which version is casual?", [
        "I can't make it.",
        "I am unable to attend.",
        "I regret that attendance is not possible.",
      ], 0),
      say("somewhere / in between / work / best here", ["Somewhere in between works best here."]),
    ],
    open: {
      q: "Take the message 'I cannot attend' and deliver it three ways: formally, casually and in between.",
      must: ["formally I'd say", "casually it's just", "somewhere in between"],
      criteria: "The answer delivers one message at three distinct levels of formality.",
      example: "Formally I'd say attendance is not possible. Casually it's just: I can't come. Somewhere in between: I'm afraid I can't.",
    },
    success: "The learner delivers one message at three distinct levels.",
    quiz: [
      qmcq("Where does most professional communication sit?", [
        "in the middle register",
        "at the most formal end",
        "at the most casual end",
      ], 0),
      qfill("___ it's just: we're not going ahead. (casual)", ["Casually"]),
      qmcq("What is itself a register error?", [
        "choosing the extreme when the middle fits",
        "using contractions in speech",
        "using full forms in writing",
      ], 0),
    ],
    scenes: [
      sc("Fatima", "a friend learning English with you", "to see the three levels side by side",
        "A friend cannot judge which level to use.",
        "Demonstrate all three.",
        "How do I know which version to use? Show me all three?", "confused"),
      sc("Viktor", "a colleague drafting three messages", "to send the right version to each audience",
        "The same news goes to three different audiences.",
        "Produce all three versions.",
        "Same message, three audiences. How do we word each?", "practical"),
      sc("Ana Lucia", "a host curious about English register", "to understand how English shifts",
        "A host is curious how English changes with formality.",
        "Demonstrate the three levels.",
        "Is English very different when you are being formal?", "curious"),
      sc("Professor Tremblay", "your tutor", "to practise register control",
        "The seminar is examining register.",
        "Deliver one message at three levels.",
        "What actually changes between the three levels, and what does not?", "probing"),
      sc("Mr. Eriksen", "the examiner", "to check register control",
        "The examiner asks for three versions.",
        "Deliver all three cleanly.",
        "Could you decline an invitation formally, casually and in between?", "neutral"),
    ],
  },
];
