/** C1 · Ünite 8-10 — Professional · Culture and Idiom · Extended Discussion (21 ders).
 *
 *  Ünite 8'de gramer dersi yok: itiraz etmek, müzakere etmek, kötü haberi vermek
 *  ve zor geri bildirimde bulunmak yapı sorunu değil, hasar kontrolü sorunu.
 *  Ünite krizde konuşmayla kapanıyor — bilgi eksikken açık kalabilmek.
 *
 *  Ünite 9 kültür ve deyim: tek gramer dersi eşdizim (`heavy rain`, ama `strong
 *  argument`), gerisi deyim, ironi işareti, kötü düşen ifadeler ve ortamı okumak.
 *  Öğretilen şey kelime değil, NEREDE hangi kelimenin düştüğü.
 *
 *  Ünite 10 C1'in ve külliyatın kapanışı: 8 dersin 6'sı konuşma. Uzun sırayı
 *  taşımak, haritalamak, temiz cevabı olmayan soruyu tartışmak, derinlemesine
 *  bildiğin ve hiç bilmediğin konuda konuşmak. Son ders bir tartışmayı iki tarafa
 *  da hakkını vererek kapatmak — seviyenin son becerisi bu.
 *
 *  Gramer derslerinde 4 alıştırma, phrases/practice'te 3.
 *
 *  PARTİ 2 İNCELEMESİNDEN: iddia ile örnek çelişemez; "şu iki şeye cevap ver"
 *  diyen görev o iki şeyi VERİR; iddialar mutlak değil ("usually", "tends to");
 *  dolaysız aktarım tırnak alır.
 */
import { fill, mcq, qfill, qmcq, say, sc, type Authored } from "./dsl.js";

export const C1_U8_10: Authored[] = [
  // --- Ünite 8 · Professional Communication ----------------------------------
  {
    id: "c1-diplomatic-disagreement",
    topic: "objecting without damaging the relationship",
    objectives: [
      "State a clear objection in non-adversarial language.",
      "Separate the disagreement from the person.",
    ],
    goal: "Disagree clearly without turning it into a conflict.",
    target: "diplomatic disagreement",
    correction: "Model the softened objection and let the learner object again.",
    summary: "You learned to state a clear objection without making it personal.",
    minutes: 8,
    points: [
      {
        form: "I see it differently",
        claims: [
          "'I see it differently' locates the disagreement in perspective rather than in error.",
          "It leaves both positions standing, which keeps the exchange open.",
        ],
        ex: ["I see it differently, and here is why.", "I see it differently on the timing."],
      },
      {
        form: "with respect I'd argue",
        claims: [
          "'With respect' signals disagreement with someone senior or in public.",
          "In British English the tone matters: said flatly it can read as sharp.",
        ],
        ex: ["With respect, I'd argue the opposite.", "With respect, I'd argue the data says otherwise."],
      },
      {
        form: "I'm not entirely convinced",
        claims: [
          "'I'm not entirely convinced' withholds agreement without asserting the opposite.",
          "'Entirely' is what softens it; without that word it lands much harder.",
        ],
        ex: ["I'm not entirely convinced by that.", "I'm not entirely convinced the risk is covered."],
      },
    ],
    ex: [
      fill("I ___ it differently, and here is why. (see)", ["see"]),
      mcq("Which sentence withholds agreement without asserting the opposite?", [
        "I'm not entirely convinced by that.",
        "That is completely wrong.",
        "You have misunderstood the data.",
      ], 0),
      say("with respect / I / would argue / the opposite", ["With respect, I'd argue the opposite.", "With respect, I would argue the opposite."]),
    ],
    open: {
      q: "A senior colleague states a view you disagree with in a meeting. Object clearly without making it personal.",
      must: ["I see it differently", "with respect I'd argue", "I'm not entirely convinced"],
      criteria: "The answer states a clear objection while keeping the disagreement impersonal.",
      example: "With respect, I'd argue the timetable is too optimistic. I see it differently because the dependency work is unfinished, so I'm not entirely convinced June is realistic.",
    },
    success: "The learner objects clearly without making the disagreement personal.",
    quiz: [
      qmcq("Which phrase locates disagreement in perspective?", [
        "I see it differently.",
        "You are mistaken.",
        "That is an error.",
      ], 0),
      qfill("I'm not ___ convinced the risk is covered. (entire)", ["entirely"]),
      qmcq("Why does 'entirely' matter?", [
        "Without it the sentence lands much harder.",
        "It is grammatically required.",
        "It makes the sentence formal.",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Alonso", "a senior director stating a view", "to hear whether anyone disagrees",
        "A senior figure has stated a view you think is wrong.",
        "Object clearly and impersonally.",
        "That is my reading of it. Does anyone see it another way?", "authoritative"),
      sc("Rashid", "a colleague defending a decision", "to be challenged constructively",
        "A colleague is defending a decision you doubt.",
        "Object without making it personal.",
        "I have made the call and I stand by it. Problem?", "defensive"),
      sc("Ines", "a client with a firm opinion", "to hear a professional counterview",
        "A client holds a view that will cause problems.",
        "Disagree diplomatically.",
        "We have always done it this way. Would you do something different?", "settled"),
      sc("Professor Osei", "your tutor", "to practise diplomatic objection",
        "The seminar is examining disagreement in professional settings.",
        "Object clearly and impersonally.",
        "How do you disagree with your boss without it becoming personal?", "probing"),
      sc("Ms. Reyes", "the examiner", "to check diplomatic register",
        "The examiner states a view you should challenge.",
        "Object diplomatically.",
        "I think written exams are the only fair assessment. Do you agree?", "neutral"),
    ],
  },

  {
    id: "c1-chairing-a-discussion",
    topic: "running a conversation with several people",
    objectives: [
      "Bring in someone who has not spoken.",
      "Return a wandering discussion to the point.",
    ],
    goal: "Run a discussion so everyone is heard and the time holds.",
    target: "chairing language",
    correction: "Model the chairing move and let the learner run the next turn.",
    summary: "You learned to bring people in, return to the point and manage the time.",
    minutes: 8,
    points: [
      {
        form: "let's hear from",
        claims: [
          "'Let's hear from' invites someone in by name, which is harder to decline than a general invitation.",
          "Naming the person also stops the loudest voice filling the gap.",
        ],
        ex: ["Let's hear from Maya on this.", "Let's hear from someone who hasn't spoken."],
      },
      {
        form: "coming back to",
        claims: [
          "'Coming back to' returns to a point that was left, rather than cutting someone off.",
          "It frames the return as picking up rather than correcting.",
        ],
        ex: ["Coming back to the budget question.", "Coming back to what Ana raised earlier."],
      },
      {
        form: "we're running short",
        claims: [
          "'We're running short of time' manages the clock without blaming a speaker.",
          "Naming the constraint rather than the person keeps the room calm.",
        ],
        ex: ["We're running short of time.", "We're running short, so briefly if you can."],
      },
    ],
    ex: [
      fill("___ hear from Maya on this. (let us)", ["Let's", "Let us"]),
      mcq("Which sentence manages the clock without blaming anyone?", [
        "We're running short of time.",
        "You have talked for too long.",
        "Somebody is using all the time.",
      ], 0),
      say("coming back / to the budget / question", ["Coming back to the budget question."]),
    ],
    open: {
      q: "You are chairing a meeting where one person dominates and another has said nothing. Handle both.",
      must: ["let's hear from", "coming back to", "we're running short"],
      criteria: "The answer brings in a quiet participant and manages the time without blaming anyone.",
      example: "We're running short of time, so I'll pause you there, Tom. Let's hear from Ana, who hasn't spoken. Then, coming back to the budget, one comment each.",
    },
    success: "The learner brings someone in and manages the time without blame.",
    quiz: [
      qmcq("Why name the person you invite in?", [
        "It is harder to decline than a general invitation.",
        "It is grammatically required.",
        "It shortens the meeting.",
      ], 0),
      qfill("___ back to what Ana raised earlier. (come)", ["Coming"]),
      qmcq("Why name the constraint rather than the person?", [
        "It keeps the room calm.",
        "It saves time.",
        "It is more formal.",
      ], 0),
    ],
    scenes: [
      sc("Mr. Reddy", "a dominant participant", "to be managed without offence",
        "One participant is filling all the available time.",
        "Manage the room.",
        "Sorry, one more thing on this — may I just finish my point?", "insistent"),
      sc("Halima", "a quiet participant", "to be brought into the discussion",
        "Someone has said nothing for twenty minutes.",
        "Bring them in.",
        "Oh — did you want me to say something?", "hesitant"),
      sc("Anders", "a co-chair watching the clock", "to keep the meeting on time",
        "A meeting is overrunning and items remain.",
        "Manage the time and the room.",
        "We have fifteen minutes and four items. Your call?", "practical"),
      sc("Mrs. Berg", "your tutor", "to practise chairing",
        "The seminar is examining facilitation language.",
        "Bring people in and manage the clock.",
        "How do you stop one person taking all the air?", "probing"),
      sc("Mr. Eriksen", "the examiner", "to check facilitation language",
        "The examiner plays a difficult participant.",
        "Chair the discussion.",
        "I have a great deal more to say on this. May I continue?", "neutral"),
    ],
  },

  {
    id: "c1-negotiating-position",
    topic: "signalling where you can and cannot move",
    objectives: [
      "Signal flexibility on one point and firmness on another.",
      "Propose a mutual concession.",
    ],
    goal: "Make clear what is negotiable without giving it away.",
    target: "signalling negotiating positions",
    correction: "Model the flexibility signal and let the learner mark their own limits.",
    summary: "You learned to signal where you can move and where you cannot.",
    minutes: 8,
    points: [
      {
        form: "there's room on",
        claims: [
          "'There's room on price' signals flexibility on one item only.",
          "Naming the flexible item implies the others are not, without saying so.",
        ],
        ex: ["There's room on the timeline.", "There's room on price, within limits."],
      },
      {
        form: "that's not something we",
        claims: [
          "'That's not something we can move on' marks a limit without ending the talk.",
          "'We' rather than 'I' makes the limit institutional rather than personal.",
        ],
        ex: ["That's not something we can move on.", "That's not something we would consider."],
      },
      {
        form: "what if we both",
        claims: [
          "'What if we both...' proposes a mutual concession rather than a one-sided one.",
          "A mutual proposal frames the agreement as reciprocal because both sides concede something.",
        ],
        ex: ["What if we both moved a little?", "What if we both took part of the risk?"],
      },
    ],
    ex: [
      fill("There's ___ on the timeline, but not on scope. (room)", ["room"]),
      mcq("Which sentence marks a limit without ending the talk?", [
        "That's not something we can move on.",
        "This conversation is over.",
        "You are wasting my time.",
      ], 0),
      say("what if / we both / move / a little", ["What if we both moved a little?"]),
    ],
    open: {
      q: "You can move on timing but not on price. Signal both and propose a mutual concession.",
      must: ["there's room on", "that's not something we", "what if we both"],
      criteria: "The answer marks one flexible item and one firm limit, then proposes a mutual move.",
      example: "There's room on the timeline. On price, though, that's not something we can move on. What if we both took a later date and held the current price?",
    },
    success: "The learner signals flexibility and a limit, and proposes a mutual concession.",
    quiz: [
      qmcq("Why say 'we' rather than 'I' about a limit?", [
        "It makes the limit institutional rather than personal.",
        "It is more grammatical.",
        "It sounds more polite in every context.",
      ], 0),
      qfill("What if we ___ took part of the risk? (both)", ["both"]),
      qmcq("What does a mutual proposal do?", [
        "It frames the agreement as reciprocal.",
        "They are shorter.",
        "They avoid the conditional.",
      ], 0),
    ],
    scenes: [
      sc("Mr. Lowell", "a supplier pushing on price", "to find a deal that works",
        "A supplier is pressing on the one item you cannot move.",
        "Signal your limits and propose a mutual move.",
        "We need movement on price. Can you do that?", "firm"),
      sc("Priscilla", "a client renegotiating scope", "to reach a workable agreement",
        "A client wants more for the same money.",
        "Mark what is negotiable.",
        "The scope has grown a bit. That is manageable, isn't it?", "optimistic"),
      sc("Kemal", "a landlord discussing terms", "to agree terms both sides accept",
        "Lease terms are under discussion.",
        "Signal flexibility and limits.",
        "I can be flexible on some things. What matters most to you?", "businesslike"),
      sc("Professor Villanueva", "your tutor", "to practise negotiation signals",
        "The seminar is examining negotiation language.",
        "Signal position precisely.",
        "How do you show flexibility without giving the point away?", "probing"),
      sc("Ms. Sorensen", "the examiner", "to check negotiation language",
        "The examiner presses on one item.",
        "Signal flexibility and limits.",
        "I need a lower figure. What can you do?", "neutral"),
    ],
  },

  {
    id: "c1-delivering-bad-news",
    topic: "announcing something unwelcome",
    objectives: [
      "State the decision before the reasons.",
      "Acknowledge the impact without softening the message.",
    ],
    goal: "Deliver bad news clearly and humanely.",
    target: "delivering bad news",
    correction: "Model the clear announcement and let the learner deliver it again.",
    summary: "You learned to deliver bad news clearly, without burying or softening it.",
    minutes: 8,
    points: [
      {
        form: "I'm afraid we've decided",
        claims: [
          "State the decision promptly and explain afterwards; leading with lengthy reasons can bury it.",
          "'I'm afraid' acknowledges the news is unwelcome without hedging the content.",
        ],
        ex: ["I'm afraid we've decided not to proceed.", "I'm afraid we've decided to end the trial."],
      },
      {
        form: "this wasn't easy",
        claims: [
          "'This wasn't an easy decision' signals that it was considered carefully; on its own it does not acknowledge the impact on the listener.",
          "To acknowledge the impact you have to name it, so add what it will mean for them.",
        ],
        ex: ["This wasn't an easy decision.", "This wasn't easy and I want to explain it."],
      },
      {
        form: "I want to be straight",
        claims: [
          "'I want to be straight with you' signals that no further softening is coming.",
          "Following it with a hedge undermines the whole message.",
        ],
        ex: ["I want to be straight with you about why.", "I want to be straight: the funding has gone."],
      },
    ],
    ex: [
      fill("I'm ___ we've decided not to proceed. (afraid)", ["afraid"]),
      mcq("Which order is right for bad news?", [
        "the decision, then the reasons",
        "the reasons, then the decision",
        "the apology, then the reasons",
      ], 0),
      say("this / not be / an easy decision", ["This wasn't an easy decision.", "This was not an easy decision."]),
    ],
    open: {
      q: "Tell someone their project has been stopped. State the decision first, then the reasons.",
      must: ["I'm afraid we've decided", "this wasn't easy", "I want to be straight"],
      criteria: "The answer states the decision before the reasons and names the impact on the listener.",
      example: "I'm afraid we've decided to stop the project. This wasn't easy, and I know it disrupts your team. I want to be straight with you: the funding has gone.",
    },
    success: "The learner states the decision first and names the impact on the listener.",
    quiz: [
      qmcq("Why state the decision promptly?", [
        "Leading with lengthy reasons can bury it.",
        "It is grammatically required.",
        "It shortens the conversation.",
      ], 0),
      qfill("I want to be ___ with you about why. (straight)", ["straight"]),
      qmcq("What undermines 'I want to be straight with you'?", [
        "following it with a hedge",
        "following it with a reason",
        "saying it after the decision",
      ], 0),
    ],
    scenes: [
      sc("Dilek", "someone whose project is being stopped", "to hear the decision clearly",
        "A project is being cancelled and its owner does not know.",
        "Deliver the news clearly.",
        "You wanted to see me? Is this about the extension?", "hopeful"),
      sc("Mr. Osei", "a supplier losing a contract", "to be told plainly",
        "A contract is not being renewed.",
        "Deliver the news plainly.",
        "We assumed we would be renewed. Is that not happening?", "wary"),
      sc("Lucia", "a guest whose booking has failed", "to be told without runaround",
        "A booking cannot be honoured.",
        "Deliver the news clearly.",
        "I have travelled a long way. There is a room, isn't there?", "tired"),
      sc("Mrs. Kowalski", "your tutor", "to practise difficult announcements",
        "The seminar is examining bad-news delivery.",
        "State the decision first.",
        "Why does putting reasons first make bad news worse?", "probing"),
      sc("Mr. Ozturk", "the examiner", "to check bad-news delivery",
        "The examiner plays the affected person.",
        "Deliver the news clearly and humanely.",
        "I have been waiting to hear. What is the decision?", "neutral"),
    ],
  },

  {
    id: "c1-giving-difficult-feedback",
    topic: "candid feedback that stays constructive",
    objectives: [
      "Describe behaviour rather than character.",
      "Invite the other person's account before concluding.",
    ],
    goal: "Give candid feedback that the other person can act on.",
    target: "constructive candid feedback",
    correction: "Model the observation and let the learner give their own feedback.",
    summary: "You practised giving candid feedback that describes behaviour rather than character.",
    minutes: 8,
    points: [
      {
        form: "what I've observed is",
        claims: [
          "'What I've observed is...' describes behaviour rather than judging the person.",
          "Behaviour can be changed; a character verdict leaves nowhere to go.",
        ],
        ex: ["What I've observed is that deadlines slip.", "What I've observed is a pattern, not one incident."],
      },
      {
        form: "how do you see it",
        claims: [
          "'How do you see it?' invites their account before you conclude.",
          "Asking after the observation but before the conclusion keeps the conversation two-way.",
        ],
        ex: ["How do you see it?", "How do you see it from where you sit?"],
      },
      {
        form: "I'd like us to",
        claims: [
          "'I'd like us to agree on...' proposes a shared next step rather than issuing an instruction.",
          "'Us' makes the follow-up joint rather than imposed.",
        ],
        ex: ["I'd like us to agree on a check-in.", "I'd like us to find a way through this."],
      },
    ],
    ex: [
      fill("What I've ___ is that deadlines slip. (observe)", ["observed"]),
      mcq("Which sentence describes behaviour rather than character?", [
        "What I've observed is that deadlines slip.",
        "You are simply disorganised.",
        "You have never been reliable.",
      ], 0),
      say("I / would like / us / to agree / on a check-in", ["I'd like us to agree on a check-in.", "I would like us to agree on a check-in."]),
    ],
    open: {
      q: "Someone's work has slipped three times. Give feedback describing behaviour, inviting their account and agreeing a step.",
      must: ["what I've observed is", "how do you see it", "I'd like us to"],
      criteria: "The answer describes behaviour, invites the other account and proposes a shared next step.",
      example: "What I've observed is that the last three deadlines were missed. How do you see it? I'd like us to agree on a weekly check-in.",
    },
    success: "The learner describes behaviour, invites an account and proposes a next step.",
    quiz: [
      qmcq("Why describe behaviour rather than character?", [
        "Behaviour can be changed; a verdict leaves nowhere to go.",
        "It is more polite in every culture.",
        "It is grammatically simpler.",
      ], 0),
      qfill("How do you ___ it from where you sit? (see)", ["see"]),
      qmcq("Why say 'I'd like us to'?", [
        "It makes the follow-up joint rather than imposed.",
        "It is more formal.",
        "It avoids the imperative.",
      ], 0),
    ],
    scenes: [
      sc("Ottoline", "someone whose work has slipped", "to understand and respond",
        "A colleague's work has slipped repeatedly.",
        "Give candid, constructive feedback.",
        "You said you wanted a word. Is something wrong?", "guarded"),
      sc("Viktor", "a team member you manage", "to receive actionable feedback",
        "A team member needs honest feedback.",
        "Describe behaviour and agree a step.",
        "I know the last few weeks have been rough. What did you want to discuss?", "open"),
      sc("Selin", "a peer you have no authority over", "to accept feedback from an equal",
        "A peer's behaviour affects your work.",
        "Give feedback without authority.",
        "We are the same level, so I am not sure what you are asking of me?", "resistant"),
      sc("Mr. Achebe", "your tutor", "to practise constructive candour",
        "The seminar is examining feedback language.",
        "Describe behaviour, invite an account, agree a step.",
        "What is the difference between describing behaviour and judging a person?", "probing"),
      sc("Ms. Berger", "the examiner", "to check feedback language",
        "The examiner plays the person receiving feedback.",
        "Give candid, constructive feedback.",
        "You wanted to talk about my work. What is this about?", "defensive"),
    ],
  },

  {
    id: "c1-a-negotiation",
    topic: "reaching an agreement neither side resents",
    objectives: [
      "State what you can accept and where your limit is.",
      "Close the agreement explicitly.",
    ],
    goal: "Reach a deal both sides can live with.",
    target: "closing a negotiation",
    correction: "Model the acceptance or limit and let the learner move the deal on.",
    summary: "You practised reaching an agreement that neither side resents.",
    minutes: 8,
    points: [
      {
        form: "I could live with",
        claims: [
          "'I could live with' accepts something without pretending to like it.",
          "Overstating your enthusiasm invites the other side to push further.",
        ],
        ex: ["I could live with that.", "I could live with the later date."],
      },
      {
        form: "that's my limit",
        claims: [
          "'That's my limit' is only useful if it is true; a bluff that is called costs you the next round.",
          "Stating a limit once, clearly, is stronger than repeating it.",
        ],
        ex: ["That's my limit, honestly.", "That's my limit on the timeline."],
      },
      {
        form: "do we have a deal",
        claims: [
          "'Do we have a deal?' closes explicitly rather than letting the talk drift.",
          "An unclosed negotiation tends to reopen at the worst moment.",
        ],
        ex: ["So do we have a deal?", "Do we have a deal on that basis?"],
      },
    ],
    ex: [
      fill("I could ___ with the later date. (live)", ["live"]),
      mcq("Which sentence accepts without overstating?", [
        "I could live with that.",
        "That is exactly what I wanted.",
        "That is perfect for us.",
      ], 0),
      say("do / we / have / a deal", ["Do we have a deal?", "So do we have a deal?"]),
    ],
    open: {
      q: "Negotiate a deadline and a price. Accept one, mark your limit on the other, and close explicitly.",
      must: ["I could live with", "that's my limit", "do we have a deal"],
      criteria: "The answer accepts one item, marks a limit on the other and closes the agreement.",
      example: "I could live with the later date. On price, that's my limit. On that basis, do we have a deal?",
    },
    success: "The learner accepts, marks a limit and closes explicitly.",
    quiz: [
      qmcq("What is the risk of overstating enthusiasm?", [
        "It invites the other side to push further.",
        "It ends the negotiation.",
        "It is considered rude.",
      ], 0),
      qfill("That's my ___ on the timeline. (limit)", ["limit"]),
      qmcq("Why close explicitly?", [
        "An unclosed negotiation tends to reopen badly.",
        "It is required in formal English.",
        "It shortens the meeting.",
      ], 0),
    ],
    scenes: [
      sc("Mr. Grant", "a counterpart in a real negotiation", "to reach a deal today",
        "A deal must be closed in this conversation.",
        "Accept, limit and close.",
        "We are close. What would it take to finish this today?", "businesslike"),
      sc("Ilaria", "a supplier's negotiator", "to settle terms",
        "Terms are nearly agreed and need closing.",
        "Mark limits and close.",
        "One item left. Where are you on it?", "focused"),
      sc("Sunita", "a market seller", "to agree a price",
        "A price is being haggled.",
        "Accept, limit and close.",
        "I will take it today. What is your best price?", "shrewd"),
      sc("Mr. Wickham", "your tutor", "to practise closing",
        "The seminar is examining negotiation closure.",
        "Accept, limit and close.",
        "Why do unclosed agreements reopen at the worst time?", "probing"),
      sc("Ms. Roux", "the examiner", "to check negotiation language",
        "The examiner negotiates with you.",
        "Accept, limit and close.",
        "I want a shorter timeline and a lower price. Both?", "neutral"),
    ],
  },

  {
    id: "c1-handling-a-crisis-call",
    topic: "staying clear while information is incomplete",
    objectives: [
      "Separate what is known from what is not.",
      "Commit to a next update rather than an answer.",
    ],
    goal: "Speak clearly in a crisis without pretending to know more than you do.",
    target: "communicating under uncertainty",
    correction: "Model the separation of known from unknown and let the learner continue.",
    summary: "You practised staying clear and calm while information was still incomplete.",
    minutes: 8,
    points: [
      {
        form: "here's what we know",
        claims: [
          "'Here's what we know' fences off the confirmed facts from everything else.",
          "The fence is what stops speculation being heard as fact.",
        ],
        ex: ["Here's what we know so far.", "Here's what we know, and what we don't."],
      },
      {
        form: "what we're doing now",
        claims: [
          "'What we're doing now' reports action, which is often what the listener needs most.",
          "Action can be reported honestly even when the cause is still unknown.",
        ],
        ex: ["What we're doing now is checking every site.", "What we're doing now is containing it."],
      },
      {
        form: "I'll update you",
        claims: [
          "'I'll update you at four' commits to a time rather than to an answer.",
          "Missing a promised update can damage trust further, even when there is still no final answer.",
        ],
        ex: ["I'll update you at four.", "I'll update you as soon as we know more."],
      },
    ],
    ex: [
      fill("___ what we know so far. (here is)", ["Here's", "Here is"]),
      mcq("Which sentence commits to a time rather than an answer?", [
        "I'll update you at four.",
        "I'll let you know eventually.",
        "We will have an answer soon.",
      ], 0),
      say("what we / be doing / now / be / containing it", ["What we're doing now is containing it.", "What we are doing now is containing it."]),
    ],
    open: {
      q: "A system has failed and you do not know why. Report what is known, what you are doing and when you will update.",
      must: ["here's what we know", "what we're doing now", "I'll update you"],
      criteria: "The answer separates known from unknown, reports action and commits to an update time.",
      example: "Here's what we know: three sites are down. We don't yet know the cause. What we're doing now is isolating them, and I'll update you at four.",
    },
    success: "The learner separates known from unknown and commits to an update time.",
    quiz: [
      qmcq("Why fence off what is known?", [
        "It stops speculation being heard as fact.",
        "It shortens the call.",
        "It avoids the passive voice.",
      ], 0),
      qfill("I'll ___ you as soon as we know more. (update)", ["update"]),
      qmcq("What can damage trust further during an incident?", [
        "missing a promised update",
        "a long explanation",
        "an early apology",
      ], 0),
    ],
    scenes: [
      sc("Mrs. Petrov", "a client whose service is down", "to know what is happening",
        "A client's service has failed and the cause is unknown.",
        "Report clearly under uncertainty.",
        "Everything is down here. What is going on?", "alarmed"),
      sc("Mr. Reddy", "an executive demanding answers", "to get a straight status",
        "An executive wants answers nobody has yet.",
        "Separate known from unknown.",
        "I need the cause, not a process update. What is it?", "pressing"),
      sc("Kwame", "a journalist calling during an incident", "to get an accurate statement",
        "A journalist is calling during a live incident.",
        "Report only what is confirmed.",
        "What can you confirm at this stage?", "persistent"),
      sc("Professor Berg", "your tutor", "to practise crisis communication",
        "The seminar is examining communication under uncertainty.",
        "Separate known from unknown.",
        "How do you speak clearly when you do not yet know the cause?", "probing"),
      sc("Ms. Kaur", "the examiner", "to check clarity under uncertainty",
        "The examiner presses for answers you do not have.",
        "Report clearly and commit to an update.",
        "Something has gone wrong and nobody will tell me what. Well?", "neutral"),
    ],
  },

  // --- Ünite 9 · Culture and Idiom -------------------------------------------
  {
    id: "c1-idioms-worth-knowing",
    topic: "fixed expressions and where they fit",
    objectives: [
      "Use a few common idioms in the right situation.",
      "Judge when an idiom would be out of place.",
    ],
    goal: "Use idiom naturally rather than decoratively.",
    target: "common fixed expressions",
    correction: "Model the idiom in its natural situation and let the learner use it.",
    summary: "You learned a few common idioms and where they belong.",
    minutes: 8,
    points: [
      {
        form: "it's a long shot",
        claims: [
          "'It's a long shot' means success is unlikely; it is often used when an attempt is still being considered.",
          "It fits a suggestion rather than a flat refusal, because the attempt is still on the table.",
        ],
        ex: ["It's a long shot, but worth asking.", "It's a long shot at this stage."],
      },
      {
        form: "that ship has sailed",
        claims: [
          "'That ship has sailed' means the opportunity has gone for good.",
          "It closes a topic, so it can sound dismissive if the other person is still hoping.",
        ],
        ex: ["That ship has sailed, I'm afraid.", "That ship sailed months ago."],
      },
      {
        form: "off the top of",
        claims: [
          "'Off the top of my head' marks an answer as immediate rather than researched or carefully considered.",
          "Idiom used to decorate rather than to mean something is usually noticeable.",
        ],
        ex: ["Off the top of my head, about thirty.", "Off the top of my head, I'd say Tuesday."],
      },
    ],
    ex: [
      fill("It's a long ___, but worth asking. (shot)", ["shot"]),
      mcq("Which idiom means the opportunity has gone?", [
        "That ship has sailed.",
        "It's a long shot.",
        "Off the top of my head.",
      ], 0),
      say("off the top of / my head / about thirty", ["Off the top of my head, about thirty."]),
    ],
    open: {
      q: "Answer these three: Can you still get a place on the course? Can last year's cancelled deal be revived? Roughly how many people came?",
      must: ["it's a long shot", "that ship has sailed", "off the top of"],
      criteria: "The answer uses each idiom in the situation that fits it.",
      example: "It's a long shot, but I'll ask. That ship has sailed, I'm afraid. Off the top of my head, about thirty came.",
    },
    success: "The learner uses at least two idioms in fitting situations.",
    quiz: [
      qmcq("What does 'it's a long shot' imply?", [
        "success is unlikely but an attempt is being considered",
        "the attempt has already been refused",
        "success is certain",
      ], 0),
      qfill("Off the top of my ___, I'd say Tuesday. (head)", ["head"]),
      qmcq("When can 'that ship has sailed' sound dismissive?", [
        "when the other person is still hoping",
        "when the topic is formal",
        "when it opens a conversation",
      ], 0),
    ],
    scenes: [
      sc("Beatriz", "a friend asking for a favour", "to hear whether it is possible",
        "A friend is asking for something unlikely.",
        "Use idiom where it fits.",
        "Any chance you could still get me a ticket?", "hopeful"),
      sc("Andres", "a colleague raising an old idea", "to learn the moment has passed",
        "A colleague is reviving an idea whose moment has gone.",
        "Close the topic without dismissiveness.",
        "Could we not revisit the proposal from last spring?", "persistent"),
      sc("Rafael", "someone asking for numbers", "to get a rough figure",
        "Someone wants a figure you have not checked.",
        "Flag the answer as unchecked.",
        "Roughly how many did we get last time?", "casual"),
      sc("Mrs. Nowak", "your tutor", "to practise idiom in context",
        "The seminar is examining idiomatic usage.",
        "Use idiom where it fits.",
        "When does an idiom help, and when does it just decorate?", "probing"),
      sc("Mr. Delacroix", "the examiner", "to check idiomatic range",
        "The examiner asks a series of quick questions.",
        "Use idiom naturally.",
        "Could you still get a place on the course this year?", "neutral"),
    ],
  },

  {
    id: "c1-words-that-go-together",
    topic: "which words habitually pair",
    objectives: [
      "Choose the collocation a native speaker would expect.",
      "Recognise that grammatical alternatives can still sound wrong.",
    ],
    goal: "Choose word pairings that sound native rather than merely correct.",
    target: "collocation",
    correction: "Give the expected pairing and let the learner use it.",
    summary: "You learned that words pair by habit, not only by grammar.",
    minutes: 9,
    points: [
      {
        form: "heavy rain",
        claims: [
          "'Heavy rain' is the usual pairing; 'strong rain' is grammatical but unidiomatic.",
          "Collocation is a matter of habit, so it has to be learned pair by pair.",
        ],
        ex: ["We had heavy rain all week.", "There was heavy traffic on the motorway."],
      },
      {
        form: "strong argument",
        claims: [
          "'Strong' pairs with argument, opinion and coffee; 'heavy' does not.",
          "The same adjective changes partner depending on the noun.",
        ],
        ex: ["She made a strong argument.", "He has strong opinions about it."],
      },
      {
        form: "deeply grateful",
        claims: [
          "'Deeply' pairs with grateful, concerned and regret rather than with ordinary adjectives.",
          "'Very grateful' is also correct; 'deeply' raises the register.",
        ],
        ex: ["I'm deeply grateful for your help.", "We are deeply concerned about it."],
      },
    ],
    ex: [
      fill("We had ___ rain all week. (heavy or strong)", ["heavy"]),
      mcq("Which pairing is idiomatic?", [
        "a strong argument",
        "a heavy argument",
        "a deep argument",
      ], 0),
      fill("I'm ___ grateful for your help. (deep)", ["deeply"]),
      say("there / be / heavy traffic / on the motorway", ["There was heavy traffic on the motorway."]),
    ],
    open: {
      q: "Describe bad weather, a convincing case and your thanks, choosing the pairing a native speaker expects.",
      must: ["heavy rain", "strong argument", "deeply grateful"],
      criteria: "The answer chooses idiomatic collocations rather than merely grammatical ones.",
      example: "There was heavy rain all week. She made a strong argument for delaying, and I'm deeply grateful she did.",
    },
    success: "The learner chooses idiomatic collocations at least twice.",
    quiz: [
      qmcq("Which pairing is idiomatic?", [
        "heavy traffic",
        "strong traffic",
        "deep traffic",
      ], 0),
      qfill("We are ___ concerned about the delay. (deep)", ["deeply"]),
      qmcq("Why must collocation be learned pair by pair?", [
        "It is a matter of habit rather than rule.",
        "The grammar changes with each noun.",
        "The words change meaning entirely.",
      ], 0),
    ],
    scenes: [
      sc("Ilse", "a friend also learning English", "to compare which pairings sound right",
        "Two learners are comparing word choices.",
        "Choose the expected pairings.",
        "I said 'strong rain' and everyone laughed. What should I have said?", "puzzled"),
      sc("Tomasz", "a colleague proofreading your text", "to make a text sound native",
        "A text is grammatical but reads oddly.",
        "Correct the pairings.",
        "Nothing here is wrong, but it does not read like English. Can you see why?", "helpful"),
      sc("Aiko", "an editor reviewing your draft", "to make wording idiomatic",
        "A draft needs idiomatic wording.",
        "Choose native pairings.",
        "These adjectives are all slightly off. Shall we go through them?", "precise"),
      sc("Professor Novak", "your tutor", "to practise collocation",
        "The seminar is examining collocation.",
        "Choose expected pairings.",
        "Why is 'strong rain' wrong when nothing in the grammar forbids it?", "probing"),
      sc("Ms. Alvarez", "the examiner", "to check collocational range",
        "The examiner asks you to describe things.",
        "Choose idiomatic pairings.",
        "Could you describe last winter's weather to me?", "neutral"),
    ],
  },

  {
    id: "c1-humour-and-irony",
    topic: "signalling that you do not mean it literally",
    objectives: [
      "Signal irony so it is not taken at face value.",
      "Recognise the risk when the signal is missed.",
    ],
    goal: "Use irony without being misunderstood.",
    target: "signalling irony",
    correction: "Model the ironic line with its signal and let the learner try one.",
    summary: "You learned to signal irony and to notice when the signal may be missed.",
    minutes: 8,
    points: [
      {
        form: "well that went well",
        claims: [
          "'Well, that went well' says the opposite of its words, carried by tone.",
          "In writing the tone is missing, so irony there needs a clearer marker.",
        ],
        ex: ["Well, that went well.", "Well, that could have gone better."],
      },
      {
        form: "just what I needed",
        claims: [
          "'Just what I needed' is ironic when the thing is plainly unwelcome.",
          "The situation carries the irony, so it works only when the situation is obvious.",
        ],
        ex: ["Rain again — just what I needed.", "Another meeting, just what I needed."],
      },
      {
        form: "no pressure then",
        claims: [
          "'No pressure then' names an obvious pressure by denying it.",
          "If irony has to be explained, it has failed to communicate in that context.",
        ],
        ex: ["Due tomorrow? No pressure then.", "Everyone is watching. No pressure then."],
      },
    ],
    ex: [
      fill("Well, that ___ well. (go)", ["went"]),
      mcq("Which line is ironic only if the situation is obvious?", [
        "Another meeting, just what I needed.",
        "I would prefer not to attend.",
        "This meeting is unnecessary.",
      ], 0),
      say("due tomorrow / no pressure then", ["Due tomorrow? No pressure then."]),
    ],
    open: {
      q: "React ironically to three unwelcome pieces of news, and say when irony would be risky.",
      must: ["well that went well", "just what I needed", "no pressure then"],
      criteria: "The answer uses irony with a clear signal and identifies when it would be risky.",
      example: "Well, that went well. Rain again, just what I needed. Due tomorrow? No pressure then. I wouldn't write any of these in an email — without tone they read literally.",
    },
    success: "The learner signals irony clearly and judges when it is risky.",
    quiz: [
      qmcq("Why is irony riskier in writing?", [
        "The tone that carries it is missing.",
        "The grammar changes.",
        "It cannot be written down.",
      ], 0),
      qfill("Everyone is watching. No ___ then. (pressure)", ["pressure"]),
      qmcq("What is true of irony that has to be explained?", [
        "It has failed to communicate in that context.",
        "It becomes funnier.",
        "It becomes more formal.",
      ], 0),
    ],
    scenes: [
      sc("Yusuf", "a friend having a bad day", "to share the absurdity",
        "A series of small disasters has piled up.",
        "React ironically.",
        "The car would not start, and then it rained. Perfect, isn't it?", "wry"),
      sc("Ottoline", "a colleague after a bad meeting", "to share a reaction quietly",
        "A meeting went badly and you are both leaving it.",
        "React ironically but discreetly.",
        "Well. That was something. What did you make of it?", "dry"),
      sc("Noor", "a fellow traveller after a delay", "to keep spirits up",
        "A third delay has been announced.",
        "React ironically.",
        "Delayed again. Three hours this time. Thoughts?", "resigned"),
      sc("Mr. Halvorsen", "your tutor", "to practise irony",
        "The seminar is examining irony and its risks.",
        "Signal irony clearly.",
        "When does irony stop being funny and start being confusing?", "probing"),
      sc("Ms. Cardoso", "the examiner", "to check control of irony",
        "The examiner reports something unwelcome.",
        "React ironically and appropriately.",
        "Your exam has been moved to tomorrow morning. Reaction?", "neutral"),
    ],
  },

  {
    id: "c1-what-not-to-say",
    topic: "expressions that land badly",
    objectives: [
      "Recognise phrasing that causes offence unintentionally.",
      "Offer a safer alternative for the same meaning.",
    ],
    goal: "Say the same thing without the phrasing that lands badly.",
    target: "avoiding phrasing that offends",
    correction: "Offer the safer alternative and let the learner rephrase.",
    summary: "You learned which phrasings land badly and how to say the same thing safely.",
    minutes: 8,
    points: [
      {
        form: "I'd avoid saying",
        claims: [
          "'I'd avoid saying that' flags a phrasing without accusing the speaker of bad intent.",
          "Most phrasing that offends is chosen without any intention to offend.",
        ],
        ex: ["I'd avoid saying 'you people'.", "I'd avoid saying that in a first meeting."],
      },
      {
        form: "that could be taken",
        claims: [
          "'That could be taken as...' names the risk rather than the intention.",
          "Naming the reading rather than the motive keeps the correction usable.",
        ],
        ex: ["That could be taken as a criticism.", "That could be taken the wrong way."],
      },
      {
        form: "safer to say",
        claims: [
          "'It's safer to say...' offers the replacement rather than only the warning.",
          "A warning without an alternative tends to make the speaker say nothing at all.",
        ],
        ex: ["It's safer to say 'I'm not sure I follow'.", "It's safer to say it differently."],
      },
    ],
    ex: [
      fill("I'd ___ saying that in a first meeting. (avoid)", ["avoid"]),
      mcq("Which sentence names the risk rather than the intention?", [
        "That could be taken as a criticism.",
        "You meant that as a criticism.",
        "You were trying to be critical.",
      ], 0),
      say("it / be safer / to say / it differently", ["It's safer to say it differently.", "It is safer to say it differently."]),
    ],
    open: {
      q: "A colleague wants to write 'Your explanation is confusing' to a client. Flag the risk and offer a safer alternative.",
      must: ["I'd avoid saying", "that could be taken", "safer to say"],
      criteria: "The answer flags the phrasing without imputing intent and offers a replacement.",
      example: "I'd avoid saying 'Your explanation is confusing' — that could be taken as a personal criticism. It's safer to say 'Could you give a little more detail on this point?'",
    },
    success: "The learner flags the phrasing and offers a usable alternative.",
    quiz: [
      qmcq("Why name the reading rather than the motive?", [
        "It keeps the correction usable.",
        "It is grammatically required.",
        "It shortens the sentence.",
      ], 0),
      qfill("That could be ___ the wrong way. (take)", ["taken"]),
      qmcq("What happens with a warning and no alternative?", [
        "The speaker tends to say nothing at all.",
        "The speaker repeats the phrase.",
        "The correction becomes formal.",
      ], 0),
    ],
    scenes: [
      sc("Bruna", "a colleague about to send an email", "to avoid a misstep with a client",
        "An email contains phrasing that will land badly.",
        "Flag it and offer an alternative.",
        "I am about to send this. Does it read all right to you?", "hurried"),
      sc("Owen", "a team member new to the culture", "to learn what lands badly here",
        "A new colleague is unfamiliar with local norms.",
        "Flag the phrasing kindly.",
        "I said something and the room went quiet. What did I do?", "worried"),
      sc("Fatima", "a friend preparing for an interview", "to avoid a phrase that will cost them",
        "A friend is rehearsing and uses a risky phrase.",
        "Flag it and replace it.",
        "Be honest with me — how did that answer sound?", "nervous"),
      sc("Mr. Tremblay", "your tutor", "to practise flagging phrasing",
        "The seminar is examining pragmatic failure.",
        "Flag and replace phrasing.",
        "How do you tell someone a phrase is risky without accusing them?", "probing"),
      sc("Ms. Petrenko", "the examiner", "to check pragmatic awareness",
        "The examiner uses a risky phrase deliberately.",
        "Flag it and offer an alternative.",
        "I would say your generation simply does not want to work. Fair?", "neutral"),
    ],
  },

  {
    id: "c1-reading-the-room",
    topic: "adjusting to the company you are in",
    objectives: [
      "Judge when a subject or register does not fit the room.",
      "Adjust mid-conversation, explaining the change only as far as the room allows.",
    ],
    goal: "Adjust how you speak to the room you are actually in.",
    target: "reading and adjusting to the room",
    correction: "Model the adjustment and let the learner change course.",
    summary: "You practised judging what fits a room and changing course when it does not.",
    minutes: 8,
    points: [
      {
        form: "maybe not here",
        claims: [
          "'Maybe not here' postpones a subject rather than dropping it.",
          "Postponing signals judgement about the setting, not about the subject.",
        ],
        ex: ["Maybe not here — I'll tell you after.", "Maybe not here, with this crowd."],
      },
      {
        form: "I'll keep it short",
        claims: [
          "'I'll keep it short' adjusts length when the room's attention is thin.",
          "Saying it and then talking at length is worse than not saying it.",
        ],
        ex: ["I'll keep it short.", "I'll keep it short, since we're nearly done."],
      },
      {
        form: "reading the mood",
        claims: [
          "'Reading the mood' names the skill and can be used to explain a change of course.",
          "Naming it out loud is itself a choice: sometimes the adjustment should be invisible.",
        ],
        ex: ["Reading the mood, I'll leave that there.", "Reading the mood, now is not the time."],
      },
    ],
    ex: [
      fill("Maybe not ___ — I'll tell you after. (here)", ["here"]),
      mcq("Which sentence postpones rather than drops a subject?", [
        "Maybe not here — I'll tell you after.",
        "Forget I mentioned it at all.",
        "That subject is closed permanently.",
      ], 0),
      say("reading the mood / I / will leave / that there", ["Reading the mood, I'll leave that there.", "Reading the mood, I will leave that there."]),
    ],
    open: {
      q: "You start a subject and realise the room is wrong for it. Change course, explaining the change only as far as the room allows.",
      must: ["maybe not here", "I'll keep it short", "reading the mood"],
      criteria: "The answer changes course mid-conversation and keeps any explanation of the change brief.",
      example: "Reading the mood, I think we should leave that for later. Maybe not here — I'll tell you afterwards. I'll keep it short for now.",
    },
    success: "The learner changes course and keeps any explanation of it brief.",
    quiz: [
      qmcq("What does postponing signal?", [
        "judgement about the setting, not the subject",
        "that the subject is forbidden",
        "that the speaker has finished",
      ], 0),
      qfill("I'll keep it ___, since we're nearly done. (short)", ["short"]),
      qmcq("When should the adjustment be invisible?", [
        "when naming it would draw attention to the problem",
        "whenever the room is formal",
        "whenever more than three people are present",
      ], 0),
    ],
    scenes: [
      sc("Kwabena", "a friend in mixed company", "to avoid an awkward moment",
        "You have started a subject that does not suit the company.",
        "Adjust course smoothly.",
        "Go on, you were saying something about the money?", "oblivious"),
      sc("Simone", "a colleague at a client dinner", "to keep the evening on track",
        "A client dinner is not the place for an internal issue.",
        "Postpone without awkwardness.",
        "You wanted to raise something about the contract?", "alert"),
      sc("Emil", "a host at a family gathering", "to keep the gathering comfortable",
        "A family gathering is not the place for a difficult topic.",
        "Adjust course.",
        "You two look like you are having a serious conversation. Everything all right?", "watchful"),
      sc("Mrs. Aguilar", "your tutor", "to practise situational judgement",
        "The seminar is examining pragmatic judgement.",
        "Adjust course convincingly.",
        "How do you drop a subject without making the drop obvious?", "probing"),
      sc("Mr. Nakamura", "the examiner", "to check situational judgement",
        "The examiner raises something inappropriate for the setting.",
        "Adjust course.",
        "Tell me, what do you actually earn in your job?", "neutral"),
    ],
  },

  {
    id: "c1-talking-across-cultures",
    topic: "when unspoken assumptions differ",
    objectives: [
      "Name your own assumption rather than presenting it as normal.",
      "Ask how something works instead of guessing.",
    ],
    goal: "Handle a conversation where the unspoken rules differ.",
    target: "navigating differing assumptions",
    correction: "Model the assumption-naming move and let the learner ask rather than guess.",
    summary: "You practised naming your own assumptions instead of treating them as normal.",
    minutes: 8,
    points: [
      {
        form: "where I'm from",
        claims: [
          "'Where I'm from' marks a practice as local rather than universal.",
          "It presents your norm as one option among several.",
        ],
        ex: ["Where I'm from, you would call first.", "Where I'm from, that would be unusual."],
      },
      {
        form: "how does that work",
        claims: [
          "'How does that work here?' asks rather than guesses.",
          "Asking directly is usually received better than guessing wrong.",
        ],
        ex: ["How does that work here?", "How does that usually work?"],
      },
      {
        form: "I don't want to assume",
        claims: [
          "'I don't want to assume' flags that you know your default may not apply.",
          "It invites correction before the mistake rather than after it.",
        ],
        ex: ["I don't want to assume anything.", "I don't want to assume it is the same."],
      },
    ],
    ex: [
      fill("___ I'm from, you would call first. (where)", ["Where"]),
      mcq("Which sentence asks rather than guesses?", [
        "How does that work here?",
        "I assume it works the same way.",
        "It must be the same everywhere.",
      ], 0),
      say("I / not want / to assume / anything", ["I don't want to assume anything.", "I do not want to assume anything."]),
    ],
    open: {
      q: "You are unsure of the local convention for something. Name your own assumption and ask instead of guessing.",
      must: ["where I'm from", "how does that work", "I don't want to assume"],
      criteria: "The answer names its own assumption as local and asks rather than guessing.",
      example: "Where I'm from you would call first. I don't want to assume it's the same — how does that work here?",
    },
    success: "The learner names an assumption as local and asks rather than guessing.",
    quiz: [
      qmcq("What does 'where I'm from' do?", [
        "marks a practice as local rather than universal",
        "claims the practice is correct",
        "asks a question",
      ], 0),
      qfill("I don't want to ___ it is the same. (assume)", ["assume"]),
      qmcq("Why ask rather than guess?", [
        "Asking is usually received better than guessing wrong.",
        "It is grammatically simpler.",
        "It takes less time.",
      ], 0),
    ],
    scenes: [
      sc("Aditi", "a new colleague from another country", "to work out the local conventions",
        "Two colleagues from different countries are working out norms.",
        "Name your assumptions and ask.",
        "I keep getting this slightly wrong. Is there a rule I am missing?", "open"),
      sc("Ferran", "a host explaining local practice", "to help you avoid a misstep",
        "A host is explaining how things are done locally.",
        "Ask rather than assume.",
        "People here do this differently. Do you want me to explain?", "helpful"),
      sc("Chiara", "a client in another market", "to establish how business is done",
        "Business norms differ between the two markets.",
        "Name your assumption and ask.",
        "We may do things differently from what you are used to. Shall we compare?", "professional"),
      sc("Professor Iversen", "your tutor", "to practise intercultural pragmatics",
        "The seminar is examining differing assumptions.",
        "Name assumptions and ask.",
        "What is the cost of treating your own norm as the default?", "probing"),
      sc("Mr. Sasaki", "the examiner", "to check intercultural awareness",
        "The examiner describes an unfamiliar convention.",
        "Name your assumption and ask.",
        "Here it would be rude to arrive on time. How would you handle that?", "neutral"),
    ],
  },

  // --- Ünite 10 · Extended Discussion ----------------------------------------
  {
    id: "c1-sustaining-a-long-turn",
    topic: "holding the floor coherently",
    objectives: [
      "Announce the shape of a long answer before giving it.",
      "Return to your thread after a digression.",
    ],
    goal: "Speak at length without losing your listener or your thread.",
    target: "sustaining a long turn",
    correction: "Model the structural marker and let the learner continue the turn.",
    summary: "You learned to hold the floor coherently for more than a few sentences.",
    minutes: 8,
    points: [
      {
        form: "there are three things",
        claims: [
          "Announcing a number tells the listener how long the turn will be.",
          "It also commits you: three announced and two delivered is noticeable.",
        ],
        ex: ["There are three things worth saying.", "There are three reasons for that."],
      },
      {
        form: "before I get to",
        claims: [
          "'Before I get to that' marks a digression as deliberate rather than accidental.",
          "The listener will wait through a digression they know is temporary.",
        ],
        ex: ["Before I get to the cost, one point on scope.", "Before I get to that, some background."],
      },
      {
        form: "coming back to my",
        claims: [
          "'Coming back to my second point' returns to the announced thread.",
          "A digression you never return from reads as losing your place.",
        ],
        ex: ["Coming back to my second point.", "Coming back to my earlier point about cost."],
      },
    ],
    ex: [
      fill("There are ___ things worth saying here. (3)", ["three"]),
      mcq("Which phrase marks a digression as deliberate?", [
        "Before I get to that, some background.",
        "Anyway, where was I?",
        "That reminds me of something else.",
      ], 0),
      say("coming back / to my / second point", ["Coming back to my second point."]),
    ],
    open: {
      q: "How has technology changed the way people work? Answer at length: announce three points, digress once deliberately, and return to your thread.",
      must: ["there are three things", "before I get to", "coming back to my"],
      criteria: "The answer announces its shape, digresses deliberately and returns to the thread.",
      example: "There are three things worth considering: flexibility, productivity and isolation. Flexibility first — remote work has widened access to many jobs. Before I get to productivity, some background: these tools spread before the pandemic. Coming back to my second point, the gains have to outweigh the coordination cost.",
    },
    success: "The learner announces a shape, digresses deliberately and returns.",
    quiz: [
      qmcq("What does announcing a number commit you to?", [
        "delivering that many points",
        "speaking for a set time",
        "using formal register",
      ], 0),
      qfill("___ I get to the cost, one point on scope. (before)", ["Before"]),
      qmcq("What does an unreturned digression read as?", [
        "losing your place",
        "a formal choice",
        "a change of topic",
      ], 0),
    ],
    scenes: [
      sc("Ravenna", "a friend who asked a big question", "to get a full answer without getting lost",
        "A friend has asked something that needs a long answer.",
        "Announce the shape and hold the thread.",
        "That is a huge question, I know. Where do you even start?", "curious"),
      sc("Idris", "a panel expecting a full answer", "to hear a structured long answer",
        "A panel has asked a broad question.",
        "Sustain the turn coherently.",
        "Take as long as you need. How do you see the whole picture?", "attentive"),
      sc("Solveig", "an interviewer on a podcast", "to get a coherent extended answer",
        "A recorded interview needs a coherent long answer.",
        "Announce the shape and hold it.",
        "We have plenty of time. Talk me through it properly?", "relaxed"),
      sc("Professor Adeyemi", "your tutor", "to practise sustained turns",
        "The seminar is examining extended speech.",
        "Announce and hold the thread.",
        "How do you keep a listener with you for three minutes?", "probing"),
      sc("Ms. Whitlock", "the examiner", "to check sustained speech",
        "The examiner asks a broad question.",
        "Sustain a long coherent turn.",
        "Could you tell me at length how your field has changed?", "neutral"),
    ],
  },

  {
    id: "c1-signposting-where-youre-going",
    topic: "mapping a long answer",
    objectives: [
      "Map the sections of a long answer at the start.",
      "Mark the final section explicitly.",
    ],
    goal: "Let the listener follow a long answer without effort.",
    target: "signposting a long answer",
    correction: "Model the signpost and let the learner move to the next section.",
    summary: "You learned to map a long answer so the listener can follow it.",
    minutes: 8,
    points: [
      {
        form: "I'll start with",
        claims: [
          "'I'll start with' names the first section, which sets the listener's expectation.",
          "Naming the order also stops you rearranging it halfway through.",
        ],
        ex: ["I'll start with the background.", "I'll start with what changed."],
      },
      {
        form: "then I'll turn to",
        claims: [
          "'Then I'll turn to' names the next section before you reach it.",
          "Announcing sections in advance is what separates a map from a list.",
        ],
        ex: ["Then I'll turn to the consequences.", "Then I'll turn to what it means now."],
      },
      {
        form: "finally I want to",
        claims: [
          "'Finally I want to' marks the last section, so the listener knows the end is coming.",
          "Using 'finally' and then adding a further section costs the listener's trust.",
        ],
        ex: ["Finally I want to say something about cost.", "Finally I want to come back to the question."],
      },
    ],
    ex: [
      fill("I'll ___ with the background. (start)", ["start"]),
      mcq("What separates a map from a list?", [
        "announcing sections before you reach them",
        "using longer sentences",
        "speaking more slowly",
      ], 0),
      say("finally / I / want to / come back / to the question", ["Finally I want to come back to the question."]),
    ],
    open: {
      q: "Map a three-part answer to a broad question before you give it, and mark the final part.",
      must: ["I'll start with", "then I'll turn to", "finally I want to"],
      criteria: "The answer maps its sections in advance and marks the final one.",
      example: "I'll start with the background, then I'll turn to what changed, and finally I want to say what it means now.",
    },
    success: "The learner maps the sections in advance and marks the last one.",
    quiz: [
      qmcq("What does naming the order prevent?", [
        "rearranging it halfway through",
        "speaking for too long",
        "using informal register",
      ], 0),
      qfill("Then I'll ___ to the consequences. (turn)", ["turn"]),
      qmcq("What costs the listener's trust?", [
        "saying 'finally' and then adding another section",
        "mapping the answer in advance",
        "marking the final section",
      ], 0),
    ],
    scenes: [
      sc("Marek", "a friend asking a complicated question", "to follow a long answer easily",
        "A friend has asked something with several parts.",
        "Map the answer before giving it.",
        "This is going to be a long answer, isn't it? Set it up for me?", "patient"),
      sc("Renata", "a colleague in a briefing", "to follow a briefing without notes",
        "A briefing must be followed without notes.",
        "Map the sections.",
        "I have no paper. Can you make it easy to follow?", "practical"),
      sc("Kofi", "an audience member at a talk", "to follow an unfamiliar subject",
        "A talk covers an unfamiliar subject.",
        "Map the answer clearly.",
        "I know nothing about this field. Where are you taking us?", "attentive"),
      sc("Mrs. Nowak", "your tutor", "to practise signposting",
        "The seminar is examining discourse mapping.",
        "Map and mark the sections.",
        "How does mapping an answer change how it is heard?", "probing"),
      sc("Mr. Delacroix", "the examiner", "to check discourse organisation",
        "The examiner asks a broad question.",
        "Map the answer in advance.",
        "Could you set out how you will answer before you answer?", "neutral"),
    ],
  },

  {
    id: "c1-an-abstract-question",
    topic: "a question with no clean answer",
    objectives: [
      "Define the terms before answering.",
      "Distinguish two senses of the question.",
    ],
    goal: "Discuss a question that has no single answer without evading it.",
    target: "handling abstract questions",
    correction: "Model the defining move and let the learner take the question apart.",
    summary: "You practised taking apart a question that has no clean answer.",
    minutes: 8,
    points: [
      {
        form: "it depends what we mean",
        claims: [
          "'It depends what we mean by X' defines before answering rather than evading.",
          "Said without then answering, it reads as evasion; said and followed, it is precision.",
        ],
        ex: ["It depends what we mean by success.", "It depends what we mean by fair."],
      },
      {
        form: "I'd distinguish between",
        claims: [
          "'I'd distinguish between X and Y' separates two senses that were being conflated.",
          "Many abstract questions become easier to discuss once the different senses are separated.",
        ],
        ex: ["I'd distinguish between cause and blame.", "I'd distinguish between two senses of it."],
      },
      {
        form: "there's no clean answer",
        claims: [
          "'There's no clean answer' admits the limit honestly rather than inventing one.",
          "Admitting it before giving your best answer is more convincing than after.",
        ],
        ex: ["There's no clean answer, but here is mine.", "There's no clean answer to that."],
      },
    ],
    ex: [
      fill("It ___ what we mean by success. (depend)", ["depends"]),
      mcq("Which sentence separates two conflated senses?", [
        "I'd distinguish between cause and blame.",
        "That is a very difficult question.",
        "Nobody can answer that properly.",
      ], 0),
      say("there be / no clean answer / but here be / mine", ["There's no clean answer, but here is mine.", "There is no clean answer, but here is mine."]),
    ],
    open: {
      q: "Answer this: is it better to be respected or liked? Define the terms, distinguish the senses, then answer.",
      must: ["it depends what we mean", "I'd distinguish between", "there's no clean answer"],
      criteria: "The answer defines the terms, separates the senses and still gives a position.",
      example: "It depends what we mean by respected. I'd distinguish between being feared, being valued for your judgement, and being liked. There's no clean answer, but if respect means genuine regard I'd choose respect; if it means deference, I'd rather be liked.",
    },
    success: "The learner defines, distinguishes and still gives a position.",
    quiz: [
      qmcq("When does 'it depends what we mean' read as evasion?", [
        "when it is not followed by an answer",
        "when the question is abstract",
        "when it opens the answer",
      ], 0),
      qfill("I'd ___ between two senses of it. (distinguish)", ["distinguish"]),
      qmcq("When is admitting there is no clean answer most convincing?", [
        "before giving your best answer",
        "after refusing to answer",
        "instead of answering",
      ], 0),
    ],
    scenes: [
      sc("Zofia", "a friend asking a big question late at night", "to have a real conversation about it",
        "A late conversation has turned to an abstract question.",
        "Take the question apart and answer it.",
        "Honestly, would you rather be respected or liked?", "thoughtful"),
      sc("Ravi", "a colleague in a values discussion", "to reach something usable",
        "A values discussion at work risks becoming vague.",
        "Define, distinguish and answer.",
        "We keep saying 'fairness' and meaning different things. What do you mean by it?", "rigorous"),
      sc("Elif", "someone met while travelling", "to have a genuine philosophical exchange",
        "A long journey has led to a real exchange.",
        "Take the question apart.",
        "I am serious about this: is anyone ever really free?", "earnest"),
      sc("Professor Kimura", "your tutor", "to practise abstract discussion",
        "The seminar is examining conceptual questions.",
        "Define, distinguish and commit.",
        "How do you answer a question whose terms are not agreed?", "probing"),
      sc("Ms. Bianchi", "the examiner", "to check abstract discussion",
        "The examiner asks a question with no clean answer.",
        "Define, distinguish and answer.",
        "Is progress always an improvement?", "neutral"),
    ],
  },

  {
    id: "c1-a-subject-you-know-deeply",
    topic: "going into real depth",
    objectives: [
      "Say what non-specialists usually get wrong.",
      "Distinguish your own experience from established fact.",
    ],
    goal: "Talk about something you know well without either simplifying or showing off.",
    target: "speaking with expertise",
    correction: "Model the depth marker and let the learner go further.",
    summary: "You practised going into real depth on something you know well.",
    minutes: 8,
    points: [
      {
        form: "what most people miss",
        claims: [
          "'What most people miss is...' introduces an overlooked aspect, though without context it can sound superior.",
          "Naming the aspect rather than the people keeps it from becoming a verdict on the listener.",
        ],
        ex: ["What most people miss is how slow it is.", "What most people miss is the cost of maintenance."],
      },
      {
        form: "in my experience",
        claims: [
          "'In my experience' marks a claim as personal rather than established.",
          "Presenting experience as fact is the fastest way to lose a specialist audience.",
        ],
        ex: ["In my experience, it never works first time.", "In my experience, that is the exception."],
      },
      {
        form: "what's interesting is",
        claims: [
          "'What's interesting is...' selects one aspect rather than covering everything.",
          "Selecting is what separates depth from a lecture.",
        ],
        ex: ["What's interesting is why it fails.", "What's interesting is the exception."],
      },
    ],
    ex: [
      fill("What most people ___ is how slow it is. (miss)", ["miss"]),
      mcq("Which sentence marks a claim as personal?", [
        "In my experience, it never works first time.",
        "It never works first time.",
        "Everyone knows it never works.",
      ], 0),
      say("what be interesting / be / why it / fail", ["What's interesting is why it fails.", "What is interesting is why it fails."]),
    ],
    open: {
      q: "Talk about something you know well: say what outsiders miss, and mark which claims are your own experience.",
      must: ["what most people miss", "in my experience", "what's interesting is"],
      criteria: "The answer offers depth and separates personal experience from established fact.",
      example: "What most people miss about a migration is that cleaning the data takes longer than moving it. In my experience the technical move is rarely the hard part; ownership is. What's interesting is how small ambiguities about responsibility become long delays at scale.",
    },
    success: "The learner offers depth and separates experience from established fact.",
    quiz: [
      qmcq("Why mark a claim as personal?", [
        "Presenting experience as fact loses a specialist audience.",
        "It is grammatically required.",
        "It shortens the claim.",
      ], 0),
      qfill("What most people ___ is the cost of maintenance. (miss)", ["miss"]),
      qmcq("What separates depth from a lecture?", [
        "selecting one aspect rather than covering everything",
        "speaking for longer",
        "using technical vocabulary",
      ], 0),
    ],
    scenes: [
      sc("Rashid", "a friend outside your field", "to understand what you actually do",
        "A friend has never understood your work.",
        "Go into depth without simplifying it away.",
        "I have never really understood what you do. Explain it properly?", "genuine"),
      sc("Halima", "a colleague from another department", "to grasp why something is hard",
        "Another department underestimates the difficulty.",
        "Explain what they are missing.",
        "It cannot be that complicated, surely?", "sceptical"),
      sc("Anders", "an interviewer on a specialist podcast", "to draw out real depth",
        "A specialist interview invites depth.",
        "Go deep and mark your claims.",
        "Our listeners know the basics. Take us further?", "informed"),
      sc("Professor Osei", "your tutor", "to practise expert register",
        "The seminar is examining expert discourse.",
        "Offer depth without showing off.",
        "How do you go deep without either simplifying or lecturing?", "probing"),
      sc("Ms. Reyes", "the examiner", "to check depth of discussion",
        "The examiner asks about your specialism.",
        "Go into real depth.",
        "Could you tell me about something you know better than most people?", "neutral"),
    ],
  },

  {
    id: "c1-a-subject-you-know-nothing-about",
    topic: "coping when you are out of your depth",
    objectives: [
      "Admit the limit of your knowledge without withdrawing.",
      "Contribute from partial knowledge honestly.",
    ],
    goal: "Stay in a conversation about something you do not know.",
    target: "operating beyond your knowledge",
    correction: "Model the honest admission and let the learner keep contributing.",
    summary: "You practised staying in a conversation about something you do not know.",
    minutes: 8,
    points: [
      {
        form: "I'm out of my depth",
        claims: [
          "'I'm out of my depth here' admits the limit without leaving the conversation.",
          "Admitting it early is usually cheaper than being found out later.",
        ],
        ex: ["I'm out of my depth here, honestly.", "I'm out of my depth on the technical side."],
      },
      {
        form: "correct me if",
        claims: [
          "'Correct me if I'm wrong' invites correction before you commit to a claim.",
          "It lets you contribute a guess without asserting it.",
        ],
        ex: ["Correct me if I'm wrong, but aren't they the same?", "Correct me if I've misunderstood."],
      },
      {
        form: "from what little I",
        claims: [
          "'From what little I know' scales the claim to the knowledge behind it.",
          "A scaled claim can still be useful; an unscaled guess is a liability.",
        ],
        ex: ["From what little I know, it is a trade-off.", "From what little I understand, it is slower."],
      },
    ],
    ex: [
      fill("I'm out of my ___ here, honestly. (depth)", ["depth"]),
      mcq("Which sentence invites correction before committing?", [
        "Correct me if I'm wrong, but aren't they the same?",
        "It is obviously the same thing.",
        "I am certain they are identical.",
      ], 0),
      say("from what little / I / know / it be / a trade-off", ["From what little I know, it is a trade-off."]),
    ],
    open: {
      q: "You are in a technical discussion you do not follow. Admit the limit and still contribute something useful.",
      must: ["I'm out of my depth", "correct me if", "from what little I"],
      criteria: "The answer admits the limit and still contributes a scaled, honest claim.",
      example: "I'm out of my depth on the engineering side. Correct me if I'm wrong, but from what little I know, energy use is the main trade-off in desalination.",
    },
    success: "The learner admits the limit and still contributes usefully.",
    quiz: [
      qmcq("Why admit the limit early?", [
        "It is cheaper than being found out later.",
        "It ends the conversation politely.",
        "It is grammatically required.",
      ], 0),
      qfill("Correct me if I've ___. (misunderstand)", ["misunderstood"]),
      qmcq("What does scaling a claim achieve?", [
        "It stays useful without becoming a liability.",
        "It shortens the claim.",
        "It makes the claim certain.",
      ], 0),
    ],
    scenes: [
      sc("Priya", "an expert explaining something technical", "to include you in the discussion",
        "A technical discussion is beyond your knowledge.",
        "Admit the limit and contribute.",
        "You are following all this, aren't you?", "assuming"),
      sc("Hugo", "a colleague from a technical team", "to get useful input from a non-specialist",
        "A technical team wants your view anyway.",
        "Contribute from partial knowledge.",
        "I know this is not your area, but what is your instinct?", "inclusive"),
      sc("Camille", "someone at a specialist gathering", "to have a real conversation anyway",
        "A gathering of specialists in an unfamiliar field.",
        "Stay in the conversation honestly.",
        "Are you in the field, or just curious?", "welcoming"),
      sc("Mr. Boateng", "your tutor", "to practise operating beyond your knowledge",
        "The seminar is examining conversational survival.",
        "Admit the limit and contribute.",
        "How do you stay useful in a conversation you cannot follow?", "probing"),
      sc("Ms. Aaltonen", "the examiner", "to check honesty under pressure",
        "The examiner raises an unfamiliar technical subject.",
        "Admit the limit and contribute.",
        "What is your view on the economics of desalination?", "neutral"),
    ],
  },

  {
    id: "c1-pet-peeves",
    topic: "complaining elegantly about small things",
    objectives: [
      "Complain about something trivial without becoming tedious.",
      "Keep the complaint proportionate to the offence.",
    ],
    goal: "Complain entertainingly about something small.",
    target: "elegant complaint",
    correction: "Model the proportionate complaint and let the learner add their own.",
    summary: "You practised complaining about small irritations without becoming tedious.",
    minutes: 8,
    points: [
      {
        form: "what really gets me",
        claims: [
          "'What really gets me is...' puts the specific irritation at the end for effect.",
          "The specificity is what makes a small complaint entertaining rather than dull.",
        ],
        ex: ["What really gets me is the queueing.", "What really gets me is people who stop dead."],
      },
      {
        form: "I can't stand",
        claims: [
          "'I can't stand' expresses strong dislike, so tone and context decide whether it sounds playful or genuinely angry.",
          "With a trivial subject the mismatch of scale is the joke; with a serious one it reads as real anger.",
        ],
        ex: ["I can't stand slow walkers.", "I can't stand it when nobody replies."],
      },
      {
        form: "drives me up the wall",
        claims: [
          "'Drives me up the wall' expresses intense irritation; with a trivial subject and playful delivery it reads as deliberate exaggeration.",
          "Delivered flatly about something serious, it reads as a real grievance instead.",
        ],
        ex: ["It drives me up the wall.", "That noise drives me up the wall."],
      },
    ],
    ex: [
      fill("What really ___ me is the queueing. (get)", ["gets"]),
      mcq("Which complaint is proportionate to something trivial?", [
        "I can't stand slow walkers.",
        "This is the worst thing about society.",
        "Nobody should be allowed to do that.",
      ], 0),
      say("that noise / drive / me / up the wall", ["That noise drives me up the wall."]),
    ],
    open: {
      q: "Complain entertainingly about three small everyday irritations, keeping each one proportionate.",
      must: ["what really gets me", "I can't stand", "drives me up the wall"],
      criteria: "The answer complains specifically and keeps the language proportionate to the offence.",
      example: "What really gets me is people stopping dead. I can't stand slow escalators. Loud chewing drives me up the wall.",
    },
    success: "The learner complains specifically and proportionately.",
    quiz: [
      qmcq("Why is specificity important in a small complaint?", [
        "It makes the complaint entertaining rather than dull.",
        "It shortens the complaint.",
        "It is grammatically required.",
      ], 0),
      qfill("I can't ___ it when nobody replies. (stand)", ["stand"]),
      qmcq("What decides whether 'drives me up the wall' sounds playful?", [
        "the subject and the delivery",
        "the tense of the verb",
        "the length of the sentence",
      ], 0),
    ],
    scenes: [
      sc("Ottoline", "a friend who enjoys a good moan", "to trade small complaints",
        "Two friends are enjoying complaining about trivia.",
        "Complain entertainingly.",
        "Right, your turn: what small things annoy you most?", "playful"),
      sc("Viktor", "a colleague on a coffee break", "to pass the time entertainingly",
        "A coffee break turns to office irritations.",
        "Complain proportionately.",
        "What is the most annoying thing about this building?", "amused"),
      sc("Noor", "a fellow traveller in a long queue", "to make a queue bearable",
        "A long queue invites shared complaining.",
        "Complain entertainingly.",
        "We are going to be here a while. What annoys you most about travelling?", "resigned"),
      sc("Mr. Halvorsen", "your tutor", "to practise proportionate complaint",
        "The seminar is examining register in complaint.",
        "Complain proportionately.",
        "Why is strong language funny about small things and not big ones?", "probing"),
      sc("Ms. Cardoso", "the examiner", "to check register control in complaint",
        "The examiner invites complaints about trivia.",
        "Complain proportionately.",
        "What small everyday thing irritates you most?", "neutral"),
    ],
  },

  {
    id: "c1-overhyped-or-worth-it",
    topic: "judging against a reputation",
    objectives: [
      "Judge something against what was claimed for it.",
      "Separate the thing from the hype around it.",
    ],
    goal: "Say whether something lived up to its reputation.",
    target: "judging against expectation",
    correction: "Model the judgement against expectation and let the learner assess their own.",
    summary: "You practised judging whether something lived up to its reputation.",
    minutes: 8,
    points: [
      {
        form: "worth the hype",
        claims: [
          "'Worth the hype' judges the thing against what was claimed, not in isolation.",
          "Something can be good and still not worth the hype.",
        ],
        ex: ["It was worth the hype, actually.", "It wasn't quite worth the hype."],
      },
      {
        form: "lives up to",
        claims: [
          "'Lives up to its reputation' is the neutral version of the same judgement.",
          "'Hype' suggests intense and possibly exaggerated publicity, where 'reputation' is more neutral.",
        ],
        ex: ["It lives up to its reputation.", "It doesn't quite live up to it."],
      },
      {
        form: "falls short of",
        claims: [
          "'Falls short of' names the gap without dismissing the thing entirely.",
          "Naming what it falls short OF keeps the judgement answerable.",
        ],
        ex: ["It falls short of the claims made for it.", "It falls short of the earlier work."],
      },
    ],
    ex: [
      fill("It was ___ the hype, actually. (worth)", ["worth"]),
      mcq("Which sentence suggests the publicity may have been exaggerated?", [
        "It wasn't worth the hype.",
        "It doesn't live up to its reputation.",
        "It falls short of the claims.",
      ], 0),
      say("it / fall short / of the claims / make for it", ["It falls short of the claims made for it."]),
    ],
    open: {
      q: "Judge something famous you have experienced: did it live up to its reputation, and where did it fall short?",
      must: ["worth the hype", "lives up to", "falls short of"],
      criteria: "The answer judges the thing against what was claimed and names the gap.",
      example: "The setting lives up to its reputation. The food was worth the hype. The service falls short of what the price led me to expect.",
    },
    success: "The learner judges against expectation and names the gap.",
    quiz: [
      qmcq("How does 'hype' differ from 'reputation'?", [
        "'Hype' suggests exaggerated publicity; 'reputation' is more neutral.",
        "It is more formal.",
        "It is shorter.",
      ], 0),
      qfill("It ___ short of the earlier work. (fall)", ["falls"]),
      qmcq("Why name what something falls short of?", [
        "It keeps the judgement answerable.",
        "It shortens the sentence.",
        "It avoids the passive.",
      ], 0),
    ],
    scenes: [
      sc("Beatriz", "a friend about to try the same thing", "to decide whether to bother",
        "A friend is deciding whether something famous is worth it.",
        "Judge it against its reputation.",
        "Everyone says it is incredible. Is it, though?", "sceptical"),
      sc("Andres", "a colleague assessing a much-praised tool", "to judge a tool fairly",
        "A widely praised tool is being evaluated.",
        "Judge it against the claims.",
        "The reviews are glowing. Does it actually deliver?", "analytical"),
      sc("Selin", "a fellow traveller at a famous site", "to compare impressions honestly",
        "You are both at a famous, heavily promoted place.",
        "Judge it honestly.",
        "Well. Was that worth the queue?", "wry"),
      sc("Mr. Achebe", "your tutor", "to practise evaluative judgement",
        "The seminar is examining judgement against expectation.",
        "Judge against the claims.",
        "How is judging against hype different from judging in isolation?", "probing"),
      sc("Ms. Lindberg", "the examiner", "to check evaluative discussion",
        "The examiner asks about something famous.",
        "Judge against its reputation.",
        "Could you tell me about something famous that disappointed you?", "neutral"),
    ],
  },

  {
    id: "c1-closing-the-loop",
    topic: "summarising a long discussion fairly",
    objectives: [
      "Summarise both positions fairly, including the one you reject.",
      "Close without claiming a victory.",
    ],
    goal: "Close a long discussion so both sides recognise their own position.",
    target: "fair closing summary",
    correction: "Model the fair summary and let the learner close their own discussion.",
    summary: "You practised closing a long discussion so both sides recognise their position.",
    minutes: 8,
    points: [
      {
        form: "so where we've landed",
        claims: [
          "'So where we've landed is...' reports the outcome, including what stays unresolved.",
          "'We' rather than 'I' makes it a joint summary rather than a verdict.",
        ],
        ex: ["So where we've landed is a trial.", "So where we've landed is that we disagree on timing."],
      },
      {
        form: "to bring it together",
        claims: [
          "'To bring it together' signals synthesis rather than repetition.",
          "A summary that only repeats your own side is not a summary.",
        ],
        ex: ["To bring it together, both concerns are real.", "To bring it together, the remaining issues are cost and timing."],
      },
      {
        form: "that's where I'll stop",
        claims: [
          "'That's where I'll stop' closes your contribution without demanding agreement.",
          "Stopping without claiming victory leaves the other side room to move later.",
        ],
        ex: ["That's where I'll stop.", "That's where I'll stop, for today at least."],
      },
    ],
    ex: [
      fill("So where we've ___ is a trial. (land)", ["landed"]),
      mcq("Which phrase signals synthesis rather than repetition?", [
        "To bring it together,",
        "As I said before,",
        "To repeat my point,",
      ], 0),
      say("that be / where I / will stop / for today", ["That's where I'll stop, for today.", "That is where I will stop, for today."]),
    ],
    open: {
      q: "Close a long disagreement: summarise both positions fairly, name what is unresolved, and stop without claiming victory.",
      must: ["so where we've landed", "to bring it together", "that's where I'll stop"],
      criteria: "The answer summarises both positions fairly and closes without claiming victory.",
      example: "To bring it together, one side thinks a full rollout is too risky, the other thinks delay costs more. So where we've landed is a limited trial, though we still disagree on its length. That's where I'll stop.",
    },
    success: "The learner summarises both positions fairly and closes without claiming victory.",
    quiz: [
      qmcq("Why say 'we' rather than 'I' in the summary?", [
        "It makes it a joint summary rather than a verdict.",
        "It is more formal.",
        "It is grammatically required.",
      ], 0),
      qfill("To bring it ___, both concerns are real. (together)", ["together"]),
      qmcq("What does stopping without claiming victory allow?", [
        "It leaves the other side room to move later.",
        "It shortens the discussion.",
        "It ends the relationship.",
      ], 0),
    ],
    scenes: [
      sc("Kwabena", "a friend after a long disagreement", "to end well despite disagreeing",
        "A long disagreement has run its course without resolution.",
        "Close it fairly.",
        "We are not going to agree tonight, are we? How do we leave it?", "tired"),
      sc("Simone", "a colleague after a difficult meeting", "to close a meeting fairly",
        "A meeting must close with both positions recorded.",
        "Summarise both fairly.",
        "We are out of time and still split. Can you sum it up?", "even"),
      sc("Emil", "someone you have debated all evening", "to part on good terms",
        "A long evening debate must end.",
        "Close it generously.",
        "That was the best argument I have lost all year. Shall we stop?", "warm"),
      sc("Mrs. Aguilar", "your tutor", "to practise fair closure",
        "The seminar is examining how discussions end.",
        "Summarise fairly and close.",
        "Why does a summary that favours you fail as a summary?", "probing"),
      sc("Mr. Nakamura", "the examiner", "to check fair summarising",
        "The examiner has argued against you at length.",
        "Summarise both positions fairly.",
        "We have disagreed for some time. How would you sum it up?", "neutral"),
    ],
  },
];
